<!DOCTYPE html>
<html lang="fr" xml:lang="fr">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>13.3 Classification ascendante hiérarchique | Méthodes quantitatives en sciences sociales : un grand bol d’R</title>
  <meta name="description" content="Ce livre vise à décrire une panoplie de méthodes quantitatives utilisées en sciences sociales avec le logiciel ouvert R. Il a d’ailleurs été écrit intégralement dans R avec rmarkdown. Le contenu est pensé pour être accessible à tous et toutes, même à ceux et celles n’ayant presque aucune base en statistique ou en programmation. Les personnes plus expérimentées y découvriront des sections sur des méthodes plus avancées comme les modèles à effets mixtes, les modèles multiniveaux, les modèles généralisés additifs ainsi que les méthodes factorielles et de classification. Ceux et celles souhaitant migrer progressivement d’un autre logiciel statistique vers R trouveront dans cet ouvrage les éléments pour une transition en douceur. La philosophie de ce livre est de donner toutes les clefs de compréhension et de mise en œuvre des méthodes abordées dans R. La présentation des méthodes est basée sur une approche compréhensive et intuitive plutôt que mathématique, sans pour autant que la rigueur statistique ne soit négligée." />
  <meta name="generator" content="bookdown 0.32 and GitBook 2.6.7" />

  <meta property="og:title" content="13.3 Classification ascendante hiérarchique | Méthodes quantitatives en sciences sociales : un grand bol d’R" />
  <meta property="og:type" content="book" />
  <meta property="og:image" content="https://laeq.github.io/LivreStatistique_website/images/introduction/ImageCouverture.png" />
  <meta property="og:description" content="Ce livre vise à décrire une panoplie de méthodes quantitatives utilisées en sciences sociales avec le logiciel ouvert R. Il a d’ailleurs été écrit intégralement dans R avec rmarkdown. Le contenu est pensé pour être accessible à tous et toutes, même à ceux et celles n’ayant presque aucune base en statistique ou en programmation. Les personnes plus expérimentées y découvriront des sections sur des méthodes plus avancées comme les modèles à effets mixtes, les modèles multiniveaux, les modèles généralisés additifs ainsi que les méthodes factorielles et de classification. Ceux et celles souhaitant migrer progressivement d’un autre logiciel statistique vers R trouveront dans cet ouvrage les éléments pour une transition en douceur. La philosophie de ce livre est de donner toutes les clefs de compréhension et de mise en œuvre des méthodes abordées dans R. La présentation des méthodes est basée sur une approche compréhensive et intuitive plutôt que mathématique, sans pour autant que la rigueur statistique ne soit négligée." />
  <meta name="github-repo" content="LAEQ/livre_statistique_Phil_Jere" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="13.3 Classification ascendante hiérarchique | Méthodes quantitatives en sciences sociales : un grand bol d’R" />
  
  <meta name="twitter:description" content="Ce livre vise à décrire une panoplie de méthodes quantitatives utilisées en sciences sociales avec le logiciel ouvert R. Il a d’ailleurs été écrit intégralement dans R avec rmarkdown. Le contenu est pensé pour être accessible à tous et toutes, même à ceux et celles n’ayant presque aucune base en statistique ou en programmation. Les personnes plus expérimentées y découvriront des sections sur des méthodes plus avancées comme les modèles à effets mixtes, les modèles multiniveaux, les modèles généralisés additifs ainsi que les méthodes factorielles et de classification. Ceux et celles souhaitant migrer progressivement d’un autre logiciel statistique vers R trouveront dans cet ouvrage les éléments pour une transition en douceur. La philosophie de ce livre est de donner toutes les clefs de compréhension et de mise en œuvre des méthodes abordées dans R. La présentation des méthodes est basée sur une approche compréhensive et intuitive plutôt que mathématique, sans pour autant que la rigueur statistique ne soit négligée." />
  <meta name="twitter:image" content="https://laeq.github.io/LivreStatistique_website/images/introduction/ImageCouverture.png" />

<meta name="author" content="Philippe Apparicio et Jérémy Gelb" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="sect132.html"/>
<link rel="next" href="sect134.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.6.1/htmlwidgets.js"></script>
<script src="libs/d3-4.13.0/d3.min.js"></script>
<script src="libs/d3-tip-0.8.1/index.js"></script>
<link href="libs/chorddiag-0.1.2.9000/chorddiag.css" rel="stylesheet" />
<script src="libs/chorddiag-0.1.2.9000/chorddiag.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="css/quizlib.min.css" type="text/css" />
<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Méthodes quantitatives en sciences sociales : un grand bol d'R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Bienvenue</a></li>
<li class="chapter" data-level="" data-path="préface.html"><a href="préface.html"><i class="fa fa-check"></i>Préface</a>
<ul>
<li class="chapter" data-level="" data-path="sect001.html"><a href="sect001.html"><i class="fa fa-check"></i>Un manuel sous la forme d’une ressource éducative libre</a></li>
<li class="chapter" data-level="" data-path="sect002.html"><a href="sect002.html"><i class="fa fa-check"></i>Un manuel conçu comme un projet collaboratif</a></li>
<li class="chapter" data-level="" data-path="sect003.html"><a href="sect003.html"><i class="fa fa-check"></i>Comment lire ce livre?</a></li>
<li class="chapter" data-level="" data-path="sect003B.html"><a href="sect003B.html"><i class="fa fa-check"></i>Comment utiliser les données du livre pour reproduire les exemples?</a></li>
<li class="chapter" data-level="" data-path="sect004.html"><a href="sect004.html"><i class="fa fa-check"></i>Structure du livre</a></li>
<li class="chapter" data-level="" data-path="sect005.html"><a href="sect005.html"><i class="fa fa-check"></i>Pourquoi faut-il programmer en sciences sociales?</a></li>
<li class="chapter" data-level="" data-path="sect006.html"><a href="sect006.html"><i class="fa fa-check"></i>Remerciements</a></li>
<li class="chapter" data-level="" data-path="sect007.html"><a href="sect007.html"><i class="fa fa-check"></i>Dédicace toute spéciale à Cargo et Ambrée</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="auteurs.html"><a href="auteurs.html"><i class="fa fa-check"></i>À propos des auteurs</a></li>
<li class="part"><span><b>I Découverte de R</b></span></li>
<li class="chapter" data-level="1" data-path="chap01.html"><a href="chap01.html"><i class="fa fa-check"></i><b>1</b> Prise en main de R</a>
<ul>
<li class="chapter" data-level="1.1" data-path="sect011.html"><a href="sect011.html"><i class="fa fa-check"></i><b>1.1</b> Histoire et philosophie de R</a></li>
<li class="chapter" data-level="1.2" data-path="sect012.html"><a href="sect012.html"><i class="fa fa-check"></i><b>1.2</b> Environnement de travail</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="sect012.html"><a href="sect012.html#sect0121"><i class="fa fa-check"></i><b>1.2.1</b> Installation de R</a></li>
<li class="chapter" data-level="1.2.2" data-path="sect012.html"><a href="sect012.html#sect0122"><i class="fa fa-check"></i><b>1.2.2</b> Environnement RStudio</a></li>
<li class="chapter" data-level="1.2.3" data-path="sect012.html"><a href="sect012.html#sect0123"><i class="fa fa-check"></i><b>1.2.3</b> Installation et chargement un <em>package</em></a></li>
<li class="chapter" data-level="1.2.4" data-path="sect012.html"><a href="sect012.html#aide-disponible"><i class="fa fa-check"></i><b>1.2.4</b> Aide disponible</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="sect013.html"><a href="sect013.html"><i class="fa fa-check"></i><b>1.3</b> Bases du langage R</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="sect013.html"><a href="sect013.html#sect0131"><i class="fa fa-check"></i><b>1.3.1</b> <em>Hello World</em>!</a></li>
<li class="chapter" data-level="1.3.2" data-path="sect013.html"><a href="sect013.html#sect0132"><i class="fa fa-check"></i><b>1.3.2</b> Objets et expressions</a></li>
<li class="chapter" data-level="1.3.3" data-path="sect013.html"><a href="sect013.html#sect0_133"><i class="fa fa-check"></i><b>1.3.3</b> Fonctions et arguments</a></li>
<li class="chapter" data-level="1.3.4" data-path="sect013.html"><a href="sect013.html#sect0134"><i class="fa fa-check"></i><b>1.3.4</b> Principaux types de données</a></li>
<li class="chapter" data-level="1.3.5" data-path="sect013.html"><a href="sect013.html#sect0135"><i class="fa fa-check"></i><b>1.3.5</b> Opérateurs</a></li>
<li class="chapter" data-level="1.3.6" data-path="sect013.html"><a href="sect013.html#sect0136"><i class="fa fa-check"></i><b>1.3.6</b> Structures de données</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="sect014.html"><a href="sect014.html"><i class="fa fa-check"></i><b>1.4</b> Manipulation de données</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="sect014.html"><a href="sect014.html#sect0141"><i class="fa fa-check"></i><b>1.4.1</b> Chargement d’un <em>DataFrame</em> depuis un fichier</a></li>
<li class="chapter" data-level="1.4.2" data-path="sect014.html"><a href="sect014.html#sect0142"><i class="fa fa-check"></i><b>1.4.2</b> Manipulation d’un <em>DataFrame</em></a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="sect016.html"><a href="sect016.html"><i class="fa fa-check"></i><b>1.5</b> Code R bien structuré</a></li>
<li class="chapter" data-level="1.6" data-path="sect017.html"><a href="sect017.html"><i class="fa fa-check"></i><b>1.6</b> Enregistrement des résultats</a></li>
<li class="chapter" data-level="1.7" data-path="sect018.html"><a href="sect018.html"><i class="fa fa-check"></i><b>1.7</b> Session de travail</a></li>
<li class="chapter" data-level="1.8" data-path="sect019.html"><a href="sect019.html"><i class="fa fa-check"></i><b>1.8</b> Conclusion et ressources pertinentes</a></li>
<li class="chapter" data-level="1.9" data-path="sect0110.html"><a href="sect0110.html"><i class="fa fa-check"></i><b>1.9</b> Quiz de révision du chapitre</a></li>
</ul></li>
<li class="part"><span><b>II Analyses univariées et graphiques dans R</b></span></li>
<li class="chapter" data-level="2" data-path="chap02.html"><a href="chap02.html"><i class="fa fa-check"></i><b>2</b> Statistiques descriptives univariées</a>
<ul>
<li class="chapter" data-level="2.1" data-path="sect021.html"><a href="sect021.html"><i class="fa fa-check"></i><b>2.1</b> Notion et types de variable</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="sect021.html"><a href="sect021.html#sect0211"><i class="fa fa-check"></i><b>2.1.1</b> Notion de variable</a></li>
<li class="chapter" data-level="2.1.2" data-path="sect021.html"><a href="sect021.html#sect0212"><i class="fa fa-check"></i><b>2.1.2</b> Types de variables</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="sect022.html"><a href="sect022.html"><i class="fa fa-check"></i><b>2.2</b> Types de données</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="sect022.html"><a href="sect022.html#sect0221"><i class="fa fa-check"></i><b>2.2.1</b> Données secondaires <em>versus</em> données primaires</a></li>
<li class="chapter" data-level="2.2.2" data-path="sect022.html"><a href="sect022.html#sect0222"><i class="fa fa-check"></i><b>2.2.2</b> Données transversales <em>versus</em> données longitudinales</a></li>
<li class="chapter" data-level="2.2.3" data-path="sect022.html"><a href="sect022.html#sect0223"><i class="fa fa-check"></i><b>2.2.3</b> Données spatiales versus données aspatiales</a></li>
<li class="chapter" data-level="2.2.4" data-path="sect022.html"><a href="sect022.html#sect0224"><i class="fa fa-check"></i><b>2.2.4</b> Données individuelles <em>versus</em> données agrégées</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="sect023.html"><a href="sect023.html"><i class="fa fa-check"></i><b>2.3</b> Statistique descriptive et statistique inférentielle</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="sect023.html"><a href="sect023.html#sect0231"><i class="fa fa-check"></i><b>2.3.1</b> Population, échantillon et inférence</a></li>
<li class="chapter" data-level="2.3.2" data-path="sect023.html"><a href="sect023.html#sect0232"><i class="fa fa-check"></i><b>2.3.2</b> Deux grandes familles de méthodes statistiques</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="sect024.html"><a href="sect024.html"><i class="fa fa-check"></i><b>2.4</b> Notion de distribution</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="sect024.html"><a href="sect024.html#définition-générale"><i class="fa fa-check"></i><b>2.4.1</b> Définition générale</a></li>
<li class="chapter" data-level="2.4.2" data-path="sect024.html"><a href="sect024.html#anatomie-dune-distribution"><i class="fa fa-check"></i><b>2.4.2</b> Anatomie d’une distribution</a></li>
<li class="chapter" data-level="2.4.3" data-path="sect024.html"><a href="sect024.html#principales-distributions"><i class="fa fa-check"></i><b>2.4.3</b> Principales distributions</a></li>
<li class="chapter" data-level="2.4.4" data-path="sect024.html"><a href="sect024.html#conclusion-sur-les-distributions"><i class="fa fa-check"></i><b>2.4.4</b> Conclusion sur les distributions</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="sect025.html"><a href="sect025.html"><i class="fa fa-check"></i><b>2.5</b> Statistiques descriptives sur des variables quantitatives</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="sect025.html"><a href="sect025.html#sect0251"><i class="fa fa-check"></i><b>2.5.1</b> Paramètres de tendance centrale</a></li>
<li class="chapter" data-level="2.5.2" data-path="sect025.html"><a href="sect025.html#sect0252"><i class="fa fa-check"></i><b>2.5.2</b> Paramètres de position</a></li>
<li class="chapter" data-level="2.5.3" data-path="sect025.html"><a href="sect025.html#sect0253"><i class="fa fa-check"></i><b>2.5.3</b> Paramètres de dispersion</a></li>
<li class="chapter" data-level="2.5.4" data-path="sect025.html"><a href="sect025.html#sect0254"><i class="fa fa-check"></i><b>2.5.4</b> Paramètres de forme</a></li>
<li class="chapter" data-level="2.5.5" data-path="sect025.html"><a href="sect025.html#sect0255"><i class="fa fa-check"></i><b>2.5.5</b> Transformation des variables</a></li>
<li class="chapter" data-level="2.5.6" data-path="sect025.html"><a href="sect025.html#sect0256"><i class="fa fa-check"></i><b>2.5.6</b> Mise en œuvre dans R</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="sect026.html"><a href="sect026.html"><i class="fa fa-check"></i><b>2.6</b> Statistiques descriptives sur des variables qualitatives et semi-qualitatives</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="sect026.html"><a href="sect026.html#sect0261"><i class="fa fa-check"></i><b>2.6.1</b> Fréquences</a></li>
<li class="chapter" data-level="2.6.2" data-path="sect026.html"><a href="sect026.html#sect0262"><i class="fa fa-check"></i><b>2.6.2</b> Mise en œuvre dans R</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="sect027.html"><a href="sect027.html"><i class="fa fa-check"></i><b>2.7</b> Statistiques descriptives pondérées : pour aller plus loin</a></li>
<li class="chapter" data-level="2.8" data-path="sect028.html"><a href="sect028.html"><i class="fa fa-check"></i><b>2.8</b> Quiz de révision du chapitre</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="chap03.html"><a href="chap03.html"><i class="fa fa-check"></i><b>3</b> Magie des graphiques</a>
<ul>
<li class="chapter" data-level="3.1" data-path="sect031.html"><a href="sect031.html"><i class="fa fa-check"></i><b>3.1</b> Philosophie du ggplot2</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="sect031.html"><a href="sect031.html#sect0311"><i class="fa fa-check"></i><b>3.1.1</b> Grammaire</a></li>
<li class="chapter" data-level="3.1.2" data-path="sect031.html"><a href="sect031.html#sect0312"><i class="fa fa-check"></i><b>3.1.2</b> Types de géométries</a></li>
<li class="chapter" data-level="3.1.3" data-path="sect031.html"><a href="sect031.html#sect0313"><i class="fa fa-check"></i><b>3.1.3</b> Habillage</a></li>
<li class="chapter" data-level="3.1.4" data-path="sect031.html"><a href="sect031.html#utilisation-des-thèmes"><i class="fa fa-check"></i><b>3.1.4</b> Utilisation des thèmes</a></li>
<li class="chapter" data-level="3.1.5" data-path="sect031.html"><a href="sect031.html#sect0314"><i class="fa fa-check"></i><b>3.1.5</b> Composition d’une figure avec plusieurs graphiques</a></li>
<li class="chapter" data-level="3.1.6" data-path="sect031.html"><a href="sect031.html#sect0315"><i class="fa fa-check"></i><b>3.1.6</b> Couleur</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="sect032.html"><a href="sect032.html"><i class="fa fa-check"></i><b>3.2</b> Principaux graphiques</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="sect032.html"><a href="sect032.html#sect0321"><i class="fa fa-check"></i><b>3.2.1</b> Histogramme</a></li>
<li class="chapter" data-level="3.2.2" data-path="sect032.html"><a href="sect032.html#sect0322"><i class="fa fa-check"></i><b>3.2.2</b> Graphique de densité</a></li>
<li class="chapter" data-level="3.2.3" data-path="sect032.html"><a href="sect032.html#sect0323"><i class="fa fa-check"></i><b>3.2.3</b> Nuage de points</a></li>
<li class="chapter" data-level="3.2.4" data-path="sect032.html"><a href="sect032.html#sect0324"><i class="fa fa-check"></i><b>3.2.4</b> Graphique en ligne</a></li>
<li class="chapter" data-level="3.2.5" data-path="sect032.html"><a href="sect032.html#sect0325"><i class="fa fa-check"></i><b>3.2.5</b> Boîte à moustaches</a></li>
<li class="chapter" data-level="3.2.6" data-path="sect032.html"><a href="sect032.html#sect0326"><i class="fa fa-check"></i><b>3.2.6</b> Graphique en violon</a></li>
<li class="chapter" data-level="3.2.7" data-path="sect032.html"><a href="sect032.html#sect0327"><i class="fa fa-check"></i><b>3.2.7</b> Graphique en barre</a></li>
<li class="chapter" data-level="3.2.8" data-path="sect032.html"><a href="sect032.html#sect0328"><i class="fa fa-check"></i><b>3.2.8</b> Graphique circulaire</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="sect033.html"><a href="sect033.html"><i class="fa fa-check"></i><b>3.3</b> Graphiques spéciaux</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="sect033.html"><a href="sect033.html#sect0331"><i class="fa fa-check"></i><b>3.3.1</b> Graphique en radar</a></li>
<li class="chapter" data-level="3.3.2" data-path="sect033.html"><a href="sect033.html#sect0332"><i class="fa fa-check"></i><b>3.3.2</b> Diagramme d’accord</a></li>
<li class="chapter" data-level="3.3.3" data-path="sect033.html"><a href="sect033.html#sect0333"><i class="fa fa-check"></i><b>3.3.3</b> Nuage de mots</a></li>
<li class="chapter" data-level="3.3.4" data-path="sect033.html"><a href="sect033.html#sect0334"><i class="fa fa-check"></i><b>3.3.4</b> Carte proportionnelle</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="sect034.html"><a href="sect034.html"><i class="fa fa-check"></i><b>3.4</b> Cartes</a></li>
<li class="chapter" data-level="3.5" data-path="sect035.html"><a href="sect035.html"><i class="fa fa-check"></i><b>3.5</b> Exportation des graphiques</a></li>
<li class="chapter" data-level="3.6" data-path="sect036.html"><a href="sect036.html"><i class="fa fa-check"></i><b>3.6</b> Conclusion sur les graphiques</a></li>
</ul></li>
<li class="part"><span><b>III Analyses bivariées</b></span></li>
<li class="chapter" data-level="4" data-path="chap04.html"><a href="chap04.html"><i class="fa fa-check"></i><b>4</b> Relation linéaire entre deux variables quantitatives</a>
<ul>
<li class="chapter" data-level="4.1" data-path="sect041.html"><a href="sect041.html"><i class="fa fa-check"></i><b>4.1</b> Bref retour sur le postulat de la relation linéaire</a></li>
<li class="chapter" data-level="4.2" data-path="sect042.html"><a href="sect042.html"><i class="fa fa-check"></i><b>4.2</b> Covariance</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="sect042.html"><a href="sect042.html#sect0421"><i class="fa fa-check"></i><b>4.2.1</b> Formulation</a></li>
<li class="chapter" data-level="4.2.2" data-path="sect042.html"><a href="sect042.html#sect0422"><i class="fa fa-check"></i><b>4.2.2</b> Interprétation</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="sect043.html"><a href="sect043.html"><i class="fa fa-check"></i><b>4.3</b> Corrélation</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="sect043.html"><a href="sect043.html#sect0431"><i class="fa fa-check"></i><b>4.3.1</b> Formulation</a></li>
<li class="chapter" data-level="4.3.2" data-path="sect043.html"><a href="sect043.html#sect0432"><i class="fa fa-check"></i><b>4.3.2</b> Interprétation</a></li>
<li class="chapter" data-level="4.3.3" data-path="sect043.html"><a href="sect043.html#sect0433"><i class="fa fa-check"></i><b>4.3.3</b> Corrélations pour des variables anormalement distribuées (coefficient de Spearman, tau de Kendall)</a></li>
<li class="chapter" data-level="4.3.4" data-path="sect043.html"><a href="sect043.html#sect0434"><i class="fa fa-check"></i><b>4.3.4</b> Corrélations robustes (<em>Biweight midcorrelation</em>, <em>Percentage bend correlation</em> et la corrélation <em>pi</em> de Shepherd)</a></li>
<li class="chapter" data-level="4.3.5" data-path="sect043.html"><a href="sect043.html#sect0435"><i class="fa fa-check"></i><b>4.3.5</b> Significativité des coefficients de corrélation</a></li>
<li class="chapter" data-level="4.3.6" data-path="sect043.html"><a href="sect043.html#sect0436"><i class="fa fa-check"></i><b>4.3.6</b> Corrélation partielle</a></li>
<li class="chapter" data-level="4.3.7" data-path="sect043.html"><a href="sect043.html#sect0437"><i class="fa fa-check"></i><b>4.3.7</b> Mise en œuvre dans R</a></li>
<li class="chapter" data-level="4.3.8" data-path="sect043.html"><a href="sect043.html#sect0438"><i class="fa fa-check"></i><b>4.3.8</b> Comment rapporter des valeurs de corrélations?</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="sect044.html"><a href="sect044.html"><i class="fa fa-check"></i><b>4.4</b> Régression linéaire simple</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="sect044.html"><a href="sect044.html#sect0441"><i class="fa fa-check"></i><b>4.4.1</b> Principe de base de la régression linéaire simple</a></li>
<li class="chapter" data-level="4.4.2" data-path="sect044.html"><a href="sect044.html#sect0442"><i class="fa fa-check"></i><b>4.4.2</b> Formulation de la droite de régression des moindres carrés ordinaires</a></li>
<li class="chapter" data-level="4.4.3" data-path="sect044.html"><a href="sect044.html#sect0443"><i class="fa fa-check"></i><b>4.4.3</b> Mesure de la qualité d’ajustement du modèle</a></li>
<li class="chapter" data-level="4.4.4" data-path="sect044.html"><a href="sect044.html#sect0444"><i class="fa fa-check"></i><b>4.4.4</b> Mise en œuvre dans R</a></li>
<li class="chapter" data-level="4.4.5" data-path="sect044.html"><a href="sect044.html#sect0445"><i class="fa fa-check"></i><b>4.4.5</b> Comment rapporter une régression linéaire simple</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="sect045.html"><a href="sect045.html"><i class="fa fa-check"></i><b>4.5</b> Quiz de révision du chapitre</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="chap05.html"><a href="chap05.html"><i class="fa fa-check"></i><b>5</b> Relation entre deux variables qualitatives</a>
<ul>
<li class="chapter" data-level="5.1" data-path="sect051.html"><a href="sect051.html"><i class="fa fa-check"></i><b>5.1</b> Construction de tableau de contingence</a></li>
<li class="chapter" data-level="5.2" data-path="sect052.html"><a href="sect052.html"><i class="fa fa-check"></i><b>5.2</b> Test du khi-deux</a></li>
<li class="chapter" data-level="5.3" data-path="sect053.html"><a href="sect053.html"><i class="fa fa-check"></i><b>5.3</b> Mise en œuvre dans R</a></li>
<li class="chapter" data-level="5.4" data-path="sect054.html"><a href="sect054.html"><i class="fa fa-check"></i><b>5.4</b> Interprétation d’un tableau de contingence</a></li>
<li class="chapter" data-level="5.5" data-path="sect055.html"><a href="sect055.html"><i class="fa fa-check"></i><b>5.5</b> Quiz de révision du chapitre</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="chap06.html"><a href="chap06.html"><i class="fa fa-check"></i><b>6</b> Relation entre une variable qualitative et une variable quantitative</a>
<ul>
<li class="chapter" data-level="6.1" data-path="sect061.html"><a href="sect061.html"><i class="fa fa-check"></i><b>6.1</b> Relation entre une variable quantitative et une variable qualitative à deux modalités</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="sect061.html"><a href="sect061.html#sect0611"><i class="fa fa-check"></i><b>6.1.1</b> Test <em>t</em> et ses différentes variantes</a></li>
<li class="chapter" data-level="6.1.2" data-path="sect061.html"><a href="sect061.html#sect0612"><i class="fa fa-check"></i><b>6.1.2</b> Test non paramétrique de Wilcoxon</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="sect062.html"><a href="sect062.html"><i class="fa fa-check"></i><b>6.2</b> Relation entre une variable quantitative et une variable qualitative à plus de deux modalités</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="sect062.html"><a href="sect062.html#sect0621"><i class="fa fa-check"></i><b>6.2.1</b> Analyse de variance</a></li>
<li class="chapter" data-level="6.2.2" data-path="sect062.html"><a href="sect062.html#sect0622"><i class="fa fa-check"></i><b>6.2.2</b> Test non paramétrique de Kruskal-Wallis</a></li>
<li class="chapter" data-level="6.2.3" data-path="sect062.html"><a href="sect062.html#sect0623"><i class="fa fa-check"></i><b>6.2.3</b> Mise en œuvre dans R</a></li>
<li class="chapter" data-level="6.2.4" data-path="sect062.html"><a href="sect062.html#sect0624"><i class="fa fa-check"></i><b>6.2.4</b> Comment rapporter les résultats d’une ANOVA et du test de Kruskal-Wallis</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="sect063.html"><a href="sect063.html"><i class="fa fa-check"></i><b>6.3</b> Conclusion sur la troisième partie</a></li>
<li class="chapter" data-level="6.4" data-path="sect064.html"><a href="sect064.html"><i class="fa fa-check"></i><b>6.4</b> Quiz de révision du chapitre</a></li>
</ul></li>
<li class="part"><span><b>IV Modèles de régression</b></span></li>
<li class="chapter" data-level="7" data-path="chap07.html"><a href="chap07.html"><i class="fa fa-check"></i><b>7</b> Régression linéaire multiple</a>
<ul>
<li class="chapter" data-level="7.1" data-path="sect071.html"><a href="sect071.html"><i class="fa fa-check"></i><b>7.1</b> Objectifs de la régression linéaire multiple et construction d’un modèle de régression</a></li>
<li class="chapter" data-level="7.2" data-path="sect072.html"><a href="sect072.html"><i class="fa fa-check"></i><b>7.2</b> Principes de base de la régression linéaire multiple</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="sect072.html"><a href="sect072.html#sect0721"><i class="fa fa-check"></i><b>7.2.1</b> Un peu d’équations…</a></li>
<li class="chapter" data-level="7.2.2" data-path="sect072.html"><a href="sect072.html#sect0722"><i class="fa fa-check"></i><b>7.2.2</b> Hypothèses de la régression linéaire multiple</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="sect073.html"><a href="sect073.html"><i class="fa fa-check"></i><b>7.3</b> Évaluation de la qualité d’ajustement du modèle</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="sect073.html"><a href="sect073.html#sect0731"><i class="fa fa-check"></i><b>7.3.1</b> Mesures de la qualité d’un modèle</a></li>
<li class="chapter" data-level="7.3.2" data-path="sect073.html"><a href="sect073.html#sect0732"><i class="fa fa-check"></i><b>7.3.2</b> Comparaison des modèles incrémentiels</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="sect074.html"><a href="sect074.html"><i class="fa fa-check"></i><b>7.4</b> Différentes mesures pour les coefficients de régression</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="sect074.html"><a href="sect074.html#sect0741"><i class="fa fa-check"></i><b>7.4.1</b> Coefficients de régression : évaluer l’effet des variables indépendantes</a></li>
<li class="chapter" data-level="7.4.2" data-path="sect074.html"><a href="sect074.html#sect0742"><i class="fa fa-check"></i><b>7.4.2</b> Coefficients de régression standardisés : repérer les variables les plus importantes du modèle</a></li>
<li class="chapter" data-level="7.4.3" data-path="sect074.html"><a href="sect074.html#sect0743"><i class="fa fa-check"></i><b>7.4.3</b> Significativité des coefficients de régression : valeurs de <em>t</em> et de <em>p</em></a></li>
<li class="chapter" data-level="7.4.4" data-path="sect074.html"><a href="sect074.html#sect0744"><i class="fa fa-check"></i><b>7.4.4</b> Intervalle de confiance des coefficients</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="sect075.html"><a href="sect075.html"><i class="fa fa-check"></i><b>7.5</b> Introduction de variables explicatives particulières</a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="sect075.html"><a href="sect075.html#sect0751"><i class="fa fa-check"></i><b>7.5.1</b> Exploration des relations non linéaires</a></li>
<li class="chapter" data-level="7.5.2" data-path="sect075.html"><a href="sect075.html#sect0752"><i class="fa fa-check"></i><b>7.5.2</b> Variable indépendante qualitative dichotomique</a></li>
<li class="chapter" data-level="7.5.3" data-path="sect075.html"><a href="sect075.html#sect0753"><i class="fa fa-check"></i><b>7.5.3</b> Variable indépendante qualitative polytomique</a></li>
<li class="chapter" data-level="7.5.4" data-path="sect075.html"><a href="sect075.html#sect0754"><i class="fa fa-check"></i><b>7.5.4</b> Variables d’interaction</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="sect076.html"><a href="sect076.html"><i class="fa fa-check"></i><b>7.6</b> Diagnostics de la régression</a>
<ul>
<li class="chapter" data-level="7.6.1" data-path="sect076.html"><a href="sect076.html#sect0761"><i class="fa fa-check"></i><b>7.6.1</b> Nombre d’observations</a></li>
<li class="chapter" data-level="7.6.2" data-path="sect076.html"><a href="sect076.html#sect0762"><i class="fa fa-check"></i><b>7.6.2</b> Normalité des résidus</a></li>
<li class="chapter" data-level="7.6.3" data-path="sect076.html"><a href="sect076.html#sect0763"><i class="fa fa-check"></i><b>7.6.3</b> Linéarité et homoscédasticité des résidus</a></li>
<li class="chapter" data-level="7.6.4" data-path="sect076.html"><a href="sect076.html#sect0764"><i class="fa fa-check"></i><b>7.6.4</b> Absence de multicolinéarité excessive</a></li>
<li class="chapter" data-level="7.6.5" data-path="sect076.html"><a href="sect076.html#sect0766"><i class="fa fa-check"></i><b>7.6.5</b> Absence d’observations aberrantes</a></li>
</ul></li>
<li class="chapter" data-level="7.7" data-path="sect077.html"><a href="sect077.html"><i class="fa fa-check"></i><b>7.7</b> Mise en œuvre dans R</a>
<ul>
<li class="chapter" data-level="7.7.1" data-path="sect077.html"><a href="sect077.html#sect0771"><i class="fa fa-check"></i><b>7.7.1</b> Fonctions <code>lm</code>, <code>summary()</code> et <code>confint()</code></a></li>
<li class="chapter" data-level="7.7.2" data-path="sect077.html"><a href="sect077.html#sect0772"><i class="fa fa-check"></i><b>7.7.2</b> Comparaison des modèles</a></li>
<li class="chapter" data-level="7.7.3" data-path="sect077.html"><a href="sect077.html#sect0773"><i class="fa fa-check"></i><b>7.7.3</b> Diagnostic sur un modèle</a></li>
<li class="chapter" data-level="7.7.4" data-path="sect077.html"><a href="sect077.html#sect0774"><i class="fa fa-check"></i><b>7.7.4</b> Graphiques pour les effets marginaux</a></li>
</ul></li>
<li class="chapter" data-level="7.8" data-path="sect078.html"><a href="sect078.html"><i class="fa fa-check"></i><b>7.8</b> Quiz de révision du chapitre</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="chap08.html"><a href="chap08.html"><i class="fa fa-check"></i><b>8</b> Régressions linéaires généralisées (GLM)</a>
<ul>
<li class="chapter" data-level="8.1" data-path="sect081.html"><a href="sect081.html"><i class="fa fa-check"></i><b>8.1</b> Qu’est qu’un modèle GLM?</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="sect081.html"><a href="sect081.html#sect0811"><i class="fa fa-check"></i><b>8.1.1</b> Formulation d’un GLM</a></li>
<li class="chapter" data-level="8.1.2" data-path="sect081.html"><a href="sect081.html#sect0812"><i class="fa fa-check"></i><b>8.1.2</b> Autres distributions et rôle de la fonction de lien</a></li>
<li class="chapter" data-level="8.1.3" data-path="sect081.html"><a href="sect081.html#sect0813"><i class="fa fa-check"></i><b>8.1.3</b> Conditions d’application</a></li>
<li class="chapter" data-level="8.1.4" data-path="sect081.html"><a href="sect081.html#sect0814"><i class="fa fa-check"></i><b>8.1.4</b> Résidus et déviance</a></li>
<li class="chapter" data-level="8.1.5" data-path="sect081.html"><a href="sect081.html#sect0815"><i class="fa fa-check"></i><b>8.1.5</b> Vérification l’ajustement</a></li>
<li class="chapter" data-level="8.1.6" data-path="sect081.html"><a href="sect081.html#sect0816"><i class="fa fa-check"></i><b>8.1.6</b> Comparaison de deux modèles GLM</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="sect082.html"><a href="sect082.html"><i class="fa fa-check"></i><b>8.2</b> Modèles GLM pour des variables qualitatives</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="sect082.html"><a href="sect082.html#sect0821"><i class="fa fa-check"></i><b>8.2.1</b> Modèle logistique binomial</a></li>
<li class="chapter" data-level="8.2.2" data-path="sect082.html"><a href="sect082.html#sect0822"><i class="fa fa-check"></i><b>8.2.2</b> Modèle probit binomial</a></li>
<li class="chapter" data-level="8.2.3" data-path="sect082.html"><a href="sect082.html#sect0823"><i class="fa fa-check"></i><b>8.2.3</b> Modèle logistique des cotes proportionnelles</a></li>
<li class="chapter" data-level="8.2.4" data-path="sect082.html"><a href="sect082.html#sect0824"><i class="fa fa-check"></i><b>8.2.4</b> Modèle logistique multinomial</a></li>
<li class="chapter" data-level="8.2.5" data-path="sect082.html"><a href="sect082.html#conclusion-sur-les-modèles-pour-des-variables-qualitatives"><i class="fa fa-check"></i><b>8.2.5</b> Conclusion sur les modèles pour des variables qualitatives</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="sect084.html"><a href="sect084.html"><i class="fa fa-check"></i><b>8.3</b> Modèles GLM pour des variables de comptage</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="sect084.html"><a href="sect084.html#sect0841"><i class="fa fa-check"></i><b>8.3.1</b> Modèle de Poisson</a></li>
<li class="chapter" data-level="8.3.2" data-path="sect084.html"><a href="sect084.html#sect0842"><i class="fa fa-check"></i><b>8.3.2</b> Modèle binomial négatif</a></li>
<li class="chapter" data-level="8.3.3" data-path="sect084.html"><a href="sect084.html#sect0843"><i class="fa fa-check"></i><b>8.3.3</b> Modèle de Poisson avec excès fixe de zéros</a></li>
<li class="chapter" data-level="8.3.4" data-path="sect084.html"><a href="sect084.html#sect0844"><i class="fa fa-check"></i><b>8.3.4</b> Modèle de Poisson avec excès ajusté de zéros</a></li>
<li class="chapter" data-level="8.3.5" data-path="sect084.html"><a href="sect084.html#sect0845"><i class="fa fa-check"></i><b>8.3.5</b> Conclusion sur les modèles destinés à des variables de comptage</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="sect085.html"><a href="sect085.html"><i class="fa fa-check"></i><b>8.4</b> Modèles GLM pour des variables continues</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="sect085.html"><a href="sect085.html#sect0851"><i class="fa fa-check"></i><b>8.4.1</b> Modèle GLM gaussien</a></li>
<li class="chapter" data-level="8.4.2" data-path="sect085.html"><a href="sect085.html#sect0852"><i class="fa fa-check"></i><b>8.4.2</b> Modèle GLM avec une distribution de Student</a></li>
<li class="chapter" data-level="8.4.3" data-path="sect085.html"><a href="sect085.html#sect0853"><i class="fa fa-check"></i><b>8.4.3</b> Modèle GLM avec distribution Gamma</a></li>
<li class="chapter" data-level="8.4.4" data-path="sect085.html"><a href="sect085.html#sect0854"><i class="fa fa-check"></i><b>8.4.4</b> Modèle GLM avec une distribution bêta</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="sect086.html"><a href="sect086.html"><i class="fa fa-check"></i><b>8.5</b> Conclusion sur les modèles linéaires généralisés</a></li>
<li class="chapter" data-level="8.6" data-path="sect087.html"><a href="sect087.html"><i class="fa fa-check"></i><b>8.6</b> Quiz de révision du chapitre</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="chap09.html"><a href="chap09.html"><i class="fa fa-check"></i><b>9</b> Régressions à effets mixtes (GLMM)</a>
<ul>
<li class="chapter" data-level="9.1" data-path="sect091.html"><a href="sect091.html"><i class="fa fa-check"></i><b>9.1</b> Introduction</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="sect091.html"><a href="sect091.html#sect0911"><i class="fa fa-check"></i><b>9.1.1</b> Indépendance des observations et effets de groupes</a></li>
<li class="chapter" data-level="9.1.2" data-path="sect091.html"><a href="sect091.html#sect0912"><i class="fa fa-check"></i><b>9.1.2</b> Terminologie: effets fixes et effets aléatoires</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="sect092.html"><a href="sect092.html"><i class="fa fa-check"></i><b>9.2</b> Principes de base des GLMM</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="sect092.html"><a href="sect092.html#sect0921"><i class="fa fa-check"></i><b>9.2.1</b> GLMM avec constantes aléatoires</a></li>
<li class="chapter" data-level="9.2.2" data-path="sect092.html"><a href="sect092.html#sect0923"><i class="fa fa-check"></i><b>9.2.2</b> GLMM avec pentes aléatoires</a></li>
<li class="chapter" data-level="9.2.3" data-path="sect092.html"><a href="sect092.html#sect0924"><i class="fa fa-check"></i><b>9.2.3</b> GLMM avec constantes et pentes aléatoires</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="sect093.html"><a href="sect093.html"><i class="fa fa-check"></i><b>9.3</b> Conditions d’application des GLMM</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="sect093.html"><a href="sect093.html#sect0931"><i class="fa fa-check"></i><b>9.3.1</b> Vérification de la distribution des effets aléatoires</a></li>
<li class="chapter" data-level="9.3.2" data-path="sect093.html"><a href="sect093.html#sect0932"><i class="fa fa-check"></i><b>9.3.2</b> Homogénéité des variances au sein des groupes</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="sect094.html"><a href="sect094.html"><i class="fa fa-check"></i><b>9.4</b> Inférence dans les modèles GLMM</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="sect094.html"><a href="sect094.html#sect0941"><i class="fa fa-check"></i><b>9.4.1</b> Inférence pour les effets fixes</a></li>
<li class="chapter" data-level="9.4.2" data-path="sect094.html"><a href="sect094.html#sect0942"><i class="fa fa-check"></i><b>9.4.2</b> Inférence pour les effets aléatoires, effet global</a></li>
<li class="chapter" data-level="9.4.3" data-path="sect094.html"><a href="sect094.html#sect0943"><i class="fa fa-check"></i><b>9.4.3</b> Inférence pour les effets aléatoires, des constantes et des pentes</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="sect095.html"><a href="sect095.html"><i class="fa fa-check"></i><b>9.5</b> Conclusion sur les GLMM</a></li>
<li class="chapter" data-level="9.6" data-path="sect096.html"><a href="sect096.html"><i class="fa fa-check"></i><b>9.6</b> Mise en œuvre des GLMM dans R</a>
<ul>
<li class="chapter" data-level="9.6.1" data-path="sect096.html"><a href="sect096.html#sect0961"><i class="fa fa-check"></i><b>9.6.1</b> Ajustement du modèle avec uniquement une constante aléatoire</a></li>
<li class="chapter" data-level="9.6.2" data-path="sect096.html"><a href="sect096.html#sect0962"><i class="fa fa-check"></i><b>9.6.2</b> Ajustement du modèle avec constantes et pentes aléatoires</a></li>
</ul></li>
<li class="chapter" data-level="9.7" data-path="sect097.html"><a href="sect097.html"><i class="fa fa-check"></i><b>9.7</b> Quiz de révision du chapitre</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="chap10.html"><a href="chap10.html"><i class="fa fa-check"></i><b>10</b> Régressions multiniveaux</a>
<ul>
<li class="chapter" data-level="10.1" data-path="sect101.html"><a href="sect101.html"><i class="fa fa-check"></i><b>10.1</b> Modèles multiniveaux : deux intérêts majeurs</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="sect101.html"><a href="sect101.html#sect1011"><i class="fa fa-check"></i><b>10.1.1</b> Répartition de la variance entre les différents niveaux</a></li>
<li class="chapter" data-level="10.1.2" data-path="sect101.html"><a href="sect101.html#sect1012"><i class="fa fa-check"></i><b>10.1.2</b> Estimation des coefficients aux différents niveaux</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="sect102.html"><a href="sect102.html"><i class="fa fa-check"></i><b>10.2</b> Différents types de modèles multiniveaux</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="sect102.html"><a href="sect102.html#sect1021"><i class="fa fa-check"></i><b>10.2.1</b> Description du jeu de données utilisé</a></li>
<li class="chapter" data-level="10.2.2" data-path="sect102.html"><a href="sect102.html#sect1022"><i class="fa fa-check"></i><b>10.2.2</b> Démarche classique pour les modèles multiniveaux</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="sect103.html"><a href="sect103.html"><i class="fa fa-check"></i><b>10.3</b> Conditions d’application des régressions multiniveaux</a></li>
<li class="chapter" data-level="10.4" data-path="sect104.html"><a href="sect104.html"><i class="fa fa-check"></i><b>10.4</b> Mise en œuvre dans R</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="sect104.html"><a href="sect104.html#sect1041"><i class="fa fa-check"></i><b>10.4.1</b> Le modèle vide</a></li>
<li class="chapter" data-level="10.4.2" data-path="sect104.html"><a href="sect104.html#sect1042"><i class="fa fa-check"></i><b>10.4.2</b> Modèle avec les variables indépendantes du niveau 1</a></li>
<li class="chapter" data-level="10.4.3" data-path="sect104.html"><a href="sect104.html#sect1043"><i class="fa fa-check"></i><b>10.4.3</b> Modèle avec les variables indépendantes aux niveaux 1 et 2</a></li>
<li class="chapter" data-level="10.4.4" data-path="sect104.html"><a href="sect104.html#sect10414"><i class="fa fa-check"></i><b>10.4.4</b> Modèle complet avec une interaction</a></li>
<li class="chapter" data-level="10.4.5" data-path="sect104.html"><a href="sect104.html#sect1045"><i class="fa fa-check"></i><b>10.4.5</b> Comparaison des quatre modèles</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="sect105.html"><a href="sect105.html"><i class="fa fa-check"></i><b>10.5</b> Quiz de révision du chapitre</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="chap11.html"><a href="chap11.html"><i class="fa fa-check"></i><b>11</b> Modèles généralisés additifs</a>
<ul>
<li class="chapter" data-level="11.1" data-path="sect111.html"><a href="sect111.html"><i class="fa fa-check"></i><b>11.1</b> Introduction</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="sect111.html"><a href="sect111.html#sect1111"><i class="fa fa-check"></i><b>11.1.1</b> Non linéarité fonctionnelle</a></li>
<li class="chapter" data-level="11.1.2" data-path="sect111.html"><a href="sect111.html#sect1112"><i class="fa fa-check"></i><b>11.1.2</b> Non linéarité avec des polynomiales</a></li>
<li class="chapter" data-level="11.1.3" data-path="sect111.html"><a href="sect111.html#sect1113"><i class="fa fa-check"></i><b>11.1.3</b> Non linéarité par segments</a></li>
<li class="chapter" data-level="11.1.4" data-path="sect111.html"><a href="sect111.html#sect1114"><i class="fa fa-check"></i><b>11.1.4</b> Non linéarité avec des <em>splines</em></a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="sect112.html"><a href="sect112.html"><i class="fa fa-check"></i><b>11.2</b> <em>Spline</em> de régression et <em>spline</em> de lissage</a></li>
<li class="chapter" data-level="11.3" data-path="sect113.html"><a href="sect113.html"><i class="fa fa-check"></i><b>11.3</b> Interprétation d’une <em>spline</em></a></li>
<li class="chapter" data-level="11.4" data-path="sect114.html"><a href="sect114.html"><i class="fa fa-check"></i><b>11.4</b> Multicolinéarité non linéaire</a></li>
<li class="chapter" data-level="11.5" data-path="sect115.html"><a href="sect115.html"><i class="fa fa-check"></i><b>11.5</b> <em>Splines</em> avancées</a>
<ul>
<li class="chapter" data-level="11.5.1" data-path="sect115.html"><a href="sect115.html#sect1151"><i class="fa fa-check"></i><b>11.5.1</b> <em>Splines</em> cycliques</a></li>
<li class="chapter" data-level="11.5.2" data-path="sect115.html"><a href="sect115.html#sect1152"><i class="fa fa-check"></i><b>11.5.2</b> Splines par groupe</a></li>
<li class="chapter" data-level="11.5.3" data-path="sect115.html"><a href="sect115.html#sect1153"><i class="fa fa-check"></i><b>11.5.3</b> <em>Splines</em> multivariées et <em>splines</em> d’interaction</a></li>
</ul></li>
<li class="chapter" data-level="11.6" data-path="sect116.html"><a href="sect116.html"><i class="fa fa-check"></i><b>11.6</b> Mise en oeuvre dans R</a></li>
<li class="chapter" data-level="11.7" data-path="sect117.html"><a href="sect117.html"><i class="fa fa-check"></i><b>11.7</b> GAMM</a></li>
<li class="chapter" data-level="11.8" data-path="sect118.html"><a href="sect118.html"><i class="fa fa-check"></i><b>11.8</b> Quiz de révision du chapitre</a></li>
</ul></li>
<li class="part"><span><b>V Analyses exploratoires multivariées</b></span></li>
<li class="chapter" data-level="12" data-path="chap12.html"><a href="chap12.html"><i class="fa fa-check"></i><b>12</b> Méthodes factorielles</a>
<ul>
<li class="chapter" data-level="12.1" data-path="sect121.html"><a href="sect121.html"><i class="fa fa-check"></i><b>12.1</b> Aperçu des méthodes factorielles</a>
<ul>
<li class="chapter" data-level="12.1.1" data-path="sect121.html"><a href="sect121.html#sect1211"><i class="fa fa-check"></i><b>12.1.1</b> Méthodes factorielles et types de données</a></li>
<li class="chapter" data-level="12.1.2" data-path="sect121.html"><a href="sect121.html#sect1212"><i class="fa fa-check"></i><b>12.1.2</b> Bref historique des méthodes factorielles</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="sect122.html"><a href="sect122.html"><i class="fa fa-check"></i><b>12.2</b> Analyses en composantes principales (ACP)</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="sect122.html"><a href="sect122.html#sect1221"><i class="fa fa-check"></i><b>12.2.1</b> Recherche d’une simplification</a></li>
<li class="chapter" data-level="12.2.2" data-path="sect122.html"><a href="sect122.html#sect1222"><i class="fa fa-check"></i><b>12.2.2</b> Aides à l’interprétation</a></li>
<li class="chapter" data-level="12.2.3" data-path="sect122.html"><a href="sect122.html#sect1223"><i class="fa fa-check"></i><b>12.2.3</b> Mise en œuvre dans R</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="sect123.html"><a href="sect123.html"><i class="fa fa-check"></i><b>12.3</b> Analyse factorielle des correspondances (AFC)</a>
<ul>
<li class="chapter" data-level="12.3.1" data-path="sect123.html"><a href="sect123.html#sect1231"><i class="fa fa-check"></i><b>12.3.1</b> Recherche d’une simplification basée sur la distance du khi-deux</a></li>
<li class="chapter" data-level="12.3.2" data-path="sect123.html"><a href="sect123.html#sect1232"><i class="fa fa-check"></i><b>12.3.2</b> Aides à l’interprétation</a></li>
<li class="chapter" data-level="12.3.3" data-path="sect123.html"><a href="sect123.html#sect1233"><i class="fa fa-check"></i><b>12.3.3</b> Mise en œuvre dans R</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="sect124.html"><a href="sect124.html"><i class="fa fa-check"></i><b>12.4</b> Analyse de correspondances multiples (ACM)</a>
<ul>
<li class="chapter" data-level="12.4.1" data-path="sect124.html"><a href="sect124.html#sect1241"><i class="fa fa-check"></i><b>12.4.1</b> Aides à l’interprétation</a></li>
<li class="chapter" data-level="12.4.2" data-path="sect124.html"><a href="sect124.html#sect1242"><i class="fa fa-check"></i><b>12.4.2</b> Mise en œuvre dans R</a></li>
</ul></li>
<li class="chapter" data-level="12.5" data-path="sect125.html"><a href="sect125.html"><i class="fa fa-check"></i><b>12.5</b> Quiz de révision du chapitre</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="chap13.html"><a href="chap13.html"><i class="fa fa-check"></i><b>13</b> Méthodes de classification non supervisée</a>
<ul>
<li class="chapter" data-level="13.1" data-path="sect131.html"><a href="sect131.html"><i class="fa fa-check"></i><b>13.1</b> Méthodes de classification : un aperçu</a></li>
<li class="chapter" data-level="13.2" data-path="sect132.html"><a href="sect132.html"><i class="fa fa-check"></i><b>13.2</b> Notions essentielles en classification</a>
<ul>
<li class="chapter" data-level="13.2.1" data-path="sect132.html"><a href="sect132.html#sect1321"><i class="fa fa-check"></i><b>13.2.1</b> Distance</a></li>
<li class="chapter" data-level="13.2.2" data-path="sect132.html"><a href="sect132.html#sect1322"><i class="fa fa-check"></i><b>13.2.2</b> Inertie</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="sect133.html"><a href="sect133.html"><i class="fa fa-check"></i><b>13.3</b> Classification ascendante hiérarchique</a>
<ul>
<li class="chapter" data-level="13.3.1" data-path="sect133.html"><a href="sect133.html#sect1331"><i class="fa fa-check"></i><b>13.3.1</b> Fonctionnement de l’algorithme</a></li>
<li class="chapter" data-level="13.3.2" data-path="sect133.html"><a href="sect133.html#sect1332"><i class="fa fa-check"></i><b>13.3.2</b> Choisir le bon nombre de groupes</a></li>
<li class="chapter" data-level="13.3.3" data-path="sect133.html"><a href="sect133.html#sect1333"><i class="fa fa-check"></i><b>13.3.3</b> Limites de la classification ascendante hiérarchique</a></li>
<li class="chapter" data-level="13.3.4" data-path="sect133.html"><a href="sect133.html#sect1334"><i class="fa fa-check"></i><b>13.3.4</b> Mise en oeuvre dans R</a></li>
</ul></li>
<li class="chapter" data-level="13.4" data-path="sect134.html"><a href="sect134.html"><i class="fa fa-check"></i><b>13.4</b> Nuées dynamiques</a>
<ul>
<li class="chapter" data-level="13.4.1" data-path="sect134.html"><a href="sect134.html#sect1341"><i class="fa fa-check"></i><b>13.4.1</b> <em>K-means</em></a></li>
<li class="chapter" data-level="13.4.2" data-path="sect134.html"><a href="sect134.html#sect1342"><i class="fa fa-check"></i><b>13.4.2</b> K-médianes</a></li>
<li class="chapter" data-level="13.4.3" data-path="sect134.html"><a href="sect134.html#sect1343"><i class="fa fa-check"></i><b>13.4.3</b> K-médoïds</a></li>
<li class="chapter" data-level="13.4.4" data-path="sect134.html"><a href="sect134.html#sect1344"><i class="fa fa-check"></i><b>13.4.4</b> Mise en oeuvre dans R</a></li>
<li class="chapter" data-level="13.4.5" data-path="sect134.html"><a href="sect134.html#sect1346"><i class="fa fa-check"></i><b>13.4.5</b> Extensions en logique floue : <em>c-means</em>, <em>c-medoids</em></a></li>
</ul></li>
<li class="chapter" data-level="13.5" data-path="sect135.html"><a href="sect135.html"><i class="fa fa-check"></i><b>13.5</b> Conclusion sur la cinquième partie</a></li>
<li class="chapter" data-level="13.6" data-path="sect136.html"><a href="sect136.html"><i class="fa fa-check"></i><b>13.6</b> Quiz de révision du chapitre</a></li>
</ul></li>
<li class="part"><span><b>VI Annexes</b></span></li>
<li class="chapter" data-level="14" data-path="annexe1.html"><a href="annexe1.html"><i class="fa fa-check"></i><b>14</b> Table des valeurs critiques de khi-deux</a></li>
<li class="chapter" data-level="15" data-path="annexe2.html"><a href="annexe2.html"><i class="fa fa-check"></i><b>15</b> Table des valeurs critiques de Fisher</a></li>
<li class="chapter" data-level="16" data-path="annexe3.html"><a href="annexe3.html"><i class="fa fa-check"></i><b>16</b> Table des valeurs critiques de <em>t</em></a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Méthodes quantitatives en sciences sociales : un grand bol d’R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="sect133" class="section level2 hasAnchor" number="13.3">
<h2><span class="header-section-number">13.3</span> Classification ascendante hiérarchique<a href="sect133.html#sect133" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>La classification ascendante hiérarchique (CAH) est un algorithme de classification non supervisée dont l’objectif est de créer un arbre de classification des observations. Cet arbre est ensuite utilisé pour déterminer le nombre de groupes à former et à quel groupe appartient chaque observation.</p>
<div id="sect1331" class="section level3 hasAnchor" number="13.3.1">
<h3><span class="header-section-number">13.3.1</span> Fonctionnement de l’algorithme<a href="sect133.html#sect1331" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>La classification ascendante hiérarchique est un algorithme permettant de regrouper les observations d’un jeu de données de façon itérative. À chaque itération, deux observations similaires sont agrégées en un groupe représenté par le point central entre les deux observations. Le processus est ensuite répété en considérant le nouveau point comme une observation jusqu’à ce que toutes les observations soient fusionnées en un seul groupe.</p>
<p>Ces regroupements successifs créent un arbre de classification appelé dendrogramme. La racine de cet arbre est le groupe unique fusionnant toutes les observations, et ses branches correspondent aux différentes agrégrations effectuées jusqu’aux observations individuelles. Cet arbre peut être vu comme une hiérarchie de classification. Chaque niveau de l’arbre est un regroupement de plus en plus généraliste au fur et à mesure que nous nous approchons de sa racine.</p>
<p>Pour appliquer cette méthode, il est nécessaire de sélectionner une <strong>fonction de distance</strong> pour mesurer la dissimilarité ou la ressemblance entre deux observations. L’algorithme fonctionne avec n’importe quelle fonction de distance, ce qui permet de l’appliquer aussi bien à des données qualitatives que quantitatives. En effet, l’opération de regroupement des observations se base sur une matrice de distance, soit un tableau de taille <em>n x n</em> indiquant pour chaque paire d’observations leur degré de dissimilarité. La figure <a href="sect133.html#fig:tablvsmat">13.11</a> illustre cette transformation en appliquant la distance du <span class="math inline">\(\Phi^2\)</span> à un jeu de données comprenant cinq observations et 5 variables qualitatives.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:tablvsmat"></span>
<img src="MethodesQuantitScSocialesBolR_files/figure-html/tablvsmat-1.png" alt="Du tableau de données à la matrice de distance" width="100%" />
<p class="caption">
Figure 13.11: Du tableau de données à la matrice de distance
</p>
</div>
<p>En plus de la fonction de distance, il est également nécessaire de sélectionner un <strong>critère d’agrégation</strong>, soit la règle permettant de décider à chaque itération quelles observations doivent être regroupées. Les méthodes les plus courantes sont :</p>
<ul>
<li>Le critère de Ward <span class="citation">(<a href="#ref-ward1963hierarchical" role="doc-biblioref">1963</a>)</span> : cette méthode consiste à agréger à chaque itération les deux observations permettant de minimiser la variance (ou l’inertie) intra-groupe, ce qui revient à maximiser l’inertie inter-groupe (autrement dit, à rendre les groupes les plus homogènes possible et les plus dissemblables entre eux). Ainsi, l’enjeu est de fusionner les deux observations permettant d’avoir les groupes les plus dissimilaires possible après fusion.</li>
<li>Le lien complet : à chaque itération, les deux groupes d’observations associés sont ceux pour lesquels la distance maximale entre les observations les composant est la plus petite parmi tous les groupes.</li>
<li>Le lien simple : à chaque itération, les deux groupes d’observations associés sont ceux pour lesquels la distance minimum entre les observations les composant est la plus petite parmi tous les groupes.</li>
</ul>
<p>La plus utilisée est de loin la méthode de Ward. La méthode du lien complet produit généralement des résultats similaires. En revanche, la méthode du lien simple peut produire des groupes non sphériques (non centrés sur leur moyenne) plus difficle à interpréter.</p>
<p>Prenons un instant pour visualiser cet algorithme (figure <a href="sect133.html#fig:animhclust">13.12</a>). Cette animation a été réalisée par David Sheehan et est également accessible sur son <a href="https://dashee87.github.io/data%20science/general/Clustering-with-Scikit-with-GIFs/">blog</a>. Elle présente bien le processus d’agglomération de la classification ascendante hiérarchique et la construction progressive du dendrogramme.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:animhclust"></span>
<img src="images/classification/CAH.gif" alt="Principe de fonctionnement de la classification ascendante hiérarchique (auteur : David Sheehan)" width="75%" />
<p class="caption">
Figure 13.12: Principe de fonctionnement de la classification ascendante hiérarchique (auteur : David Sheehan)
</p>
</div>
</div>
<div id="sect1332" class="section level3 hasAnchor" number="13.3.2">
<h3><span class="header-section-number">13.3.2</span> Choisir le bon nombre de groupes<a href="sect133.html#sect1332" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Une fois que l’algorithme a été appliqué aux données et le dendrogramme obtenu, il faut encore choisir le nombre optimal de groupes pour la classification finale. Chaque embranchement du dendrogramme constitue une classification possible, allant de la plus complexe (chaque observation appartient à un groupe formé d’elle seule) à la plus simple (toutes les observations appartiennent au même groupe). Si le nombre de groupes n’est pas connu à l’avance et qu’aucune forte justification théorique n’existe, il est possible d’utiliser plusieurs techniques pour déterminer un nombre de groupes judicieux à partir des données. Nous en présentons ici trois, mais il convient de ne pas s’en tenir uniquement à ses critères arbitraires. Il est important d’explorer les résultats de la classification obtenue pour plusieurs valeurs de <em>k</em> candidates et de tenir compte de la qualité des informations qu’elles fournissent. Au final, il est pertinent de retenir la classification dont les résultats offrent l’interprétation la plus claire avec un nombre de groupes réduit (principe de parcimonie).</p>
<div id="sect13321" class="section level4 hasAnchor" number="13.3.2.1">
<h4><span class="header-section-number">13.3.2.1</span> Méthode du coude<a href="sect133.html#sect13321" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Cette première approche est la plus simple à mettre en oeuvre. Il s’agit simplement de produire plusieurs classifications à partir du dendrogramme avec différentes valeurs de <em>k</em> (nombre de groupes) et de calculer à chaque fois la part de l’inertie expliquée. Chaque groupe supplémentaire ne peut qu’améliorer l’inertie expliquée, car pour rappel, si <span class="math inline">\(k=n\)</span>, alors nous expliquons 100 % de l’inertie totale. L’objectif est de déterminer à quel moment l’ajout d’un groupe supplémentaire ne contribue que de façon marginale à améliorer l’inertie expliquée. Si nous représentons les valeurs d’inertie expliquée pour les différentes valeurs de <em>k</em> dans un graphique, une rupture (un coude) indiquerait le point au-delà duquel les groupes supplémentaires ne captent finalement que du bruit et non plus de l’information.</p>
<p>Si nous reprenons l’exemple du jeu de données <code>IRIS</code>, nous pouvons créer ce graphique avec <em>k</em> allant de 2 à 8 (figure <a href="sect133.html#fig:kmeans2">13.13</a>). Un premier coude très net est observable pour <span class="math inline">\(k = 3\)</span> et un second plus faible, mais tout de même marqué pour <span class="math inline">\(k = 4\)</span>.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:kmeans2"></span>
<img src="MethodesQuantitScSocialesBolR_files/figure-html/kmeans2-1.png" alt="Méthode du coude" width="75%" />
<p class="caption">
Figure 13.13: Méthode du coude
</p>
</div>
<div class="bloc_notes">
<p><strong>Inertie expliquée et centre de groupe</strong></p>
<p>Pour calculer l’inertie expliquée, il est nécessaire de pouvoir déterminer pour le centre de gravité (ou centroïde) chaque groupe. Lorsque la distance euclidienne est utilisée, il s’agit simplement de calculer pour chaque groupe la valeur moyenne des différentes colonnes des observations. Cependant, lorsque d’autres distances sont utilisées, il peut être plus difficile de déterminer le centre d’un groupe. Avec la distance de Manhattan, il est par exemple recommandé d’utiliser la médiane des colonnes plutôt que la moyenne. Pour la distance de Hamming, la moyenne peut aussi être utilisée, car elle représente pour cette distance la fréquence d’occurrence des différentes modalités des variables qualitatives. Pour d’autres distances plus complexes, il est préférable de définir le centre d’un groupe comme le point de ce groupe minimisant les distances à tous les autres points du groupe. Il s’agit du médoïde du groupe.</p>
</div>
</div>
<div id="sect13322" class="section level4 hasAnchor" number="13.3.2.2">
<h4><span class="header-section-number">13.3.2.2</span> Indicateur de silhouette<a href="sect133.html#sect13322" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Si un coude net ne s’observe pas pour la méthode précédente, il est possible d’utiliser l’indicateur de silhouette. Il permet de mesurer pour une classification à quel point une observation est similaire à celles dans son propre groupe (cohésion) comparativement aux observations des autres groupes. Elle se calcule de la façon suivante :</p>
<p><span class="math display" id="eq:silhouetteidx">\[\begin{equation}  
\begin{aligned}
s(i) &amp;= \frac{b(i)-a(i)}{\max \{a(i), b(i)\}} \\
a(i) &amp;= \frac{1}{|C_i|-1}\sum_{j \in C_i,i \neq j}d(i,j) \\
b(i) &amp;= min_{i \neq j}\frac{1}{|C_j|}\sum_{j \in C_j}d(i,j)
\end{aligned}
\tag{13.9}
\end{equation}\]</span>
</p>
<p>avec <span class="math inline">\(s(i)\)</span> la valeur de l’indice de silhouette pour l’observation <em>i</em>, <span class="math inline">\(a(i)\)</span> la distance moyenne entre l’observation <em>i</em> et son groupe <span class="math inline">\(C_i\)</span> et <span class="math inline">\(b(i)\)</span> la distance minimale entre l’observation <em>i</em> et le centre de chaque autre groupe <span class="math inline">\(C_j\)</span>.</p>
<p>La valeur totale de l’indice est simplement la moyenne des valeurs moyennes des indices de silhouette au sein de chaque groupe. Une valeur plus élevée indique une meilleure classification. Il est nécessaire de déterminer le centre des groupes pour calculer cet indicateur ce qui peut être un exercice difficile quand une distance autre que la distance euclidienne est utilisée. Référez-vous à la note de la section précédente pour plus d’informations. L’indice de silhouette semble indiquer que seulement trois groupes serait un choix optimal, soit la valeur la plus haute (figure <a href="sect133.html#fig:kmeans3">13.14</a>).</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:kmeans3"></span>
<img src="MethodesQuantitScSocialesBolR_files/figure-html/kmeans3-1.png" alt="Méthode de l'indice de silhouette" width="75%" />
<p class="caption">
Figure 13.14: Méthode de l’indice de silhouette
</p>
</div>
</div>
<div id="sect13323" class="section level4 hasAnchor" number="13.3.2.3">
<h4><span class="header-section-number">13.3.2.3</span> Méthode GAP<a href="sect133.html#sect13323" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Cette méthode, proposée par <span class="citation">Tibshirani, Walther et Hastie (<a href="#ref-tibshirani2001estimating" role="doc-biblioref">2001</a>)</span>, consiste à comparer l’inertie intra-groupe (inexpliquée) avec l’inertie observée pour un jeu de données généré aléatoirement (distribution uniforme des valeurs entre le minimum et le maximum de chaque variable) pour différentes valeurs successives de <em>k</em>. Une fois ces calculs effectués, l’objectif est de trouver la valeur de <em>k</em> telle que la valeur de GAP à <em>k + 1</em> n’est pas plus grande qu’un écart type pour GAP à <em>k + 1</em>.</p>
<p>La statistique GAP est calculée ainsi :</p>
<p><span class="math display" id="eq:gapidx">\[\begin{equation}  
\begin{aligned}
GAP(k) = \frac{1}{\text{nsim}} \sum^{\text{nsim}}_{\text{sim} = 1} log(W_{ksim}) - log(W_k)
\end{aligned}
\tag{13.10}
\end{equation}\]</span>
</p>
<p>avec <span class="math inline">\(W_k\)</span> l’inertie non expliquée (intra-groupe), <span class="math inline">\(W_{ksim}\)</span> l’inertie non expliquée (intra-groupe) obtenue pour un jeu de données simulé et <em>k</em> le nombre de groupes.</p>
<p>L’idée est qu’une bonne classification doit produire des résultats plus structurés que ce que nous pourrions attendre du hasard. Chaque groupe supplémentaire permet de réduire l’inertie, mais lorsque l’ajout d’un groupe ne permet pas un gain significatif comparativement au hasard, alors l’ajout de ce groupe ne se justifie pas. À nouveau, il est possible de visualiser la situation avec un simple graphique (figure <a href="sect133.html#fig:kmeans4">13.15</a>). Selon cette méthode, il faudrait sélectionner quatre groupes, car il s’agit de la première valeur de <em>k</em> validant le critère de cette méthode. La seconde valeur retenue par cette méthode est 6.</p>
<pre><code>## Clustering k = 1,2,..., K.max (= 8): .. done
## Bootstrapping, b = 1,2,..., B (= 100)  [one &quot;.&quot; per sample]:
## .................................................. 50 
## .................................................. 100</code></pre>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:kmeans4"></span>
<img src="MethodesQuantitScSocialesBolR_files/figure-html/kmeans4-1.png" alt="Méthode GAP" width="75%" />
<p class="caption">
Figure 13.15: Méthode GAP
</p>
</div>
</div>
</div>
<div id="sect1333" class="section level3 hasAnchor" number="13.3.3">
<h3><span class="header-section-number">13.3.3</span> Limites de la classification ascendante hiérarchique<a href="sect133.html#sect1333" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Bien que très flexible (choix de la fonction de distance et du critère d’agrégation), la CAH fait face à un enjeu majeur : la vitesse d’exécution et la consommation de mémoire lorsque des grands jeux de données sont utilisés. En effet, il est nécessaire de calculer à chaque étape une matrice de distance entre les groupes. Si un jeu de données comprend 1000 observations, cette matrice comprend donc 1000 x 1000 cases, soit un million de distances. Même en divisant ce nombre par deux (les éléments de la matrice sont symétriques, donc <span class="math inline">\(d(ij) = d(ji)\)</span>), ce nombre augmente avec le carré du nombre d’observations. Pour de grands jeux de données, la CAH peut donc échouer à cause des limites de l’ordinateur utilisé. Il existe des versions plus performantes de l’algorithme réduisant cette limite, mais il convient de la garder en mémoire. Quand un très grand jeu de données doit être analysé, les méthodes des nuées dynamiques sont une solution à considérer.</p>
</div>
<div id="sect1334" class="section level3 hasAnchor" number="13.3.4">
<h3><span class="header-section-number">13.3.4</span> Mise en oeuvre dans R<a href="sect133.html#sect1334" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Nous proposons ici un exemple issu d’un article portant sur les parcs urbains de Montréal <span class="citation">(<a href="#ref-apparicio2010accessibilite" role="doc-biblioref">Apparicio et al. 2010</a>)</span>, dont l’objectif était notamment de classifier ces parcs en fonction de leur superficie et des équipements qu’ils comprennent, et ce, en utilisant la classification ascendante hiérarchique. Nous proposons ici de reproduire l’étape de classification effectuée dans cet article. La base de données comporte 653 parcs pour lesquels la présence de 18 équipements est codée comme un ensemble de variables binaires (0 signifiant absence et 1 présence). Nous disposons également de la taille de ces parcs, recodée en cinq catégories : moins d’un hectare, de 1 à 5 hectares, de 5 à 10 hectares, de 10 à 20 hectares et 20 hectares et plus. Le tableau <a href="sect133.html#tab:exampleHclust1DF">13.4</a> indique le nombre d’équipements recensés dans les parcs.</p>
<table>
<caption>
<span id="tab:exampleHclust1DF">Tableau 13.4: </span>Équipements recensés dans les différents parcs de Montréal
</caption>
<thead>
<tr>
<th style="text-align:left;">
Équipements
</th>
<th style="text-align:right;">
N
</th>
</tr>
</thead>
<tbody>
<tr grouplength="3">
<td colspan="2" style="border-bottom: 1px solid;">
<strong>Équipements pour les 0 à 4 ans</strong>
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Aire de jeux
</td>
<td style="text-align:right;">
601
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Pataugeoire
</td>
<td style="text-align:right;">
161
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Jeux d’eau
</td>
<td style="text-align:right;">
28
</td>
</tr>
<tr grouplength="7">
<td colspan="2" style="border-bottom: 1px solid;">
<strong>Terrains de sport</strong>
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Baseball
</td>
<td style="text-align:right;">
188
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Soccer (football)
</td>
<td style="text-align:right;">
169
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Basketball
</td>
<td style="text-align:right;">
144
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Tennis
</td>
<td style="text-align:right;">
125
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Football
</td>
<td style="text-align:right;">
36
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Volleyball
</td>
<td style="text-align:right;">
24
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Athlétisme
</td>
<td style="text-align:right;">
20
</td>
</tr>
<tr grouplength="4">
<td colspan="2" style="border-bottom: 1px solid;">
<strong>Équipements d’hiver</strong>
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Patinoire extérieure
</td>
<td style="text-align:right;">
241
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Glissade
</td>
<td style="text-align:right;">
30
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Piste de ski de fond
</td>
<td style="text-align:right;">
14
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Piste de raquette
</td>
<td style="text-align:right;">
9
</td>
</tr>
<tr grouplength="2">
<td colspan="2" style="border-bottom: 1px solid;">
<strong>Équipements spécialisés</strong>
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Parc de planches à roulettes
</td>
<td style="text-align:right;">
18
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Patins à roues alignées
</td>
<td style="text-align:right;">
8
</td>
</tr>
<tr grouplength="2">
<td colspan="2" style="border-bottom: 1px solid;">
<strong>Autres équipements</strong>
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Piscine intérieure
</td>
<td style="text-align:right;">
92
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Chemin de randonnée
</td>
<td style="text-align:right;">
15
</td>
</tr>
</tbody>
</table>
<p>Puisque notre jeu de données ne comporte que des variables qualitatives, nous utilisons la distance du <span class="math inline">\(\Phi^2\)</span> pour construire notre matrice de distance entre les parcs. Notons que, dans l’article original, la distance euclidienne au carrée avait été utilisée, alors nous n’obtiendrons probablement pas les mêmes résultats, car la distance du <span class="math inline">\(\Phi^2\)</span> tient compte des fréquences d’occurrence des modalités des variables qualitatives.</p>
<div id="sect13341" class="section level4 hasAnchor" number="13.3.4.1">
<h4><span class="header-section-number">13.3.4.1</span> Calcul de la matrice de distance<a href="sect133.html#sect13341" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>La première étape consiste donc à charger notre jeu de données et à calculer la matrice de distance.</p>
<div class="sourceCode" id="cb1130"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1130-1"><a href="sect133.html#cb1130-1" aria-hidden="true" tabindex="-1"></a><span class="co"># chargement du jeu de données et sélection des colonnes pour l&#39;analyse</span></span>
<span id="cb1130-2"><a href="sect133.html#cb1130-2" aria-hidden="true" tabindex="-1"></a>parcs <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;data/classification/Parcs.txt&quot;</span>, <span class="at">header =</span> <span class="cn">TRUE</span>, <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1130-3"><a href="sect133.html#cb1130-3" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> parcs[<span class="fu">c</span>(<span class="dv">5</span><span class="sc">:</span><span class="dv">22</span>, <span class="dv">27</span>)]</span></code></pre></div>
<p>Pour calculer la distance du <span class="math inline">\(\Phi^2\)</span>, nous utilisons la fonction <code>dist</code> du <em>package</em> <code>proxy</code> avec le paramètre <code>method = "Phi-squared"</code>. Elle requiert que l’ensemble des variables catégorielles soient converties en variables binaires. Pour cela, nous pouvons utiliser la fonction <code>dummy_cols</code> du <em>package</em> <code>fastDummies</code>.</p>
<div class="sourceCode" id="cb1131"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1131-1"><a href="sect133.html#cb1131-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(fastDummies)</span>
<span id="cb1131-2"><a href="sect133.html#cb1131-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(proxy)</span>
<span id="cb1131-3"><a href="sect133.html#cb1131-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1131-4"><a href="sect133.html#cb1131-4" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">dummy_cols</span>(X,<span class="at">select_columns =</span> <span class="st">&quot;HaTypo&quot;</span>,<span class="at">remove_selected_columns =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1131-5"><a href="sect133.html#cb1131-5" aria-hidden="true" tabindex="-1"></a>parc_distances <span class="ot">&lt;-</span> <span class="fu">dist</span>(<span class="fu">as.matrix</span>(X), <span class="at">method =</span> <span class="st">&quot;Phi-squared&quot;</span>)</span></code></pre></div>
</div>
<div id="sect13342" class="section level4 hasAnchor" number="13.3.4.2">
<h4><span class="header-section-number">13.3.4.2</span> Application de l’algorithme de classification ascendante hiérarchique<a href="sect133.html#sect13342" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Une fois la matrice obtenue, il ne reste plus qu’à appliquer la fonction <code>hclust</code> disponible de base dans R pour obtenir le dendrogramme. Comme dans l’article, nous utilisons le critère d’agrégation de Ward pour la création des groupes.</p>
<div class="sourceCode" id="cb1132"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1132-1"><a href="sect133.html#cb1132-1" aria-hidden="true" tabindex="-1"></a>dendogramme_parcs <span class="ot">&lt;-</span> <span class="fu">hclust</span>(parc_distances, <span class="at">method =</span> <span class="st">&quot;ward.D&quot;</span>)</span></code></pre></div>
<p>Puisque nous n’utilisons pas la distance euclidienne, nous optons ici pour l’indice de silhouette pour déterminer le nombre adéquat de groupes à former. Nous testons toutes les valeurs comprises entre 2 et 10.</p>
<div class="sourceCode" id="cb1133"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1133-1"><a href="sect133.html#cb1133-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(cluster)</span>
<span id="cb1133-2"><a href="sect133.html#cb1133-2" aria-hidden="true" tabindex="-1"></a>ks <span class="ot">&lt;-</span> <span class="dv">2</span><span class="sc">:</span><span class="dv">10</span></span>
<span id="cb1133-3"><a href="sect133.html#cb1133-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1133-4"><a href="sect133.html#cb1133-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcul des indices de silhouette pour les différentes valeurs de k</span></span>
<span id="cb1133-5"><a href="sect133.html#cb1133-5" aria-hidden="true" tabindex="-1"></a>values <span class="ot">&lt;-</span> <span class="fu">sapply</span>(ks, <span class="cf">function</span>(k){</span>
<span id="cb1133-6"><a href="sect133.html#cb1133-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># découpage du dendrogramme</span></span>
<span id="cb1133-7"><a href="sect133.html#cb1133-7" aria-hidden="true" tabindex="-1"></a>  groupes <span class="ot">&lt;-</span> <span class="fu">cutree</span>(dendogramme_parcs, <span class="at">k =</span> k)</span>
<span id="cb1133-8"><a href="sect133.html#cb1133-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># calcul des valeurs de silhouette</span></span>
<span id="cb1133-9"><a href="sect133.html#cb1133-9" aria-hidden="true" tabindex="-1"></a>  sil <span class="ot">&lt;-</span> <span class="fu">silhouette</span>(groupes, <span class="at">dist =</span> parc_distances)</span>
<span id="cb1133-10"><a href="sect133.html#cb1133-10" aria-hidden="true" tabindex="-1"></a>  <span class="co"># extraction de l&#39;indice global (moyenne des moyennes)</span></span>
<span id="cb1133-11"><a href="sect133.html#cb1133-11" aria-hidden="true" tabindex="-1"></a>  idx <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">summary</span>(sil)<span class="sc">$</span>clus.avg.widths)</span>
<span id="cb1133-12"><a href="sect133.html#cb1133-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(idx)</span>
<span id="cb1133-13"><a href="sect133.html#cb1133-13" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb1133-14"><a href="sect133.html#cb1133-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1133-15"><a href="sect133.html#cb1133-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Création d&#39;un graphique avec les résultats</span></span>
<span id="cb1133-16"><a href="sect133.html#cb1133-16" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">k =</span> ks,  <span class="at">silhouette =</span> values)</span>
<span id="cb1133-17"><a href="sect133.html#cb1133-17" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df) <span class="sc">+</span> </span>
<span id="cb1133-18"><a href="sect133.html#cb1133-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> k, <span class="at">y =</span> silhouette)) <span class="sc">+</span> </span>
<span id="cb1133-19"><a href="sect133.html#cb1133-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> k, <span class="at">y =</span> silhouette), <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span> </span>
<span id="cb1133-20"><a href="sect133.html#cb1133-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;nombre de groupes&quot;</span>, <span class="at">y=</span><span class="st">&quot;indice global de silhouette&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:exampleHclust4"></span>
<img src="MethodesQuantitScSocialesBolR_files/figure-html/exampleHclust4-1.png" alt="Valeur de l'indice de silhouette pour différents nombres de groupes" width="75%" />
<p class="caption">
Figure 13.16: Valeur de l’indice de silhouette pour différents nombres de groupes
</p>
</div>
<p>Si nous écartons d’emblée les résultats pour k = 2 et k = 3 (trop peu de groupes pour l’interprétation), nous constatons que la solution optimale selon ce critère est k = 5. Dans l’article original, la solution k = 6 avait été retenue en examinant le dendrogramme. Comparons les résultats pour k = 5 et k = 6.</p>
<div class="sourceCode" id="cb1134"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1134-1"><a href="sect133.html#cb1134-1" aria-hidden="true" tabindex="-1"></a>resk5 <span class="ot">&lt;-</span> <span class="fu">cutree</span>(dendogramme_parcs, <span class="at">k =</span> <span class="dv">5</span>)</span>
<span id="cb1134-2"><a href="sect133.html#cb1134-2" aria-hidden="true" tabindex="-1"></a>resk6 <span class="ot">&lt;-</span> <span class="fu">cutree</span>(dendogramme_parcs, <span class="at">k =</span> <span class="dv">6</span>)</span>
<span id="cb1134-3"><a href="sect133.html#cb1134-3" aria-hidden="true" tabindex="-1"></a>sil5 <span class="ot">&lt;-</span> <span class="fu">silhouette</span>(resk5, <span class="at">dist =</span> parc_distances)</span>
<span id="cb1134-4"><a href="sect133.html#cb1134-4" aria-hidden="true" tabindex="-1"></a>sil6 <span class="ot">&lt;-</span> <span class="fu">silhouette</span>(resk6, <span class="at">dist =</span> parc_distances)</span>
<span id="cb1134-5"><a href="sect133.html#cb1134-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1134-6"><a href="sect133.html#cb1134-6" aria-hidden="true" tabindex="-1"></a><span class="co"># résumé pour l&#39;indice de silhouette pour k = 5</span></span>
<span id="cb1134-7"><a href="sect133.html#cb1134-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(sil5)</span></code></pre></div>
<pre><code>## Silhouette of 693 units in 5 clusters from silhouette.default(x = resk5, dist = parc_distances) :
##  Cluster sizes and average silhouette widths:
##         116         212         246          84          35 
##  0.07029553  1.00000000 -0.11827930 -0.19969707  1.00000000 
## Individual silhouette widths:
##     Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
## -0.62041 -0.08502  0.09814  0.30200  1.00000  1.00000</code></pre>
<div class="sourceCode" id="cb1136"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1136-1"><a href="sect133.html#cb1136-1" aria-hidden="true" tabindex="-1"></a><span class="co"># résumé pour l&#39;indice de silhouette pour k = 6</span></span>
<span id="cb1136-2"><a href="sect133.html#cb1136-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(sil6)</span></code></pre></div>
<pre><code>## Silhouette of 693 units in 6 clusters from silhouette.default(x = resk6, dist = parc_distances) :
##  Cluster sizes and average silhouette widths:
##         116         212         197          49          84          35 
##  0.05906553  1.00000000 -0.10289391  0.07935325 -0.19969707  1.00000000 
## Individual silhouette widths:
##     Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
## -0.62041 -0.06414  0.10998  0.31846  1.00000  1.00000</code></pre>
<p>Nous constatons que le groupe supplémentaire vient séparer le groupe trois comprenant 246 parcs dans la solution avec k = 5. Ce dernier ne comprend plus que 197 parcs pour la solution k = 6 et le nouveau groupe en compte 49. Ce nouveau groupe à un indice de silhouette moyen relativement faible (0,079), et le fait de découper le groupe trois améliore très peu sa propre valeur (passant de -0,12 à -0,10). Nous retenons cependant ici la solution avec k = 6 afin de tenter de reproduire les résultats de l’article.</p>
</div>
<div id="sect13343" class="section level4 hasAnchor" number="13.3.4.3">
<h4><span class="header-section-number">13.3.4.3</span> Interprétation des résultats<a href="sect133.html#sect13343" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>La dernière étape consiste à identifier les groupes obtenus et leur attribuer un intitulé en fonction de leurs caractéristiques. Dans notre cas, la classification ne comporte que des variables binaires, nous pouvons donc calculer le pourcentage de valeurs à 1 (présence d’un équipement) dans chacun des groupes.</p>
<div class="sourceCode" id="cb1138"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1138-1"><a href="sect133.html#cb1138-1" aria-hidden="true" tabindex="-1"></a><span class="co"># calcul du nombre de fois où chaque modalité est observée dans un groupe</span></span>
<span id="cb1138-2"><a href="sect133.html#cb1138-2" aria-hidden="true" tabindex="-1"></a>X<span class="sc">$</span>groupe <span class="ot">&lt;-</span> resk6</span>
<span id="cb1138-3"><a href="sect133.html#cb1138-3" aria-hidden="true" tabindex="-1"></a>df_groupes <span class="ot">&lt;-</span> X <span class="sc">%&gt;%</span> </span>
<span id="cb1138-4"><a href="sect133.html#cb1138-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(groupe) <span class="sc">%&gt;%</span> <span class="fu">summarise_all</span>(<span class="at">.funs =</span> sum)</span>
<span id="cb1138-5"><a href="sect133.html#cb1138-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1138-6"><a href="sect133.html#cb1138-6" aria-hidden="true" tabindex="-1"></a><span class="co"># calcul du nombre d&#39;observations par groupe</span></span>
<span id="cb1138-7"><a href="sect133.html#cb1138-7" aria-hidden="true" tabindex="-1"></a>nb_gp <span class="ot">&lt;-</span> <span class="fu">table</span>(resk6)</span>
<span id="cb1138-8"><a href="sect133.html#cb1138-8" aria-hidden="true" tabindex="-1"></a>groupe_ratios <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="dv">100</span> <span class="sc">*</span> <span class="fu">as.matrix</span>(df_groupes)[,<span class="dv">2</span><span class="sc">:</span><span class="fu">ncol</span>(df_groupes)] <span class="sc">/</span> <span class="fu">as.vector</span>(nb_gp),<span class="dv">1</span>)</span>
<span id="cb1138-9"><a href="sect133.html#cb1138-9" aria-hidden="true" tabindex="-1"></a>groupe_ratios <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">t</span>(groupe_ratios))</span>
<span id="cb1138-10"><a href="sect133.html#cb1138-10" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(groupe_ratios) <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="st">&quot;groupe &quot;</span>, <span class="dv">1</span><span class="sc">:</span><span class="fu">ncol</span>(groupe_ratios))</span>
<span id="cb1138-11"><a href="sect133.html#cb1138-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1138-12"><a href="sect133.html#cb1138-12" aria-hidden="true" tabindex="-1"></a><span class="co"># calcul du nombre moyen d&#39;équipements par catégorie par parc</span></span>
<span id="cb1138-13"><a href="sect133.html#cb1138-13" aria-hidden="true" tabindex="-1"></a>equip_class <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb1138-14"><a href="sect133.html#cb1138-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">c</span>(<span class="st">&quot;AIRE_JEUX&quot;</span>, <span class="st">&quot;JEUX_EAU&quot;</span>, <span class="st">&quot;PATAUGEOIRE&quot;</span>),</span>
<span id="cb1138-15"><a href="sect133.html#cb1138-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">c</span>(<span class="st">&quot;ATHLETISME&quot;</span>, <span class="st">&quot;BASEBALL_S&quot;</span>, <span class="st">&quot;BASKETBALL&quot;</span>, <span class="st">&quot;FOOTBALL&quot;</span>, <span class="st">&quot;SOCCER&quot;</span>, <span class="st">&quot;TENNIS&quot;</span>, <span class="st">&quot;VOLLEY_BALL&quot;</span>),</span>
<span id="cb1138-16"><a href="sect133.html#cb1138-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">c</span>(<span class="st">&quot;TOBBOGAN_G&quot;</span>, <span class="st">&quot;PATINOIRE_E&quot;</span>, <span class="st">&quot;RAQUETTES&quot;</span>, <span class="st">&quot;SKI_FOND&quot;</span>),</span>
<span id="cb1138-17"><a href="sect133.html#cb1138-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">c</span>(<span class="st">&quot;PATIN_ROUE&quot;</span>, <span class="st">&quot;ROULI_ROUL&quot;</span>),</span>
<span id="cb1138-18"><a href="sect133.html#cb1138-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">c</span>(<span class="st">&quot;PISC_EXT&quot;</span>, <span class="st">&quot;RANDONNEE&quot;</span>)</span>
<span id="cb1138-19"><a href="sect133.html#cb1138-19" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1138-20"><a href="sect133.html#cb1138-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1138-21"><a href="sect133.html#cb1138-21" aria-hidden="true" tabindex="-1"></a>class_compte <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="fu">sapply</span>(equip_class, <span class="cf">function</span>(equip){</span>
<span id="cb1138-22"><a href="sect133.html#cb1138-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rowSums</span>(X[equip])</span>
<span id="cb1138-23"><a href="sect133.html#cb1138-23" aria-hidden="true" tabindex="-1"></a>}))</span>
<span id="cb1138-24"><a href="sect133.html#cb1138-24" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(class_compte) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;enfants&quot;</span>, <span class="st">&quot;terrain_sport&quot;</span>, <span class="st">&quot;hiver&quot;</span>, <span class="st">&quot;specialise&quot;</span>, <span class="st">&quot;autre&quot;</span>)</span>
<span id="cb1138-25"><a href="sect133.html#cb1138-25" aria-hidden="true" tabindex="-1"></a>class_compte<span class="sc">$</span>groupe <span class="ot">&lt;-</span> resk6</span>
<span id="cb1138-26"><a href="sect133.html#cb1138-26" aria-hidden="true" tabindex="-1"></a>df_class_equip <span class="ot">&lt;-</span> class_compte <span class="sc">%&gt;%</span> </span>
<span id="cb1138-27"><a href="sect133.html#cb1138-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(groupe) <span class="sc">%&gt;%</span> </span>
<span id="cb1138-28"><a href="sect133.html#cb1138-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise_all</span>(mean)</span>
<span id="cb1138-29"><a href="sect133.html#cb1138-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1138-30"><a href="sect133.html#cb1138-30" aria-hidden="true" tabindex="-1"></a>df_class_equip <span class="ot">&lt;-</span> <span class="fu">t</span>(df_class_equip[<span class="dv">2</span><span class="sc">:</span><span class="fu">ncol</span>(df_class_equip)])</span>
<span id="cb1138-31"><a href="sect133.html#cb1138-31" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(df_class_equip) <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="st">&quot;groupe &quot;</span>, <span class="dv">1</span><span class="sc">:</span><span class="fu">ncol</span>(df_class_equip))</span>
<span id="cb1138-32"><a href="sect133.html#cb1138-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1138-33"><a href="sect133.html#cb1138-33" aria-hidden="true" tabindex="-1"></a><span class="co"># comptage du nombre moyen total d&#39;équipements</span></span>
<span id="cb1138-34"><a href="sect133.html#cb1138-34" aria-hidden="true" tabindex="-1"></a>df_equip_tot <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb1138-35"><a href="sect133.html#cb1138-35" aria-hidden="true" tabindex="-1"></a>  <span class="at">nb =</span> <span class="fu">rowSums</span>(X[<span class="dv">1</span><span class="sc">:</span><span class="dv">18</span>]),</span>
<span id="cb1138-36"><a href="sect133.html#cb1138-36" aria-hidden="true" tabindex="-1"></a>  <span class="at">groupe =</span> resk6</span>
<span id="cb1138-37"><a href="sect133.html#cb1138-37" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1138-38"><a href="sect133.html#cb1138-38" aria-hidden="true" tabindex="-1"></a>df_equip_tot_mean <span class="ot">&lt;-</span> df_equip_tot <span class="sc">%&gt;%</span> </span>
<span id="cb1138-39"><a href="sect133.html#cb1138-39" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(groupe) <span class="sc">%&gt;%</span> </span>
<span id="cb1138-40"><a href="sect133.html#cb1138-40" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize_all</span>(mean)</span>
<span id="cb1138-41"><a href="sect133.html#cb1138-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1138-42"><a href="sect133.html#cb1138-42" aria-hidden="true" tabindex="-1"></a><span class="co"># mise dans l&#39;ordre de la première partie du tableau</span></span>
<span id="cb1138-43"><a href="sect133.html#cb1138-43" aria-hidden="true" tabindex="-1"></a>all_types <span class="ot">&lt;-</span> <span class="fu">do.call</span>(c,equip_class)</span>
<span id="cb1138-44"><a href="sect133.html#cb1138-44" aria-hidden="true" tabindex="-1"></a>idxs <span class="ot">&lt;-</span> <span class="fu">match</span>(all_types,<span class="fu">row.names</span>(groupe_ratios[<span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(all_types),]))</span>
<span id="cb1138-45"><a href="sect133.html#cb1138-45" aria-hidden="true" tabindex="-1"></a>groupe_ratios <span class="ot">&lt;-</span> <span class="fu">rbind</span>(groupe_ratios[idxs,],</span>
<span id="cb1138-46"><a href="sect133.html#cb1138-46" aria-hidden="true" tabindex="-1"></a>                       groupe_ratios[(<span class="fu">length</span>(all_types)<span class="sc">+</span><span class="dv">1</span>)<span class="sc">:</span><span class="fu">nrow</span>(groupe_ratios),])</span>
<span id="cb1138-47"><a href="sect133.html#cb1138-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1138-48"><a href="sect133.html#cb1138-48" aria-hidden="true" tabindex="-1"></a><span class="co"># combinaison des deux tableaux</span></span>
<span id="cb1138-49"><a href="sect133.html#cb1138-49" aria-hidden="true" tabindex="-1"></a>groupe_ratios <span class="ot">&lt;-</span> <span class="fu">rbind</span>(groupe_ratios, df_class_equip, df_equip_tot_mean<span class="sc">$</span>nb, <span class="fu">as.integer</span>(nb_gp))</span></code></pre></div>
<p>Il est ensuite possible d’afficher le tableau obtenu pour l’interpréter. Les résultats sont ici rapportés au tableau <a href="sect133.html#tab:exampleHclust7">13.5</a>.</p>
<table>
<caption>
<span id="tab:exampleHclust7">Tableau 13.5: </span>Caractéristiques des groupes obtenus lors de la CAH
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
groupe 1
</th>
<th style="text-align:right;">
groupe 2
</th>
<th style="text-align:right;">
groupe 3
</th>
<th style="text-align:right;">
groupe 4
</th>
<th style="text-align:right;">
groupe 5
</th>
<th style="text-align:right;">
groupe 6
</th>
</tr>
</thead>
<tbody>
<tr grouplength="3">
<td colspan="7" style="border-bottom: 1px solid;">
<strong>Équipements pour les 0 à 4 ans (%)</strong>
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Aire de jeux
</td>
<td style="text-align:right;">
69,8
</td>
<td style="text-align:right;">
100
</td>
<td style="text-align:right;">
83,2
</td>
<td style="text-align:right;">
71,4
</td>
<td style="text-align:right;">
88,1
</td>
<td style="text-align:right;">
100
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Jeux d’eau
</td>
<td style="text-align:right;">
7,8
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
2,5
</td>
<td style="text-align:right;">
18,4
</td>
<td style="text-align:right;">
6,0
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Pataugeoire
</td>
<td style="text-align:right;">
36,2
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
47,2
</td>
<td style="text-align:right;">
2,0
</td>
<td style="text-align:right;">
29,8
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr grouplength="7">
<td colspan="7" style="border-bottom: 1px solid;">
<strong>Terrains de sport (%)</strong>
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Athlétisme
</td>
<td style="text-align:right;">
12,1
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
2,0
</td>
<td style="text-align:right;">
2,0
</td>
<td style="text-align:right;">
1,2
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Baseball
</td>
<td style="text-align:right;">
62,1
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
50,8
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
19,0
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Basketball
</td>
<td style="text-align:right;">
37,9
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
36,0
</td>
<td style="text-align:right;">
16,3
</td>
<td style="text-align:right;">
21,4
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Football américain
</td>
<td style="text-align:right;">
15,5
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
7,1
</td>
<td style="text-align:right;">
8,2
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Soccer (football)
</td>
<td style="text-align:right;">
52,6
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
29,9
</td>
<td style="text-align:right;">
87,8
</td>
<td style="text-align:right;">
7,1
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Tennis
</td>
<td style="text-align:right;">
38,8
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
32,5
</td>
<td style="text-align:right;">
8,2
</td>
<td style="text-align:right;">
14,3
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Volleyball
</td>
<td style="text-align:right;">
7,8
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
4,6
</td>
<td style="text-align:right;">
12,2
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr grouplength="4">
<td colspan="7" style="border-bottom: 1px solid;">
<strong>Équipements d’hiver (%)</strong>
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Glissade
</td>
<td style="text-align:right;">
19,8
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
3,0
</td>
<td style="text-align:right;">
2,0
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Patinoire
</td>
<td style="text-align:right;">
58,6
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
59,4
</td>
<td style="text-align:right;">
34,7
</td>
<td style="text-align:right;">
46,4
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Piste de ski de fond
</td>
<td style="text-align:right;">
7,8
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Raquettes
</td>
<td style="text-align:right;">
12,1
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr grouplength="2">
<td colspan="7" style="border-bottom: 1px solid;">
<strong>Équipements spécialisés (%)</strong>
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Parc de planches à roulettes
</td>
<td style="text-align:right;">
6,0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0,5
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Patins à roues alignées
</td>
<td style="text-align:right;">
8,6
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
4,1
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr grouplength="2">
<td colspan="7" style="border-bottom: 1px solid;">
<strong>Autres équipements (%)</strong>
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Piscine extérieure
</td>
<td style="text-align:right;">
27,6
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
27,4
</td>
<td style="text-align:right;">
4,1
</td>
<td style="text-align:right;">
4,8
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Chemin de randonnée
</td>
<td style="text-align:right;">
12,9
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr grouplength="5">
<td colspan="7" style="border-bottom: 1px solid;">
<strong>Superficie (%)</strong>
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Moins d’un hectare
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
100
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
100,0
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
1 à 5 hectares
</td>
<td style="text-align:right;">
5,2
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
98,5
</td>
<td style="text-align:right;">
100,0
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
100
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
5 à 10 hectares
</td>
<td style="text-align:right;">
61,2
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
10 à 20 hectares
</td>
<td style="text-align:right;">
17,2
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1,0
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
20 hectares et plus
</td>
<td style="text-align:right;">
16,4
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0,5
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr grouplength="6">
<td colspan="7" style="border-bottom: 1px solid;">
<strong>Nombre moyen d’équipement du type</strong>
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Équipements pour les 0 à 4 ans
</td>
<td style="text-align:right;">
1,1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1,3
</td>
<td style="text-align:right;">
0,9
</td>
<td style="text-align:right;">
1,2
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Terrains de sport
</td>
<td style="text-align:right;">
2,3
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1,6
</td>
<td style="text-align:right;">
1,3
</td>
<td style="text-align:right;">
0,6
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Équipements d’hiver
</td>
<td style="text-align:right;">
1,0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0,6
</td>
<td style="text-align:right;">
0,4
</td>
<td style="text-align:right;">
0,5
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Équipements spécialisés
</td>
<td style="text-align:right;">
0,1
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Autres équipements
</td>
<td style="text-align:right;">
0,4
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0,3
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Tous les équipements
</td>
<td style="text-align:right;">
4,9
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3,9
</td>
<td style="text-align:right;">
2,7
</td>
<td style="text-align:right;">
2,4
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr grouplength="1">
<td colspan="7" style="border-bottom: 1px solid;">
<strong>Nombre d’observations par groupe</strong>
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
</td>
<td style="text-align:right;">
116,0
</td>
<td style="text-align:right;">
212
</td>
<td style="text-align:right;">
197,0
</td>
<td style="text-align:right;">
49,0
</td>
<td style="text-align:right;">
84,0
</td>
<td style="text-align:right;">
35
</td>
</tr>
</tbody>
</table>
<ul>
<li><p>Le premier groupe correspond à de grands parcs (superficie généralement comprise entre 5 et plus de 20 hectares), il comporte 116 observations. Ces grands parcs sont en moyenne équipés de deux terrains de sport et d’un équipement d’hiver. Il s’agit vraisemblablement des grands parcs identifiés dans l’article original, dans lesquels se retrouvent également les parcs à vocation métropolitaine.</p></li>
<li><p>Le second groupe (212 parcs) correspond à de très petits parcs (moins d’un hectare) comportant uniquement une aire de jeu.</p></li>
<li><p>Le troisième groupe (197 parcs) correspond à de petits parcs (entre 1 et 5 hectares), souvent équipés d’une piscine extérieure (27,4 % des cas), et en moyenne de deux terrains de sports (essentiellement des terrains de tennis et de soccer). Ces parcs comprennent en moyenne plus de 4 équipements et doivent donc correspondre à la classe D dans l’article original (Petit parc (1 à 5 ha) avec en moyenne six équipements, dont une patinoire et une piscine).</p></li>
<li><p>Le quatrième groupe (49 parcs) comprend de petits parcs (entre 1 et 5 hectares) qui ressemblent aux parcs du groupe 2 mais tendent à disposer en plus d’un terrain de sport (baseball ou basketball).</p></li>
<li><p>Le quatrième groupe (84 parcs) correspond à de petits parcs, il est caractérisé par une présence plus marquée de pataugeoires (39 %).</p></li>
<li><p>Le cinquième groupe (35 parcs) est très similaire au second groupe (uniquement une aire de jeux), excepté sont les parcs qui s’y trouvent sont de taille supérieure (de 1 à 5 hectares).</p></li>
</ul>
<p>Considérant les différences minimes entre certains des groupes que nous avons obtenus, il est clair que retenir seulement trois ou cinq groupes serait préférable. Notez également l’importance du choix de la distance, car nous obtenons des résultats sensiblement différents de ceux de l’article original en ayant opté pour la distance du <span class="math inline">\(\Phi^2\)</span> plutôt que la distance euclidienne au carré.</p>
</div>
<div id="sect13344" class="section level4 hasAnchor" number="13.3.4.4">
<h4><span class="header-section-number">13.3.4.4</span> Utilisation de la matrice de distance eucidienne au carré<a href="sect133.html#sect13344" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Pour obtenir des résultats plus proches de ceux de l’article original, nous pouvons reprendre notre analyse et utiliser cette fois-ci une distance euclidienne au carré.</p>
<div class="sourceCode" id="cb1139"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1139-1"><a href="sect133.html#cb1139-1" aria-hidden="true" tabindex="-1"></a>X<span class="sc">$</span>groupe <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb1139-2"><a href="sect133.html#cb1139-2" aria-hidden="true" tabindex="-1"></a><span class="co"># calcule de la matrice de distance</span></span>
<span id="cb1139-3"><a href="sect133.html#cb1139-3" aria-hidden="true" tabindex="-1"></a>parc_distances_euc <span class="ot">&lt;-</span> <span class="fu">dist</span>(<span class="fu">as.matrix</span>(X), <span class="at">method =</span> <span class="st">&quot;Euclidean&quot;</span>)<span class="sc">**</span><span class="dv">2</span></span>
<span id="cb1139-4"><a href="sect133.html#cb1139-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1139-5"><a href="sect133.html#cb1139-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Application de la CAH</span></span>
<span id="cb1139-6"><a href="sect133.html#cb1139-6" aria-hidden="true" tabindex="-1"></a>dendogramme_parcs_euc <span class="ot">&lt;-</span> <span class="fu">hclust</span>(parc_distances_euc, <span class="at">method =</span> <span class="st">&quot;ward.D&quot;</span>)</span>
<span id="cb1139-7"><a href="sect133.html#cb1139-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1139-8"><a href="sect133.html#cb1139-8" aria-hidden="true" tabindex="-1"></a><span class="co"># calcul de l&#39;indice de silhouette</span></span>
<span id="cb1139-9"><a href="sect133.html#cb1139-9" aria-hidden="true" tabindex="-1"></a>ks <span class="ot">&lt;-</span> <span class="dv">2</span><span class="sc">:</span><span class="dv">10</span></span>
<span id="cb1139-10"><a href="sect133.html#cb1139-10" aria-hidden="true" tabindex="-1"></a>values <span class="ot">&lt;-</span> <span class="fu">sapply</span>(ks, <span class="cf">function</span>(k){</span>
<span id="cb1139-11"><a href="sect133.html#cb1139-11" aria-hidden="true" tabindex="-1"></a>  <span class="co"># découpage du dendrogramme</span></span>
<span id="cb1139-12"><a href="sect133.html#cb1139-12" aria-hidden="true" tabindex="-1"></a>  groupes <span class="ot">&lt;-</span> <span class="fu">cutree</span>(dendogramme_parcs_euc, <span class="at">k =</span> k)</span>
<span id="cb1139-13"><a href="sect133.html#cb1139-13" aria-hidden="true" tabindex="-1"></a>  <span class="co"># calcul des valeurs de silhouette</span></span>
<span id="cb1139-14"><a href="sect133.html#cb1139-14" aria-hidden="true" tabindex="-1"></a>  sil <span class="ot">&lt;-</span> <span class="fu">silhouette</span>(groupes, <span class="at">dist =</span> parc_distances_euc)</span>
<span id="cb1139-15"><a href="sect133.html#cb1139-15" aria-hidden="true" tabindex="-1"></a>  <span class="co"># extraction de l&#39;indice global (moyenne des moyennes)</span></span>
<span id="cb1139-16"><a href="sect133.html#cb1139-16" aria-hidden="true" tabindex="-1"></a>  idx <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">summary</span>(sil)<span class="sc">$</span>clus.avg.widths)</span>
<span id="cb1139-17"><a href="sect133.html#cb1139-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(idx)</span>
<span id="cb1139-18"><a href="sect133.html#cb1139-18" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb1139-19"><a href="sect133.html#cb1139-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1139-20"><a href="sect133.html#cb1139-20" aria-hidden="true" tabindex="-1"></a><span class="co"># création d&#39;un graphique avec les résultats</span></span>
<span id="cb1139-21"><a href="sect133.html#cb1139-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1139-22"><a href="sect133.html#cb1139-22" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb1139-23"><a href="sect133.html#cb1139-23" aria-hidden="true" tabindex="-1"></a>  <span class="at">k =</span> ks,</span>
<span id="cb1139-24"><a href="sect133.html#cb1139-24" aria-hidden="true" tabindex="-1"></a>  <span class="at">silhouette =</span> values</span>
<span id="cb1139-25"><a href="sect133.html#cb1139-25" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1139-26"><a href="sect133.html#cb1139-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1139-27"><a href="sect133.html#cb1139-27" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df) <span class="sc">+</span> </span>
<span id="cb1139-28"><a href="sect133.html#cb1139-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> k, <span class="at">y =</span> silhouette)) <span class="sc">+</span> </span>
<span id="cb1139-29"><a href="sect133.html#cb1139-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> k, <span class="at">y =</span> silhouette), <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span> </span>
<span id="cb1139-30"><a href="sect133.html#cb1139-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;nombre de groupes&quot;</span>, <span class="at">y=</span><span class="st">&quot;indice global de silhouette&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:exampleHclust8"></span>
<img src="MethodesQuantitScSocialesBolR_files/figure-html/exampleHclust8-1.png" alt="Valeur de l'indice de silhouette pour différents nombres de groupes (distance euclidienne au carré)" width="75%" />
<p class="caption">
Figure 13.17: Valeur de l’indice de silhouette pour différents nombres de groupes (distance euclidienne au carré)
</p>
</div>
<p>Nous constatons cette fois-ci, que quatre groupes serait probablement le meilleur choix et qu’au-delà de ce nombre, l’indice global de silhouette ne fait que diminuer. Tentons cependant de reproduire les résultats de l’article avec k = 6.</p>
<div class="sourceCode" id="cb1140"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1140-1"><a href="sect133.html#cb1140-1" aria-hidden="true" tabindex="-1"></a>resk6 <span class="ot">&lt;-</span> <span class="fu">cutree</span>(dendogramme_parcs_euc, <span class="at">k =</span> <span class="dv">6</span>)</span>
<span id="cb1140-2"><a href="sect133.html#cb1140-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1140-3"><a href="sect133.html#cb1140-3" aria-hidden="true" tabindex="-1"></a><span class="co"># calcul du nombre de fois ou chaque modalité est observée dans un groupe</span></span>
<span id="cb1140-4"><a href="sect133.html#cb1140-4" aria-hidden="true" tabindex="-1"></a>X<span class="sc">$</span>groupe <span class="ot">&lt;-</span> resk6</span>
<span id="cb1140-5"><a href="sect133.html#cb1140-5" aria-hidden="true" tabindex="-1"></a>df_groupes <span class="ot">&lt;-</span> X <span class="sc">%&gt;%</span> </span>
<span id="cb1140-6"><a href="sect133.html#cb1140-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(groupe) <span class="sc">%&gt;%</span> <span class="fu">summarise_all</span>(<span class="at">.funs =</span> sum)</span>
<span id="cb1140-7"><a href="sect133.html#cb1140-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1140-8"><a href="sect133.html#cb1140-8" aria-hidden="true" tabindex="-1"></a><span class="co"># calcul du nombre d&#39;observations par groupe</span></span>
<span id="cb1140-9"><a href="sect133.html#cb1140-9" aria-hidden="true" tabindex="-1"></a>nb_gp <span class="ot">&lt;-</span> <span class="fu">table</span>(resk6)</span>
<span id="cb1140-10"><a href="sect133.html#cb1140-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1140-11"><a href="sect133.html#cb1140-11" aria-hidden="true" tabindex="-1"></a>groupe_ratios <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="dv">100</span> <span class="sc">*</span> <span class="fu">as.matrix</span>(df_groupes)[,<span class="dv">2</span><span class="sc">:</span><span class="fu">ncol</span>(df_groupes)] <span class="sc">/</span> <span class="fu">as.vector</span>(nb_gp),<span class="dv">1</span>)</span>
<span id="cb1140-12"><a href="sect133.html#cb1140-12" aria-hidden="true" tabindex="-1"></a>groupe_ratios <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">t</span>(groupe_ratios))</span>
<span id="cb1140-13"><a href="sect133.html#cb1140-13" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(groupe_ratios) <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="st">&quot;groupe &quot;</span>, <span class="dv">1</span><span class="sc">:</span><span class="fu">ncol</span>(groupe_ratios))</span>
<span id="cb1140-14"><a href="sect133.html#cb1140-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1140-15"><a href="sect133.html#cb1140-15" aria-hidden="true" tabindex="-1"></a><span class="co"># calcul du nombre moyen d&#39;équipements par catégorie par parc</span></span>
<span id="cb1140-16"><a href="sect133.html#cb1140-16" aria-hidden="true" tabindex="-1"></a>equip_class <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb1140-17"><a href="sect133.html#cb1140-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">c</span>(<span class="st">&quot;AIRE_JEUX&quot;</span>, <span class="st">&quot;JEUX_EAU&quot;</span>, <span class="st">&quot;PATAUGEOIRE&quot;</span>),</span>
<span id="cb1140-18"><a href="sect133.html#cb1140-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">c</span>(<span class="st">&quot;ATHLETISME&quot;</span>, <span class="st">&quot;BASEBALL_S&quot;</span>, <span class="st">&quot;BASKETBALL&quot;</span>, <span class="st">&quot;FOOTBALL&quot;</span>, <span class="st">&quot;SOCCER&quot;</span>, <span class="st">&quot;TENNIS&quot;</span>, <span class="st">&quot;VOLLEY_BALL&quot;</span>),</span>
<span id="cb1140-19"><a href="sect133.html#cb1140-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">c</span>(<span class="st">&quot;TOBBOGAN_G&quot;</span>, <span class="st">&quot;PATINOIRE_E&quot;</span>, <span class="st">&quot;RAQUETTES&quot;</span>, <span class="st">&quot;SKI_FOND&quot;</span>),</span>
<span id="cb1140-20"><a href="sect133.html#cb1140-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">c</span>(<span class="st">&quot;PATIN_ROUE&quot;</span>, <span class="st">&quot;ROULI_ROUL&quot;</span>),</span>
<span id="cb1140-21"><a href="sect133.html#cb1140-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">c</span>(<span class="st">&quot;PISC_EXT&quot;</span>, <span class="st">&quot;RANDONNEE&quot;</span>)</span>
<span id="cb1140-22"><a href="sect133.html#cb1140-22" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1140-23"><a href="sect133.html#cb1140-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1140-24"><a href="sect133.html#cb1140-24" aria-hidden="true" tabindex="-1"></a>class_compte <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="fu">sapply</span>(equip_class, <span class="cf">function</span>(equip){</span>
<span id="cb1140-25"><a href="sect133.html#cb1140-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rowSums</span>(X[equip])</span>
<span id="cb1140-26"><a href="sect133.html#cb1140-26" aria-hidden="true" tabindex="-1"></a>}))</span>
<span id="cb1140-27"><a href="sect133.html#cb1140-27" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(class_compte) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;enfants&quot;</span>, <span class="st">&quot;terrain_sport&quot;</span>, <span class="st">&quot;hiver&quot;</span>, <span class="st">&quot;specialise&quot;</span>, <span class="st">&quot;autre&quot;</span>)</span>
<span id="cb1140-28"><a href="sect133.html#cb1140-28" aria-hidden="true" tabindex="-1"></a>class_compte<span class="sc">$</span>groupe <span class="ot">&lt;-</span> resk6</span>
<span id="cb1140-29"><a href="sect133.html#cb1140-29" aria-hidden="true" tabindex="-1"></a>df_class_equip <span class="ot">&lt;-</span> class_compte <span class="sc">%&gt;%</span> </span>
<span id="cb1140-30"><a href="sect133.html#cb1140-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(groupe) <span class="sc">%&gt;%</span> </span>
<span id="cb1140-31"><a href="sect133.html#cb1140-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise_all</span>(mean)</span>
<span id="cb1140-32"><a href="sect133.html#cb1140-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1140-33"><a href="sect133.html#cb1140-33" aria-hidden="true" tabindex="-1"></a>df_class_equip <span class="ot">&lt;-</span> <span class="fu">t</span>(df_class_equip[<span class="dv">2</span><span class="sc">:</span><span class="fu">ncol</span>(df_class_equip)])</span>
<span id="cb1140-34"><a href="sect133.html#cb1140-34" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(df_class_equip) <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="st">&quot;groupe &quot;</span>, <span class="dv">1</span><span class="sc">:</span><span class="fu">ncol</span>(df_class_equip))</span>
<span id="cb1140-35"><a href="sect133.html#cb1140-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1140-36"><a href="sect133.html#cb1140-36" aria-hidden="true" tabindex="-1"></a><span class="co"># comptage du nombre moyen d&#39;équipements</span></span>
<span id="cb1140-37"><a href="sect133.html#cb1140-37" aria-hidden="true" tabindex="-1"></a>df_equip_tot <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb1140-38"><a href="sect133.html#cb1140-38" aria-hidden="true" tabindex="-1"></a>  <span class="at">nb =</span> <span class="fu">rowSums</span>(X[<span class="dv">1</span><span class="sc">:</span><span class="dv">18</span>]),</span>
<span id="cb1140-39"><a href="sect133.html#cb1140-39" aria-hidden="true" tabindex="-1"></a>  <span class="at">groupe =</span> resk6</span>
<span id="cb1140-40"><a href="sect133.html#cb1140-40" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1140-41"><a href="sect133.html#cb1140-41" aria-hidden="true" tabindex="-1"></a>df_equip_tot_mean <span class="ot">&lt;-</span> df_equip_tot <span class="sc">%&gt;%</span> </span>
<span id="cb1140-42"><a href="sect133.html#cb1140-42" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(groupe) <span class="sc">%&gt;%</span> </span>
<span id="cb1140-43"><a href="sect133.html#cb1140-43" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize_all</span>(mean)</span>
<span id="cb1140-44"><a href="sect133.html#cb1140-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1140-45"><a href="sect133.html#cb1140-45" aria-hidden="true" tabindex="-1"></a><span class="co"># mise dans l&#39;ordre de la première partie du tableau</span></span>
<span id="cb1140-46"><a href="sect133.html#cb1140-46" aria-hidden="true" tabindex="-1"></a>all_types <span class="ot">&lt;-</span> <span class="fu">do.call</span>(c,equip_class)</span>
<span id="cb1140-47"><a href="sect133.html#cb1140-47" aria-hidden="true" tabindex="-1"></a>idxs <span class="ot">&lt;-</span> <span class="fu">match</span>(all_types,<span class="fu">row.names</span>(groupe_ratios[<span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(all_types),]))</span>
<span id="cb1140-48"><a href="sect133.html#cb1140-48" aria-hidden="true" tabindex="-1"></a>groupe_ratios <span class="ot">&lt;-</span> <span class="fu">rbind</span>(groupe_ratios[idxs,],</span>
<span id="cb1140-49"><a href="sect133.html#cb1140-49" aria-hidden="true" tabindex="-1"></a>                       groupe_ratios[(<span class="fu">length</span>(all_types)<span class="sc">+</span><span class="dv">1</span>)<span class="sc">:</span><span class="fu">nrow</span>(groupe_ratios),])</span>
<span id="cb1140-50"><a href="sect133.html#cb1140-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1140-51"><a href="sect133.html#cb1140-51" aria-hidden="true" tabindex="-1"></a><span class="co"># combinaison des deux tableaux</span></span>
<span id="cb1140-52"><a href="sect133.html#cb1140-52" aria-hidden="true" tabindex="-1"></a>groupe_ratios <span class="ot">&lt;-</span> <span class="fu">rbind</span>(groupe_ratios, df_class_equip, df_equip_tot_mean<span class="sc">$</span>nb, <span class="fu">as.integer</span>(nb_gp))</span></code></pre></div>
<p>Recréons le tableau final des résultats au tableau <a href="sect133.html#tab:exampleHclust10">13.6</a>. Si vous comparez ce tableau avec celui de l’article original, vous verrez que notre groupe 3 correspond exactement à la classe A et que notre groupe 5 correspond exactement à la classe F. Pour les autres groupes, nous pouvons observer de légères variations, ce qui correspond vraisemblablement à des divergences d’implémentation des algorithmes entre le logiciel utilisé pour l’article (SAS) et R.</p>
<table>
<caption>
<span id="tab:exampleHclust10">Tableau 13.6: </span>Caractéristiques des groupes obtenus lors de la CAH (distance euclidienne au carré)
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
groupe 1
</th>
<th style="text-align:right;">
groupe 2
</th>
<th style="text-align:right;">
groupe 3
</th>
<th style="text-align:right;">
groupe 4
</th>
<th style="text-align:right;">
groupe 5
</th>
<th style="text-align:right;">
groupe 6
</th>
</tr>
</thead>
<tbody>
<tr grouplength="3">
<td colspan="7" style="border-bottom: 1px solid;">
<strong>Équipements pour les 0 à 4 ans (%)</strong>
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Aire de jeux
</td>
<td style="text-align:right;">
79,6
</td>
<td style="text-align:right;">
74,2
</td>
<td style="text-align:right;">
96,6
</td>
<td style="text-align:right;">
100,0
</td>
<td style="text-align:right;">
20,0
</td>
<td style="text-align:right;">
79,3
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Jeux d’eau
</td>
<td style="text-align:right;">
11,1
</td>
<td style="text-align:right;">
3,0
</td>
<td style="text-align:right;">
1,7
</td>
<td style="text-align:right;">
5,1
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
5,9
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Pataugeoire
</td>
<td style="text-align:right;">
59,3
</td>
<td style="text-align:right;">
42,4
</td>
<td style="text-align:right;">
8,4
</td>
<td style="text-align:right;">
61,0
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
19,7
</td>
</tr>
<tr grouplength="7">
<td colspan="7" style="border-bottom: 1px solid;">
<strong>Terrains de sport (%)</strong>
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Athlétisme
</td>
<td style="text-align:right;">
13,0
</td>
<td style="text-align:right;">
15,2
</td>
<td style="text-align:right;">
0,3
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
1,0
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Baseball
</td>
<td style="text-align:right;">
88,9
</td>
<td style="text-align:right;">
63,6
</td>
<td style="text-align:right;">
5,4
</td>
<td style="text-align:right;">
89,8
</td>
<td style="text-align:right;">
6,7
</td>
<td style="text-align:right;">
13,8
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Basketball
</td>
<td style="text-align:right;">
83,3
</td>
<td style="text-align:right;">
30,3
</td>
<td style="text-align:right;">
6,1
</td>
<td style="text-align:right;">
35,6
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
18,2
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Football
</td>
<td style="text-align:right;">
31,5
</td>
<td style="text-align:right;">
12,1
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
10,2
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
2,5
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Soccer (football)
</td>
<td style="text-align:right;">
75,9
</td>
<td style="text-align:right;">
57,6
</td>
<td style="text-align:right;">
2,0
</td>
<td style="text-align:right;">
27,1
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
33,5
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Tennis
</td>
<td style="text-align:right;">
90,7
</td>
<td style="text-align:right;">
19,7
</td>
<td style="text-align:right;">
4,1
</td>
<td style="text-align:right;">
35,6
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
14,8
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Volleyball
</td>
<td style="text-align:right;">
20,4
</td>
<td style="text-align:right;">
3,0
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
1,7
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
4,9
</td>
</tr>
<tr grouplength="4">
<td colspan="7" style="border-bottom: 1px solid;">
<strong>Équipements d’hiver (%)</strong>
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Glissade
</td>
<td style="text-align:right;">
14,8
</td>
<td style="text-align:right;">
16,7
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
1,7
</td>
<td style="text-align:right;">
33,3
</td>
<td style="text-align:right;">
2,5
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Patinoire
</td>
<td style="text-align:right;">
87,0
</td>
<td style="text-align:right;">
57,6
</td>
<td style="text-align:right;">
13,2
</td>
<td style="text-align:right;">
86,4
</td>
<td style="text-align:right;">
26,7
</td>
<td style="text-align:right;">
30,5
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Piste de ski de fond
</td>
<td style="text-align:right;">
1,9
</td>
<td style="text-align:right;">
1,5
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
46,7
</td>
<td style="text-align:right;">
0,0
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Raquettes
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
1,5
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
86,7
</td>
<td style="text-align:right;">
0,0
</td>
</tr>
<tr grouplength="2">
<td colspan="7" style="border-bottom: 1px solid;">
<strong>Équipements spécialisés (%)</strong>
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Parc de planches à roulettes
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
1,7
</td>
<td style="text-align:right;">
46,7
</td>
<td style="text-align:right;">
0,0
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Patins à roues alignées
</td>
<td style="text-align:right;">
16,7
</td>
<td style="text-align:right;">
7,6
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
5,1
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
0,5
</td>
</tr>
<tr grouplength="2">
<td colspan="7" style="border-bottom: 1px solid;">
<strong>Autres équipements (%)</strong>
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Piscine extérieure
</td>
<td style="text-align:right;">
75,9
</td>
<td style="text-align:right;">
16,7
</td>
<td style="text-align:right;">
1,4
</td>
<td style="text-align:right;">
11,9
</td>
<td style="text-align:right;">
6,7
</td>
<td style="text-align:right;">
13,8
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Chemin de andonnée
</td>
<td style="text-align:right;">
1,9
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
93,3
</td>
<td style="text-align:right;">
0,0
</td>
</tr>
<tr grouplength="5">
<td colspan="7" style="border-bottom: 1px solid;">
<strong>Superficie (%)</strong>
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Moins d’un hectare
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
100,0
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
0,0
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
1 à 5 hectares
</td>
<td style="text-align:right;">
42,6
</td>
<td style="text-align:right;">
1,5
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
98,3
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
99,5
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
5 à 10 hectares
</td>
<td style="text-align:right;">
46,3
</td>
<td style="text-align:right;">
69,7
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
0,0
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
10 à 20 hectares
</td>
<td style="text-align:right;">
1,9
</td>
<td style="text-align:right;">
27,3
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
13,3
</td>
<td style="text-align:right;">
0,5
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
20 hectares et plus
</td>
<td style="text-align:right;">
9,3
</td>
<td style="text-align:right;">
1,5
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
1,7
</td>
<td style="text-align:right;">
86,7
</td>
<td style="text-align:right;">
0,0
</td>
</tr>
<tr grouplength="6">
<td colspan="7" style="border-bottom: 1px solid;">
<strong>Nombre moyen d’équipement du type</strong>
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Équipements pour les 0 à 4 ans
</td>
<td style="text-align:right;">
1,5
</td>
<td style="text-align:right;">
1,2
</td>
<td style="text-align:right;">
1,1
</td>
<td style="text-align:right;">
1,7
</td>
<td style="text-align:right;">
0,2
</td>
<td style="text-align:right;">
1,0
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Terrains de sport
</td>
<td style="text-align:right;">
4,0
</td>
<td style="text-align:right;">
2,0
</td>
<td style="text-align:right;">
0,2
</td>
<td style="text-align:right;">
2,0
</td>
<td style="text-align:right;">
0,1
</td>
<td style="text-align:right;">
0,9
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Équipements d’hiver
</td>
<td style="text-align:right;">
1,0
</td>
<td style="text-align:right;">
0,8
</td>
<td style="text-align:right;">
0,1
</td>
<td style="text-align:right;">
0,9
</td>
<td style="text-align:right;">
1,9
</td>
<td style="text-align:right;">
0,3
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Équipements spécialisés
</td>
<td style="text-align:right;">
0,2
</td>
<td style="text-align:right;">
0,1
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
0,1
</td>
<td style="text-align:right;">
0,5
</td>
<td style="text-align:right;">
0,0
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Autres équipements
</td>
<td style="text-align:right;">
0,8
</td>
<td style="text-align:right;">
0,2
</td>
<td style="text-align:right;">
0,0
</td>
<td style="text-align:right;">
0,1
</td>
<td style="text-align:right;">
1,0
</td>
<td style="text-align:right;">
0,1
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Tous les équipements
</td>
<td style="text-align:right;">
7,5
</td>
<td style="text-align:right;">
4,2
</td>
<td style="text-align:right;">
1,4
</td>
<td style="text-align:right;">
4,7
</td>
<td style="text-align:right;">
3,7
</td>
<td style="text-align:right;">
2,4
</td>
</tr>
<tr grouplength="1">
<td colspan="7" style="border-bottom: 1px solid;">
<strong>Nombre d’observations par groupe</strong>
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
</td>
<td style="text-align:right;">
54,0
</td>
<td style="text-align:right;">
66,0
</td>
<td style="text-align:right;">
296,0
</td>
<td style="text-align:right;">
59,0
</td>
<td style="text-align:right;">
15,0
</td>
<td style="text-align:right;">
203,0
</td>
</tr>
</tbody>
</table>
<div style="page-break-after: always;"></div>
</div>
</div>
</div>
<h3>R&eacute;f&eacute;rences</h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-apparicio2010accessibilite" class="csl-entry">
Apparicio, Philippe, Marie-Soleil Cloutier, Anne-Marie Séguin et Josefina Ades. 2010. <span>« Accessibilit<span>é</span> spatiale aux parcs urbains pour les enfants et injustice environnementale. Exploration du cas montr<span>é</span>alais. »</span> <em>Revue internationale de g<span>é</span>omatique</em> 20 (3): 363‑389. <a href="http://rig.revuesonline.com/article.jsp?articleId=15208">http://rig.revuesonline.com/article.jsp?articleId=15208</a>.
</div>
<div id="ref-tibshirani2001estimating" class="csl-entry">
Tibshirani, Robert, Guenther Walther et Trevor Hastie. 2001. <span>« Estimating the number of clusters in a data set via the gap statistic. »</span> <em>Journal of the Royal Statistical Society: Series B (Statistical Methodology)</em> 63 (2): 411‑423. <a href="https://doi.org/10.1111/1467-9868.00293">https://doi.org/10.1111/1467-9868.00293</a>.
</div>
<div id="ref-ward1963hierarchical" class="csl-entry">
Ward, Joe H. 1963. <span>« Hierarchical grouping to optimize an objective function. »</span> <em>Journal of the American statistical association</em> 58 (301): 236‑244. <a href="https://doi.org/10.1080/01621459.1963.10500845">https://doi.org/10.1080/01621459.1963.10500845</a>.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="sect132.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="sect134.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["MethodesQuantitScSocialesBolR.pdf"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "none"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
