<!DOCTYPE html>
<html lang="fr" xml:lang="fr">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>12.3 Analyse factorielle des correspondances (AFC) | Méthodes quantitatives en sciences sociales : un grand bol d’R</title>
  <meta name="description" content="Ce livre vise à décrire une panoplie de méthodes quantitatives utilisées en sciences sociales avec le logiciel ouvert R. Il a d’ailleurs été écrit intégralement dans R avec rmarkdown. Le contenu est pensé pour être accessible à tous et toutes, même à ceux et celles n’ayant presque aucune base en statistique ou en programmation. Les personnes plus expérimentées y découvriront des sections sur des méthodes plus avancées comme les modèles à effets mixtes, les modèles multiniveaux, les modèles généralisés additifs ainsi que les méthodes factorielles et de classification. Ceux et celles souhaitant migrer progressivement d’un autre logiciel statistique vers R trouveront dans cet ouvrage les éléments pour une transition en douceur. La philosophie de ce livre est de donner toutes les clefs de compréhension et de mise en œuvre des méthodes abordées dans R. La présentation des méthodes est basée sur une approche compréhensive et intuitive plutôt que mathématique, sans pour autant que la rigueur statistique ne soit négligée." />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="12.3 Analyse factorielle des correspondances (AFC) | Méthodes quantitatives en sciences sociales : un grand bol d’R" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="https://laeq.github.io/LivreStatistique_website/" />
  <meta property="og:image" content="https://laeq.github.io/LivreStatistique_website/images/introduction/ImageCouverture.png" />
  <meta property="og:description" content="Ce livre vise à décrire une panoplie de méthodes quantitatives utilisées en sciences sociales avec le logiciel ouvert R. Il a d’ailleurs été écrit intégralement dans R avec rmarkdown. Le contenu est pensé pour être accessible à tous et toutes, même à ceux et celles n’ayant presque aucune base en statistique ou en programmation. Les personnes plus expérimentées y découvriront des sections sur des méthodes plus avancées comme les modèles à effets mixtes, les modèles multiniveaux, les modèles généralisés additifs ainsi que les méthodes factorielles et de classification. Ceux et celles souhaitant migrer progressivement d’un autre logiciel statistique vers R trouveront dans cet ouvrage les éléments pour une transition en douceur. La philosophie de ce livre est de donner toutes les clefs de compréhension et de mise en œuvre des méthodes abordées dans R. La présentation des méthodes est basée sur une approche compréhensive et intuitive plutôt que mathématique, sans pour autant que la rigueur statistique ne soit négligée." />
  <meta name="github-repo" content="LAEQ/livre_statistique_Phil_Jere" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="12.3 Analyse factorielle des correspondances (AFC) | Méthodes quantitatives en sciences sociales : un grand bol d’R" />
  
  <meta name="twitter:description" content="Ce livre vise à décrire une panoplie de méthodes quantitatives utilisées en sciences sociales avec le logiciel ouvert R. Il a d’ailleurs été écrit intégralement dans R avec rmarkdown. Le contenu est pensé pour être accessible à tous et toutes, même à ceux et celles n’ayant presque aucune base en statistique ou en programmation. Les personnes plus expérimentées y découvriront des sections sur des méthodes plus avancées comme les modèles à effets mixtes, les modèles multiniveaux, les modèles généralisés additifs ainsi que les méthodes factorielles et de classification. Ceux et celles souhaitant migrer progressivement d’un autre logiciel statistique vers R trouveront dans cet ouvrage les éléments pour une transition en douceur. La philosophie de ce livre est de donner toutes les clefs de compréhension et de mise en œuvre des méthodes abordées dans R. La présentation des méthodes est basée sur une approche compréhensive et intuitive plutôt que mathématique, sans pour autant que la rigueur statistique ne soit négligée." />
  <meta name="twitter:image" content="https://laeq.github.io/LivreStatistique_website/images/introduction/ImageCouverture.png" />

<meta name="author" content="Philippe Apparicio et Jérémy Gelb" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="sect122.html"/>
<link rel="next" href="sect124.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<script src="libs/htmlwidgets-1.5.3/htmlwidgets.js"></script>
<script src="libs/d3-4.13.0/d3.min.js"></script>
<script src="libs/d3-tip-0.8.1/index.js"></script>
<link href="libs/chorddiag-0.1.2.9000/chorddiag.css" rel="stylesheet" />
<script src="libs/chorddiag-0.1.2.9000/chorddiag.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="css/quizlib.min.css" type="text/css" />
<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Méthodes quantitatives en sciences sociales : un grand bol d'R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Bienvenue</a></li>
<li class="chapter" data-level="" data-path="préface.html"><a href="préface.html"><i class="fa fa-check"></i>Préface</a><ul>
<li class="chapter" data-level="" data-path="sect001.html"><a href="sect001.html"><i class="fa fa-check"></i>Un manuel sous la forme d’une ressource éducative libre</a></li>
<li class="chapter" data-level="" data-path="sect002.html"><a href="sect002.html"><i class="fa fa-check"></i>Un manuel conçu comme un projet collaboratif</a></li>
<li class="chapter" data-level="" data-path="sect003.html"><a href="sect003.html"><i class="fa fa-check"></i>Comment lire ce livre?</a></li>
<li class="chapter" data-level="" data-path="sect003B.html"><a href="sect003B.html"><i class="fa fa-check"></i>Comment utiliser les données du livre pour reproduire les exemples?</a></li>
<li class="chapter" data-level="" data-path="sect004.html"><a href="sect004.html"><i class="fa fa-check"></i>Structure du livre</a></li>
<li class="chapter" data-level="" data-path="sect005.html"><a href="sect005.html"><i class="fa fa-check"></i>Pourquoi faut-il programmer en sciences sociales?</a></li>
<li class="chapter" data-level="" data-path="sect006.html"><a href="sect006.html"><i class="fa fa-check"></i>Remerciements</a></li>
<li class="chapter" data-level="" data-path="sect007.html"><a href="sect007.html"><i class="fa fa-check"></i>Dédicace toute spéciale à Cargo et Ambrée</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="auteurs.html"><a href="auteurs.html"><i class="fa fa-check"></i>À propos des auteurs</a></li>
<li class="part"><span><b>I Découverte de R</b></span></li>
<li class="chapter" data-level="1" data-path="chap01.html"><a href="chap01.html"><i class="fa fa-check"></i><b>1</b> Prise en main de R</a><ul>
<li class="chapter" data-level="1.1" data-path="sect011.html"><a href="sect011.html"><i class="fa fa-check"></i><b>1.1</b> Histoire et philosophie de R</a></li>
<li class="chapter" data-level="1.2" data-path="sect012.html"><a href="sect012.html"><i class="fa fa-check"></i><b>1.2</b> Environnement de travail</a><ul>
<li class="chapter" data-level="1.2.1" data-path="sect012.html"><a href="sect012.html#sect0121"><i class="fa fa-check"></i><b>1.2.1</b> Installation de R</a></li>
<li class="chapter" data-level="1.2.2" data-path="sect012.html"><a href="sect012.html#sect0122"><i class="fa fa-check"></i><b>1.2.2</b> Environnement RStudio</a></li>
<li class="chapter" data-level="1.2.3" data-path="sect012.html"><a href="sect012.html#sect0123"><i class="fa fa-check"></i><b>1.2.3</b> Installation et chargement un <em>package</em></a></li>
<li class="chapter" data-level="1.2.4" data-path="sect012.html"><a href="sect012.html#aide-disponible"><i class="fa fa-check"></i><b>1.2.4</b> Aide disponible</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="sect013.html"><a href="sect013.html"><i class="fa fa-check"></i><b>1.3</b> Bases du langage R</a><ul>
<li class="chapter" data-level="1.3.1" data-path="sect013.html"><a href="sect013.html#sect0131"><i class="fa fa-check"></i><b>1.3.1</b> <em>Hello World</em>!</a></li>
<li class="chapter" data-level="1.3.2" data-path="sect013.html"><a href="sect013.html#sect0132"><i class="fa fa-check"></i><b>1.3.2</b> Objets et expressions</a></li>
<li class="chapter" data-level="1.3.3" data-path="sect013.html"><a href="sect013.html#sect0_133"><i class="fa fa-check"></i><b>1.3.3</b> Fonctions et arguments</a></li>
<li class="chapter" data-level="1.3.4" data-path="sect013.html"><a href="sect013.html#sect0134"><i class="fa fa-check"></i><b>1.3.4</b> Principaux types de données</a></li>
<li class="chapter" data-level="1.3.5" data-path="sect013.html"><a href="sect013.html#sect0135"><i class="fa fa-check"></i><b>1.3.5</b> Opérateurs</a></li>
<li class="chapter" data-level="1.3.6" data-path="sect013.html"><a href="sect013.html#sect0136"><i class="fa fa-check"></i><b>1.3.6</b> Structures de données</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="sect014.html"><a href="sect014.html"><i class="fa fa-check"></i><b>1.4</b> Manipulation de données</a><ul>
<li class="chapter" data-level="1.4.1" data-path="sect014.html"><a href="sect014.html#sect0141"><i class="fa fa-check"></i><b>1.4.1</b> Chargement d’un <em>DataFrame</em> depuis un fichier</a></li>
<li class="chapter" data-level="1.4.2" data-path="sect014.html"><a href="sect014.html#sect0142"><i class="fa fa-check"></i><b>1.4.2</b> Manipulation d’un <em>DataFrame</em></a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="sect016.html"><a href="sect016.html"><i class="fa fa-check"></i><b>1.5</b> Code R bien structuré</a></li>
<li class="chapter" data-level="1.6" data-path="sect017.html"><a href="sect017.html"><i class="fa fa-check"></i><b>1.6</b> Enregistrement des résultats</a></li>
<li class="chapter" data-level="1.7" data-path="sect018.html"><a href="sect018.html"><i class="fa fa-check"></i><b>1.7</b> Session de travail</a></li>
<li class="chapter" data-level="1.8" data-path="sect019.html"><a href="sect019.html"><i class="fa fa-check"></i><b>1.8</b> Conclusion et ressources pertinentes</a></li>
<li class="chapter" data-level="1.9" data-path="sect0110.html"><a href="sect0110.html"><i class="fa fa-check"></i><b>1.9</b> Quiz de révision du chapitre</a></li>
</ul></li>
<li class="part"><span><b>II Analyses univariées et graphiques dans R</b></span></li>
<li class="chapter" data-level="2" data-path="chap02.html"><a href="chap02.html"><i class="fa fa-check"></i><b>2</b> Statistiques descriptives univariées</a><ul>
<li class="chapter" data-level="2.1" data-path="sect021.html"><a href="sect021.html"><i class="fa fa-check"></i><b>2.1</b> Notion et types de variable</a><ul>
<li class="chapter" data-level="2.1.1" data-path="sect021.html"><a href="sect021.html#sect0211"><i class="fa fa-check"></i><b>2.1.1</b> Notion de variable</a></li>
<li class="chapter" data-level="2.1.2" data-path="sect021.html"><a href="sect021.html#sect0212"><i class="fa fa-check"></i><b>2.1.2</b> Types de variables</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="sect022.html"><a href="sect022.html"><i class="fa fa-check"></i><b>2.2</b> Types de données</a><ul>
<li class="chapter" data-level="2.2.1" data-path="sect022.html"><a href="sect022.html#sect0221"><i class="fa fa-check"></i><b>2.2.1</b> Données secondaires <em>versus</em> données primaires</a></li>
<li class="chapter" data-level="2.2.2" data-path="sect022.html"><a href="sect022.html#sect0222"><i class="fa fa-check"></i><b>2.2.2</b> Données transversales <em>versus</em> données longitudinales</a></li>
<li class="chapter" data-level="2.2.3" data-path="sect022.html"><a href="sect022.html#sect0223"><i class="fa fa-check"></i><b>2.2.3</b> Données spatiales versus données aspatiales</a></li>
<li class="chapter" data-level="2.2.4" data-path="sect022.html"><a href="sect022.html#sect0224"><i class="fa fa-check"></i><b>2.2.4</b> Données individuelles <em>versus</em> données agrégées</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="sect023.html"><a href="sect023.html"><i class="fa fa-check"></i><b>2.3</b> Statistique descriptive et statistique inférentielle</a><ul>
<li class="chapter" data-level="2.3.1" data-path="sect023.html"><a href="sect023.html#sect0231"><i class="fa fa-check"></i><b>2.3.1</b> Population, échantillon et inférence</a></li>
<li class="chapter" data-level="2.3.2" data-path="sect023.html"><a href="sect023.html#sect0232"><i class="fa fa-check"></i><b>2.3.2</b> Deux grandes familles de méthodes statistiques</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="sect024.html"><a href="sect024.html"><i class="fa fa-check"></i><b>2.4</b> Notion de distribution</a><ul>
<li class="chapter" data-level="2.4.1" data-path="sect024.html"><a href="sect024.html#définition-générale"><i class="fa fa-check"></i><b>2.4.1</b> Définition générale</a></li>
<li class="chapter" data-level="2.4.2" data-path="sect024.html"><a href="sect024.html#anatomie-dune-distribution"><i class="fa fa-check"></i><b>2.4.2</b> Anatomie d’une distribution</a></li>
<li class="chapter" data-level="2.4.3" data-path="sect024.html"><a href="sect024.html#principales-distributions"><i class="fa fa-check"></i><b>2.4.3</b> Principales distributions</a></li>
<li class="chapter" data-level="2.4.4" data-path="sect024.html"><a href="sect024.html#conclusion-sur-les-distributions"><i class="fa fa-check"></i><b>2.4.4</b> Conclusion sur les distributions</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="sect025.html"><a href="sect025.html"><i class="fa fa-check"></i><b>2.5</b> Statistiques descriptives sur des variables quantitatives</a><ul>
<li class="chapter" data-level="2.5.1" data-path="sect025.html"><a href="sect025.html#sect0251"><i class="fa fa-check"></i><b>2.5.1</b> Paramètres de tendance centrale</a></li>
<li class="chapter" data-level="2.5.2" data-path="sect025.html"><a href="sect025.html#sect0252"><i class="fa fa-check"></i><b>2.5.2</b> Paramètres de position</a></li>
<li class="chapter" data-level="2.5.3" data-path="sect025.html"><a href="sect025.html#sect0253"><i class="fa fa-check"></i><b>2.5.3</b> Paramètres de dispersion</a></li>
<li class="chapter" data-level="2.5.4" data-path="sect025.html"><a href="sect025.html#sect0254"><i class="fa fa-check"></i><b>2.5.4</b> Paramètres de forme</a></li>
<li class="chapter" data-level="2.5.5" data-path="sect025.html"><a href="sect025.html#sect0255"><i class="fa fa-check"></i><b>2.5.5</b> Transformation des variables</a></li>
<li class="chapter" data-level="2.5.6" data-path="sect025.html"><a href="sect025.html#sect0256"><i class="fa fa-check"></i><b>2.5.6</b> Mise en œuvre dans R</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="sect026.html"><a href="sect026.html"><i class="fa fa-check"></i><b>2.6</b> Statistiques descriptives sur des variables qualitatives et semi-qualitatives</a><ul>
<li class="chapter" data-level="2.6.1" data-path="sect026.html"><a href="sect026.html#sect0261"><i class="fa fa-check"></i><b>2.6.1</b> Fréquences</a></li>
<li class="chapter" data-level="2.6.2" data-path="sect026.html"><a href="sect026.html#sect0262"><i class="fa fa-check"></i><b>2.6.2</b> Mise en œuvre dans R</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="sect027.html"><a href="sect027.html"><i class="fa fa-check"></i><b>2.7</b> Statistiques descriptives pondérées : pour aller plus loin</a></li>
<li class="chapter" data-level="2.8" data-path="sect028.html"><a href="sect028.html"><i class="fa fa-check"></i><b>2.8</b> Quiz de révision du chapitre</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="chap03.html"><a href="chap03.html"><i class="fa fa-check"></i><b>3</b> Magie des graphiques</a><ul>
<li class="chapter" data-level="3.1" data-path="sect031.html"><a href="sect031.html"><i class="fa fa-check"></i><b>3.1</b> Philosophie du ggplot2</a><ul>
<li class="chapter" data-level="3.1.1" data-path="sect031.html"><a href="sect031.html#sect0311"><i class="fa fa-check"></i><b>3.1.1</b> Grammaire</a></li>
<li class="chapter" data-level="3.1.2" data-path="sect031.html"><a href="sect031.html#sect0312"><i class="fa fa-check"></i><b>3.1.2</b> Types de géométries</a></li>
<li class="chapter" data-level="3.1.3" data-path="sect031.html"><a href="sect031.html#sect0313"><i class="fa fa-check"></i><b>3.1.3</b> Habillage</a></li>
<li class="chapter" data-level="3.1.4" data-path="sect031.html"><a href="sect031.html#utilisation-des-thèmes"><i class="fa fa-check"></i><b>3.1.4</b> Utilisation des thèmes</a></li>
<li class="chapter" data-level="3.1.5" data-path="sect031.html"><a href="sect031.html#sect0314"><i class="fa fa-check"></i><b>3.1.5</b> Composition d’une figure avec plusieurs graphiques</a></li>
<li class="chapter" data-level="3.1.6" data-path="sect031.html"><a href="sect031.html#sect0315"><i class="fa fa-check"></i><b>3.1.6</b> Couleur</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="sect032.html"><a href="sect032.html"><i class="fa fa-check"></i><b>3.2</b> Principaux graphiques</a><ul>
<li class="chapter" data-level="3.2.1" data-path="sect032.html"><a href="sect032.html#sect0321"><i class="fa fa-check"></i><b>3.2.1</b> Histogramme</a></li>
<li class="chapter" data-level="3.2.2" data-path="sect032.html"><a href="sect032.html#sect0322"><i class="fa fa-check"></i><b>3.2.2</b> Graphique de densité</a></li>
<li class="chapter" data-level="3.2.3" data-path="sect032.html"><a href="sect032.html#sect0323"><i class="fa fa-check"></i><b>3.2.3</b> Nuage de points</a></li>
<li class="chapter" data-level="3.2.4" data-path="sect032.html"><a href="sect032.html#sect0324"><i class="fa fa-check"></i><b>3.2.4</b> Graphique en ligne</a></li>
<li class="chapter" data-level="3.2.5" data-path="sect032.html"><a href="sect032.html#sect0325"><i class="fa fa-check"></i><b>3.2.5</b> Boîte à moustaches</a></li>
<li class="chapter" data-level="3.2.6" data-path="sect032.html"><a href="sect032.html#sect0326"><i class="fa fa-check"></i><b>3.2.6</b> Graphique en violon</a></li>
<li class="chapter" data-level="3.2.7" data-path="sect032.html"><a href="sect032.html#sect0327"><i class="fa fa-check"></i><b>3.2.7</b> Graphique en barre</a></li>
<li class="chapter" data-level="3.2.8" data-path="sect032.html"><a href="sect032.html#sect0328"><i class="fa fa-check"></i><b>3.2.8</b> Graphique circulaire</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="sect033.html"><a href="sect033.html"><i class="fa fa-check"></i><b>3.3</b> Graphiques spéciaux</a><ul>
<li class="chapter" data-level="3.3.1" data-path="sect033.html"><a href="sect033.html#sect0331"><i class="fa fa-check"></i><b>3.3.1</b> Graphique en radar</a></li>
<li class="chapter" data-level="3.3.2" data-path="sect033.html"><a href="sect033.html#sect0332"><i class="fa fa-check"></i><b>3.3.2</b> Diagramme d’accord</a></li>
<li class="chapter" data-level="3.3.3" data-path="sect033.html"><a href="sect033.html#sect0333"><i class="fa fa-check"></i><b>3.3.3</b> Nuage de mots</a></li>
<li class="chapter" data-level="3.3.4" data-path="sect033.html"><a href="sect033.html#sect0334"><i class="fa fa-check"></i><b>3.3.4</b> Carte proportionnelle</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="sect034.html"><a href="sect034.html"><i class="fa fa-check"></i><b>3.4</b> Cartes</a></li>
<li class="chapter" data-level="3.5" data-path="sect035.html"><a href="sect035.html"><i class="fa fa-check"></i><b>3.5</b> Exportation des graphiques</a></li>
<li class="chapter" data-level="3.6" data-path="sect036.html"><a href="sect036.html"><i class="fa fa-check"></i><b>3.6</b> Conclusion sur les graphiques</a></li>
</ul></li>
<li class="part"><span><b>III Analyses bivariées</b></span></li>
<li class="chapter" data-level="4" data-path="chap04.html"><a href="chap04.html"><i class="fa fa-check"></i><b>4</b> Relation linéaire entre deux variables quantitatives</a><ul>
<li class="chapter" data-level="4.1" data-path="sect041.html"><a href="sect041.html"><i class="fa fa-check"></i><b>4.1</b> Bref retour sur le postulat de la relation linéaire</a></li>
<li class="chapter" data-level="4.2" data-path="sect042.html"><a href="sect042.html"><i class="fa fa-check"></i><b>4.2</b> Covariance</a><ul>
<li class="chapter" data-level="4.2.1" data-path="sect042.html"><a href="sect042.html#sect0421"><i class="fa fa-check"></i><b>4.2.1</b> Formulation</a></li>
<li class="chapter" data-level="4.2.2" data-path="sect042.html"><a href="sect042.html#sect0422"><i class="fa fa-check"></i><b>4.2.2</b> Interprétation</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="sect043.html"><a href="sect043.html"><i class="fa fa-check"></i><b>4.3</b> Corrélation</a><ul>
<li class="chapter" data-level="4.3.1" data-path="sect043.html"><a href="sect043.html#sect0431"><i class="fa fa-check"></i><b>4.3.1</b> Formulation</a></li>
<li class="chapter" data-level="4.3.2" data-path="sect043.html"><a href="sect043.html#sect0432"><i class="fa fa-check"></i><b>4.3.2</b> Interprétation</a></li>
<li class="chapter" data-level="4.3.3" data-path="sect043.html"><a href="sect043.html#sect0433"><i class="fa fa-check"></i><b>4.3.3</b> Corrélations pour des variables anormalement distribuées (coefficient de Spearman, tau de Kendall)</a></li>
<li class="chapter" data-level="4.3.4" data-path="sect043.html"><a href="sect043.html#sect0434"><i class="fa fa-check"></i><b>4.3.4</b> Corrélations robustes (<em>Biweight midcorrelation</em>, <em>Percentage bend correlation</em> et la corrélation <em>pi</em> de Shepherd)</a></li>
<li class="chapter" data-level="4.3.5" data-path="sect043.html"><a href="sect043.html#sect0435"><i class="fa fa-check"></i><b>4.3.5</b> Significativité des coefficients de corrélation</a></li>
<li class="chapter" data-level="4.3.6" data-path="sect043.html"><a href="sect043.html#sect0436"><i class="fa fa-check"></i><b>4.3.6</b> Corrélation partielle</a></li>
<li class="chapter" data-level="4.3.7" data-path="sect043.html"><a href="sect043.html#sect0437"><i class="fa fa-check"></i><b>4.3.7</b> Mise en œuvre dans R</a></li>
<li class="chapter" data-level="4.3.8" data-path="sect043.html"><a href="sect043.html#sect0438"><i class="fa fa-check"></i><b>4.3.8</b> Comment rapporter des valeurs de corrélations?</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="sect044.html"><a href="sect044.html"><i class="fa fa-check"></i><b>4.4</b> Régression linéaire simple</a><ul>
<li class="chapter" data-level="4.4.1" data-path="sect044.html"><a href="sect044.html#sect0441"><i class="fa fa-check"></i><b>4.4.1</b> Principe de base de la régression linéaire simple</a></li>
<li class="chapter" data-level="4.4.2" data-path="sect044.html"><a href="sect044.html#sect0442"><i class="fa fa-check"></i><b>4.4.2</b> Formulation de la droite de régression des moindres carrés ordinaires</a></li>
<li class="chapter" data-level="4.4.3" data-path="sect044.html"><a href="sect044.html#sect0443"><i class="fa fa-check"></i><b>4.4.3</b> Mesure de la qualité d’ajustement du modèle</a></li>
<li class="chapter" data-level="4.4.4" data-path="sect044.html"><a href="sect044.html#sect0444"><i class="fa fa-check"></i><b>4.4.4</b> Mise en œuvre dans R</a></li>
<li class="chapter" data-level="4.4.5" data-path="sect044.html"><a href="sect044.html#sect0445"><i class="fa fa-check"></i><b>4.4.5</b> Comment rapporter une régression linéaire simple</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="sect045.html"><a href="sect045.html"><i class="fa fa-check"></i><b>4.5</b> Quiz de révision du chapitre</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="chap05.html"><a href="chap05.html"><i class="fa fa-check"></i><b>5</b> Relation entre deux variables qualitatives</a><ul>
<li class="chapter" data-level="5.1" data-path="sect051.html"><a href="sect051.html"><i class="fa fa-check"></i><b>5.1</b> Construction de tableau de contingence</a></li>
<li class="chapter" data-level="5.2" data-path="sect052.html"><a href="sect052.html"><i class="fa fa-check"></i><b>5.2</b> Test du khi-deux</a></li>
<li class="chapter" data-level="5.3" data-path="sect053.html"><a href="sect053.html"><i class="fa fa-check"></i><b>5.3</b> Mise en œuvre dans R</a></li>
<li class="chapter" data-level="5.4" data-path="sect054.html"><a href="sect054.html"><i class="fa fa-check"></i><b>5.4</b> Interprétation d’un tableau de contingence</a></li>
<li class="chapter" data-level="5.5" data-path="sect055.html"><a href="sect055.html"><i class="fa fa-check"></i><b>5.5</b> Quiz de révision du chapitre</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="chap06.html"><a href="chap06.html"><i class="fa fa-check"></i><b>6</b> Relation entre une variable qualitative et une variable quantitative</a><ul>
<li class="chapter" data-level="6.1" data-path="sect061.html"><a href="sect061.html"><i class="fa fa-check"></i><b>6.1</b> Relation entre une variable quantitative et une variable qualitative à deux modalités</a><ul>
<li class="chapter" data-level="6.1.1" data-path="sect061.html"><a href="sect061.html#sect0611"><i class="fa fa-check"></i><b>6.1.1</b> Test <em>t</em> et ses différentes variantes</a></li>
<li class="chapter" data-level="6.1.2" data-path="sect061.html"><a href="sect061.html#sect0612"><i class="fa fa-check"></i><b>6.1.2</b> Test non paramétrique de Wilcoxon</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="sect062.html"><a href="sect062.html"><i class="fa fa-check"></i><b>6.2</b> Relation entre une variable quantitative et une variable qualitative à plus de deux modalités</a><ul>
<li class="chapter" data-level="6.2.1" data-path="sect062.html"><a href="sect062.html#sect0621"><i class="fa fa-check"></i><b>6.2.1</b> Analyse de variance</a></li>
<li class="chapter" data-level="6.2.2" data-path="sect062.html"><a href="sect062.html#sect0622"><i class="fa fa-check"></i><b>6.2.2</b> Test non paramétrique de Kruskal-Wallis</a></li>
<li class="chapter" data-level="6.2.3" data-path="sect062.html"><a href="sect062.html#sect0623"><i class="fa fa-check"></i><b>6.2.3</b> Mise en œuvre dans R</a></li>
<li class="chapter" data-level="6.2.4" data-path="sect062.html"><a href="sect062.html#sect0624"><i class="fa fa-check"></i><b>6.2.4</b> Comment rapporter les résultats d’une ANOVA et du test de Kruskal-Wallis</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="sect063.html"><a href="sect063.html"><i class="fa fa-check"></i><b>6.3</b> Conclusion sur la troisième partie</a></li>
<li class="chapter" data-level="6.4" data-path="sect064.html"><a href="sect064.html"><i class="fa fa-check"></i><b>6.4</b> Quiz de révision du chapitre</a></li>
</ul></li>
<li class="part"><span><b>IV Modèles de régression</b></span></li>
<li class="chapter" data-level="7" data-path="chap07.html"><a href="chap07.html"><i class="fa fa-check"></i><b>7</b> Régression linéaire multiple</a><ul>
<li class="chapter" data-level="7.1" data-path="sect071.html"><a href="sect071.html"><i class="fa fa-check"></i><b>7.1</b> Objectifs de la régression linéaire multiple et construction d’un modèle de régression</a></li>
<li class="chapter" data-level="7.2" data-path="sect072.html"><a href="sect072.html"><i class="fa fa-check"></i><b>7.2</b> Principes de base de la régression linéaire multiple</a><ul>
<li class="chapter" data-level="7.2.1" data-path="sect072.html"><a href="sect072.html#sect0721"><i class="fa fa-check"></i><b>7.2.1</b> Un peu d’équations…</a></li>
<li class="chapter" data-level="7.2.2" data-path="sect072.html"><a href="sect072.html#sect0722"><i class="fa fa-check"></i><b>7.2.2</b> Hypothèses de la régression linéaire multiple</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="sect073.html"><a href="sect073.html"><i class="fa fa-check"></i><b>7.3</b> Évaluation de la qualité d’ajustement du modèle</a><ul>
<li class="chapter" data-level="7.3.1" data-path="sect073.html"><a href="sect073.html#sect0731"><i class="fa fa-check"></i><b>7.3.1</b> Mesures de la qualité d’un modèle</a></li>
<li class="chapter" data-level="7.3.2" data-path="sect073.html"><a href="sect073.html#sect0732"><i class="fa fa-check"></i><b>7.3.2</b> Comparaison des modèles incrémentiels</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="sect074.html"><a href="sect074.html"><i class="fa fa-check"></i><b>7.4</b> Différentes mesures pour les coefficients de régression</a><ul>
<li class="chapter" data-level="7.4.1" data-path="sect074.html"><a href="sect074.html#sect0741"><i class="fa fa-check"></i><b>7.4.1</b> Coefficients de régression : évaluer l’effet des variables indépendantes</a></li>
<li class="chapter" data-level="7.4.2" data-path="sect074.html"><a href="sect074.html#sect0742"><i class="fa fa-check"></i><b>7.4.2</b> Coefficients de régression standardisés : repérer les variables les plus importantes du modèle</a></li>
<li class="chapter" data-level="7.4.3" data-path="sect074.html"><a href="sect074.html#sect0743"><i class="fa fa-check"></i><b>7.4.3</b> Significativité des coefficients de régression : valeurs de <em>t</em> et de <em>p</em></a></li>
<li class="chapter" data-level="7.4.4" data-path="sect074.html"><a href="sect074.html#sect0744"><i class="fa fa-check"></i><b>7.4.4</b> Intervalle de confiance des coefficients</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="sect075.html"><a href="sect075.html"><i class="fa fa-check"></i><b>7.5</b> Introduction de variables explicatives particulières</a><ul>
<li class="chapter" data-level="7.5.1" data-path="sect075.html"><a href="sect075.html#sect0751"><i class="fa fa-check"></i><b>7.5.1</b> Exploration des relations non linéaires</a></li>
<li class="chapter" data-level="7.5.2" data-path="sect075.html"><a href="sect075.html#sect0752"><i class="fa fa-check"></i><b>7.5.2</b> Variable indépendante qualitative dichotomique</a></li>
<li class="chapter" data-level="7.5.3" data-path="sect075.html"><a href="sect075.html#sect0753"><i class="fa fa-check"></i><b>7.5.3</b> Variable indépendante qualitative polytomique</a></li>
<li class="chapter" data-level="7.5.4" data-path="sect075.html"><a href="sect075.html#sect0754"><i class="fa fa-check"></i><b>7.5.4</b> Variables d’interaction</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="sect076.html"><a href="sect076.html"><i class="fa fa-check"></i><b>7.6</b> Diagnostics de la régression</a><ul>
<li class="chapter" data-level="7.6.1" data-path="sect076.html"><a href="sect076.html#sect0761"><i class="fa fa-check"></i><b>7.6.1</b> Nombre d’observations</a></li>
<li class="chapter" data-level="7.6.2" data-path="sect076.html"><a href="sect076.html#sect0762"><i class="fa fa-check"></i><b>7.6.2</b> Normalité des résidus</a></li>
<li class="chapter" data-level="7.6.3" data-path="sect076.html"><a href="sect076.html#sect0763"><i class="fa fa-check"></i><b>7.6.3</b> Linéarité et homoscédasticité des résidus</a></li>
<li class="chapter" data-level="7.6.4" data-path="sect076.html"><a href="sect076.html#sect0764"><i class="fa fa-check"></i><b>7.6.4</b> Absence de multicolinéarité excessive</a></li>
<li class="chapter" data-level="7.6.5" data-path="sect076.html"><a href="sect076.html#sect0766"><i class="fa fa-check"></i><b>7.6.5</b> Absence d’observations aberrantes</a></li>
</ul></li>
<li class="chapter" data-level="7.7" data-path="sect077.html"><a href="sect077.html"><i class="fa fa-check"></i><b>7.7</b> Mise en œuvre dans R</a><ul>
<li class="chapter" data-level="7.7.1" data-path="sect077.html"><a href="sect077.html#sect0771"><i class="fa fa-check"></i><b>7.7.1</b> Fonctions <code>lm</code>, <code>summary()</code> et <code>confint()</code></a></li>
<li class="chapter" data-level="7.7.2" data-path="sect077.html"><a href="sect077.html#sect0772"><i class="fa fa-check"></i><b>7.7.2</b> Comparaison des modèles</a></li>
<li class="chapter" data-level="7.7.3" data-path="sect077.html"><a href="sect077.html#sect0773"><i class="fa fa-check"></i><b>7.7.3</b> Diagnostic sur un modèle</a></li>
<li class="chapter" data-level="7.7.4" data-path="sect077.html"><a href="sect077.html#sect0774"><i class="fa fa-check"></i><b>7.7.4</b> Graphiques pour les effets marginaux</a></li>
</ul></li>
<li class="chapter" data-level="7.8" data-path="sect078.html"><a href="sect078.html"><i class="fa fa-check"></i><b>7.8</b> Quiz de révision du chapitre</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="chap08.html"><a href="chap08.html"><i class="fa fa-check"></i><b>8</b> Régressions linéaires généralisées (GLM)</a><ul>
<li class="chapter" data-level="8.1" data-path="sect081.html"><a href="sect081.html"><i class="fa fa-check"></i><b>8.1</b> Qu’est qu’un modèle GLM?</a><ul>
<li class="chapter" data-level="8.1.1" data-path="sect081.html"><a href="sect081.html#sect0811"><i class="fa fa-check"></i><b>8.1.1</b> Formulation d’un GLM</a></li>
<li class="chapter" data-level="8.1.2" data-path="sect081.html"><a href="sect081.html#sect0812"><i class="fa fa-check"></i><b>8.1.2</b> Autres distributions et rôle de la fonction de lien</a></li>
<li class="chapter" data-level="8.1.3" data-path="sect081.html"><a href="sect081.html#sect0813"><i class="fa fa-check"></i><b>8.1.3</b> Conditions d’application</a></li>
<li class="chapter" data-level="8.1.4" data-path="sect081.html"><a href="sect081.html#sect0814"><i class="fa fa-check"></i><b>8.1.4</b> Résidus et déviance</a></li>
<li class="chapter" data-level="8.1.5" data-path="sect081.html"><a href="sect081.html#sect0815"><i class="fa fa-check"></i><b>8.1.5</b> Vérification l’ajustement</a></li>
<li class="chapter" data-level="8.1.6" data-path="sect081.html"><a href="sect081.html#sect0816"><i class="fa fa-check"></i><b>8.1.6</b> Comparaison de deux modèles GLM</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="sect082.html"><a href="sect082.html"><i class="fa fa-check"></i><b>8.2</b> Modèles GLM pour des variables qualitatives</a><ul>
<li class="chapter" data-level="8.2.1" data-path="sect082.html"><a href="sect082.html#sect0821"><i class="fa fa-check"></i><b>8.2.1</b> Modèle logistique binomial</a></li>
<li class="chapter" data-level="8.2.2" data-path="sect082.html"><a href="sect082.html#sect0822"><i class="fa fa-check"></i><b>8.2.2</b> Modèle probit binomial</a></li>
<li class="chapter" data-level="8.2.3" data-path="sect082.html"><a href="sect082.html#sect0823"><i class="fa fa-check"></i><b>8.2.3</b> Modèle logistique des cotes proportionnelles</a></li>
<li class="chapter" data-level="8.2.4" data-path="sect082.html"><a href="sect082.html#sect0824"><i class="fa fa-check"></i><b>8.2.4</b> Modèle logistique multinomial</a></li>
<li class="chapter" data-level="8.2.5" data-path="sect082.html"><a href="sect082.html#conclusion-sur-les-modèles-pour-des-variables-qualitatives"><i class="fa fa-check"></i><b>8.2.5</b> Conclusion sur les modèles pour des variables qualitatives</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="sect084.html"><a href="sect084.html"><i class="fa fa-check"></i><b>8.3</b> Modèles GLM pour des variables de comptage</a><ul>
<li class="chapter" data-level="8.3.1" data-path="sect084.html"><a href="sect084.html#sect0841"><i class="fa fa-check"></i><b>8.3.1</b> Modèle de Poisson</a></li>
<li class="chapter" data-level="8.3.2" data-path="sect084.html"><a href="sect084.html#sect0842"><i class="fa fa-check"></i><b>8.3.2</b> Modèle binomial négatif</a></li>
<li class="chapter" data-level="8.3.3" data-path="sect084.html"><a href="sect084.html#sect0843"><i class="fa fa-check"></i><b>8.3.3</b> Modèle de Poisson avec excès fixe de zéros</a></li>
<li class="chapter" data-level="8.3.4" data-path="sect084.html"><a href="sect084.html#sect0844"><i class="fa fa-check"></i><b>8.3.4</b> Modèle de Poisson avec excès ajusté de zéros</a></li>
<li class="chapter" data-level="8.3.5" data-path="sect084.html"><a href="sect084.html#sect0845"><i class="fa fa-check"></i><b>8.3.5</b> Conclusion sur les modèles destinés à des variables de comptage</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="sect085.html"><a href="sect085.html"><i class="fa fa-check"></i><b>8.4</b> Modèles GLM pour des variables continues</a><ul>
<li class="chapter" data-level="8.4.1" data-path="sect085.html"><a href="sect085.html#sect0851"><i class="fa fa-check"></i><b>8.4.1</b> Modèle GLM gaussien</a></li>
<li class="chapter" data-level="8.4.2" data-path="sect085.html"><a href="sect085.html#sect0852"><i class="fa fa-check"></i><b>8.4.2</b> Modèle GLM avec une distribution de Student</a></li>
<li class="chapter" data-level="8.4.3" data-path="sect085.html"><a href="sect085.html#sect0853"><i class="fa fa-check"></i><b>8.4.3</b> Modèle GLM avec distribution Gamma</a></li>
<li class="chapter" data-level="8.4.4" data-path="sect085.html"><a href="sect085.html#sect0854"><i class="fa fa-check"></i><b>8.4.4</b> Modèle GLM avec une distribution bêta</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="sect086.html"><a href="sect086.html"><i class="fa fa-check"></i><b>8.5</b> Conclusion sur les modèles linéaires généralisés</a></li>
<li class="chapter" data-level="8.6" data-path="sect087.html"><a href="sect087.html"><i class="fa fa-check"></i><b>8.6</b> Quiz de révision du chapitre</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="chap09.html"><a href="chap09.html"><i class="fa fa-check"></i><b>9</b> Régressions à effets mixtes (GLMM)</a><ul>
<li class="chapter" data-level="9.1" data-path="sect091.html"><a href="sect091.html"><i class="fa fa-check"></i><b>9.1</b> Introduction</a><ul>
<li class="chapter" data-level="9.1.1" data-path="sect091.html"><a href="sect091.html#sect0911"><i class="fa fa-check"></i><b>9.1.1</b> Indépendance des observations et effets de groupes</a></li>
<li class="chapter" data-level="9.1.2" data-path="sect091.html"><a href="sect091.html#sect0912"><i class="fa fa-check"></i><b>9.1.2</b> Terminologie: effets fixes et effets aléatoires</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="sect092.html"><a href="sect092.html"><i class="fa fa-check"></i><b>9.2</b> Principes de base des GLMM</a><ul>
<li class="chapter" data-level="9.2.1" data-path="sect092.html"><a href="sect092.html#sect0921"><i class="fa fa-check"></i><b>9.2.1</b> GLMM avec constantes aléatoires</a></li>
<li class="chapter" data-level="9.2.2" data-path="sect092.html"><a href="sect092.html#sect0923"><i class="fa fa-check"></i><b>9.2.2</b> GLMM avec pentes aléatoires</a></li>
<li class="chapter" data-level="9.2.3" data-path="sect092.html"><a href="sect092.html#sect0924"><i class="fa fa-check"></i><b>9.2.3</b> GLMM avec constantes et pentes aléatoires</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="sect093.html"><a href="sect093.html"><i class="fa fa-check"></i><b>9.3</b> Conditions d’application des GLMM</a><ul>
<li class="chapter" data-level="9.3.1" data-path="sect093.html"><a href="sect093.html#sect0931"><i class="fa fa-check"></i><b>9.3.1</b> Vérification de la distribution des effets aléatoires</a></li>
<li class="chapter" data-level="9.3.2" data-path="sect093.html"><a href="sect093.html#sect0932"><i class="fa fa-check"></i><b>9.3.2</b> Homogénéité des variances au sein des groupes</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="sect094.html"><a href="sect094.html"><i class="fa fa-check"></i><b>9.4</b> Inférence dans les modèles GLMM</a><ul>
<li class="chapter" data-level="9.4.1" data-path="sect094.html"><a href="sect094.html#sect0941"><i class="fa fa-check"></i><b>9.4.1</b> Inférence pour les effets fixes</a></li>
<li class="chapter" data-level="9.4.2" data-path="sect094.html"><a href="sect094.html#sect0942"><i class="fa fa-check"></i><b>9.4.2</b> Inférence pour les effets aléatoires, effet global</a></li>
<li class="chapter" data-level="9.4.3" data-path="sect094.html"><a href="sect094.html#sect0943"><i class="fa fa-check"></i><b>9.4.3</b> Inférence pour les effets aléatoires, des constantes et des pentes</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="sect095.html"><a href="sect095.html"><i class="fa fa-check"></i><b>9.5</b> Conclusion sur les GLMM</a></li>
<li class="chapter" data-level="9.6" data-path="sect096.html"><a href="sect096.html"><i class="fa fa-check"></i><b>9.6</b> Mise en œuvre des GLMM dans R</a><ul>
<li class="chapter" data-level="9.6.1" data-path="sect096.html"><a href="sect096.html#sect0961"><i class="fa fa-check"></i><b>9.6.1</b> Ajustement du modèle avec uniquement une constante aléatoire</a></li>
<li class="chapter" data-level="9.6.2" data-path="sect096.html"><a href="sect096.html#sect0962"><i class="fa fa-check"></i><b>9.6.2</b> Ajustement du modèle avec constantes et pentes aléatoires</a></li>
</ul></li>
<li class="chapter" data-level="9.7" data-path="sect097.html"><a href="sect097.html"><i class="fa fa-check"></i><b>9.7</b> Quiz de révision du chapitre</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="chap10.html"><a href="chap10.html"><i class="fa fa-check"></i><b>10</b> Régressions multiniveaux</a><ul>
<li class="chapter" data-level="10.1" data-path="sect101.html"><a href="sect101.html"><i class="fa fa-check"></i><b>10.1</b> Modèles multiniveaux : deux intérêts majeurs</a><ul>
<li class="chapter" data-level="10.1.1" data-path="sect101.html"><a href="sect101.html#sect1011"><i class="fa fa-check"></i><b>10.1.1</b> Répartition de la variance entre les différents niveaux</a></li>
<li class="chapter" data-level="10.1.2" data-path="sect101.html"><a href="sect101.html#sect1012"><i class="fa fa-check"></i><b>10.1.2</b> Estimation des coefficients aux différents niveaux</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="sect102.html"><a href="sect102.html"><i class="fa fa-check"></i><b>10.2</b> Différents types de modèles multiniveaux</a><ul>
<li class="chapter" data-level="10.2.1" data-path="sect102.html"><a href="sect102.html#sect1021"><i class="fa fa-check"></i><b>10.2.1</b> Description du jeu de données utilisé</a></li>
<li class="chapter" data-level="10.2.2" data-path="sect102.html"><a href="sect102.html#sect1022"><i class="fa fa-check"></i><b>10.2.2</b> Démarche classique pour les modèles multiniveaux</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="sect103.html"><a href="sect103.html"><i class="fa fa-check"></i><b>10.3</b> Conditions d’application des régressions multiniveaux</a></li>
<li class="chapter" data-level="10.4" data-path="sect104.html"><a href="sect104.html"><i class="fa fa-check"></i><b>10.4</b> Mise en œuvre dans R</a><ul>
<li class="chapter" data-level="10.4.1" data-path="sect104.html"><a href="sect104.html#sect1041"><i class="fa fa-check"></i><b>10.4.1</b> Le modèle vide</a></li>
<li class="chapter" data-level="10.4.2" data-path="sect104.html"><a href="sect104.html#sect1042"><i class="fa fa-check"></i><b>10.4.2</b> Modèle avec les variables indépendantes du niveau 1</a></li>
<li class="chapter" data-level="10.4.3" data-path="sect104.html"><a href="sect104.html#sect1043"><i class="fa fa-check"></i><b>10.4.3</b> Modèle avec les variables indépendantes aux niveaux 1 et 2</a></li>
<li class="chapter" data-level="10.4.4" data-path="sect104.html"><a href="sect104.html#sect10414"><i class="fa fa-check"></i><b>10.4.4</b> Modèle complet avec une interaction</a></li>
<li class="chapter" data-level="10.4.5" data-path="sect104.html"><a href="sect104.html#sect1045"><i class="fa fa-check"></i><b>10.4.5</b> Comparaison des quatre modèles</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="sect105.html"><a href="sect105.html"><i class="fa fa-check"></i><b>10.5</b> Quiz de révision du chapitre</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="chap11.html"><a href="chap11.html"><i class="fa fa-check"></i><b>11</b> Modèles généralisés additifs</a><ul>
<li class="chapter" data-level="11.1" data-path="sect111.html"><a href="sect111.html"><i class="fa fa-check"></i><b>11.1</b> Introduction</a><ul>
<li class="chapter" data-level="11.1.1" data-path="sect111.html"><a href="sect111.html#sect1111"><i class="fa fa-check"></i><b>11.1.1</b> Non linéarité fonctionnelle</a></li>
<li class="chapter" data-level="11.1.2" data-path="sect111.html"><a href="sect111.html#sect1112"><i class="fa fa-check"></i><b>11.1.2</b> Non linéarité avec des polynomiales</a></li>
<li class="chapter" data-level="11.1.3" data-path="sect111.html"><a href="sect111.html#sect1113"><i class="fa fa-check"></i><b>11.1.3</b> Non linéarité par segments</a></li>
<li class="chapter" data-level="11.1.4" data-path="sect111.html"><a href="sect111.html#sect1114"><i class="fa fa-check"></i><b>11.1.4</b> Non linéarité avec des <em>splines</em></a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="sect112.html"><a href="sect112.html"><i class="fa fa-check"></i><b>11.2</b> <em>Spline</em> de régression et <em>spline</em> de lissage</a></li>
<li class="chapter" data-level="11.3" data-path="sect113.html"><a href="sect113.html"><i class="fa fa-check"></i><b>11.3</b> Interprétation d’une <em>spline</em></a></li>
<li class="chapter" data-level="11.4" data-path="sect114.html"><a href="sect114.html"><i class="fa fa-check"></i><b>11.4</b> Multicolinéarité non linéaire</a></li>
<li class="chapter" data-level="11.5" data-path="sect115.html"><a href="sect115.html"><i class="fa fa-check"></i><b>11.5</b> <em>Splines</em> avancées</a><ul>
<li class="chapter" data-level="11.5.1" data-path="sect115.html"><a href="sect115.html#sect1151"><i class="fa fa-check"></i><b>11.5.1</b> <em>Splines</em> cycliques</a></li>
<li class="chapter" data-level="11.5.2" data-path="sect115.html"><a href="sect115.html#sect1152"><i class="fa fa-check"></i><b>11.5.2</b> Splines par groupe</a></li>
<li class="chapter" data-level="11.5.3" data-path="sect115.html"><a href="sect115.html#sect1153"><i class="fa fa-check"></i><b>11.5.3</b> <em>Splines</em> multivariées et <em>splines</em> d’interaction</a></li>
</ul></li>
<li class="chapter" data-level="11.6" data-path="sect116.html"><a href="sect116.html"><i class="fa fa-check"></i><b>11.6</b> Mise en oeuvre dans R</a></li>
<li class="chapter" data-level="11.7" data-path="sect117.html"><a href="sect117.html"><i class="fa fa-check"></i><b>11.7</b> GAMM</a></li>
<li class="chapter" data-level="11.8" data-path="sect118.html"><a href="sect118.html"><i class="fa fa-check"></i><b>11.8</b> Quiz de révision du chapitre</a></li>
</ul></li>
<li class="part"><span><b>V Analyses exploratoires multivariées</b></span></li>
<li class="chapter" data-level="12" data-path="chap12.html"><a href="chap12.html"><i class="fa fa-check"></i><b>12</b> Méthodes factorielles</a><ul>
<li class="chapter" data-level="12.1" data-path="sect121.html"><a href="sect121.html"><i class="fa fa-check"></i><b>12.1</b> Aperçu des méthodes factorielles</a><ul>
<li class="chapter" data-level="12.1.1" data-path="sect121.html"><a href="sect121.html#sect1211"><i class="fa fa-check"></i><b>12.1.1</b> Méthodes factorielles et types de données</a></li>
<li class="chapter" data-level="12.1.2" data-path="sect121.html"><a href="sect121.html#sect1212"><i class="fa fa-check"></i><b>12.1.2</b> Bref historique des méthodes factorielles</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="sect122.html"><a href="sect122.html"><i class="fa fa-check"></i><b>12.2</b> Analyses en composantes principales (ACP)</a><ul>
<li class="chapter" data-level="12.2.1" data-path="sect122.html"><a href="sect122.html#sect1221"><i class="fa fa-check"></i><b>12.2.1</b> Recherche d’une simplification</a></li>
<li class="chapter" data-level="12.2.2" data-path="sect122.html"><a href="sect122.html#sect1222"><i class="fa fa-check"></i><b>12.2.2</b> Aides à l’interprétation</a></li>
<li class="chapter" data-level="12.2.3" data-path="sect122.html"><a href="sect122.html#sect1223"><i class="fa fa-check"></i><b>12.2.3</b> Mise en œuvre dans R</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="sect123.html"><a href="sect123.html"><i class="fa fa-check"></i><b>12.3</b> Analyse factorielle des correspondances (AFC)</a><ul>
<li class="chapter" data-level="12.3.1" data-path="sect123.html"><a href="sect123.html#sect1231"><i class="fa fa-check"></i><b>12.3.1</b> Recherche d’une simplification basée sur la distance du khi-deux</a></li>
<li class="chapter" data-level="12.3.2" data-path="sect123.html"><a href="sect123.html#sect1232"><i class="fa fa-check"></i><b>12.3.2</b> Aides à l’interprétation</a></li>
<li class="chapter" data-level="12.3.3" data-path="sect123.html"><a href="sect123.html#sect1233"><i class="fa fa-check"></i><b>12.3.3</b> Mise en œuvre dans R</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="sect124.html"><a href="sect124.html"><i class="fa fa-check"></i><b>12.4</b> Analyse de correspondances multiples (ACM)</a><ul>
<li class="chapter" data-level="12.4.1" data-path="sect124.html"><a href="sect124.html#sect1241"><i class="fa fa-check"></i><b>12.4.1</b> Aides à l’interprétation</a></li>
<li class="chapter" data-level="12.4.2" data-path="sect124.html"><a href="sect124.html#sect1242"><i class="fa fa-check"></i><b>12.4.2</b> Mise en œuvre dans R</a></li>
</ul></li>
<li class="chapter" data-level="12.5" data-path="sect125.html"><a href="sect125.html"><i class="fa fa-check"></i><b>12.5</b> Quiz de révision du chapitre</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="chap13.html"><a href="chap13.html"><i class="fa fa-check"></i><b>13</b> Méthodes de classification non supervisée</a><ul>
<li class="chapter" data-level="13.1" data-path="sect131.html"><a href="sect131.html"><i class="fa fa-check"></i><b>13.1</b> Méthodes de classification : un aperçu</a></li>
<li class="chapter" data-level="13.2" data-path="sect132.html"><a href="sect132.html"><i class="fa fa-check"></i><b>13.2</b> Notions essentielles en classification</a><ul>
<li class="chapter" data-level="13.2.1" data-path="sect132.html"><a href="sect132.html#sect1321"><i class="fa fa-check"></i><b>13.2.1</b> Distance</a></li>
<li class="chapter" data-level="13.2.2" data-path="sect132.html"><a href="sect132.html#sect1322"><i class="fa fa-check"></i><b>13.2.2</b> Inertie</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="sect133.html"><a href="sect133.html"><i class="fa fa-check"></i><b>13.3</b> Classification ascendante hiérarchique</a><ul>
<li class="chapter" data-level="13.3.1" data-path="sect133.html"><a href="sect133.html#sect1331"><i class="fa fa-check"></i><b>13.3.1</b> Fonctionnement de l’algorithme</a></li>
<li class="chapter" data-level="13.3.2" data-path="sect133.html"><a href="sect133.html#sect1332"><i class="fa fa-check"></i><b>13.3.2</b> Choisir le bon nombre de groupes</a></li>
<li class="chapter" data-level="13.3.3" data-path="sect133.html"><a href="sect133.html#sect1333"><i class="fa fa-check"></i><b>13.3.3</b> Limites de la classification ascendante hiérarchique</a></li>
<li class="chapter" data-level="13.3.4" data-path="sect133.html"><a href="sect133.html#sect1334"><i class="fa fa-check"></i><b>13.3.4</b> Mise en oeuvre dans R</a></li>
</ul></li>
<li class="chapter" data-level="13.4" data-path="sect134.html"><a href="sect134.html"><i class="fa fa-check"></i><b>13.4</b> Nuées dynamiques</a><ul>
<li class="chapter" data-level="13.4.1" data-path="sect134.html"><a href="sect134.html#sect1341"><i class="fa fa-check"></i><b>13.4.1</b> <em>K-means</em></a></li>
<li class="chapter" data-level="13.4.2" data-path="sect134.html"><a href="sect134.html#sect1342"><i class="fa fa-check"></i><b>13.4.2</b> K-médianes</a></li>
<li class="chapter" data-level="13.4.3" data-path="sect134.html"><a href="sect134.html#sect1343"><i class="fa fa-check"></i><b>13.4.3</b> K-médoïds</a></li>
<li class="chapter" data-level="13.4.4" data-path="sect134.html"><a href="sect134.html#sect1344"><i class="fa fa-check"></i><b>13.4.4</b> Mise en oeuvre dans R</a></li>
<li class="chapter" data-level="13.4.5" data-path="sect134.html"><a href="sect134.html#sect1346"><i class="fa fa-check"></i><b>13.4.5</b> Extensions en logique floue : <em>c-means</em>, <em>c-medoids</em></a></li>
</ul></li>
<li class="chapter" data-level="13.5" data-path="sect135.html"><a href="sect135.html"><i class="fa fa-check"></i><b>13.5</b> Conclusion sur la cinquième partie</a></li>
<li class="chapter" data-level="13.6" data-path="sect136.html"><a href="sect136.html"><i class="fa fa-check"></i><b>13.6</b> Quiz de révision du chapitre</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="annexes.html"><a href="annexes.html"><i class="fa fa-check"></i><b>14</b> Annexes</a><ul>
<li class="chapter" data-level="14.1" data-path="annexe1.html"><a href="annexe1.html"><i class="fa fa-check"></i><b>14.1</b> Table des valeurs critiques de khi-deux</a></li>
<li class="chapter" data-level="14.2" data-path="annexe2.html"><a href="annexe2.html"><i class="fa fa-check"></i><b>14.2</b> Table des valeurs critiques de Fisher</a></li>
<li class="chapter" data-level="14.3" data-path="annexe3.html"><a href="annexe3.html"><i class="fa fa-check"></i><b>14.3</b> Table des valeurs critiques de <em>t</em></a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Méthodes quantitatives en sciences sociales : un grand bol d’R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="sect123" class="section level2">
<h2><span class="header-section-number">12.3</span> Analyse factorielle des correspondances (AFC)</h2>
<div class="bloc_notes">
<p>Pour bien comprendre l’AFC, il est essentiel de bien maîtriser les notions de tableau de contingence (marges du tableau, fréquences observées et théoriques, pourcentages en ligne et en colonne, contributions au khi-deux) et de distance du khi-deux. Si ce n’est pas le cas, il est conseillé de (re)lire le chapitre <a href="chap05.html#chap05">5</a>.</p>
</div>
<p>Dans le chapitre <a href="chap05.html#chap05">5</a>, nous avons vu comment construire un tableau de contingence (figure <a href="sect123.html#fig:AnalysesFactoriellesTabAFCFig">12.23</a>) à partir de deux variables qualitatives comprenant plusieurs modalités, puis comment vérifier s’il y a dépendance entre les deux variables qualitatives avec le test du khi-deux. Or, s’il y a bien dépendance, il est peut-être judicieux de résumer l’information que contient le tableau de contingence en quelques nouvelles variables synthétiques, objectif auquel répond l’analyse factorielle des correspondances (AFC).</p>
<div class="figure" style="text-align: center"><span id="fig:AnalysesFactoriellesTabAFCFig"></span>
<img src="images/analysesfactorielles/AnalysesFactoriellesTabAFC.png" alt="Tableau de contingence pour une AFC" width="70%" />
<p class="caption">
Figure 12.23: Tableau de contingence pour une AFC
</p>
</div>
<p>À titre de rappel (section <a href="sect121.html#sect1212">12.1.2</a>), l’AFC a été développée par le statisticien français Jean-Paul Benzécri <span class="citation">(<a href="#ref-benzecri1973analyse" role="doc-biblioref">1973</a>)</span>. Cela explique qu’elle est souvent enseignée et utilisée en sciences sociales dans les universités francophones, mais plus rarement dans les universités anglophones. Pourtant, les applications de l’AFC sont nombreuses dans différentes disciplines des sciences sociales comme illustrées avec les exemples suivants :</p>
<ul>
<li>En géographie, les modalités de la première variable du tableau de contingence sont souvent des entités spatiales (régions, municipalités, quartiers, etc.) croisées avec les modalités d’une autre variable qualitative (catégories socioprofessionnelles, modes de transport, tranches de revenu des ménages ou des individus, etc.).</li>
<li>En économie régionale, nous pourrions vouloir explorer un tableau de contingence croisant des entités spatiales (par exemple, MRC au Québec, départements en France) et les effectifs d’emplois pour différents secteurs d’activité.</li>
<li>En sciences politiques, le recours à l’AFC peut être intéressant pour explorer les résultats d’une élection. Les deux variables qualitatives pourraient être les <em>circonscriptions électorales</em> et les <em>partis politiques</em>. Le croisement des lignes et des colonnes du tableau de contingence représenterait le nombre de votes obtenus par un parti politique <em>j</em> dans la circonscription électorale <em>i</em>. Appliquer une AFC sur un tel tableau de contingence permettrait de révéler les ressemblances entre les différents partis politiques et celles entre les circonscriptions électorales.</li>
</ul>
<p>::: {.bloc_attention data-latex=""}</p>
<p><strong>Application d’une ACP sur un tableau de contingence transformé en un tableau avec les pourcentages en ligne : un bien mauvais calcul…</strong></p>
<p>Il pourrait être tentant de transformer le tableau de contingence initial (tableau <a href="sect123.html#tab:encadreAFCACP1">12.7</a>) en un tableau avec les pourcentages en ligne (tableau <a href="sect123.html#tab:encadreAFCACP2">12.8</a>) afin de lui appliquer une analyse en composantes principales. Une telle démarche a deux inconvénients majeurs : chacune des modalités de la première variable qualitative (<em>I</em>) aurait alors le même poids; chacune des modalités de la deuxième variable (<em>J</em>) aurait aussi le même poids. Or, à la lecture des marges en ligne et en colonne au tableau <a href="sect123.html#tab:encadreAFCACP1">12.7</a>, il est clair que les modalités <code>j1</code> et <code>i1</code> comprennent bien plus d’individus que les autres modalités respectives.</p>
<p>Si nous reprenons le dernier exemple applicatif, cela signifierait que le même poids est accordé à chaque parti puisque les variables sont centrées réduites en ACP (moyenne = 0 et variance = 1). Autrement dit, les grands partis traditionnels seraient ainsi sur le pied d’égalité que les autres partis. Aussi, chaque circonscription électorale aurait le même poids bien que certaines comprennent bien plus d’électeurs et d’électrices que d’autres.</p>
<table>
<caption>
<span id="tab:encadreAFCACP1">Tableau 12.7: </span>Exemple de tableau de contingence pour l’AFC
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
j1
</th>
<th style="text-align:right;">
j2
</th>
<th style="text-align:right;">
j3
</th>
<th style="text-align:right;">
j4
</th>
<th style="text-align:right;">
j5
</th>
<th style="text-align:right;">
Marge (ligne)
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
i1
</td>
<td style="text-align:right;">
357 060
</td>
<td style="text-align:right;">
22 010
</td>
<td style="text-align:right;">
276 625
</td>
<td style="text-align:right;">
65 000
</td>
<td style="text-align:right;">
29 415
</td>
<td style="text-align:right;">
750 110
</td>
</tr>
<tr>
<td style="text-align:left;">
i2
</td>
<td style="text-align:right;">
427 530
</td>
<td style="text-align:right;">
26 400
</td>
<td style="text-align:right;">
295 860
</td>
<td style="text-align:right;">
69 410
</td>
<td style="text-align:right;">
30 645
</td>
<td style="text-align:right;">
849 845
</td>
</tr>
<tr>
<td style="text-align:left;">
i3
</td>
<td style="text-align:right;">
147 500
</td>
<td style="text-align:right;">
6 545
</td>
<td style="text-align:right;">
34 545
</td>
<td style="text-align:right;">
4 415
</td>
<td style="text-align:right;">
1 040
</td>
<td style="text-align:right;">
194 045
</td>
</tr>
<tr>
<td style="text-align:left;">
i4
</td>
<td style="text-align:right;">
128 520
</td>
<td style="text-align:right;">
6 405
</td>
<td style="text-align:right;">
42 925
</td>
<td style="text-align:right;">
6 565
</td>
<td style="text-align:right;">
2 670
</td>
<td style="text-align:right;">
187 085
</td>
</tr>
<tr>
<td style="text-align:left;">
Marge (colonne)
</td>
<td style="text-align:right;">
1 060 610
</td>
<td style="text-align:right;">
61 360
</td>
<td style="text-align:right;">
649 955
</td>
<td style="text-align:right;">
145 390
</td>
<td style="text-align:right;">
63 770
</td>
<td style="text-align:right;">
1 981 085
</td>
</tr>
</tbody>
</table>
<table>
<caption>
<span id="tab:encadreAFCACP2">Tableau 12.8: </span>Exemple d’un tableau de contingence transformé (pourcentage en ligne) pour l’ACP
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
V1
</th>
<th style="text-align:right;">
V2
</th>
<th style="text-align:right;">
V3
</th>
<th style="text-align:right;">
V4
</th>
<th style="text-align:right;">
V5
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
i1
</td>
<td style="text-align:right;">
47,6
</td>
<td style="text-align:right;">
2,9
</td>
<td style="text-align:right;">
36,9
</td>
<td style="text-align:right;">
8,7
</td>
<td style="text-align:right;">
3,9
</td>
</tr>
<tr>
<td style="text-align:left;">
i2
</td>
<td style="text-align:right;">
50,3
</td>
<td style="text-align:right;">
3,1
</td>
<td style="text-align:right;">
34,8
</td>
<td style="text-align:right;">
8,2
</td>
<td style="text-align:right;">
3,6
</td>
</tr>
<tr>
<td style="text-align:left;">
i3
</td>
<td style="text-align:right;">
76,0
</td>
<td style="text-align:right;">
3,4
</td>
<td style="text-align:right;">
17,8
</td>
<td style="text-align:right;">
2,3
</td>
<td style="text-align:right;">
0,5
</td>
</tr>
<tr>
<td style="text-align:left;">
i4
</td>
<td style="text-align:right;">
68,7
</td>
<td style="text-align:right;">
3,4
</td>
<td style="text-align:right;">
22,9
</td>
<td style="text-align:right;">
3,5
</td>
<td style="text-align:right;">
1,4
</td>
</tr>
</tbody>
</table>
<p>:::</p>
<div id="sect1231" class="section level3">
<h3><span class="header-section-number">12.3.1</span> Recherche d’une simplification basée sur la distance du khi-deux</h3>
<p>Sur le plan mathématique et des objectifs visés, l’AFC est similaire à l’ACP puisqu’elle permet d’explorer un tableau de trois façons : 1) en montrant les ressemblances entre un ensemble d’individus (<em>I</em>), 2) en révélant les liaisons entre les variables (<em>J</em>) et 3) en résumant le tout avec des variables synthétiques. Toutefois, avec l’AFC, les ensembles <em>I</em> et <em>J</em> sont les modalités de deux variables qualitatives (dont le croisement forme un tableau de contingence) et elle est basée sur la distance du khi-deux (et non sur la distance euclidienne comme en ACP).</p>
<p>Ainsi, avec la distance du khi-deux, la proximité (ressemblance) entre deux lignes (<em>i</em> et <em>l</em>) et deux colonnes (<em>j</em> et <em>k</em>) est mesurée comme suit :</p>

<p><span class="math display" id="eq:khideuxlignes">\[\begin{equation}
d_{\chi_{il}^2} = \sum_j \frac{1}{f_{.j}}(\frac{f_{ij}}{f_{i.}}-\frac{f_{lj}}{f_{l.}})^2
\tag{12.5}
\end{equation}\]</span>
</p>

<p><span class="math display" id="eq:khideuxcolonnes">\[\begin{equation}
d_{\chi_{jk}^2} = \sum_i \frac{1}{f_{i.}}(\frac{f_{ij}}{f_{.j}}-\frac{f_{ik}}{f_{.k}})^2
\tag{12.6}
\end{equation}\]</span>
</p>
<p>Prenons un exemple fictif pour calculer ces deux distances. Le tableau <a href="sect123.html#tab:afcdataex1">12.9</a> comprend trois modalités en ligne (<em>I</em>) et trois autres en colonne (<em>J</em>). Le total des effectifs de ce tableau de contingence est égal à 1 665.</p>
<p>À partir des données brutes, il est facile de construire deux tableaux : le profil des lignes et le profil des colonnes (tableau <a href="sect123.html#tab:afcProfilsLignesCols">12.10</a>), c’est-à-dire les proportions en ligne et en colonne.</p>
<table>
<caption>
<span id="tab:afcdataex1">Tableau 12.9: </span>Données brutes du tableau de contingence
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:center;">
j1
</th>
<th style="text-align:center;">
j2
</th>
<th style="text-align:center;">
j3
</th>
<th style="text-align:center;">
Total (ligne)
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
i1
</td>
<td style="text-align:center;">
360
</td>
<td style="text-align:center;">
65
</td>
<td style="text-align:center;">
275
</td>
<td style="text-align:center;">
700
</td>
</tr>
<tr>
<td style="text-align:left;">
i2
</td>
<td style="text-align:center;">
420
</td>
<td style="text-align:center;">
70
</td>
<td style="text-align:center;">
290
</td>
<td style="text-align:center;">
780
</td>
</tr>
<tr>
<td style="text-align:left;">
i3
</td>
<td style="text-align:center;">
145
</td>
<td style="text-align:center;">
5
</td>
<td style="text-align:center;">
35
</td>
<td style="text-align:center;">
185
</td>
</tr>
<tr>
<td style="text-align:left;">
Total (colonne)
</td>
<td style="text-align:center;">
925
</td>
<td style="text-align:center;">
140
</td>
<td style="text-align:center;">
600
</td>
<td style="text-align:center;">
1 665
</td>
</tr>
</tbody>
</table>
<table>
<caption>
<span id="tab:afcProfilsLignesCols">Tableau 12.10: </span>Profils des lignes et des colonnes
</caption>
<thead>
<tr>
<th style="text-align:center;">
</th>
<th style="text-align:center;">
j1
</th>
<th style="text-align:center;">
j2
</th>
<th style="text-align:center;">
j3
</th>
<th style="text-align:center;">
Total
</th>
</tr>
</thead>
<tbody>
<tr grouplength="3">
<td colspan="5" style="border-bottom: 1px solid;">
<strong>Profil des lignes</strong>
</td>
</tr>
<tr>
<td style="text-align:center;padding-left: 2em;" indentlevel="1">
i1
</td>
<td style="text-align:center;">
0,514
</td>
<td style="text-align:center;">
0,093
</td>
<td style="text-align:center;">
0,393
</td>
<td style="text-align:center;">
1
</td>
</tr>
<tr>
<td style="text-align:center;padding-left: 2em;" indentlevel="1">
i2
</td>
<td style="text-align:center;">
0,538
</td>
<td style="text-align:center;">
0,090
</td>
<td style="text-align:center;">
0,372
</td>
<td style="text-align:center;">
1
</td>
</tr>
<tr>
<td style="text-align:center;padding-left: 2em;" indentlevel="1">
i3
</td>
<td style="text-align:center;">
0,784
</td>
<td style="text-align:center;">
0,027
</td>
<td style="text-align:center;">
0,189
</td>
<td style="text-align:center;">
1
</td>
</tr>
<tr grouplength="4">
<td colspan="5" style="border-bottom: 1px solid;">
<strong>Profils des colonnes</strong>
</td>
</tr>
<tr>
<td style="text-align:center;padding-left: 2em;" indentlevel="1">
i1
</td>
<td style="text-align:center;">
0,389
</td>
<td style="text-align:center;">
0,464
</td>
<td style="text-align:center;">
0,458
</td>
<td style="text-align:center;">
</td>
</tr>
<tr>
<td style="text-align:center;padding-left: 2em;" indentlevel="1">
i2
</td>
<td style="text-align:center;">
0,454
</td>
<td style="text-align:center;">
0,500
</td>
<td style="text-align:center;">
0,483
</td>
<td style="text-align:center;">
</td>
</tr>
<tr>
<td style="text-align:center;padding-left: 2em;" indentlevel="1">
i3
</td>
<td style="text-align:center;">
0,157
</td>
<td style="text-align:center;">
0,036
</td>
<td style="text-align:center;">
0,058
</td>
<td style="text-align:center;">
</td>
</tr>
<tr>
<td style="text-align:center;padding-left: 2em;" indentlevel="1">
Total
</td>
<td style="text-align:center;">
1,000
</td>
<td style="text-align:center;">
1,000
</td>
<td style="text-align:center;">
1,000
</td>
<td style="text-align:center;">
</td>
</tr>
</tbody>
</table>
<p>En divisant les valeurs du tableau <a href="sect123.html#tab:afcdataex1">12.9</a> par le grand total (1 665), nous obtenons tous les termes utilisés dans les équations <a href="sect123.html#eq:khideuxlignes">(12.5)</a> et <a href="sect123.html#eq:khideuxcolonnes">(12.6)</a> au tableau <a href="sect123.html#tab:afcdataex2">12.11</a> :</p>
<ul>
<li>Les fréquences relatives dénommées <span class="math inline">\(f_{ij}\)</span>.</li>
<li>La marge <span class="math inline">\(fi.\)</span> est égale à la somme des fréquences relatives en ligne.</li>
<li>La marge <span class="math inline">\(f.j\)</span> est égale à la somme des fréquences relatives en colonne.</li>
<li>La somme de toutes les fréquences relatives est donc égale à 1, soit <span class="math inline">\(\sum{f_{i.}}\)</span> ou <span class="math inline">\(\sum{f_{.j}}\)</span>.</li>
</ul>
<table>
<caption>
<span id="tab:afcdataex2">Tableau 12.11: </span>Données relatives du tableau de contingence (fij)
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
j1
</th>
<th style="text-align:right;">
j2
</th>
<th style="text-align:right;">
j3
</th>
<th style="text-align:right;">
Total (fi.)
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
i1
</td>
<td style="text-align:right;">
0,216
</td>
<td style="text-align:right;">
0,039
</td>
<td style="text-align:right;">
0,165
</td>
<td style="text-align:right;">
0,420
</td>
</tr>
<tr>
<td style="text-align:left;">
i2
</td>
<td style="text-align:right;">
0,252
</td>
<td style="text-align:right;">
0,042
</td>
<td style="text-align:right;">
0,174
</td>
<td style="text-align:right;">
0,468
</td>
</tr>
<tr>
<td style="text-align:left;">
i3
</td>
<td style="text-align:right;">
0,087
</td>
<td style="text-align:right;">
0,003
</td>
<td style="text-align:right;">
0,021
</td>
<td style="text-align:right;">
0,111
</td>
</tr>
<tr>
<td style="text-align:left;">
Total (f.j)
</td>
<td style="text-align:right;">
0,556
</td>
<td style="text-align:right;">
0,084
</td>
<td style="text-align:right;">
0,360
</td>
<td style="text-align:right;">
1,000
</td>
</tr>
</tbody>
</table>
<p>Il est possible de calculer les distances entre les différentes modalités de <em>I</em> en appliquant l’équation <a href="sect123.html#eq:khideuxlignes">(12.5)</a>; par exemple, la distance entre les observations <code>i1</code> et <code>i2</code> est égale à :</p>
<p><span class="math display">\[d_{(i1,i2)}=\frac{\mbox{1}}{\mbox{0,556}}(\mbox{0,216}-\mbox{0,252})^2+\frac{\mbox{1}}{\mbox{0,084}}(\mbox{0,039}-\mbox{0,042})^2+
\frac{\mbox{1}}{\mbox{0,360}}(\mbox{0,165}-\mbox{0,174})^2=\mbox{0,003}\]</span></p>
<p>Avec l’équation <a href="sect123.html#eq:khideuxcolonnes">(12.6)</a>, la distance entre les modalités <code>j1</code> et <code>j2</code> de <em>J</em> est égale à :</p>
<p><span class="math display">\[d_{(j1,j2)}=\frac{\mbox{1}}{\mbox{0,420}}(\mbox{0,216}-\mbox{0,039})^2+ \frac{\mbox{1}}{\mbox{0,468}}(\mbox{0,252}-\mbox{0,042})^2 + \frac{\mbox{1}}{\mbox{0,111}}(\mbox{0,087}-\mbox{0,003})^2=\mbox{0,233}\]</span></p>
<p>À la lecture du tableau <a href="sect123.html#tab:MatriceDistKhi">12.12</a>, les modalités les plus semblables sont
<code>i1</code> et <code>i2</code> (0,003) pour <em>I</em> et <code>j1</code> et <code>j3</code> (0,058) pour <em>J</em>.</p>
<table>
<caption>
<span id="tab:MatriceDistKhi">Tableau 12.12: </span>Distances du khi-deux entre les modalités I et les modalités J
</caption>
<thead>
<tr>
<th style="text-align:center;">
Ind.
</th>
<th style="text-align:center;">
i1
</th>
<th style="text-align:center;">
i2
</th>
<th style="text-align:center;">
i3
</th>
<th style="text-align:center;">
Col.
</th>
<th style="text-align:center;">
j1
</th>
<th style="text-align:center;">
j2
</th>
<th style="text-align:center;">
j3
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
i1
</td>
<td style="text-align:center;">
0,000
</td>
<td style="text-align:center;">
0,003
</td>
<td style="text-align:center;">
0,103
</td>
<td style="text-align:center;">
j1
</td>
<td style="text-align:center;">
0,000
</td>
<td style="text-align:center;">
0,233
</td>
<td style="text-align:center;">
0,058
</td>
</tr>
<tr>
<td style="text-align:center;">
i2
</td>
<td style="text-align:center;">
0,003
</td>
<td style="text-align:center;">
0,000
</td>
<td style="text-align:center;">
0,132
</td>
<td style="text-align:center;">
j2
</td>
<td style="text-align:center;">
0,233
</td>
<td style="text-align:center;">
0,000
</td>
<td style="text-align:center;">
0,078
</td>
</tr>
<tr>
<td style="text-align:center;">
i3
</td>
<td style="text-align:center;">
0,103
</td>
<td style="text-align:center;">
0,132
</td>
<td style="text-align:center;">
0,000
</td>
<td style="text-align:center;">
j3
</td>
<td style="text-align:center;">
0,058
</td>
<td style="text-align:center;">
0,078
</td>
<td style="text-align:center;">
0,000
</td>
</tr>
</tbody>
</table>
<p>Finalement, l’approche pour déterminer les axes factoriels de l’AFC est similaire à celle de l’ACP : les axes factoriels sont les droites orthogonales qui minimisent les distances aux points du profil des lignes, excepté que la métrique pour mesurer ces distances est celle du khi-deux (et non celle la distance euclidienne comme pour l’ACP). Pour plus détails sur le calcul de ces axes (notamment les formulations matricielles), consultez notamment Benzécri <span class="citation">(<a href="#ref-benzecri1973analyse" role="doc-biblioref">1973</a>)</span>, Escofier et Pagès <span class="citation">(<a href="#ref-escofier1998analyses" role="doc-biblioref">1998</a>)</span> et Lebart et al. <span class="citation">(<a href="#ref-lebart1995statistique" role="doc-biblioref">1995</a>)</span>.</p>
</div>
<div id="sect1232" class="section level3">
<h3><span class="header-section-number">12.3.2</span> Aides à l’interprétation</h3>
<p>Pour illustrer les aides à l’interprétation de l’AFC, nous utilisons un jeu de données spatiales extrait du <a href="https://www12.statcan.gc.ca/census-recensement/2016/dp-pd/prof/index.cfm?Lang=F" target="_blank">profil du recensement de 2016 de Statistique Canada</a> pour les secteurs de recensement de l’île de Montréal. La liste des modalités des variables qu’il comprend est reportée au tableau <a href="sect123.html#tab:dataAfc">12.13</a>. L’AFC est calculée sur un tableau de contingence croisant les secteurs de recensement (lignes) et les modalités d’une variable relative au mode de transport utilisé pour les déplacements domicile-travail (colonnes). Ces modalités sont cartographiées à la figure <a href="sect123.html#fig:cartovarAFC">12.24</a>.</p>
<table>
<caption>
<span id="tab:dataAfc">Tableau 12.13: </span>Jeu de données utilisé pour l’analyse factorielle des correspondances
</caption>
<thead>
<tr>
<th style="text-align:left;">
Nom
</th>
<th style="text-align:left;">
Intitulé
</th>
<th style="text-align:right;">
Somme
</th>
</tr>
</thead>
<tbody>
<tr grouplength="6">
<td colspan="3" style="border-bottom: 1px solid;">
<strong>Modalités de la variable utilisée dans l’AFC (mode de transport)</strong>
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
VehCond
</td>
<td style="text-align:left;">
Véhicule motorisé (conducteur·trice)
</td>
<td style="text-align:right;">
427 560
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
VehPass
</td>
<td style="text-align:left;">
Véhicule motorisé (passager·ère)
</td>
<td style="text-align:right;">
26 490
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
TranspC
</td>
<td style="text-align:left;">
Transport en commun
</td>
<td style="text-align:right;">
295 800
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Apied
</td>
<td style="text-align:left;">
À pied
</td>
<td style="text-align:right;">
69 330
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Velo
</td>
<td style="text-align:left;">
Bicyclette
</td>
<td style="text-align:right;">
30 615
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
AutreMoyen
</td>
<td style="text-align:left;">
Autre moyen
</td>
<td style="text-align:right;">
7 750
</td>
</tr>
<tr grouplength="5">
<td colspan="3" style="border-bottom: 1px solid;">
<strong>Modalités de la variable supplémentaire (durée du trajet)</strong>
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
T15min
</td>
<td style="text-align:left;">
Moins de 15 minutes
</td>
<td style="text-align:right;">
130 435
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
T1529min
</td>
<td style="text-align:left;">
15 à 29 minutes
</td>
<td style="text-align:right;">
287 500
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
T3044min
</td>
<td style="text-align:left;">
30 à 44 minutes
</td>
<td style="text-align:right;">
244 425
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
T4559min
</td>
<td style="text-align:left;">
45 à 59 minutes
</td>
<td style="text-align:right;">
107 065
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
T60plus
</td>
<td style="text-align:left;">
60 minutes et plus
</td>
<td style="text-align:right;">
88 050
</td>
</tr>
</tbody>
</table>
<div class="figure" style="text-align: center"><span id="fig:cartovarAFC"></span>
<img src="MethodesQuantitScSocialesBolR_files/figure-html/cartovarAFC-1.png" alt="Cartographie des modalités de la variable mode de transport utilisée pour l'AFC" width="100%" />
<p class="caption">
Figure 12.24: Cartographie des modalités de la variable mode de transport utilisée pour l’AFC
</p>
</div>
<div id="sect12321" class="section level4">
<h4><span class="header-section-number">12.3.2.1</span> Résultats de l’AFC pour les valeurs propres</h4>
<p>Avant de calculer l’AFC, il convient de vérifier s’il y a bien une dépendance entre les modalités des deux variables qualitatives. En effet, si les deux variables sont indépendantes, il n’est pas nécessaire de résumer le tableau de contingence avec une AFC. Pour ce faire, nous utilisons le test du khi-deux largement décrit à la section <a href="sect052.html#sect052">5.2</a>. Les résultats de ce test signalent qu’il existe des associations entre les modalités des deux variables (<span class="math inline">\(\chi\)</span> = 203 971, <em>p</em> &lt; 0,001, tableau <a href="sect123.html#tab:dataafckhi2">12.14</a>). Nous pouvons donc appliquer une AFC sur ce tableau de contingence.</p>
<table>
<caption>
<span id="tab:dataafckhi2">Tableau 12.14: </span>Résultats du test du khi-deux sur le tableau de contingence
</caption>
<thead>
<tr>
<th style="text-align:left;">
Mesure
</th>
<th style="text-align:right;">
Valeur
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Modalités <em>I</em> (secteurs de recensement)
</td>
<td style="text-align:right;">
521,00
</td>
</tr>
<tr>
<td style="text-align:left;">
Modalités <em>J</em> (variable mode de transport)
</td>
<td style="text-align:right;">
6,00
</td>
</tr>
<tr>
<td style="text-align:left;">
Somme des données brutes (<span class="math inline">\(n_{ij}\)</span>)
</td>
<td style="text-align:right;">
857 545,00
</td>
</tr>
<tr>
<td style="text-align:left;">
Khi-deux (<span class="math inline">\(\chi^2\)</span>)
</td>
<td style="text-align:right;">
207 129,27
</td>
</tr>
<tr>
<td style="text-align:left;">
Degrés de liberté, soit <span class="math inline">\((c-1)\times(l-1)\)</span>
</td>
<td style="text-align:right;">
2 600,00
</td>
</tr>
<tr>
<td style="text-align:left;">
Valeur de <em>p</em>
</td>
<td style="text-align:right;">
0,00
</td>
</tr>
<tr>
<td style="text-align:left;">
Coefficient Phi au carré (<span class="math inline">\(\phi^2=\chi^2 / n_{ij})\)</span>
</td>
<td style="text-align:right;">
0,24
</td>
</tr>
</tbody>
</table>
<p>Nous avons vu qu’en ACP normée (section <a href="sect122.html#sect12221">12.2.2.1</a>), la somme des valeurs propres est égale au nombre de variables puisqu’elles sont centrées réduites. Par contre, en AFC, cette somme est égale à l’inertie totale du tableau de contingence, c’est-à-dire à la valeur du khi-deux divisée par le nombre total des effectifs bruts (soit le coefficient phi au carré, <span class="math inline">\(\phi^2\)</span>) (section <a href="sect052.html#sect052">5.2</a>). Le tableau <a href="sect123.html#tab:dataafcValeurPropres">12.15</a> permet de vérifier que la somme des valeurs propres est bien égale au coefficient phi au carré :</p>
<p><span class="math display">\[\mbox{0,156}+\mbox{0,046}+\mbox{0,031}+\mbox{0,004}+\mbox{0,004} = \mbox{0,24}\]</span></p>
<span class="math display">\[\phi^2 = \chi^2 / n_{ij}=\mbox{203 971}/ \mbox{849 795} = \mbox{0,24}\]</span>
<table>
<caption>
<span id="tab:dataafcValeurPropres">Tableau 12.15: </span>Résultats de l’AFC pour les valeurs propres
</caption>
<thead>
<tr>
<th style="text-align:right;">
Axe factoriel
</th>
<th style="text-align:right;">
Valeur propre
</th>
<th style="text-align:right;">
Pourcentage
</th>
<th style="text-align:right;">
Pourc. cumulé
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0,156
</td>
<td style="text-align:right;">
64,590
</td>
<td style="text-align:right;">
64,590
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
0,046
</td>
<td style="text-align:right;">
19,250
</td>
<td style="text-align:right;">
83,840
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
0,031
</td>
<td style="text-align:right;">
12,995
</td>
<td style="text-align:right;">
96,835
</td>
</tr>
<tr>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
0,004
</td>
<td style="text-align:right;">
1,683
</td>
<td style="text-align:right;">
98,518
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
0,004
</td>
<td style="text-align:right;">
1,482
</td>
<td style="text-align:right;">
100,000
</td>
</tr>
</tbody>
</table>
<div style="page-break-after: always;"></div>
<p><strong>Combien d’axes d’une AFC faut-il retenir?</strong></p>
<ul>
<li><p><strong>Approche statistique</strong>. Mike Bendixen <span class="citation">(<a href="#ref-bendixen1995compositional" role="doc-biblioref">1995</a>)</span>, cité dans l’excellent site <a href="http://www.sthda.com/french/articles/38-methodes-des-composantes-principales-dans-r-guide-pratique/74-afc-analyse-factorielle-des-correspondances-avec-r-l-essentiel/#valeurs-propres-variances" target="_blank">STHDA</a>, propose deux critères pour sélectionner les premiers axes d’une AFC : <span class="math inline">\(c_1= 1 / (l-1) \times 100\)</span> et <span class="math inline">\(c_2= 1 / (c-1) \times 100\)</span> avec <em>l</em> et <em>c</em> étant respectivement les nombres de modalités en ligne et en colonne. Autrement dit, lorsque les données sont distribuées aléatoirement, la valeur propre en pourcentage devrait être égale à <span class="math inline">\(c_1\)</span> et celle de l’axe factoriel moyen à <span class="math inline">\(c_2\)</span>. Par conséquent, nous pourrions retenir uniquement les axes dont les valeurs propres en pourcentage excèdent : <span class="math inline">\(c_1 = \mbox{1}/(\mbox{521}-\mbox{1})\times \mbox{100}=\mbox{0,19 }%\)</span> et <span class="math inline">\(c_2=\mbox{1}/(\mbox{6}-\mbox{1})\times \mbox{100}=\mbox{20 }%\)</span>. En appliquant ces deux critères, seul le premier axe factoriel qui résume 65,6 % mérite d’être retenu.</p></li>
<li><p><strong>Approche empirique</strong> basée sur la lecture des pourcentages et des pourcentages cumulés. Nous retenons uniquement les deux premières composantes qui résument 85 % de la variance totale. Pour faciliter le choix du nombre d’axes avec cette approche empirique, il est fortement conseillé de construire un histogramme à partir des valeurs propres, soit brutes, soit en pourcentage, soit en pourcentage cumulé (figure <a href="sect123.html#fig:afcGraphVP">12.25</a>).</p></li>
</ul>
<div class="figure" style="text-align: center"><span id="fig:afcGraphVP"></span>
<img src="MethodesQuantitScSocialesBolR_files/figure-html/afcGraphVP-1.png" alt="Histogramme des valeurs propres de l'AFC" width="80%" />
<p class="caption">
Figure 12.25: Histogramme des valeurs propres de l’AFC
</p>
</div>
</div>
<div id="sect12322" class="section level4">
<h4><span class="header-section-number">12.3.2.2</span> Résultats de l’AFC pour les variables et les individus</h4>
<p>Comme pour l’ACP, nous retrouvons les trois mêmes mesures pour les variables et les individus : 1) les coordonnées factorielles, 2) les contributions et 3) les cosinus carrés.</p>
<div class="bloc_objectif">
<p><strong>Compréhension des axes factoriels de l’AFC : une étape essentielle, incontournable…</strong></p>
<p>Comme en ACP, l’analyse des trois mesures (coordonnées, contributions et cosinus carrés) pour les variables et les individus doit vous permettre de comprendre la signification des axes factoriels retenus de l’AFC. Cette étape d’interprétation est essentielle afin de qualifier les variables latentes (axes factoriels, variables synthétiques) produites par l’AFC.</p>
</div>
<ul>
<li><strong>Les coordonnées factorielles</strong> sont simplement les projections des points-lignes et des points-colonnes sur les axes de l’AFC. Tant pour les lignes que pour les colonnes, ces coordonnées bénéficient de deux propriétés intéressantes. Premièrement, pour chaque axe factoriel <em>k</em>, la somme du produit des marges des variables (<span class="math inline">\(f.j\)</span>, colonnes) ou des individus (<span class="math inline">\(fi.\)</span>, lignes) avec leurs coordonnées respectives (<span class="math inline">\(C^k_j\)</span> et <span class="math inline">\(C^k_i\)</span>) est égale à 0 (équation <a href="sect123.html#eq:CoordPropr1">(12.7)</a>). Deuxièmement, pour chaque axe factoriel <em>k</em>, la somme des produits entre les marges (en ligne et en colonne) et les coordonnées au carré (en ligne et en colonne) est égale à la valeur propre de l’axe (équation <a href="sect123.html#eq:CoordPropr2">(12.8)</a>).</li>
</ul>

<p><span class="math display" id="eq:CoordPropr1">\[\begin{equation}
\sum{f.j (C^k_j)}= 0 \text{ et} \sum{fi. (C^k_i)}= 0
\tag{12.7}
\end{equation}\]</span>
</p>

<p><span class="math display" id="eq:CoordPropr2">\[\begin{equation}
\sum{fi. (C^k_i)^2}= \mu_k \text{ et} \sum{f.j (C^k_j)^2}= \mu_k
\tag{12.8}
\end{equation}\]</span>
</p>
<p>En guise d’exemple, le tableau <a href="sect123.html#tab:dataafcCoordVars2">12.16</a> permet de vérifier les deux propriétés des coordonnées pour les variables. Les sommes de <span class="math inline">\({f.j (C^k_j)}\)</span> pour les axes 1 et 2 sont bien égales à 0; et les sommes de <span class="math inline">\({f.j (C^k_j)^2}\)</span> pour les axes 1 et 2 sont bien égales aux valeurs propres de ces deux axes, soit 0,156 et 0,046 (comparez ces valeurs avec celles reportées au tableau <a href="sect123.html#tab:dataafcValeurPropres">12.15</a> plus haut).</p>
<table>
<caption>
<span id="tab:dataafcCoordVars2">Tableau 12.16: </span>Vérification des deux propriétés des coordonnées factorielles pour les variables
</caption>
<thead>
<tr>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="2">
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Coord.
</div>
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
f.j x Coord.
</div>
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
f.j x Coord2
</div>
</th>
</tr>
<tr>
<th style="text-align:left;">
Modalité
</th>
<th style="text-align:right;">
f.j
</th>
<th style="text-align:right;">
1
</th>
<th style="text-align:right;">
2
</th>
<th style="text-align:right;">
1
</th>
<th style="text-align:right;">
2
</th>
<th style="text-align:right;">
1
</th>
<th style="text-align:right;">
2
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
VehCond
</td>
<td style="text-align:right;">
0,499
</td>
<td style="text-align:right;">
-0,329
</td>
<td style="text-align:right;">
0,077
</td>
<td style="text-align:right;">
-0,164
</td>
<td style="text-align:right;">
0,038
</td>
<td style="text-align:right;">
0,054
</td>
<td style="text-align:right;">
0,003
</td>
</tr>
<tr>
<td style="text-align:left;">
VehPass
</td>
<td style="text-align:right;">
0,031
</td>
<td style="text-align:right;">
-0,255
</td>
<td style="text-align:right;">
0,081
</td>
<td style="text-align:right;">
-0,008
</td>
<td style="text-align:right;">
0,003
</td>
<td style="text-align:right;">
0,002
</td>
<td style="text-align:right;">
0,000
</td>
</tr>
<tr>
<td style="text-align:left;">
TranspC
</td>
<td style="text-align:right;">
0,345
</td>
<td style="text-align:right;">
0,208
</td>
<td style="text-align:right;">
-0,229
</td>
<td style="text-align:right;">
0,072
</td>
<td style="text-align:right;">
-0,079
</td>
<td style="text-align:right;">
0,015
</td>
<td style="text-align:right;">
0,018
</td>
</tr>
<tr>
<td style="text-align:left;">
Apied
</td>
<td style="text-align:right;">
0,081
</td>
<td style="text-align:right;">
0,813
</td>
<td style="text-align:right;">
0,545
</td>
<td style="text-align:right;">
0,066
</td>
<td style="text-align:right;">
0,044
</td>
<td style="text-align:right;">
0,053
</td>
<td style="text-align:right;">
0,024
</td>
</tr>
<tr>
<td style="text-align:left;">
Velo
</td>
<td style="text-align:right;">
0,036
</td>
<td style="text-align:right;">
0,938
</td>
<td style="text-align:right;">
-0,187
</td>
<td style="text-align:right;">
0,033
</td>
<td style="text-align:right;">
-0,007
</td>
<td style="text-align:right;">
0,031
</td>
<td style="text-align:right;">
0,001
</td>
</tr>
<tr>
<td style="text-align:left;">
AutreMoyen
</td>
<td style="text-align:right;">
0,009
</td>
<td style="text-align:right;">
0,142
</td>
<td style="text-align:right;">
0,078
</td>
<td style="text-align:right;">
0,001
</td>
<td style="text-align:right;">
0,001
</td>
<td style="text-align:right;">
0,000
</td>
<td style="text-align:right;">
0,000
</td>
</tr>
<tr>
<td style="text-align:left;">
Somme
</td>
<td style="text-align:right;">
1,000
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
0,000
</td>
<td style="text-align:right;">
0,000
</td>
<td style="text-align:right;">
0,156
</td>
<td style="text-align:right;">
0,046
</td>
</tr>
</tbody>
</table>
<div class="bloc_attention">
<p>Contrairement à l’ACP, les coordonnées factorielles pour les variables en AFC ne sont pas les coefficients de corrélation de Pearson des variables sur les axes!</p>
</div>
<ul>
<li><strong>Les contributions</strong> des colonnes ou des lignes en AFC permettent des repérer celles qui contribuent le plus à la formation des axes factoriels (de manière analogue à l’ACP). Pour un axe donné, leur sommation est égale à 100 %. Elles s’obtiennent en multipliant la coordonnée au carré avec la marge et en divisant le tout par la valeur propre de l’axe (équations <a href="sect123.html#eq:CtrAFCVar">(12.9)</a> et <a href="sect123.html#eq:CtrAFCInd">(12.10)</a>).</li>
</ul>

<p><span class="math display" id="eq:CtrAFCVar">\[\begin{equation}
\mbox{Ctr}_j^k =\frac{f.j(C^k_j)^2}{\mu_{k}}\times 100
\tag{12.9}
\end{equation}\]</span>
</p>

<p><span class="math display" id="eq:CtrAFCInd">\[\begin{equation}
\mbox{Ctr}_i^k =\frac{fi.(C^k_i)^2}{\mu_{k}}\times 100
\tag{12.10}
\end{equation}\]</span>
</p>
<ul>
<li><strong>Les cosinus carrés</strong> (Cos<sup>2</sup>) (appelés aussi les qualités de représentation sur un axe) permettent de repérer le ou les axes qui concourent le plus à donner un sens aux colonnes (variables) et aux lignes (individus), de manière analogue à l’ACP. Pour une variable ou un individu, la sommation des Cos<sup>2</sup> pour tous les axes de l’AFC est aussi égale à 1.</li>
</ul>
<p><strong>Interprétation des résultats pour les colonnes (variables)</strong></p>
<p>Maintenant, analysons ces trois statistiques pour les variables pour les deux premiers axes de l’AFC (tableau <a href="sect123.html#tab:dataafcCoordVars">12.17</a> et figure <a href="sect123.html#fig:afc1erplanfactVars">12.26</a>).</p>
<p>Pour l’axe 1, résumant 65 % de la variance, trois modalités concourent à sa formation : <code>VehCond</code> (34,69 %), <code>Apied</code> (34,25 %) et <code>Velo</code> (20,13 %). À la lecture des coordonnées factorielles sur cet axe, les modes de transport relatifs aux véhicules motorisés (<code>VehCond</code> = -0,33 et <code>VehPass</code> = -0,25) s’opposent clairement aux modes actifs (<code>Apied</code> = 0,81 et <code>Velo</code> = 0,94), constat qu’il est possible de confirmer visuellement avec la figure <a href="sect123.html#fig:afc1erplanfactVars">12.26</a>. La modalité <code>VehCond</code> a d’ailleurs la plus forte valeur de Cos<sup>2</sup> sur cet axe (0,92), ce qui signale, sans l’ombre d’un doute, que l’axe 1 est celui qui donne le plus de sens à cette modalité.</p>
<p>Puisque l’axe 2 résume une partie beaucoup plus limitée de la variance du tableau (19,25 %), il n’est pas étonnant qu’un nombre plus limité de modalités concourent à sa formation : seules les contributions de la modalité <code>Apied</code> (51,68 %) et secondairement de <code>VehPass</code> (38,81 %) sont importantes. Leurs coordonnées factorielles s’opposent d’ailleurs sur cet axe (respectivement 0,81 et 0,21).</p>
<table>
<caption>
<span id="tab:dataafcCoordVars">Tableau 12.17: </span>Résultats de l’AFC pour les variables
</caption>
<thead>
<tr>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="1">
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Coordonnées
</div>
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Cosinus carrés
</div>
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Contributions (%)
</div>
</th>
</tr>
<tr>
<th style="text-align:left;">
Modalité
</th>
<th style="text-align:right;">
1
</th>
<th style="text-align:right;">
2
</th>
<th style="text-align:right;">
1
</th>
<th style="text-align:right;">
2
</th>
<th style="text-align:right;">
1
</th>
<th style="text-align:right;">
2
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
VehCond
</td>
<td style="text-align:right;">
-0,33
</td>
<td style="text-align:right;">
0,08
</td>
<td style="text-align:right;">
0,92
</td>
<td style="text-align:right;">
0,05
</td>
<td style="text-align:right;">
34,69
</td>
<td style="text-align:right;">
6,33
</td>
</tr>
<tr>
<td style="text-align:left;">
VehPass
</td>
<td style="text-align:right;">
-0,25
</td>
<td style="text-align:right;">
0,08
</td>
<td style="text-align:right;">
0,34
</td>
<td style="text-align:right;">
0,03
</td>
<td style="text-align:right;">
1,28
</td>
<td style="text-align:right;">
0,44
</td>
</tr>
<tr>
<td style="text-align:left;">
TranspC
</td>
<td style="text-align:right;">
0,21
</td>
<td style="text-align:right;">
-0,23
</td>
<td style="text-align:right;">
0,39
</td>
<td style="text-align:right;">
0,47
</td>
<td style="text-align:right;">
9,53
</td>
<td style="text-align:right;">
38,81
</td>
</tr>
<tr>
<td style="text-align:left;">
Apied
</td>
<td style="text-align:right;">
0,81
</td>
<td style="text-align:right;">
0,54
</td>
<td style="text-align:right;">
0,67
</td>
<td style="text-align:right;">
0,30
</td>
<td style="text-align:right;">
34,25
</td>
<td style="text-align:right;">
51,61
</td>
</tr>
<tr>
<td style="text-align:left;">
Velo
</td>
<td style="text-align:right;">
0,94
</td>
<td style="text-align:right;">
-0,19
</td>
<td style="text-align:right;">
0,56
</td>
<td style="text-align:right;">
0,02
</td>
<td style="text-align:right;">
20,13
</td>
<td style="text-align:right;">
2,69
</td>
</tr>
<tr>
<td style="text-align:left;">
AutreMoyen
</td>
<td style="text-align:right;">
0,14
</td>
<td style="text-align:right;">
0,08
</td>
<td style="text-align:right;">
0,05
</td>
<td style="text-align:right;">
0,01
</td>
<td style="text-align:right;">
0,12
</td>
<td style="text-align:right;">
0,12
</td>
</tr>
</tbody>
</table>
<div class="figure" style="text-align: center"><span id="fig:afc1erplanfactVars"></span>
<img src="MethodesQuantitScSocialesBolR_files/figure-html/afc1erplanfactVars-1.png" alt="Premier plan factoriel de l'AFC pour les variables" width="75%" />
<p class="caption">
Figure 12.26: Premier plan factoriel de l’AFC pour les variables
</p>
</div>
<p><strong>Interprétation des résultats pour les individus</strong></p>
<div class="bloc_notes">
<p><strong>Premier plan factoriel pour les variables et les individus</strong></p>
<p>Lorsque le jeu de données comprend à la fois peu de modalités en ligne et en colonne, il est judicieux de les représenter simultanément sur le premier plan factoriel (axes 1 et 2). Pour ce faire, vous pouvez utiliser la fonction <code>fviz_ca_biplot</code> du <em>package</em> <code>factoextra</code>.</p>
</div>
<p>Étant donné que notre jeu de données comprend 521 secteurs de recensement, nous proposons ici de cartographier les coordonnées factorielles des individus pour les deux premiers axes de l’AFC (figure <a href="sect123.html#fig:afc1erplanfactInds2">12.27</a>). Pour l’axe 1, les secteurs de recensement à l’est et l’ouest de l’île de Montréal présentent les coordonnées les plus fortement négatives (en rouge); dans ces zones, l’usage des véhicules motorisés pour des déplacements domicile-travail est certainement surreprésenté, comparativement aux modes actifs. À l’inverse, dans les secteurs de recensement du centre de l’île présentant de fortes valeurs positives (en rouge), le recours aux modes de transports actifs (marche et vélo) est bien plus important, toutes proportions gardées. Quant à la cartographie des coordonnées pour l’axe 2, elle permet surtout de repérer quelques secteurs de recensement autour du centre-ville (très fortes valeurs positives en vert foncé) où les déplacements domicile-travail à pied sont plus fréquents, toutes proportions gardées.</p>
<p>En résumé, suite à l’analyse des coordonnées factorielles des variables et des individus, nous pouvons conclure que le premier axe est certainement le plus intéressant puisqu’il permet d’opposer l’usage des modes de transports motorisés versus les modes de transports actifs pour les déplacements domicile-travail sur l’île de Montréal. Cette nouvelle variable synthétique (variable latente) pourrait ainsi être introduite dans des analyses subséquentes (par exemple, dans un modèle de régression). Cela démontre qu’au même titre que l’ACP, l’AFC est une méthode de réduction de données puisque nous sommes passés d’un tableau comprenant 512 secteurs de recensement et six modalités à un tableau comprenant une seule variable synthétique (axe 1).</p>
<div class="figure" style="text-align: center"><span id="fig:afc1erplanfactInds2"></span>
<img src="MethodesQuantitScSocialesBolR_files/figure-html/afc1erplanfactInds2-1.png" alt="Cartographie de coordonnées factorielles des individus pour l'AFC" width="85%" />
<p class="caption">
Figure 12.27: Cartographie de coordonnées factorielles des individus pour l’AFC
</p>
</div>
<div class="bloc_aller_loin">
<p><strong>Ajout de modalités supplémentaires dans une analyse des correspondances (AFC)</strong></p>
<p>Comme pour l’ACP, il est possible d’ajouter des variables et des individus supplémentaires une fois l’AFC calculée. En guise d’illustration, nous avons ajouté à l’AFC précédemment analysée des modalités relatives à la durée des temps de déplacements : moins de 15 minutes, 15 à 29, 30 à 44, 45 à 59, 60 minutes et plus. Sans surprise, sur le premier plan factoriel à la figure <a href="sect123.html#fig:afc1erplanfactInds2">12.27</a>, cette dernière modalité, représentant les trajets les plus longs, est la plus proche des modalités relatives à l’usage des véhicules motorisés (<code>VehCond</code> et <code>VehPass</code>).</p>
<div class="figure" style="text-align: center"><span id="fig:afcAjoutModalites"></span>
<img src="MethodesQuantitScSocialesBolR_files/figure-html/afcAjoutModalites-1.png" alt="Ajout de modalités supplémentaires sur le premier plan factoriel de l'AFC" width="75%" />
<p class="caption">
Figure 12.28: Ajout de modalités supplémentaires sur le premier plan factoriel de l’AFC
</p>
</div>
</div>
</div>
</div>
<div id="sect1233" class="section level3">
<h3><span class="header-section-number">12.3.3</span> Mise en œuvre dans R</h3>
<div id="sect12331" class="section level4">
<h4><span class="header-section-number">12.3.3.1</span> Calcul d’une AFC avec <code>FactoMineR</code></h4>
<p>Plusieurs <em>packages</em> permettent de calculer une AFC dans R, notamment <code>ca</code> (fonction <code>ca</code>), <code>MASS</code> (fonction <code>corresp</code>), <code>ade4</code> (fonction <code>dudi.coa</code>) et <code>FactoMineR</code> (fonction <code>CA</code>). De nouveau, nous utilisons <code>FactoMineR</code> couplé au <em>package</em> <code>factoextra</code> pour réaliser rapidement des graphiques avec les résultats pour les variables et les coordonnées.</p>
<p>Pour calculer l’AFC, il suffit d’utiliser la fonction <code>CA</code> de <code>FactoMineR</code>, puis la fonction <code>summary(res.afc)</code>, qui renvoie les résultats de l’AFC pour :</p>
<ul>
<li>Les valeurs propres (section <code>Eigenvalues</code>) pour les axes factoriels (<code>Dim.1</code> à <code>Dim.n</code>) avec leur variance expliquée brute (<code>Variance</code>), en pourcentage (<code>% of var.</code>) et en pourcentage cumulé (<code>Cumulative % of var.</code>).</li>
<li>Les dix premières observations (section <code>Rows</code>) avec les coordonnées factorielles (<code>Dim.1</code> à <code>Dim.n</code>), les contributions (<code>ctr</code>) et les cosinus carrés (<code>cos2</code>). Pour accéder aux résultats pour toutes les observations, utilisez les fonctions <code>res.afc$row</code> ou encore <code>res.afc$row$coord</code> (uniquement les coordonnées factorielles), <code>res.afc$row$contrib</code> (uniquement les contributions) et <code>res.afc$row$cos2</code> (uniquement les cosinus carrés).</li>
<li>Les colonnes (section <code>Columns</code>) avec les coordonnées factorielles (D<code>im.1</code> à <code>Dim.n</code>), les contributions (<code>ctr</code>) et les cosinus carrés (<code>cos2</code>).</li>
</ul>
<div class="sourceCode" id="cb1097"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1097-1"><a href="sect123.html#cb1097-1"></a><span class="co"># Chargement des packages</span></span>
<span id="cb1097-2"><a href="sect123.html#cb1097-2"></a><span class="kw">library</span>(FactoMineR)</span>
<span id="cb1097-3"><a href="sect123.html#cb1097-3"></a><span class="kw">library</span>(factoextra)</span>
<span id="cb1097-4"><a href="sect123.html#cb1097-4"></a><span class="co"># Chargement des données</span></span>
<span id="cb1097-5"><a href="sect123.html#cb1097-5"></a><span class="kw">load</span>(<span class="st">&quot;data/analysesfactorielles/DonneesAFC.Rdata&quot;</span>)</span>
<span id="cb1097-6"><a href="sect123.html#cb1097-6"></a><span class="co"># Avant de calculer l&#39;AFC, il convient de vérifier si les deux variables</span></span>
<span id="cb1097-7"><a href="sect123.html#cb1097-7"></a><span class="co"># qualitatives sont dépendantes avec le test du khi-deux</span></span>
<span id="cb1097-8"><a href="sect123.html#cb1097-8"></a>khideux &lt;-<span class="st"> </span><span class="kw">chisq.test</span>(dfDonneesAFC[,<span class="dv">1</span><span class="op">:</span><span class="dv">6</span>])</span>
<span id="cb1097-9"><a href="sect123.html#cb1097-9"></a><span class="kw">print</span>(khideux)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  dfDonneesAFC[, 1:6]
## X-squared = 207129, df = 2600, p-value &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb1099"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1099-1"><a href="sect123.html#cb1099-1"></a><span class="cf">if</span>(khideux<span class="op">$</span>p.value <span class="op">&lt;=</span><span class="fl">0.05</span>){</span>
<span id="cb1099-2"><a href="sect123.html#cb1099-2"></a>  <span class="kw">cat</span>(<span class="st">&quot;La valeur de p &lt; 0,05. Les variables sont dépendantes. Calculer l&#39;AFC.&quot;</span>)</span>
<span id="cb1099-3"><a href="sect123.html#cb1099-3"></a>}<span class="cf">else</span> {</span>
<span id="cb1099-4"><a href="sect123.html#cb1099-4"></a>    <span class="kw">cat</span>(<span class="st">&quot;La valeur de p &gt; 0,05. Les variables sont indépendantes. Inutile de calculer l&#39;AFC&quot;</span>)</span>
<span id="cb1099-5"><a href="sect123.html#cb1099-5"></a>}</span></code></pre></div>
<pre><code>## La valeur de p &lt; 0,05. Les variables sont dépendantes. Calculer l&#39;AFC.</code></pre>
<div class="sourceCode" id="cb1101"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1101-1"><a href="sect123.html#cb1101-1"></a><span class="co"># Calcul de l&#39;analyse des correspondances sur les six premières variables</span></span>
<span id="cb1101-2"><a href="sect123.html#cb1101-2"></a>res.afc &lt;-<span class="st"> </span><span class="kw">CA</span>(dfDonneesAFC[,<span class="dv">1</span><span class="op">:</span><span class="dv">6</span>], <span class="dt">graph=</span>F)</span>
<span id="cb1101-3"><a href="sect123.html#cb1101-3"></a><span class="co"># Affichage des résultats de la fonction CA</span></span>
<span id="cb1101-4"><a href="sect123.html#cb1101-4"></a><span class="kw">print</span>(res.afc)</span></code></pre></div>
<pre><code>## **Results of the Correspondence Analysis (CA)**
## The row variable has  521  categories; the column variable has 6 categories
## The chi square of independence between the two variables is equal to 207129.3 (p-value =  0 ).
## *The results are available in the following objects:
## 
##    name              description                   
## 1  &quot;$eig&quot;            &quot;eigenvalues&quot;                 
## 2  &quot;$col&quot;            &quot;results for the columns&quot;     
## 3  &quot;$col$coord&quot;      &quot;coord. for the columns&quot;      
## 4  &quot;$col$cos2&quot;       &quot;cos2 for the columns&quot;        
## 5  &quot;$col$contrib&quot;    &quot;contributions of the columns&quot;
## 6  &quot;$row&quot;            &quot;results for the rows&quot;        
## 7  &quot;$row$coord&quot;      &quot;coord. for the rows&quot;         
## 8  &quot;$row$cos2&quot;       &quot;cos2 for the rows&quot;           
## 9  &quot;$row$contrib&quot;    &quot;contributions of the rows&quot;   
## 10 &quot;$call&quot;           &quot;summary called parameters&quot;   
## 11 &quot;$call$marge.col&quot; &quot;weights of the columns&quot;      
## 12 &quot;$call$marge.row&quot; &quot;weights of the rows&quot;</code></pre>
<div class="sourceCode" id="cb1103"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1103-1"><a href="sect123.html#cb1103-1"></a><span class="co"># Visualisation des marges en colonne</span></span>
<span id="cb1103-2"><a href="sect123.html#cb1103-2"></a><span class="kw">round</span>(res.afc<span class="op">$</span>call<span class="op">$</span>marge.col,<span class="dv">4</span>)</span></code></pre></div>
<pre><code>##    VehCond    VehPass    TranspC      Apied       Velo AutreMoyen 
##     0.4986     0.0309     0.3449     0.0808     0.0357     0.0090</code></pre>
<div class="sourceCode" id="cb1105"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1105-1"><a href="sect123.html#cb1105-1"></a><span class="co"># Visualisation des marges en ligne. Étant donnée que nous avons 521 individus, </span></span>
<span id="cb1105-2"><a href="sect123.html#cb1105-2"></a><span class="co"># la ligne ci-dessous est en commentaire</span></span>
<span id="cb1105-3"><a href="sect123.html#cb1105-3"></a><span class="co"># round(res.afc$call$marge.row,4)</span></span>
<span id="cb1105-4"><a href="sect123.html#cb1105-4"></a></span>
<span id="cb1105-5"><a href="sect123.html#cb1105-5"></a><span class="co"># Sommaire des résultats de l&#39;AFC</span></span>
<span id="cb1105-6"><a href="sect123.html#cb1105-6"></a><span class="co"># Remarquez que la première ligne de ce sommaire est le résultat du khi-deux</span></span>
<span id="cb1105-7"><a href="sect123.html#cb1105-7"></a><span class="kw">summary</span>(res.afc)</span></code></pre></div>
<pre><code>## 
## Call:
## CA(X = dfDonneesAFC[, 1:6], graph = F) 
## 
## The chi square of independence between the two variables is equal to 207129.3 (p-value =  0 ).
## 
## Eigenvalues
##                        Dim.1   Dim.2   Dim.3   Dim.4   Dim.5
## Variance               0.156   0.046   0.031   0.004   0.004
## % of var.             64.590  19.250  12.995   1.683   1.482
## Cumulative % of var.  64.590  83.840  96.835  98.518 100.000
## 
## Rows (the 10 first)
##              Iner*1000    Dim.1    ctr   cos2    Dim.2    ctr   cos2    Dim.3
## 1          |     0.155 | -0.304  0.095  0.961 | -0.023  0.002  0.006 |  0.048
## 2          |     0.123 | -0.232  0.067  0.850 |  0.028  0.003  0.012 | -0.021
## 3          |     0.268 | -0.246  0.127  0.737 | -0.002  0.000  0.000 | -0.046
## 4          |     0.102 | -0.168  0.034  0.513 | -0.111  0.049  0.222 | -0.117
## 5          |     0.118 | -0.251  0.067  0.883 |  0.004  0.000  0.000 | -0.007
## 6          |     0.120 | -0.130  0.024  0.313 | -0.103  0.051  0.196 | -0.144
## 7          |     0.124 | -0.029  0.002  0.022 | -0.158  0.167  0.626 | -0.079
## 8          |     0.073 | -0.157  0.028  0.598 | -0.090  0.031  0.195 | -0.006
## 9          |     0.014 | -0.060  0.005  0.506 | -0.033  0.005  0.150 | -0.018
## 10         |     0.040 |  0.004  0.000  0.000 | -0.204  0.073  0.838 |  0.053
##               ctr   cos2  
## 1           0.012  0.024 |
## 2           0.003  0.007 |
## 3           0.022  0.026 |
## 4           0.080  0.246 |
## 5           0.000  0.001 |
## 6           0.146  0.380 |
## 7           0.061  0.155 |
## 8           0.000  0.001 |
## 9           0.002  0.048 |
## 10          0.007  0.056 |
## 
## Columns
##              Iner*1000    Dim.1    ctr   cos2    Dim.2    ctr   cos2    Dim.3
## VehCond    |    58.559 | -0.329 34.687  0.924 |  0.077  6.331  0.050 |  0.051
## VehPass    |     5.923 | -0.255  1.283  0.338 |  0.081  0.440  0.035 |  0.001
## TranspC    |    38.261 |  0.208  9.534  0.389 | -0.229 38.812  0.472 | -0.124
## Apied      |    79.193 |  0.813 34.252  0.675 |  0.545 51.610  0.303 | -0.147
## Velo       |    55.633 |  0.938 20.126  0.564 | -0.187  2.688  0.022 |  0.802
## AutreMoyen |     3.969 |  0.142  0.117  0.046 |  0.078  0.119  0.014 |  0.070
##               ctr   cos2  
## VehCond     4.141  0.022 |
## VehPass     0.000  0.000 |
## TranspC    16.995  0.139 |
## Apied       5.543  0.022 |
## Velo       73.180  0.413 |
## AutreMoyen  0.140  0.011 |</code></pre>
</div>
<div id="sect12332" class="section level4">
<h4><span class="header-section-number">12.3.3.2</span> Exploration graphique des résultats de l’AFC avec <code>factoextra</code></h4>
<p>Comme pour l’ACP, <code>factoextra</code> dispose de plusieurs fonctions très intéressantes pour construire rapidement des graphiques avec les résultats de l’AFC. Premièrement, la syntaxe ci-dessous (avec la fonction <code>fviz_screeplot</code>) renvoie deux graphiques pour analyser les résultats des valeurs propres de l’AFC (figure <a href="sect123.html#fig:factoextraAFC1">12.29</a>).</p>
<div class="sourceCode" id="cb1107"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1107-1"><a href="sect123.html#cb1107-1"></a><span class="kw">library</span>(factoextra)</span>
<span id="cb1107-2"><a href="sect123.html#cb1107-2"></a><span class="kw">library</span>(ggplot2)</span>
<span id="cb1107-3"><a href="sect123.html#cb1107-3"></a><span class="kw">library</span>(ggpubr)</span>
<span id="cb1107-4"><a href="sect123.html#cb1107-4"></a></span>
<span id="cb1107-5"><a href="sect123.html#cb1107-5"></a><span class="co"># Nombre de modalités en ligne et en colonne</span></span>
<span id="cb1107-6"><a href="sect123.html#cb1107-6"></a>ModalitesLig &lt;-<span class="st"> </span><span class="kw">nrow</span>(dfDonneesAFC)</span>
<span id="cb1107-7"><a href="sect123.html#cb1107-7"></a>ModalitesCol &lt;-<span class="st"> </span><span class="kw">ncol</span>(dfDonneesAFC[,<span class="dv">1</span><span class="op">:</span><span class="dv">6</span>])</span>
<span id="cb1107-8"><a href="sect123.html#cb1107-8"></a><span class="co"># Critère statistique du profil moyen</span></span>
<span id="cb1107-9"><a href="sect123.html#cb1107-9"></a>critere2 &lt;-<span class="st"> </span><span class="kw">round</span>(<span class="dv">1</span><span class="op">/</span>(ModalitesCol<span class="dv">-1</span>)<span class="op">*</span><span class="dv">100</span>,<span class="dv">2</span>)</span>
<span id="cb1107-10"><a href="sect123.html#cb1107-10"></a>texte &lt;-<span class="st"> </span><span class="kw">paste0</span>(<span class="st">&quot;Critère pour le profil moyen : &quot;</span>, <span class="kw">as.character</span>(critere2), <span class="st">&quot; %&quot;</span>)</span>
<span id="cb1107-11"><a href="sect123.html#cb1107-11"></a><span class="co"># Graphique avec les valeurs propres</span></span>
<span id="cb1107-12"><a href="sect123.html#cb1107-12"></a>G1 &lt;-<span class="st"> </span><span class="kw">fviz_screeplot</span>(res.afc, <span class="dt">choice=</span><span class="st">&quot;eigenvalue&quot;</span>,</span>
<span id="cb1107-13"><a href="sect123.html#cb1107-13"></a>               <span class="dt">ylab=</span><span class="st">&quot;Valeurs propres&quot;</span>,</span>
<span id="cb1107-14"><a href="sect123.html#cb1107-14"></a>               <span class="dt">xlab=</span><span class="st">&quot;Axes factoriels&quot;</span>,</span>
<span id="cb1107-15"><a href="sect123.html#cb1107-15"></a>               <span class="dt">main=</span><span class="st">&quot;Valeurs propres&quot;</span>)</span>
<span id="cb1107-16"><a href="sect123.html#cb1107-16"></a>G2 &lt;-<span class="st"> </span><span class="kw">fviz_screeplot</span>(res.afc, <span class="dt">choice=</span><span class="st">&quot;variance&quot;</span>, <span class="dt">addlabels =</span> <span class="ot">TRUE</span>, <span class="dt">ylim =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">70</span>),</span>
<span id="cb1107-17"><a href="sect123.html#cb1107-17"></a>                     <span class="dt">ylab=</span><span class="st">&quot;Variance expliquée (%)&quot;</span>,</span>
<span id="cb1107-18"><a href="sect123.html#cb1107-18"></a>                     <span class="dt">xlab=</span><span class="st">&quot;Axes factoriels&quot;</span>,</span>
<span id="cb1107-19"><a href="sect123.html#cb1107-19"></a>                     <span class="dt">main=</span><span class="st">&quot;Valeurs propres (%)&quot;</span>)<span class="op">+</span></span>
<span id="cb1107-20"><a href="sect123.html#cb1107-20"></a><span class="st">  </span><span class="kw">geom_hline</span>(<span class="dt">yintercept =</span> c2, <span class="dt">linetype =</span> <span class="dv">1</span>, <span class="dt">color =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">size=</span><span class="dv">1</span>)<span class="op">+</span></span>
<span id="cb1107-21"><a href="sect123.html#cb1107-21"></a><span class="st">  </span><span class="kw">annotate</span>(<span class="dt">geom=</span><span class="st">&quot;text&quot;</span>, <span class="dt">x =</span> ModalitesCol<span class="fl">-.5</span>,</span>
<span id="cb1107-22"><a href="sect123.html#cb1107-22"></a>          <span class="dt">y=</span> critere2<span class="op">+</span><span class="dv">3</span>, <span class="dt">label=</span>texte, </span>
<span id="cb1107-23"><a href="sect123.html#cb1107-23"></a>          <span class="dt">color=</span><span class="st">&quot;red&quot;</span>, <span class="dt">hjust =</span> <span class="dv">1</span>, <span class="dt">size =</span> <span class="dv">4</span>)</span>
<span id="cb1107-24"><a href="sect123.html#cb1107-24"></a><span class="kw">ggarrange</span>(G1, G2)</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:factoextraAFC1"></span>
<img src="MethodesQuantitScSocialesBolR_files/figure-html/factoextraAFC1-1.png" alt="Graphiques pour les valeurs propres de l'AFC avec factoextra" width="65%" />
<p class="caption">
Figure 12.29: Graphiques pour les valeurs propres de l’AFC avec factoextra
</p>
</div>
<p>Avec les fonctions <code>fviz_contrib</code> et <code>fviz_cos2</code>, il est très facile de réaliser des histogrammes pour les contributions et les cosinus carrés pour les variables (colonnes) ou les individus (lignes), et ce, avec le paramètre <code>choice = c("row", "col")</code> (figure <a href="sect123.html#fig:acp1erplanfactVars2a">12.30</a>).</p>
<div class="sourceCode" id="cb1108"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1108-1"><a href="sect123.html#cb1108-1"></a><span class="kw">library</span>(factoextra)</span>
<span id="cb1108-2"><a href="sect123.html#cb1108-2"></a><span class="kw">library</span>(ggplot2)</span>
<span id="cb1108-3"><a href="sect123.html#cb1108-3"></a><span class="kw">library</span>(ggpubr)</span>
<span id="cb1108-4"><a href="sect123.html#cb1108-4"></a>VP1pct &lt;-<span class="st"> </span><span class="kw">round</span>(res.afc<span class="op">$</span>eig[<span class="dv">1</span>,<span class="dv">2</span>],<span class="dv">2</span>)</span>
<span id="cb1108-5"><a href="sect123.html#cb1108-5"></a>VP2pct &lt;-<span class="st"> </span><span class="kw">round</span>(res.afc<span class="op">$</span>eig[<span class="dv">2</span>,<span class="dv">2</span>],<span class="dv">2</span>)</span>
<span id="cb1108-6"><a href="sect123.html#cb1108-6"></a>G1 &lt;-<span class="st"> </span><span class="kw">fviz_contrib</span> (res.afc, <span class="dt">choice =</span> <span class="st">&quot;col&quot;</span>, <span class="dt">axes =</span> <span class="dv">1</span>, <span class="dt">title=</span><span class="st">&quot;Axe 1&quot;</span>)</span>
<span id="cb1108-7"><a href="sect123.html#cb1108-7"></a>G2 &lt;-<span class="st"> </span><span class="kw">fviz_contrib</span> (res.afc, <span class="dt">choice =</span> <span class="st">&quot;col&quot;</span>, <span class="dt">axes =</span> <span class="dv">2</span>, <span class="dt">title=</span><span class="st">&quot;Axe 2&quot;</span>)</span>
<span id="cb1108-8"><a href="sect123.html#cb1108-8"></a><span class="kw">ggarrange</span>(G1, G2, <span class="dt">ncol =</span> <span class="dv">2</span>, <span class="dt">nrow =</span> <span class="dv">1</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:acp1erplanfactVars2a"></span>
<img src="MethodesQuantitScSocialesBolR_files/figure-html/acp1erplanfactVars2a-1.png" alt="Contributions des variables avec factoextra" width="65%" />
<p class="caption">
Figure 12.30: Contributions des variables avec factoextra
</p>
</div>
<p>Quant aux fonctions <code>fviz_ca_col</code> et <code>fviz_ca_row</code>, elles permettent rapidement de construire le premier plan factoriel pour les colonnes (variables) et les lignes (individus) (figure <a href="sect123.html#fig:afc1erplanfactVars2b">12.31</a>). Aussi, la fonction <code>fviz_ca_biplot</code> permet de construire un plan factoriel, mais avec les lignes et les colonnes simultanément.</p>
<div class="sourceCode" id="cb1109"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1109-1"><a href="sect123.html#cb1109-1"></a>G3 &lt;-<span class="st"> </span><span class="kw">fviz_ca_col</span>(res.afc,</span>
<span id="cb1109-2"><a href="sect123.html#cb1109-2"></a>            <span class="dt">repel =</span> <span class="ot">TRUE</span>,</span>
<span id="cb1109-3"><a href="sect123.html#cb1109-3"></a>            <span class="dt">geom=</span> <span class="kw">c</span>(<span class="st">&quot;text&quot;</span>,<span class="st">&quot;point&quot;</span>),</span>
<span id="cb1109-4"><a href="sect123.html#cb1109-4"></a>            <span class="dt">col.col =</span> <span class="st">&quot;steelblue&quot;</span>,</span>
<span id="cb1109-5"><a href="sect123.html#cb1109-5"></a>            <span class="dt">title =</span> <span class="st">&quot;Mode de transport&quot;</span>,</span>
<span id="cb1109-6"><a href="sect123.html#cb1109-6"></a>            <span class="dt">xlab=</span><span class="kw">paste0</span>(<span class="st">&quot;Axe 1 (&quot;</span>, VP1pct, <span class="st">&quot; %)&quot;</span>),</span>
<span id="cb1109-7"><a href="sect123.html#cb1109-7"></a>            <span class="dt">ylab=</span><span class="kw">paste0</span>(<span class="st">&quot;Axe 2 (&quot;</span>, VP2pct, <span class="st">&quot; %)&quot;</span>))</span>
<span id="cb1109-8"><a href="sect123.html#cb1109-8"></a>G4 &lt;-<span class="st"> </span><span class="kw">fviz_ca_row</span>(res.afc,</span>
<span id="cb1109-9"><a href="sect123.html#cb1109-9"></a>            <span class="dt">repel =</span> <span class="ot">TRUE</span>,</span>
<span id="cb1109-10"><a href="sect123.html#cb1109-10"></a>            <span class="dt">geom=</span> <span class="kw">c</span>(<span class="st">&quot;point&quot;</span>),</span>
<span id="cb1109-11"><a href="sect123.html#cb1109-11"></a>            <span class="dt">col.row =</span> <span class="st">&quot;steelblue&quot;</span>,</span>
<span id="cb1109-12"><a href="sect123.html#cb1109-12"></a>            <span class="dt">title =</span> <span class="st">&quot;Secteurs de recensement&quot;</span>,</span>
<span id="cb1109-13"><a href="sect123.html#cb1109-13"></a>            <span class="dt">xlab=</span><span class="kw">paste0</span>(<span class="st">&quot;Axe 1 (&quot;</span>, VP1pct, <span class="st">&quot; %)&quot;</span>),</span>
<span id="cb1109-14"><a href="sect123.html#cb1109-14"></a>            <span class="dt">ylab=</span><span class="kw">paste0</span>(<span class="st">&quot;Axe 2 (&quot;</span>, VP2pct, <span class="st">&quot; %)&quot;</span>))</span>
<span id="cb1109-15"><a href="sect123.html#cb1109-15"></a><span class="kw">ggarrange</span>(G3, G4, <span class="dt">ncol =</span> <span class="dv">2</span>, <span class="dt">nrow =</span> <span class="dv">1</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:afc1erplanfactVars2b"></span>
<img src="MethodesQuantitScSocialesBolR_files/figure-html/afc1erplanfactVars2b-1.png" alt="Premier plan factoriel de l'AFC pour les variables et les individus avec factoextra" width="65%" />
<p class="caption">
Figure 12.31: Premier plan factoriel de l’AFC pour les variables et les individus avec factoextra
</p>
</div>
<p>La syntaxe ci-dessous permet d’ajouter des modalités supplémentaires dans l’AFC et de constuire le graphique du premier plan factoriel (figure <a href="sect123.html#fig:afcAjoutModalites2">12.32</a>).</p>
<div class="sourceCode" id="cb1110"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1110-1"><a href="sect123.html#cb1110-1"></a><span class="co"># Les colonnes 7 à 11 sont mises comme des variables supplémentaires dans l&#39;AFC</span></span>
<span id="cb1110-2"><a href="sect123.html#cb1110-2"></a>res.afc2 &lt;-<span class="st"> </span><span class="kw">CA</span>(dfDonneesAFC, <span class="dt">col.sup =</span> <span class="dv">7</span><span class="op">:</span><span class="dv">11</span>, <span class="dt">graph =</span> <span class="ot">FALSE</span>)</span>
<span id="cb1110-3"><a href="sect123.html#cb1110-3"></a>VP1pct &lt;-<span class="st"> </span><span class="kw">round</span>(res.afc2<span class="op">$</span>eig[<span class="dv">1</span>,<span class="dv">2</span>],<span class="dv">2</span>)</span>
<span id="cb1110-4"><a href="sect123.html#cb1110-4"></a>VP2pct &lt;-<span class="st"> </span><span class="kw">round</span>(res.afc2<span class="op">$</span>eig[<span class="dv">2</span>,<span class="dv">2</span>],<span class="dv">2</span>)</span>
<span id="cb1110-5"><a href="sect123.html#cb1110-5"></a><span class="kw">fviz_ca_col</span>(res.afc2,</span>
<span id="cb1110-6"><a href="sect123.html#cb1110-6"></a>            <span class="dt">repel =</span> <span class="ot">TRUE</span>,</span>
<span id="cb1110-7"><a href="sect123.html#cb1110-7"></a>            <span class="dt">geom=</span> <span class="kw">c</span>(<span class="st">&quot;text&quot;</span>,<span class="st">&quot;point&quot;</span>),</span>
<span id="cb1110-8"><a href="sect123.html#cb1110-8"></a>            <span class="dt">col.col =</span> <span class="st">&quot;steelblue&quot;</span>,</span>
<span id="cb1110-9"><a href="sect123.html#cb1110-9"></a>            <span class="dt">title =</span> <span class="st">&quot;&quot;</span>,</span>
<span id="cb1110-10"><a href="sect123.html#cb1110-10"></a>            <span class="dt">xlab=</span><span class="kw">paste0</span>(<span class="st">&quot;Axe 1 (&quot;</span>, VP1pct, <span class="st">&quot; %)&quot;</span>),</span>
<span id="cb1110-11"><a href="sect123.html#cb1110-11"></a>            <span class="dt">ylab=</span><span class="kw">paste0</span>(<span class="st">&quot;Axe 2 (&quot;</span>, VP2pct, <span class="st">&quot; %)&quot;</span>))</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:afcAjoutModalites2"></span>
<img src="MethodesQuantitScSocialesBolR_files/figure-html/afcAjoutModalites2-1.png" alt="Ajout de modalités supplémentaires sur le premier plan factoriel l'AFC avec factoextra" width="65%" />
<p class="caption">
Figure 12.32: Ajout de modalités supplémentaires sur le premier plan factoriel l’AFC avec factoextra
</p>
</div>
<p>Finalement, la syntaxe ci-dessous permet de cartographier les coordonnées factorielles des individus de l’AFC avec le <em>package</em> <code>tmap</code> (figure <a href="sect123.html#fig:afc1erplanfactInds2B">12.33</a>).</p>
<div class="sourceCode" id="cb1111"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1111-1"><a href="sect123.html#cb1111-1"></a><span class="kw">library</span>(tmap)</span>
<span id="cb1111-2"><a href="sect123.html#cb1111-2"></a><span class="kw">library</span>(stringr)</span>
<span id="cb1111-3"><a href="sect123.html#cb1111-3"></a>dfAFCInd &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">Coord =</span> res.afc<span class="op">$</span>row<span class="op">$</span>coord, </span>
<span id="cb1111-4"><a href="sect123.html#cb1111-4"></a>                       <span class="dt">Cos2 =</span> res.afc<span class="op">$</span>row<span class="op">$</span>cos2, </span>
<span id="cb1111-5"><a href="sect123.html#cb1111-5"></a>                       <span class="dt">Ctr =</span> res.afc<span class="op">$</span>row<span class="op">$</span>contrib)</span>
<span id="cb1111-6"><a href="sect123.html#cb1111-6"></a><span class="kw">names</span>(dfAFCInd) &lt;-<span class="st"> </span><span class="kw">str_replace</span>(<span class="kw">names</span>(dfAFCInd), <span class="st">&quot;.Dim.&quot;</span>, <span class="st">&quot;Comp&quot;</span>)</span>
<span id="cb1111-7"><a href="sect123.html#cb1111-7"></a>CartoAFC &lt;-<span class="st"> </span><span class="kw">cbind</span>(sfDonneesAFC, dfAFCInd)</span>
<span id="cb1111-8"><a href="sect123.html#cb1111-8"></a>VP1pct &lt;-<span class="st"> </span><span class="kw">tofr</span>(<span class="kw">round</span>(res.afc<span class="op">$</span>eig[<span class="dv">1</span>,<span class="dv">2</span>],<span class="dv">2</span>))</span>
<span id="cb1111-9"><a href="sect123.html#cb1111-9"></a>VP2pct &lt;-<span class="st"> </span><span class="kw">tofr</span>(<span class="kw">round</span>(res.afc<span class="op">$</span>eig[<span class="dv">2</span>,<span class="dv">2</span>],<span class="dv">2</span>))</span>
<span id="cb1111-10"><a href="sect123.html#cb1111-10"></a>Carte1 &lt;-<span class="st"> </span><span class="kw">tm_shape</span>(CartoAFC) <span class="op">+</span></span>
<span id="cb1111-11"><a href="sect123.html#cb1111-11"></a><span class="st">  </span><span class="kw">tm_fill</span>(<span class="dt">col =</span> <span class="st">&quot;CoordComp1&quot;</span>, <span class="dt">style =</span> <span class="st">&quot;cont&quot;</span>, <span class="dt">midpoint =</span> <span class="dv">0</span>, <span class="dt">title =</span> <span class="st">&#39;Coordonnées&#39;</span>)<span class="op">+</span></span>
<span id="cb1111-12"><a href="sect123.html#cb1111-12"></a><span class="st">  </span><span class="kw">tm_layout</span>(<span class="dt">title =</span> <span class="kw">paste0</span>(<span class="st">&quot;Axe 1 (&quot;</span>, VP1pct,<span class="st">&quot;%)&quot;</span>), <span class="dt">attr.outside =</span> <span class="ot">TRUE</span>, <span class="dt">frame =</span> <span class="ot">FALSE</span>)</span>
<span id="cb1111-13"><a href="sect123.html#cb1111-13"></a>Carte2 &lt;-<span class="st"> </span><span class="kw">tm_shape</span>(CartoAFC) <span class="op">+</span></span>
<span id="cb1111-14"><a href="sect123.html#cb1111-14"></a><span class="st">  </span><span class="kw">tm_fill</span>(<span class="dt">col =</span> <span class="st">&quot;CoordComp2&quot;</span>, <span class="dt">style =</span> <span class="st">&quot;cont&quot;</span>, <span class="dt">midpoint =</span> <span class="dv">0</span>, <span class="dt">title =</span> <span class="st">&#39;Coordonnées&#39;</span>)<span class="op">+</span></span>
<span id="cb1111-15"><a href="sect123.html#cb1111-15"></a><span class="st">  </span><span class="kw">tm_layout</span>(<span class="dt">title =</span> <span class="kw">paste0</span>(<span class="st">&quot;Axe 2 (&quot;</span>, VP2pct,<span class="st">&quot;%)&quot;</span>), <span class="dt">attr.outside =</span> <span class="ot">TRUE</span>, <span class="dt">frame =</span> <span class="ot">FALSE</span>)</span>
<span id="cb1111-16"><a href="sect123.html#cb1111-16"></a><span class="kw">tmap_arrange</span>(Carte1, Carte2, <span class="dt">nrow =</span> <span class="dv">1</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:afc1erplanfactInds2B"></span>
<img src="MethodesQuantitScSocialesBolR_files/figure-html/afc1erplanfactInds2B-1.png" alt="Cartographie de coordonnées factorielles des individus pour l'AFC" width="85%" />
<p class="caption">
Figure 12.33: Cartographie de coordonnées factorielles des individus pour l’AFC
</p>
</div>
</div>
</div>
</div>
<h3>R&eacute;f&eacute;rences</h3>
<div id="refs" class="references">
<div id="ref-bendixen1995compositional">
<p>Bendixen, Mike T. 1995. « Compositional perceptual mapping using chi-squared trees analysis and correspondence analysis ». <em>Journal of Marketing Management</em> 11 (6): 571‑581. <a href="https://doi.org/10.1080/0267257X.1995.9964368">https://doi.org/10.1080/0267257X.1995.9964368</a>.</p>
</div>
<div id="ref-benzecri1973analyse">
<p>Benzécri, Jean-Paul. 1973. <em>L’analyse des données. Tome 1. La taxinomie. Tome 2. L’analyse des correspondances</em>. Vol. 2. Dunod.</p>
</div>
<div id="ref-escofier1998analyses">
<p>Escofier, Brigitte et Jérôme Pagès. 1998. « Analyses factorielles simples et multiples ». <em>Dunod, Paris</em>.</p>
</div>
<div id="ref-lebart1995statistique">
<p>Lebart, Ludovic, Alain Morineau et Marie Piron. 1995. <em>Statistique exploratoire multidimensionnelle</em>. Dunod.</p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="sect122.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="sect124.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["MethodesQuantitScSocialesBolR.pdf"],
"toc": {
"collapse": "none"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
