<!DOCTYPE html>
<html lang="fr" xml:lang="fr">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>6.1 Relation entre une variable quantitative et une variable qualitative à deux modalités | Méthodes quantitatives en sciences sociales : un grand bol d’R</title>
  <meta name="description" content="Ce livre vise à décrire une panoplie de méthodes quantitatives utilisées en sciences sociales avec le logiciel ouvert R. Il a d’ailleurs été écrit intégralement dans R avec rmarkdown. Le contenu est pensé pour être accessible à tous et toutes, même à ceux et celles n’ayant presque aucune base en statistique ou en programmation. Les personnes plus expérimentées y découvriront des sections sur des méthodes plus avancées comme les modèles à effets mixtes, les modèles multiniveaux, les modèles généralisés additifs ainsi que les méthodes factorielles et de classification. Ceux et celles souhaitant migrer progressivement d’un autre logiciel statistique vers R trouveront dans cet ouvrage les éléments pour une transition en douceur. La philosophie de ce livre est de donner toutes les clefs de compréhension et de mise en œuvre des méthodes abordées dans R. La présentation des méthodes est basée sur une approche compréhensive et intuitive plutôt que mathématique, sans pour autant que la rigueur statistique ne soit négligée." />
  <meta name="generator" content="bookdown 0.32 and GitBook 2.6.7" />

  <meta property="og:title" content="6.1 Relation entre une variable quantitative et une variable qualitative à deux modalités | Méthodes quantitatives en sciences sociales : un grand bol d’R" />
  <meta property="og:type" content="book" />
  <meta property="og:image" content="https://laeq.github.io/LivreStatistique_website/images/introduction/ImageCouverture.png" />
  <meta property="og:description" content="Ce livre vise à décrire une panoplie de méthodes quantitatives utilisées en sciences sociales avec le logiciel ouvert R. Il a d’ailleurs été écrit intégralement dans R avec rmarkdown. Le contenu est pensé pour être accessible à tous et toutes, même à ceux et celles n’ayant presque aucune base en statistique ou en programmation. Les personnes plus expérimentées y découvriront des sections sur des méthodes plus avancées comme les modèles à effets mixtes, les modèles multiniveaux, les modèles généralisés additifs ainsi que les méthodes factorielles et de classification. Ceux et celles souhaitant migrer progressivement d’un autre logiciel statistique vers R trouveront dans cet ouvrage les éléments pour une transition en douceur. La philosophie de ce livre est de donner toutes les clefs de compréhension et de mise en œuvre des méthodes abordées dans R. La présentation des méthodes est basée sur une approche compréhensive et intuitive plutôt que mathématique, sans pour autant que la rigueur statistique ne soit négligée." />
  <meta name="github-repo" content="LAEQ/livre_statistique_Phil_Jere" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="6.1 Relation entre une variable quantitative et une variable qualitative à deux modalités | Méthodes quantitatives en sciences sociales : un grand bol d’R" />
  
  <meta name="twitter:description" content="Ce livre vise à décrire une panoplie de méthodes quantitatives utilisées en sciences sociales avec le logiciel ouvert R. Il a d’ailleurs été écrit intégralement dans R avec rmarkdown. Le contenu est pensé pour être accessible à tous et toutes, même à ceux et celles n’ayant presque aucune base en statistique ou en programmation. Les personnes plus expérimentées y découvriront des sections sur des méthodes plus avancées comme les modèles à effets mixtes, les modèles multiniveaux, les modèles généralisés additifs ainsi que les méthodes factorielles et de classification. Ceux et celles souhaitant migrer progressivement d’un autre logiciel statistique vers R trouveront dans cet ouvrage les éléments pour une transition en douceur. La philosophie de ce livre est de donner toutes les clefs de compréhension et de mise en œuvre des méthodes abordées dans R. La présentation des méthodes est basée sur une approche compréhensive et intuitive plutôt que mathématique, sans pour autant que la rigueur statistique ne soit négligée." />
  <meta name="twitter:image" content="https://laeq.github.io/LivreStatistique_website/images/introduction/ImageCouverture.png" />

<meta name="author" content="Philippe Apparicio et Jérémy Gelb" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="chap06.html"/>
<link rel="next" href="sect062.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.6.1/htmlwidgets.js"></script>
<script src="libs/d3-4.13.0/d3.min.js"></script>
<script src="libs/d3-tip-0.8.1/index.js"></script>
<link href="libs/chorddiag-0.1.2.9000/chorddiag.css" rel="stylesheet" />
<script src="libs/chorddiag-0.1.2.9000/chorddiag.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="css/quizlib.min.css" type="text/css" />
<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Méthodes quantitatives en sciences sociales : un grand bol d'R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Bienvenue</a></li>
<li class="chapter" data-level="" data-path="préface.html"><a href="préface.html"><i class="fa fa-check"></i>Préface</a>
<ul>
<li class="chapter" data-level="" data-path="sect001.html"><a href="sect001.html"><i class="fa fa-check"></i>Un manuel sous la forme d’une ressource éducative libre</a></li>
<li class="chapter" data-level="" data-path="sect002.html"><a href="sect002.html"><i class="fa fa-check"></i>Un manuel conçu comme un projet collaboratif</a></li>
<li class="chapter" data-level="" data-path="sect003.html"><a href="sect003.html"><i class="fa fa-check"></i>Comment lire ce livre?</a></li>
<li class="chapter" data-level="" data-path="sect003B.html"><a href="sect003B.html"><i class="fa fa-check"></i>Comment utiliser les données du livre pour reproduire les exemples?</a></li>
<li class="chapter" data-level="" data-path="sect004.html"><a href="sect004.html"><i class="fa fa-check"></i>Structure du livre</a></li>
<li class="chapter" data-level="" data-path="sect005.html"><a href="sect005.html"><i class="fa fa-check"></i>Pourquoi faut-il programmer en sciences sociales?</a></li>
<li class="chapter" data-level="" data-path="sect006.html"><a href="sect006.html"><i class="fa fa-check"></i>Remerciements</a></li>
<li class="chapter" data-level="" data-path="sect007.html"><a href="sect007.html"><i class="fa fa-check"></i>Dédicace toute spéciale à Cargo et Ambrée</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="auteurs.html"><a href="auteurs.html"><i class="fa fa-check"></i>À propos des auteurs</a></li>
<li class="part"><span><b>I Découverte de R</b></span></li>
<li class="chapter" data-level="1" data-path="chap01.html"><a href="chap01.html"><i class="fa fa-check"></i><b>1</b> Prise en main de R</a>
<ul>
<li class="chapter" data-level="1.1" data-path="sect011.html"><a href="sect011.html"><i class="fa fa-check"></i><b>1.1</b> Histoire et philosophie de R</a></li>
<li class="chapter" data-level="1.2" data-path="sect012.html"><a href="sect012.html"><i class="fa fa-check"></i><b>1.2</b> Environnement de travail</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="sect012.html"><a href="sect012.html#sect0121"><i class="fa fa-check"></i><b>1.2.1</b> Installation de R</a></li>
<li class="chapter" data-level="1.2.2" data-path="sect012.html"><a href="sect012.html#sect0122"><i class="fa fa-check"></i><b>1.2.2</b> Environnement RStudio</a></li>
<li class="chapter" data-level="1.2.3" data-path="sect012.html"><a href="sect012.html#sect0123"><i class="fa fa-check"></i><b>1.2.3</b> Installation et chargement un <em>package</em></a></li>
<li class="chapter" data-level="1.2.4" data-path="sect012.html"><a href="sect012.html#aide-disponible"><i class="fa fa-check"></i><b>1.2.4</b> Aide disponible</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="sect013.html"><a href="sect013.html"><i class="fa fa-check"></i><b>1.3</b> Bases du langage R</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="sect013.html"><a href="sect013.html#sect0131"><i class="fa fa-check"></i><b>1.3.1</b> <em>Hello World</em>!</a></li>
<li class="chapter" data-level="1.3.2" data-path="sect013.html"><a href="sect013.html#sect0132"><i class="fa fa-check"></i><b>1.3.2</b> Objets et expressions</a></li>
<li class="chapter" data-level="1.3.3" data-path="sect013.html"><a href="sect013.html#sect0_133"><i class="fa fa-check"></i><b>1.3.3</b> Fonctions et arguments</a></li>
<li class="chapter" data-level="1.3.4" data-path="sect013.html"><a href="sect013.html#sect0134"><i class="fa fa-check"></i><b>1.3.4</b> Principaux types de données</a></li>
<li class="chapter" data-level="1.3.5" data-path="sect013.html"><a href="sect013.html#sect0135"><i class="fa fa-check"></i><b>1.3.5</b> Opérateurs</a></li>
<li class="chapter" data-level="1.3.6" data-path="sect013.html"><a href="sect013.html#sect0136"><i class="fa fa-check"></i><b>1.3.6</b> Structures de données</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="sect014.html"><a href="sect014.html"><i class="fa fa-check"></i><b>1.4</b> Manipulation de données</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="sect014.html"><a href="sect014.html#sect0141"><i class="fa fa-check"></i><b>1.4.1</b> Chargement d’un <em>DataFrame</em> depuis un fichier</a></li>
<li class="chapter" data-level="1.4.2" data-path="sect014.html"><a href="sect014.html#sect0142"><i class="fa fa-check"></i><b>1.4.2</b> Manipulation d’un <em>DataFrame</em></a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="sect016.html"><a href="sect016.html"><i class="fa fa-check"></i><b>1.5</b> Code R bien structuré</a></li>
<li class="chapter" data-level="1.6" data-path="sect017.html"><a href="sect017.html"><i class="fa fa-check"></i><b>1.6</b> Enregistrement des résultats</a></li>
<li class="chapter" data-level="1.7" data-path="sect018.html"><a href="sect018.html"><i class="fa fa-check"></i><b>1.7</b> Session de travail</a></li>
<li class="chapter" data-level="1.8" data-path="sect019.html"><a href="sect019.html"><i class="fa fa-check"></i><b>1.8</b> Conclusion et ressources pertinentes</a></li>
<li class="chapter" data-level="1.9" data-path="sect0110.html"><a href="sect0110.html"><i class="fa fa-check"></i><b>1.9</b> Quiz de révision du chapitre</a></li>
</ul></li>
<li class="part"><span><b>II Analyses univariées et graphiques dans R</b></span></li>
<li class="chapter" data-level="2" data-path="chap02.html"><a href="chap02.html"><i class="fa fa-check"></i><b>2</b> Statistiques descriptives univariées</a>
<ul>
<li class="chapter" data-level="2.1" data-path="sect021.html"><a href="sect021.html"><i class="fa fa-check"></i><b>2.1</b> Notion et types de variable</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="sect021.html"><a href="sect021.html#sect0211"><i class="fa fa-check"></i><b>2.1.1</b> Notion de variable</a></li>
<li class="chapter" data-level="2.1.2" data-path="sect021.html"><a href="sect021.html#sect0212"><i class="fa fa-check"></i><b>2.1.2</b> Types de variables</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="sect022.html"><a href="sect022.html"><i class="fa fa-check"></i><b>2.2</b> Types de données</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="sect022.html"><a href="sect022.html#sect0221"><i class="fa fa-check"></i><b>2.2.1</b> Données secondaires <em>versus</em> données primaires</a></li>
<li class="chapter" data-level="2.2.2" data-path="sect022.html"><a href="sect022.html#sect0222"><i class="fa fa-check"></i><b>2.2.2</b> Données transversales <em>versus</em> données longitudinales</a></li>
<li class="chapter" data-level="2.2.3" data-path="sect022.html"><a href="sect022.html#sect0223"><i class="fa fa-check"></i><b>2.2.3</b> Données spatiales versus données aspatiales</a></li>
<li class="chapter" data-level="2.2.4" data-path="sect022.html"><a href="sect022.html#sect0224"><i class="fa fa-check"></i><b>2.2.4</b> Données individuelles <em>versus</em> données agrégées</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="sect023.html"><a href="sect023.html"><i class="fa fa-check"></i><b>2.3</b> Statistique descriptive et statistique inférentielle</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="sect023.html"><a href="sect023.html#sect0231"><i class="fa fa-check"></i><b>2.3.1</b> Population, échantillon et inférence</a></li>
<li class="chapter" data-level="2.3.2" data-path="sect023.html"><a href="sect023.html#sect0232"><i class="fa fa-check"></i><b>2.3.2</b> Deux grandes familles de méthodes statistiques</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="sect024.html"><a href="sect024.html"><i class="fa fa-check"></i><b>2.4</b> Notion de distribution</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="sect024.html"><a href="sect024.html#définition-générale"><i class="fa fa-check"></i><b>2.4.1</b> Définition générale</a></li>
<li class="chapter" data-level="2.4.2" data-path="sect024.html"><a href="sect024.html#anatomie-dune-distribution"><i class="fa fa-check"></i><b>2.4.2</b> Anatomie d’une distribution</a></li>
<li class="chapter" data-level="2.4.3" data-path="sect024.html"><a href="sect024.html#principales-distributions"><i class="fa fa-check"></i><b>2.4.3</b> Principales distributions</a></li>
<li class="chapter" data-level="2.4.4" data-path="sect024.html"><a href="sect024.html#conclusion-sur-les-distributions"><i class="fa fa-check"></i><b>2.4.4</b> Conclusion sur les distributions</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="sect025.html"><a href="sect025.html"><i class="fa fa-check"></i><b>2.5</b> Statistiques descriptives sur des variables quantitatives</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="sect025.html"><a href="sect025.html#sect0251"><i class="fa fa-check"></i><b>2.5.1</b> Paramètres de tendance centrale</a></li>
<li class="chapter" data-level="2.5.2" data-path="sect025.html"><a href="sect025.html#sect0252"><i class="fa fa-check"></i><b>2.5.2</b> Paramètres de position</a></li>
<li class="chapter" data-level="2.5.3" data-path="sect025.html"><a href="sect025.html#sect0253"><i class="fa fa-check"></i><b>2.5.3</b> Paramètres de dispersion</a></li>
<li class="chapter" data-level="2.5.4" data-path="sect025.html"><a href="sect025.html#sect0254"><i class="fa fa-check"></i><b>2.5.4</b> Paramètres de forme</a></li>
<li class="chapter" data-level="2.5.5" data-path="sect025.html"><a href="sect025.html#sect0255"><i class="fa fa-check"></i><b>2.5.5</b> Transformation des variables</a></li>
<li class="chapter" data-level="2.5.6" data-path="sect025.html"><a href="sect025.html#sect0256"><i class="fa fa-check"></i><b>2.5.6</b> Mise en œuvre dans R</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="sect026.html"><a href="sect026.html"><i class="fa fa-check"></i><b>2.6</b> Statistiques descriptives sur des variables qualitatives et semi-qualitatives</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="sect026.html"><a href="sect026.html#sect0261"><i class="fa fa-check"></i><b>2.6.1</b> Fréquences</a></li>
<li class="chapter" data-level="2.6.2" data-path="sect026.html"><a href="sect026.html#sect0262"><i class="fa fa-check"></i><b>2.6.2</b> Mise en œuvre dans R</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="sect027.html"><a href="sect027.html"><i class="fa fa-check"></i><b>2.7</b> Statistiques descriptives pondérées : pour aller plus loin</a></li>
<li class="chapter" data-level="2.8" data-path="sect028.html"><a href="sect028.html"><i class="fa fa-check"></i><b>2.8</b> Quiz de révision du chapitre</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="chap03.html"><a href="chap03.html"><i class="fa fa-check"></i><b>3</b> Magie des graphiques</a>
<ul>
<li class="chapter" data-level="3.1" data-path="sect031.html"><a href="sect031.html"><i class="fa fa-check"></i><b>3.1</b> Philosophie du ggplot2</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="sect031.html"><a href="sect031.html#sect0311"><i class="fa fa-check"></i><b>3.1.1</b> Grammaire</a></li>
<li class="chapter" data-level="3.1.2" data-path="sect031.html"><a href="sect031.html#sect0312"><i class="fa fa-check"></i><b>3.1.2</b> Types de géométries</a></li>
<li class="chapter" data-level="3.1.3" data-path="sect031.html"><a href="sect031.html#sect0313"><i class="fa fa-check"></i><b>3.1.3</b> Habillage</a></li>
<li class="chapter" data-level="3.1.4" data-path="sect031.html"><a href="sect031.html#utilisation-des-thèmes"><i class="fa fa-check"></i><b>3.1.4</b> Utilisation des thèmes</a></li>
<li class="chapter" data-level="3.1.5" data-path="sect031.html"><a href="sect031.html#sect0314"><i class="fa fa-check"></i><b>3.1.5</b> Composition d’une figure avec plusieurs graphiques</a></li>
<li class="chapter" data-level="3.1.6" data-path="sect031.html"><a href="sect031.html#sect0315"><i class="fa fa-check"></i><b>3.1.6</b> Couleur</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="sect032.html"><a href="sect032.html"><i class="fa fa-check"></i><b>3.2</b> Principaux graphiques</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="sect032.html"><a href="sect032.html#sect0321"><i class="fa fa-check"></i><b>3.2.1</b> Histogramme</a></li>
<li class="chapter" data-level="3.2.2" data-path="sect032.html"><a href="sect032.html#sect0322"><i class="fa fa-check"></i><b>3.2.2</b> Graphique de densité</a></li>
<li class="chapter" data-level="3.2.3" data-path="sect032.html"><a href="sect032.html#sect0323"><i class="fa fa-check"></i><b>3.2.3</b> Nuage de points</a></li>
<li class="chapter" data-level="3.2.4" data-path="sect032.html"><a href="sect032.html#sect0324"><i class="fa fa-check"></i><b>3.2.4</b> Graphique en ligne</a></li>
<li class="chapter" data-level="3.2.5" data-path="sect032.html"><a href="sect032.html#sect0325"><i class="fa fa-check"></i><b>3.2.5</b> Boîte à moustaches</a></li>
<li class="chapter" data-level="3.2.6" data-path="sect032.html"><a href="sect032.html#sect0326"><i class="fa fa-check"></i><b>3.2.6</b> Graphique en violon</a></li>
<li class="chapter" data-level="3.2.7" data-path="sect032.html"><a href="sect032.html#sect0327"><i class="fa fa-check"></i><b>3.2.7</b> Graphique en barre</a></li>
<li class="chapter" data-level="3.2.8" data-path="sect032.html"><a href="sect032.html#sect0328"><i class="fa fa-check"></i><b>3.2.8</b> Graphique circulaire</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="sect033.html"><a href="sect033.html"><i class="fa fa-check"></i><b>3.3</b> Graphiques spéciaux</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="sect033.html"><a href="sect033.html#sect0331"><i class="fa fa-check"></i><b>3.3.1</b> Graphique en radar</a></li>
<li class="chapter" data-level="3.3.2" data-path="sect033.html"><a href="sect033.html#sect0332"><i class="fa fa-check"></i><b>3.3.2</b> Diagramme d’accord</a></li>
<li class="chapter" data-level="3.3.3" data-path="sect033.html"><a href="sect033.html#sect0333"><i class="fa fa-check"></i><b>3.3.3</b> Nuage de mots</a></li>
<li class="chapter" data-level="3.3.4" data-path="sect033.html"><a href="sect033.html#sect0334"><i class="fa fa-check"></i><b>3.3.4</b> Carte proportionnelle</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="sect034.html"><a href="sect034.html"><i class="fa fa-check"></i><b>3.4</b> Cartes</a></li>
<li class="chapter" data-level="3.5" data-path="sect035.html"><a href="sect035.html"><i class="fa fa-check"></i><b>3.5</b> Exportation des graphiques</a></li>
<li class="chapter" data-level="3.6" data-path="sect036.html"><a href="sect036.html"><i class="fa fa-check"></i><b>3.6</b> Conclusion sur les graphiques</a></li>
</ul></li>
<li class="part"><span><b>III Analyses bivariées</b></span></li>
<li class="chapter" data-level="4" data-path="chap04.html"><a href="chap04.html"><i class="fa fa-check"></i><b>4</b> Relation linéaire entre deux variables quantitatives</a>
<ul>
<li class="chapter" data-level="4.1" data-path="sect041.html"><a href="sect041.html"><i class="fa fa-check"></i><b>4.1</b> Bref retour sur le postulat de la relation linéaire</a></li>
<li class="chapter" data-level="4.2" data-path="sect042.html"><a href="sect042.html"><i class="fa fa-check"></i><b>4.2</b> Covariance</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="sect042.html"><a href="sect042.html#sect0421"><i class="fa fa-check"></i><b>4.2.1</b> Formulation</a></li>
<li class="chapter" data-level="4.2.2" data-path="sect042.html"><a href="sect042.html#sect0422"><i class="fa fa-check"></i><b>4.2.2</b> Interprétation</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="sect043.html"><a href="sect043.html"><i class="fa fa-check"></i><b>4.3</b> Corrélation</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="sect043.html"><a href="sect043.html#sect0431"><i class="fa fa-check"></i><b>4.3.1</b> Formulation</a></li>
<li class="chapter" data-level="4.3.2" data-path="sect043.html"><a href="sect043.html#sect0432"><i class="fa fa-check"></i><b>4.3.2</b> Interprétation</a></li>
<li class="chapter" data-level="4.3.3" data-path="sect043.html"><a href="sect043.html#sect0433"><i class="fa fa-check"></i><b>4.3.3</b> Corrélations pour des variables anormalement distribuées (coefficient de Spearman, tau de Kendall)</a></li>
<li class="chapter" data-level="4.3.4" data-path="sect043.html"><a href="sect043.html#sect0434"><i class="fa fa-check"></i><b>4.3.4</b> Corrélations robustes (<em>Biweight midcorrelation</em>, <em>Percentage bend correlation</em> et la corrélation <em>pi</em> de Shepherd)</a></li>
<li class="chapter" data-level="4.3.5" data-path="sect043.html"><a href="sect043.html#sect0435"><i class="fa fa-check"></i><b>4.3.5</b> Significativité des coefficients de corrélation</a></li>
<li class="chapter" data-level="4.3.6" data-path="sect043.html"><a href="sect043.html#sect0436"><i class="fa fa-check"></i><b>4.3.6</b> Corrélation partielle</a></li>
<li class="chapter" data-level="4.3.7" data-path="sect043.html"><a href="sect043.html#sect0437"><i class="fa fa-check"></i><b>4.3.7</b> Mise en œuvre dans R</a></li>
<li class="chapter" data-level="4.3.8" data-path="sect043.html"><a href="sect043.html#sect0438"><i class="fa fa-check"></i><b>4.3.8</b> Comment rapporter des valeurs de corrélations?</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="sect044.html"><a href="sect044.html"><i class="fa fa-check"></i><b>4.4</b> Régression linéaire simple</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="sect044.html"><a href="sect044.html#sect0441"><i class="fa fa-check"></i><b>4.4.1</b> Principe de base de la régression linéaire simple</a></li>
<li class="chapter" data-level="4.4.2" data-path="sect044.html"><a href="sect044.html#sect0442"><i class="fa fa-check"></i><b>4.4.2</b> Formulation de la droite de régression des moindres carrés ordinaires</a></li>
<li class="chapter" data-level="4.4.3" data-path="sect044.html"><a href="sect044.html#sect0443"><i class="fa fa-check"></i><b>4.4.3</b> Mesure de la qualité d’ajustement du modèle</a></li>
<li class="chapter" data-level="4.4.4" data-path="sect044.html"><a href="sect044.html#sect0444"><i class="fa fa-check"></i><b>4.4.4</b> Mise en œuvre dans R</a></li>
<li class="chapter" data-level="4.4.5" data-path="sect044.html"><a href="sect044.html#sect0445"><i class="fa fa-check"></i><b>4.4.5</b> Comment rapporter une régression linéaire simple</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="sect045.html"><a href="sect045.html"><i class="fa fa-check"></i><b>4.5</b> Quiz de révision du chapitre</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="chap05.html"><a href="chap05.html"><i class="fa fa-check"></i><b>5</b> Relation entre deux variables qualitatives</a>
<ul>
<li class="chapter" data-level="5.1" data-path="sect051.html"><a href="sect051.html"><i class="fa fa-check"></i><b>5.1</b> Construction de tableau de contingence</a></li>
<li class="chapter" data-level="5.2" data-path="sect052.html"><a href="sect052.html"><i class="fa fa-check"></i><b>5.2</b> Test du khi-deux</a></li>
<li class="chapter" data-level="5.3" data-path="sect053.html"><a href="sect053.html"><i class="fa fa-check"></i><b>5.3</b> Mise en œuvre dans R</a></li>
<li class="chapter" data-level="5.4" data-path="sect054.html"><a href="sect054.html"><i class="fa fa-check"></i><b>5.4</b> Interprétation d’un tableau de contingence</a></li>
<li class="chapter" data-level="5.5" data-path="sect055.html"><a href="sect055.html"><i class="fa fa-check"></i><b>5.5</b> Quiz de révision du chapitre</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="chap06.html"><a href="chap06.html"><i class="fa fa-check"></i><b>6</b> Relation entre une variable qualitative et une variable quantitative</a>
<ul>
<li class="chapter" data-level="6.1" data-path="sect061.html"><a href="sect061.html"><i class="fa fa-check"></i><b>6.1</b> Relation entre une variable quantitative et une variable qualitative à deux modalités</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="sect061.html"><a href="sect061.html#sect0611"><i class="fa fa-check"></i><b>6.1.1</b> Test <em>t</em> et ses différentes variantes</a></li>
<li class="chapter" data-level="6.1.2" data-path="sect061.html"><a href="sect061.html#sect0612"><i class="fa fa-check"></i><b>6.1.2</b> Test non paramétrique de Wilcoxon</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="sect062.html"><a href="sect062.html"><i class="fa fa-check"></i><b>6.2</b> Relation entre une variable quantitative et une variable qualitative à plus de deux modalités</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="sect062.html"><a href="sect062.html#sect0621"><i class="fa fa-check"></i><b>6.2.1</b> Analyse de variance</a></li>
<li class="chapter" data-level="6.2.2" data-path="sect062.html"><a href="sect062.html#sect0622"><i class="fa fa-check"></i><b>6.2.2</b> Test non paramétrique de Kruskal-Wallis</a></li>
<li class="chapter" data-level="6.2.3" data-path="sect062.html"><a href="sect062.html#sect0623"><i class="fa fa-check"></i><b>6.2.3</b> Mise en œuvre dans R</a></li>
<li class="chapter" data-level="6.2.4" data-path="sect062.html"><a href="sect062.html#sect0624"><i class="fa fa-check"></i><b>6.2.4</b> Comment rapporter les résultats d’une ANOVA et du test de Kruskal-Wallis</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="sect063.html"><a href="sect063.html"><i class="fa fa-check"></i><b>6.3</b> Conclusion sur la troisième partie</a></li>
<li class="chapter" data-level="6.4" data-path="sect064.html"><a href="sect064.html"><i class="fa fa-check"></i><b>6.4</b> Quiz de révision du chapitre</a></li>
</ul></li>
<li class="part"><span><b>IV Modèles de régression</b></span></li>
<li class="chapter" data-level="7" data-path="chap07.html"><a href="chap07.html"><i class="fa fa-check"></i><b>7</b> Régression linéaire multiple</a>
<ul>
<li class="chapter" data-level="7.1" data-path="sect071.html"><a href="sect071.html"><i class="fa fa-check"></i><b>7.1</b> Objectifs de la régression linéaire multiple et construction d’un modèle de régression</a></li>
<li class="chapter" data-level="7.2" data-path="sect072.html"><a href="sect072.html"><i class="fa fa-check"></i><b>7.2</b> Principes de base de la régression linéaire multiple</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="sect072.html"><a href="sect072.html#sect0721"><i class="fa fa-check"></i><b>7.2.1</b> Un peu d’équations…</a></li>
<li class="chapter" data-level="7.2.2" data-path="sect072.html"><a href="sect072.html#sect0722"><i class="fa fa-check"></i><b>7.2.2</b> Hypothèses de la régression linéaire multiple</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="sect073.html"><a href="sect073.html"><i class="fa fa-check"></i><b>7.3</b> Évaluation de la qualité d’ajustement du modèle</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="sect073.html"><a href="sect073.html#sect0731"><i class="fa fa-check"></i><b>7.3.1</b> Mesures de la qualité d’un modèle</a></li>
<li class="chapter" data-level="7.3.2" data-path="sect073.html"><a href="sect073.html#sect0732"><i class="fa fa-check"></i><b>7.3.2</b> Comparaison des modèles incrémentiels</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="sect074.html"><a href="sect074.html"><i class="fa fa-check"></i><b>7.4</b> Différentes mesures pour les coefficients de régression</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="sect074.html"><a href="sect074.html#sect0741"><i class="fa fa-check"></i><b>7.4.1</b> Coefficients de régression : évaluer l’effet des variables indépendantes</a></li>
<li class="chapter" data-level="7.4.2" data-path="sect074.html"><a href="sect074.html#sect0742"><i class="fa fa-check"></i><b>7.4.2</b> Coefficients de régression standardisés : repérer les variables les plus importantes du modèle</a></li>
<li class="chapter" data-level="7.4.3" data-path="sect074.html"><a href="sect074.html#sect0743"><i class="fa fa-check"></i><b>7.4.3</b> Significativité des coefficients de régression : valeurs de <em>t</em> et de <em>p</em></a></li>
<li class="chapter" data-level="7.4.4" data-path="sect074.html"><a href="sect074.html#sect0744"><i class="fa fa-check"></i><b>7.4.4</b> Intervalle de confiance des coefficients</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="sect075.html"><a href="sect075.html"><i class="fa fa-check"></i><b>7.5</b> Introduction de variables explicatives particulières</a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="sect075.html"><a href="sect075.html#sect0751"><i class="fa fa-check"></i><b>7.5.1</b> Exploration des relations non linéaires</a></li>
<li class="chapter" data-level="7.5.2" data-path="sect075.html"><a href="sect075.html#sect0752"><i class="fa fa-check"></i><b>7.5.2</b> Variable indépendante qualitative dichotomique</a></li>
<li class="chapter" data-level="7.5.3" data-path="sect075.html"><a href="sect075.html#sect0753"><i class="fa fa-check"></i><b>7.5.3</b> Variable indépendante qualitative polytomique</a></li>
<li class="chapter" data-level="7.5.4" data-path="sect075.html"><a href="sect075.html#sect0754"><i class="fa fa-check"></i><b>7.5.4</b> Variables d’interaction</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="sect076.html"><a href="sect076.html"><i class="fa fa-check"></i><b>7.6</b> Diagnostics de la régression</a>
<ul>
<li class="chapter" data-level="7.6.1" data-path="sect076.html"><a href="sect076.html#sect0761"><i class="fa fa-check"></i><b>7.6.1</b> Nombre d’observations</a></li>
<li class="chapter" data-level="7.6.2" data-path="sect076.html"><a href="sect076.html#sect0762"><i class="fa fa-check"></i><b>7.6.2</b> Normalité des résidus</a></li>
<li class="chapter" data-level="7.6.3" data-path="sect076.html"><a href="sect076.html#sect0763"><i class="fa fa-check"></i><b>7.6.3</b> Linéarité et homoscédasticité des résidus</a></li>
<li class="chapter" data-level="7.6.4" data-path="sect076.html"><a href="sect076.html#sect0764"><i class="fa fa-check"></i><b>7.6.4</b> Absence de multicolinéarité excessive</a></li>
<li class="chapter" data-level="7.6.5" data-path="sect076.html"><a href="sect076.html#sect0766"><i class="fa fa-check"></i><b>7.6.5</b> Absence d’observations aberrantes</a></li>
</ul></li>
<li class="chapter" data-level="7.7" data-path="sect077.html"><a href="sect077.html"><i class="fa fa-check"></i><b>7.7</b> Mise en œuvre dans R</a>
<ul>
<li class="chapter" data-level="7.7.1" data-path="sect077.html"><a href="sect077.html#sect0771"><i class="fa fa-check"></i><b>7.7.1</b> Fonctions <code>lm</code>, <code>summary()</code> et <code>confint()</code></a></li>
<li class="chapter" data-level="7.7.2" data-path="sect077.html"><a href="sect077.html#sect0772"><i class="fa fa-check"></i><b>7.7.2</b> Comparaison des modèles</a></li>
<li class="chapter" data-level="7.7.3" data-path="sect077.html"><a href="sect077.html#sect0773"><i class="fa fa-check"></i><b>7.7.3</b> Diagnostic sur un modèle</a></li>
<li class="chapter" data-level="7.7.4" data-path="sect077.html"><a href="sect077.html#sect0774"><i class="fa fa-check"></i><b>7.7.4</b> Graphiques pour les effets marginaux</a></li>
</ul></li>
<li class="chapter" data-level="7.8" data-path="sect078.html"><a href="sect078.html"><i class="fa fa-check"></i><b>7.8</b> Quiz de révision du chapitre</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="chap08.html"><a href="chap08.html"><i class="fa fa-check"></i><b>8</b> Régressions linéaires généralisées (GLM)</a>
<ul>
<li class="chapter" data-level="8.1" data-path="sect081.html"><a href="sect081.html"><i class="fa fa-check"></i><b>8.1</b> Qu’est qu’un modèle GLM?</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="sect081.html"><a href="sect081.html#sect0811"><i class="fa fa-check"></i><b>8.1.1</b> Formulation d’un GLM</a></li>
<li class="chapter" data-level="8.1.2" data-path="sect081.html"><a href="sect081.html#sect0812"><i class="fa fa-check"></i><b>8.1.2</b> Autres distributions et rôle de la fonction de lien</a></li>
<li class="chapter" data-level="8.1.3" data-path="sect081.html"><a href="sect081.html#sect0813"><i class="fa fa-check"></i><b>8.1.3</b> Conditions d’application</a></li>
<li class="chapter" data-level="8.1.4" data-path="sect081.html"><a href="sect081.html#sect0814"><i class="fa fa-check"></i><b>8.1.4</b> Résidus et déviance</a></li>
<li class="chapter" data-level="8.1.5" data-path="sect081.html"><a href="sect081.html#sect0815"><i class="fa fa-check"></i><b>8.1.5</b> Vérification l’ajustement</a></li>
<li class="chapter" data-level="8.1.6" data-path="sect081.html"><a href="sect081.html#sect0816"><i class="fa fa-check"></i><b>8.1.6</b> Comparaison de deux modèles GLM</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="sect082.html"><a href="sect082.html"><i class="fa fa-check"></i><b>8.2</b> Modèles GLM pour des variables qualitatives</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="sect082.html"><a href="sect082.html#sect0821"><i class="fa fa-check"></i><b>8.2.1</b> Modèle logistique binomial</a></li>
<li class="chapter" data-level="8.2.2" data-path="sect082.html"><a href="sect082.html#sect0822"><i class="fa fa-check"></i><b>8.2.2</b> Modèle probit binomial</a></li>
<li class="chapter" data-level="8.2.3" data-path="sect082.html"><a href="sect082.html#sect0823"><i class="fa fa-check"></i><b>8.2.3</b> Modèle logistique des cotes proportionnelles</a></li>
<li class="chapter" data-level="8.2.4" data-path="sect082.html"><a href="sect082.html#sect0824"><i class="fa fa-check"></i><b>8.2.4</b> Modèle logistique multinomial</a></li>
<li class="chapter" data-level="8.2.5" data-path="sect082.html"><a href="sect082.html#conclusion-sur-les-modèles-pour-des-variables-qualitatives"><i class="fa fa-check"></i><b>8.2.5</b> Conclusion sur les modèles pour des variables qualitatives</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="sect084.html"><a href="sect084.html"><i class="fa fa-check"></i><b>8.3</b> Modèles GLM pour des variables de comptage</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="sect084.html"><a href="sect084.html#sect0841"><i class="fa fa-check"></i><b>8.3.1</b> Modèle de Poisson</a></li>
<li class="chapter" data-level="8.3.2" data-path="sect084.html"><a href="sect084.html#sect0842"><i class="fa fa-check"></i><b>8.3.2</b> Modèle binomial négatif</a></li>
<li class="chapter" data-level="8.3.3" data-path="sect084.html"><a href="sect084.html#sect0843"><i class="fa fa-check"></i><b>8.3.3</b> Modèle de Poisson avec excès fixe de zéros</a></li>
<li class="chapter" data-level="8.3.4" data-path="sect084.html"><a href="sect084.html#sect0844"><i class="fa fa-check"></i><b>8.3.4</b> Modèle de Poisson avec excès ajusté de zéros</a></li>
<li class="chapter" data-level="8.3.5" data-path="sect084.html"><a href="sect084.html#sect0845"><i class="fa fa-check"></i><b>8.3.5</b> Conclusion sur les modèles destinés à des variables de comptage</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="sect085.html"><a href="sect085.html"><i class="fa fa-check"></i><b>8.4</b> Modèles GLM pour des variables continues</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="sect085.html"><a href="sect085.html#sect0851"><i class="fa fa-check"></i><b>8.4.1</b> Modèle GLM gaussien</a></li>
<li class="chapter" data-level="8.4.2" data-path="sect085.html"><a href="sect085.html#sect0852"><i class="fa fa-check"></i><b>8.4.2</b> Modèle GLM avec une distribution de Student</a></li>
<li class="chapter" data-level="8.4.3" data-path="sect085.html"><a href="sect085.html#sect0853"><i class="fa fa-check"></i><b>8.4.3</b> Modèle GLM avec distribution Gamma</a></li>
<li class="chapter" data-level="8.4.4" data-path="sect085.html"><a href="sect085.html#sect0854"><i class="fa fa-check"></i><b>8.4.4</b> Modèle GLM avec une distribution bêta</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="sect086.html"><a href="sect086.html"><i class="fa fa-check"></i><b>8.5</b> Conclusion sur les modèles linéaires généralisés</a></li>
<li class="chapter" data-level="8.6" data-path="sect087.html"><a href="sect087.html"><i class="fa fa-check"></i><b>8.6</b> Quiz de révision du chapitre</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="chap09.html"><a href="chap09.html"><i class="fa fa-check"></i><b>9</b> Régressions à effets mixtes (GLMM)</a>
<ul>
<li class="chapter" data-level="9.1" data-path="sect091.html"><a href="sect091.html"><i class="fa fa-check"></i><b>9.1</b> Introduction</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="sect091.html"><a href="sect091.html#sect0911"><i class="fa fa-check"></i><b>9.1.1</b> Indépendance des observations et effets de groupes</a></li>
<li class="chapter" data-level="9.1.2" data-path="sect091.html"><a href="sect091.html#sect0912"><i class="fa fa-check"></i><b>9.1.2</b> Terminologie: effets fixes et effets aléatoires</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="sect092.html"><a href="sect092.html"><i class="fa fa-check"></i><b>9.2</b> Principes de base des GLMM</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="sect092.html"><a href="sect092.html#sect0921"><i class="fa fa-check"></i><b>9.2.1</b> GLMM avec constantes aléatoires</a></li>
<li class="chapter" data-level="9.2.2" data-path="sect092.html"><a href="sect092.html#sect0923"><i class="fa fa-check"></i><b>9.2.2</b> GLMM avec pentes aléatoires</a></li>
<li class="chapter" data-level="9.2.3" data-path="sect092.html"><a href="sect092.html#sect0924"><i class="fa fa-check"></i><b>9.2.3</b> GLMM avec constantes et pentes aléatoires</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="sect093.html"><a href="sect093.html"><i class="fa fa-check"></i><b>9.3</b> Conditions d’application des GLMM</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="sect093.html"><a href="sect093.html#sect0931"><i class="fa fa-check"></i><b>9.3.1</b> Vérification de la distribution des effets aléatoires</a></li>
<li class="chapter" data-level="9.3.2" data-path="sect093.html"><a href="sect093.html#sect0932"><i class="fa fa-check"></i><b>9.3.2</b> Homogénéité des variances au sein des groupes</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="sect094.html"><a href="sect094.html"><i class="fa fa-check"></i><b>9.4</b> Inférence dans les modèles GLMM</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="sect094.html"><a href="sect094.html#sect0941"><i class="fa fa-check"></i><b>9.4.1</b> Inférence pour les effets fixes</a></li>
<li class="chapter" data-level="9.4.2" data-path="sect094.html"><a href="sect094.html#sect0942"><i class="fa fa-check"></i><b>9.4.2</b> Inférence pour les effets aléatoires, effet global</a></li>
<li class="chapter" data-level="9.4.3" data-path="sect094.html"><a href="sect094.html#sect0943"><i class="fa fa-check"></i><b>9.4.3</b> Inférence pour les effets aléatoires, des constantes et des pentes</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="sect095.html"><a href="sect095.html"><i class="fa fa-check"></i><b>9.5</b> Conclusion sur les GLMM</a></li>
<li class="chapter" data-level="9.6" data-path="sect096.html"><a href="sect096.html"><i class="fa fa-check"></i><b>9.6</b> Mise en œuvre des GLMM dans R</a>
<ul>
<li class="chapter" data-level="9.6.1" data-path="sect096.html"><a href="sect096.html#sect0961"><i class="fa fa-check"></i><b>9.6.1</b> Ajustement du modèle avec uniquement une constante aléatoire</a></li>
<li class="chapter" data-level="9.6.2" data-path="sect096.html"><a href="sect096.html#sect0962"><i class="fa fa-check"></i><b>9.6.2</b> Ajustement du modèle avec constantes et pentes aléatoires</a></li>
</ul></li>
<li class="chapter" data-level="9.7" data-path="sect097.html"><a href="sect097.html"><i class="fa fa-check"></i><b>9.7</b> Quiz de révision du chapitre</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="chap10.html"><a href="chap10.html"><i class="fa fa-check"></i><b>10</b> Régressions multiniveaux</a>
<ul>
<li class="chapter" data-level="10.1" data-path="sect101.html"><a href="sect101.html"><i class="fa fa-check"></i><b>10.1</b> Modèles multiniveaux : deux intérêts majeurs</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="sect101.html"><a href="sect101.html#sect1011"><i class="fa fa-check"></i><b>10.1.1</b> Répartition de la variance entre les différents niveaux</a></li>
<li class="chapter" data-level="10.1.2" data-path="sect101.html"><a href="sect101.html#sect1012"><i class="fa fa-check"></i><b>10.1.2</b> Estimation des coefficients aux différents niveaux</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="sect102.html"><a href="sect102.html"><i class="fa fa-check"></i><b>10.2</b> Différents types de modèles multiniveaux</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="sect102.html"><a href="sect102.html#sect1021"><i class="fa fa-check"></i><b>10.2.1</b> Description du jeu de données utilisé</a></li>
<li class="chapter" data-level="10.2.2" data-path="sect102.html"><a href="sect102.html#sect1022"><i class="fa fa-check"></i><b>10.2.2</b> Démarche classique pour les modèles multiniveaux</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="sect103.html"><a href="sect103.html"><i class="fa fa-check"></i><b>10.3</b> Conditions d’application des régressions multiniveaux</a></li>
<li class="chapter" data-level="10.4" data-path="sect104.html"><a href="sect104.html"><i class="fa fa-check"></i><b>10.4</b> Mise en œuvre dans R</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="sect104.html"><a href="sect104.html#sect1041"><i class="fa fa-check"></i><b>10.4.1</b> Le modèle vide</a></li>
<li class="chapter" data-level="10.4.2" data-path="sect104.html"><a href="sect104.html#sect1042"><i class="fa fa-check"></i><b>10.4.2</b> Modèle avec les variables indépendantes du niveau 1</a></li>
<li class="chapter" data-level="10.4.3" data-path="sect104.html"><a href="sect104.html#sect1043"><i class="fa fa-check"></i><b>10.4.3</b> Modèle avec les variables indépendantes aux niveaux 1 et 2</a></li>
<li class="chapter" data-level="10.4.4" data-path="sect104.html"><a href="sect104.html#sect10414"><i class="fa fa-check"></i><b>10.4.4</b> Modèle complet avec une interaction</a></li>
<li class="chapter" data-level="10.4.5" data-path="sect104.html"><a href="sect104.html#sect1045"><i class="fa fa-check"></i><b>10.4.5</b> Comparaison des quatre modèles</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="sect105.html"><a href="sect105.html"><i class="fa fa-check"></i><b>10.5</b> Quiz de révision du chapitre</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="chap11.html"><a href="chap11.html"><i class="fa fa-check"></i><b>11</b> Modèles généralisés additifs</a>
<ul>
<li class="chapter" data-level="11.1" data-path="sect111.html"><a href="sect111.html"><i class="fa fa-check"></i><b>11.1</b> Introduction</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="sect111.html"><a href="sect111.html#sect1111"><i class="fa fa-check"></i><b>11.1.1</b> Non linéarité fonctionnelle</a></li>
<li class="chapter" data-level="11.1.2" data-path="sect111.html"><a href="sect111.html#sect1112"><i class="fa fa-check"></i><b>11.1.2</b> Non linéarité avec des polynomiales</a></li>
<li class="chapter" data-level="11.1.3" data-path="sect111.html"><a href="sect111.html#sect1113"><i class="fa fa-check"></i><b>11.1.3</b> Non linéarité par segments</a></li>
<li class="chapter" data-level="11.1.4" data-path="sect111.html"><a href="sect111.html#sect1114"><i class="fa fa-check"></i><b>11.1.4</b> Non linéarité avec des <em>splines</em></a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="sect112.html"><a href="sect112.html"><i class="fa fa-check"></i><b>11.2</b> <em>Spline</em> de régression et <em>spline</em> de lissage</a></li>
<li class="chapter" data-level="11.3" data-path="sect113.html"><a href="sect113.html"><i class="fa fa-check"></i><b>11.3</b> Interprétation d’une <em>spline</em></a></li>
<li class="chapter" data-level="11.4" data-path="sect114.html"><a href="sect114.html"><i class="fa fa-check"></i><b>11.4</b> Multicolinéarité non linéaire</a></li>
<li class="chapter" data-level="11.5" data-path="sect115.html"><a href="sect115.html"><i class="fa fa-check"></i><b>11.5</b> <em>Splines</em> avancées</a>
<ul>
<li class="chapter" data-level="11.5.1" data-path="sect115.html"><a href="sect115.html#sect1151"><i class="fa fa-check"></i><b>11.5.1</b> <em>Splines</em> cycliques</a></li>
<li class="chapter" data-level="11.5.2" data-path="sect115.html"><a href="sect115.html#sect1152"><i class="fa fa-check"></i><b>11.5.2</b> Splines par groupe</a></li>
<li class="chapter" data-level="11.5.3" data-path="sect115.html"><a href="sect115.html#sect1153"><i class="fa fa-check"></i><b>11.5.3</b> <em>Splines</em> multivariées et <em>splines</em> d’interaction</a></li>
</ul></li>
<li class="chapter" data-level="11.6" data-path="sect116.html"><a href="sect116.html"><i class="fa fa-check"></i><b>11.6</b> Mise en oeuvre dans R</a></li>
<li class="chapter" data-level="11.7" data-path="sect117.html"><a href="sect117.html"><i class="fa fa-check"></i><b>11.7</b> GAMM</a></li>
<li class="chapter" data-level="11.8" data-path="sect118.html"><a href="sect118.html"><i class="fa fa-check"></i><b>11.8</b> Quiz de révision du chapitre</a></li>
</ul></li>
<li class="part"><span><b>V Analyses exploratoires multivariées</b></span></li>
<li class="chapter" data-level="12" data-path="chap12.html"><a href="chap12.html"><i class="fa fa-check"></i><b>12</b> Méthodes factorielles</a>
<ul>
<li class="chapter" data-level="12.1" data-path="sect121.html"><a href="sect121.html"><i class="fa fa-check"></i><b>12.1</b> Aperçu des méthodes factorielles</a>
<ul>
<li class="chapter" data-level="12.1.1" data-path="sect121.html"><a href="sect121.html#sect1211"><i class="fa fa-check"></i><b>12.1.1</b> Méthodes factorielles et types de données</a></li>
<li class="chapter" data-level="12.1.2" data-path="sect121.html"><a href="sect121.html#sect1212"><i class="fa fa-check"></i><b>12.1.2</b> Bref historique des méthodes factorielles</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="sect122.html"><a href="sect122.html"><i class="fa fa-check"></i><b>12.2</b> Analyses en composantes principales (ACP)</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="sect122.html"><a href="sect122.html#sect1221"><i class="fa fa-check"></i><b>12.2.1</b> Recherche d’une simplification</a></li>
<li class="chapter" data-level="12.2.2" data-path="sect122.html"><a href="sect122.html#sect1222"><i class="fa fa-check"></i><b>12.2.2</b> Aides à l’interprétation</a></li>
<li class="chapter" data-level="12.2.3" data-path="sect122.html"><a href="sect122.html#sect1223"><i class="fa fa-check"></i><b>12.2.3</b> Mise en œuvre dans R</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="sect123.html"><a href="sect123.html"><i class="fa fa-check"></i><b>12.3</b> Analyse factorielle des correspondances (AFC)</a>
<ul>
<li class="chapter" data-level="12.3.1" data-path="sect123.html"><a href="sect123.html#sect1231"><i class="fa fa-check"></i><b>12.3.1</b> Recherche d’une simplification basée sur la distance du khi-deux</a></li>
<li class="chapter" data-level="12.3.2" data-path="sect123.html"><a href="sect123.html#sect1232"><i class="fa fa-check"></i><b>12.3.2</b> Aides à l’interprétation</a></li>
<li class="chapter" data-level="12.3.3" data-path="sect123.html"><a href="sect123.html#sect1233"><i class="fa fa-check"></i><b>12.3.3</b> Mise en œuvre dans R</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="sect124.html"><a href="sect124.html"><i class="fa fa-check"></i><b>12.4</b> Analyse de correspondances multiples (ACM)</a>
<ul>
<li class="chapter" data-level="12.4.1" data-path="sect124.html"><a href="sect124.html#sect1241"><i class="fa fa-check"></i><b>12.4.1</b> Aides à l’interprétation</a></li>
<li class="chapter" data-level="12.4.2" data-path="sect124.html"><a href="sect124.html#sect1242"><i class="fa fa-check"></i><b>12.4.2</b> Mise en œuvre dans R</a></li>
</ul></li>
<li class="chapter" data-level="12.5" data-path="sect125.html"><a href="sect125.html"><i class="fa fa-check"></i><b>12.5</b> Quiz de révision du chapitre</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="chap13.html"><a href="chap13.html"><i class="fa fa-check"></i><b>13</b> Méthodes de classification non supervisée</a>
<ul>
<li class="chapter" data-level="13.1" data-path="sect131.html"><a href="sect131.html"><i class="fa fa-check"></i><b>13.1</b> Méthodes de classification : un aperçu</a></li>
<li class="chapter" data-level="13.2" data-path="sect132.html"><a href="sect132.html"><i class="fa fa-check"></i><b>13.2</b> Notions essentielles en classification</a>
<ul>
<li class="chapter" data-level="13.2.1" data-path="sect132.html"><a href="sect132.html#sect1321"><i class="fa fa-check"></i><b>13.2.1</b> Distance</a></li>
<li class="chapter" data-level="13.2.2" data-path="sect132.html"><a href="sect132.html#sect1322"><i class="fa fa-check"></i><b>13.2.2</b> Inertie</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="sect133.html"><a href="sect133.html"><i class="fa fa-check"></i><b>13.3</b> Classification ascendante hiérarchique</a>
<ul>
<li class="chapter" data-level="13.3.1" data-path="sect133.html"><a href="sect133.html#sect1331"><i class="fa fa-check"></i><b>13.3.1</b> Fonctionnement de l’algorithme</a></li>
<li class="chapter" data-level="13.3.2" data-path="sect133.html"><a href="sect133.html#sect1332"><i class="fa fa-check"></i><b>13.3.2</b> Choisir le bon nombre de groupes</a></li>
<li class="chapter" data-level="13.3.3" data-path="sect133.html"><a href="sect133.html#sect1333"><i class="fa fa-check"></i><b>13.3.3</b> Limites de la classification ascendante hiérarchique</a></li>
<li class="chapter" data-level="13.3.4" data-path="sect133.html"><a href="sect133.html#sect1334"><i class="fa fa-check"></i><b>13.3.4</b> Mise en oeuvre dans R</a></li>
</ul></li>
<li class="chapter" data-level="13.4" data-path="sect134.html"><a href="sect134.html"><i class="fa fa-check"></i><b>13.4</b> Nuées dynamiques</a>
<ul>
<li class="chapter" data-level="13.4.1" data-path="sect134.html"><a href="sect134.html#sect1341"><i class="fa fa-check"></i><b>13.4.1</b> <em>K-means</em></a></li>
<li class="chapter" data-level="13.4.2" data-path="sect134.html"><a href="sect134.html#sect1342"><i class="fa fa-check"></i><b>13.4.2</b> K-médianes</a></li>
<li class="chapter" data-level="13.4.3" data-path="sect134.html"><a href="sect134.html#sect1343"><i class="fa fa-check"></i><b>13.4.3</b> K-médoïds</a></li>
<li class="chapter" data-level="13.4.4" data-path="sect134.html"><a href="sect134.html#sect1344"><i class="fa fa-check"></i><b>13.4.4</b> Mise en oeuvre dans R</a></li>
<li class="chapter" data-level="13.4.5" data-path="sect134.html"><a href="sect134.html#sect1346"><i class="fa fa-check"></i><b>13.4.5</b> Extensions en logique floue : <em>c-means</em>, <em>c-medoids</em></a></li>
</ul></li>
<li class="chapter" data-level="13.5" data-path="sect135.html"><a href="sect135.html"><i class="fa fa-check"></i><b>13.5</b> Conclusion sur la cinquième partie</a></li>
<li class="chapter" data-level="13.6" data-path="sect136.html"><a href="sect136.html"><i class="fa fa-check"></i><b>13.6</b> Quiz de révision du chapitre</a></li>
</ul></li>
<li class="part"><span><b>VI Annexes</b></span></li>
<li class="chapter" data-level="14" data-path="annexe1.html"><a href="annexe1.html"><i class="fa fa-check"></i><b>14</b> Table des valeurs critiques de khi-deux</a></li>
<li class="chapter" data-level="15" data-path="annexe2.html"><a href="annexe2.html"><i class="fa fa-check"></i><b>15</b> Table des valeurs critiques de Fisher</a></li>
<li class="chapter" data-level="16" data-path="annexe3.html"><a href="annexe3.html"><i class="fa fa-check"></i><b>16</b> Table des valeurs critiques de <em>t</em></a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Méthodes quantitatives en sciences sociales : un grand bol d’R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="sect061" class="section level2 hasAnchor" number="6.1">
<h2><span class="header-section-number">6.1</span> Relation entre une variable quantitative et une variable qualitative à deux modalités<a href="sect061.html#sect061" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="bloc_objectif">
<p><strong>Les moyennes de deux groupes de population sont-elles significativement différentes?</strong> Nous souhaitons ici comparer deux groupes de population en fonction d’une variable continue.
Par exemple, pour deux échantillons respectivement d’hommes et de femmes travaillant dans le même secteur d’activité, nous pourrions souhaiter vérifier si les moyennes des salaires des hommes et des femmes sont différentes et ainsi vérifier la présence ou l’absence d’une iniquité systématique. En études urbaines, dans le cadre d’une étude sur un espace public, nous pourrions vouloir vérifier si la différence des moyennes du sentiment de sécurité des femmes et des hommes est significative (c’est-à-dire différente de 0).</p>
<p><strong>Pour un même groupe, la moyenne de la différence d’un phénomène donné mesuré à deux moments est-elle ou non égale à zéro?</strong> Autrement dit, nous cherchons à comparer un même groupe d’individus avant et après une expérimentation ou dans deux contextes différents. Prenons un exemple d’application en études urbaines. Dans le cadre d’une étude sur la perception des risques associés à la pratique du vélo en ville, 50 personnes utilisant habituellement l’automobile pour se rendre au travail sont recrutées. L’expérimentation pourrait consister à leur donner une formation sur la pratique du vélo en ville et à les accompagner quelques jours durant leurs déplacements domicile-travail. Nous évaluerons la différence de leurs perceptions des risques associés à la pratique du vélo sur une échelle de 0 à 100 avant et après l’expérimentation. Nous pourrions supposer que la moyenne des différences est significativement négative, ce qui indiquerait que la perception du risque a diminué après l’expérimentation; autrement dit, la perception du risque serait plus faible en fin de période.</p>
</div>
<div id="sect0611" class="section level3 hasAnchor" number="6.1.1">
<h3><span class="header-section-number">6.1.1</span> Test <em>t</em> et ses différentes variantes<a href="sect061.html#sect0611" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Le <strong>t de Student</strong>, appelé aussi <strong>test <em>t</em></strong> (<em>t-test</em> en anglais), est un test paramétrique permettant de comparer les moyennes de deux groupes (échantillons), qui peuvent être indépendantes ou non :</p>
<ul>
<li><p><strong>Échantillons indépendants (dits non appariés)</strong> : les observations de deux groupes qui n’ont aucun lien entre eux. Par exemple, nous souhaitons vérifier si les moyennes du sentiment de sécurité des hommes et des femmes, ou encore si, les moyennes des loyers entre deux villes sont statistiquement différentes. Ainsi, les tailles des deux échantillons peuvent être différentes (<span class="math inline">\(n_a \neq n_b\)</span>).</p></li>
<li><p><strong>Échantillons dépendants (dits appariés)</strong> : les individus des deux groupes sont les mêmes et sont donc associés par paires. Autrement dit, nous avons deux séries de valeurs de taille identique <span class="math inline">\(n_a = n_b\)</span> et <span class="math inline">\(n_{ai}\)</span> est le même individu que <span class="math inline">\(n_{bi}\)</span>. Ce type d’analyse est souvent utilisée en études cliniques : pour <span class="math inline">\(n\)</span> individus, nous disposons d’une mesure quantitative de leur état de santé pour deux séries (l’une avant le traitement, l’autre une fois le traitement terminé). Cela permet de comparer les mêmes individus avant et après un traitement; nous parlons alors d’étude, d’expérience ou d’analyse pré-post. Concrètement, nous cherchons à savoir si la moyenne des différences des observations avant et après est significativement différente de 0. Si c’est le cas, nous pouvons conclure que l’expérimentation a eu un impact sur le phénomène mesuré (variable continue). Ce type d’analyse pré-post peut aussi être utilisé pour évaluer l’impact du réaménagement d’un espace public (rue commerciale, place publique, parc, etc.). Par exemple, nous pourrions questionner le même échantillon de commerçant(e)s ou personnes l’utilisant avant et après le réaménagement d’une artère commerciale.</p></li>
</ul>
<p><strong>Condition d’application</strong>. Pour utiliser les tests de Student et de Welch, la variable continue doit être normalement distribuée. Si elle est fortement anormale, nous utiliserons le test non paramétrique de Wilcoxon (section <a href="sect061.html#sect0612">6.1.2</a>). Il existe trois principaux tests pour comparer les moyennes de deux groupes :</p>
<ul>
<li>Test de Student (test <em>t</em>) avec échantillons indépendants et variances similaires (méthode <em>pooled</em>). Les variances de deux groupes sont semblables quand leur ratio varie de 0,5 à 2, soit <span class="math inline">\(\mbox{0,5}&lt; (S^2_{X_A}/S^2_{X_B})&lt;\mbox{2}\)</span>.</li>
<li>Test de Welch (appelé aussi Satterthwaite) avec échantillons indépendants quand les variances des deux groupes sont dissemblables.</li>
<li>Test de Student (test <em>t</em>) avec échantillons dépendants.</li>
</ul>
<p>Il s’agit de vérifier si les moyennes des deux groupes sont statistiquement différentes avec les étapes suivantes :</p>
<ul>
<li>Nous posons l’hypothèse nulle (<em>H<sub>0</sub></em>), soit que les moyennes des deux groupes <em>A</em> et <em>B</em> ne sont pas différentes (<span class="math inline">\(\bar{X}_{A}=\bar{X}_{B}\)</span>) ou, autrement dit, la différence des deux moyennes est nulle (<span class="math inline">\(\bar{X}_{A}-\bar{X}_{B}=0\)</span>). L’hypothèse alternative (<em>H<sub>1</sub></em>) est donc <span class="math inline">\(\bar{X}_{A}\ne\bar{X}_{B}\)</span>.</li>
<li>Nous calculons la valeur de <em>t</em> et le nombre de degrés de liberté. La valeur de <em>t</em> est négative quand la moyenne du groupe A est inférieure au groupe B et inversement.</li>
<li>Nous comparons la valeur absolue de <em>t</em> (<span class="math inline">\(\mbox{|t|}\)</span>) avec celle issue de la table des valeurs critiques de T (voir section <a href="annexe2.html#annexe2">15</a>) avec le bon nombre de degrés de liberté et en choisissant un degré de signification (habituellement, <em>p</em> = 0,05). Si <span class="math inline">\(\mbox{|t|}\)</span> est supérieure à la valeur <em>t</em> critique, alors les moyennes sont statistiquement différentes au degré de signification retenu.</li>
<li>Si les moyennes sont statistiquement différentes, nous pouvons calculer la taille de l’effet.</li>
</ul>
<p><strong>Cas 1. Test de Student pour des échantillons indépendants avec des variances similaires (méthode <em>pooled</em>).</strong> La valeur de <em>t</em> est le ratio entre la différence des moyennes des deux groupes (numérateur) et l’erreur type groupée des deux échantillons (dénominateur) :</p>
<p><span class="math display" id="eq:cas1pooled">\[\begin{equation}
t = \frac{\bar{X}_{A}-\bar{X}_{B}}{\sqrt{\frac{S^2_p}{n_A}+\frac{S^2_p}{n_B}}}\mbox{ avec } S^2_p = \frac{(n_A-1)S^2_{X_A}+(n_B-1)S^2_{X_B}}{n_A+n_B-2}
\tag{6.1}
\end{equation}\]</span>
</p>
<p>avec <span class="math inline">\(n_A\)</span>,<span class="math inline">\(n_B\)</span>, <span class="math inline">\(S^2_{X_A}\)</span> et <span class="math inline">\(S^2_{X_B}\)</span> étant respectivement les nombres d’observations et les variances pour les groupes <em>A</em> et <em>B</em>, <span class="math inline">\(S^2_p\)</span> étant la variance groupée des deux échantillons et <span class="math inline">\(n_A+n_B-2\)</span> étant le nombre de degrés de liberté.</p>
<p><strong>Cas 2. Test de Welch pour des échantillons indépendants (avec variances dissemblables).</strong> Le test de Welch est très similaire au test de Student; seul le calcul de la valeur de <em>t</em> est différent, pour tenir compte des variances respectives des groupes :</p>
<p><span class="math display" id="eq:cas2welch">\[\begin{equation}
t = \frac{\bar{X}_{A}-\bar{X}_{B}}{\sqrt{\frac{S^2_{X_A}}{n_A}+\frac{S^2_{X_B}}{n_B}}} \mbox{ et } dl = \frac{ \left( \frac{S^2_{X_A}}{n_A}+\frac{S^2_{X_B}}{n_B} \right)^2} {\frac{S^4_{X_A}}{n^2_A(n_A-1)}+\frac{S^4_{X_B}}{n^2_B(n_B-1)}}
\tag{6.2}
\end{equation}\]</span>
</p>
<p>Dans la syntaxe ci-dessous, nous avons écrit une fonction dénommée <code>test_independants</code> permettant de calculer les deux tests pour des échantillons indépendants. Dans cette fonction, vous pouvez repérer comment sont calculés les moyennes, les nombres d’observations et les variances pour les deux groupes, le nombre de degrés de liberté et les valeurs de <em>t</em> et de <em>p</em> pour les deux tests. Puis, nous avons créé aléatoirement deux jeux de données relativement à la vitesse de déplacement de cyclistes utilisant un vélo personnel ou un vélo en libre-service (généralement plus lourd) :</p>
<ul>
<li><p>Au cas 1, 60 cyclistes utilisant un vélo personnel roulant en moyenne à 18 km/h (écart-type de 1,5) et 50 autres utilisant un système de vélopartage avec une vitesse moyenne de 15 km/h (écart-type de 1,5).</p></li>
<li><p>Au cas 2, 60 cyclistes utilisant un vélo personnel roulant en moyenne à 16 km/h (écart-type de 3) et 50 autres utilisant un système de vélopartage avec une vitesse moyenne de 15 km/h (écart-type de 1,5). Ce faible écart des moyennes, combiné à une plus forte variance réduit la significativité de la différence entre les deux groupes.</p></li>
</ul>
<p>D’emblée, l’analyse visuelle des boîtes à moustaches (figure <a href="sect061.html#fig:figttest1">6.1</a>) signale qu’au cas 1, contrairement au cas 2, les groupes sont plus homogènes (boîtes plus compactes) et les moyennes semblent différentes (les boîtes sont centrées différemment sur l’axe des ordonnées). Cela est confirmé par les résultats des tests.</p>
<div class="sourceCode" id="cb547"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb547-1"><a href="sect061.html#cb547-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;ggplot2&quot;</span>)</span>
<span id="cb547-2"><a href="sect061.html#cb547-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;ggpubr&quot;</span>)</span>
<span id="cb547-3"><a href="sect061.html#cb547-3" aria-hidden="true" tabindex="-1"></a><span class="co"># fonction ------------------</span></span>
<span id="cb547-4"><a href="sect061.html#cb547-4" aria-hidden="true" tabindex="-1"></a>tstudent_independants <span class="ot">&lt;-</span> <span class="cf">function</span>(A, B){</span>
<span id="cb547-5"><a href="sect061.html#cb547-5" aria-hidden="true" tabindex="-1"></a>    x_a <span class="ot">&lt;-</span> <span class="fu">mean</span>(A)           <span class="co"># Moyenne du groupe A</span></span>
<span id="cb547-6"><a href="sect061.html#cb547-6" aria-hidden="true" tabindex="-1"></a>    x_b <span class="ot">&lt;-</span> <span class="fu">mean</span>(B)           <span class="co"># Moyenne du groupe B</span></span>
<span id="cb547-7"><a href="sect061.html#cb547-7" aria-hidden="true" tabindex="-1"></a>    var_a <span class="ot">&lt;-</span> <span class="fu">var</span>(A)          <span class="co"># Variance du groupe A</span></span>
<span id="cb547-8"><a href="sect061.html#cb547-8" aria-hidden="true" tabindex="-1"></a>    var_b <span class="ot">&lt;-</span> <span class="fu">var</span>(B)          <span class="co"># Variance du groupe B</span></span>
<span id="cb547-9"><a href="sect061.html#cb547-9" aria-hidden="true" tabindex="-1"></a>    sd_a <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(var_a)      <span class="co"># Écart-type du groupe A</span></span>
<span id="cb547-10"><a href="sect061.html#cb547-10" aria-hidden="true" tabindex="-1"></a>    sd_b <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(var_b)      <span class="co"># Écart-type du groupe B</span></span>
<span id="cb547-11"><a href="sect061.html#cb547-11" aria-hidden="true" tabindex="-1"></a>    ratio_v <span class="ot">&lt;-</span> var_a <span class="sc">/</span> var_b <span class="co"># ratio des variances</span></span>
<span id="cb547-12"><a href="sect061.html#cb547-12" aria-hidden="true" tabindex="-1"></a>    n_a <span class="ot">&lt;-</span> <span class="fu">length</span>(A)         <span class="co"># nombre d&#39;observation du groupe A</span></span>
<span id="cb547-13"><a href="sect061.html#cb547-13" aria-hidden="true" tabindex="-1"></a>    n_b <span class="ot">&lt;-</span> <span class="fu">length</span>(B)         <span class="co"># nombre d&#39;observation du groupe B</span></span>
<span id="cb547-14"><a href="sect061.html#cb547-14" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb547-15"><a href="sect061.html#cb547-15" aria-hidden="true" tabindex="-1"></a>    <span class="co"># T-test (variances égales)</span></span>
<span id="cb547-16"><a href="sect061.html#cb547-16" aria-hidden="true" tabindex="-1"></a>    dl_test <span class="ot">&lt;-</span> n_a<span class="sc">+</span>n_b<span class="dv">-2</span>       <span class="co"># degrés de liberté</span></span>
<span id="cb547-17"><a href="sect061.html#cb547-17" aria-hidden="true" tabindex="-1"></a>    PooledVar <span class="ot">&lt;-</span> (((n_a<span class="dv">-1</span>)<span class="sc">*</span>var_a)<span class="sc">+</span>((n_b<span class="dv">-1</span>)<span class="sc">*</span>var_b))<span class="sc">/</span>dl_test</span>
<span id="cb547-18"><a href="sect061.html#cb547-18" aria-hidden="true" tabindex="-1"></a>    t_test <span class="ot">&lt;-</span> (x_a<span class="sc">-</span>x_b) <span class="sc">/</span> <span class="fu">sqrt</span>(((PooledVar<span class="sc">/</span>n_a)<span class="sc">+</span>(PooledVar<span class="sc">/</span>n_b)))</span>
<span id="cb547-19"><a href="sect061.html#cb547-19" aria-hidden="true" tabindex="-1"></a>    p_test <span class="ot">&lt;-</span>  <span class="dv">2</span><span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>(<span class="fu">pt</span>(<span class="fu">abs</span>(t_test), dl_test)))     </span>
<span id="cb547-20"><a href="sect061.html#cb547-20" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Test Welch-Sattherwaite (variances inégales)</span></span>
<span id="cb547-21"><a href="sect061.html#cb547-21" aria-hidden="true" tabindex="-1"></a>    t_welch <span class="ot">&lt;-</span> (x_a<span class="sc">-</span>x_b) <span class="sc">/</span> <span class="fu">sqrt</span>( (var_a<span class="sc">/</span>n_a) <span class="sc">+</span> (var_b<span class="sc">/</span>n_b))</span>
<span id="cb547-22"><a href="sect061.html#cb547-22" aria-hidden="true" tabindex="-1"></a>    dl_num <span class="ot">=</span> ((var_a<span class="sc">/</span>n_a) <span class="sc">+</span> (var_b<span class="sc">/</span>n_b))<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb547-23"><a href="sect061.html#cb547-23" aria-hidden="true" tabindex="-1"></a>    dl_dem <span class="ot">=</span> ((var_a<span class="sc">/</span>n_a)<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>(n_a<span class="dv">-1</span>))  <span class="sc">+</span> ((var_b<span class="sc">/</span>n_b)<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>(n_b<span class="dv">-1</span>))</span>
<span id="cb547-24"><a href="sect061.html#cb547-24" aria-hidden="true" tabindex="-1"></a>    dl_welch <span class="ot">=</span> dl_num <span class="sc">/</span> dl_dem <span class="co"># degrés de liberté</span></span>
<span id="cb547-25"><a href="sect061.html#cb547-25" aria-hidden="true" tabindex="-1"></a>    p_welch <span class="ot">&lt;-</span> <span class="dv">2</span><span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>(<span class="fu">pt</span>(<span class="fu">abs</span>(t_welch), dl_welch)))     </span>
<span id="cb547-26"><a href="sect061.html#cb547-26" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb547-27"><a href="sect061.html#cb547-27" aria-hidden="true" tabindex="-1"></a>    <span class="fu">cat</span>(<span class="st">&quot;</span><span class="sc">\n</span><span class="st"> groupe A (n = &quot;</span>, n_a,<span class="st">&quot;), moy = &quot;</span>, <span class="fu">round</span>(x_a,<span class="dv">1</span>),<span class="st">&quot;, </span></span>
<span id="cb547-28"><a href="sect061.html#cb547-28" aria-hidden="true" tabindex="-1"></a><span class="st">           variance = &quot;</span>, <span class="fu">round</span>(var_a,<span class="dv">1</span>),<span class="st">&quot;, écart-type = &quot;</span>, <span class="fu">round</span>(sd_a,<span class="dv">1</span>),</span>
<span id="cb547-29"><a href="sect061.html#cb547-29" aria-hidden="true" tabindex="-1"></a>        <span class="st">&quot;</span><span class="sc">\n</span><span class="st"> groupe B (n = &quot;</span>, n_b,<span class="st">&quot;), moy = &quot;</span>, <span class="fu">round</span>(x_b,<span class="dv">1</span>),<span class="st">&quot;, </span></span>
<span id="cb547-30"><a href="sect061.html#cb547-30" aria-hidden="true" tabindex="-1"></a><span class="st">          variance = &quot;</span>, <span class="fu">round</span>(var_b,<span class="dv">1</span>),<span class="st">&quot;, écart-type = &quot;</span>, <span class="fu">round</span>(sd_b,<span class="dv">1</span>),</span>
<span id="cb547-31"><a href="sect061.html#cb547-31" aria-hidden="true" tabindex="-1"></a>        <span class="st">&quot;</span><span class="sc">\n</span><span class="st"> ratio variance = &quot;</span>,<span class="fu">round</span>(ratio_v,<span class="dv">2</span>),</span>
<span id="cb547-32"><a href="sect061.html#cb547-32" aria-hidden="true" tabindex="-1"></a>        <span class="st">&quot;</span><span class="sc">\n</span><span class="st"> t-test (variances égales): t(dl = &quot;</span>, dl_test, <span class="st">&quot;) = &quot;</span>,<span class="fu">round</span>(t_test,<span class="dv">4</span>),</span>
<span id="cb547-33"><a href="sect061.html#cb547-33" aria-hidden="true" tabindex="-1"></a>         <span class="st">&quot;, p = &quot;</span>, <span class="fu">round</span>(p_test,<span class="dv">6</span>),</span>
<span id="cb547-34"><a href="sect061.html#cb547-34" aria-hidden="true" tabindex="-1"></a>         <span class="st">&quot;</span><span class="sc">\n</span><span class="st"> t-Welch (variances inégales): t(dl = &quot;</span>, <span class="fu">round</span>(dl_welch,<span class="dv">3</span>), <span class="st">&quot;) = &quot;</span>,</span>
<span id="cb547-35"><a href="sect061.html#cb547-35" aria-hidden="true" tabindex="-1"></a>        <span class="fu">round</span>(t_welch,<span class="dv">4</span>), <span class="st">&quot;, p = &quot;</span>, <span class="fu">round</span>(p_welch,<span class="dv">6</span>),  <span class="at">sep=</span><span class="st">&quot;&quot;</span>)    </span>
<span id="cb547-36"><a href="sect061.html#cb547-36" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb547-37"><a href="sect061.html#cb547-37" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (ratio_v <span class="sc">&gt;</span> <span class="fl">0.5</span> <span class="sc">&amp;&amp;</span> ratio_v <span class="sc">&lt;</span> <span class="dv">2</span>)  {</span>
<span id="cb547-38"><a href="sect061.html#cb547-38" aria-hidden="true" tabindex="-1"></a>      <span class="fu">cat</span>(<span class="st">&quot;</span><span class="sc">\n</span><span class="st"> Variances semblables. Utilisez le test de Student!&quot;</span>)</span>
<span id="cb547-39"><a href="sect061.html#cb547-39" aria-hidden="true" tabindex="-1"></a>      p <span class="ot">&lt;-</span> p_test</span>
<span id="cb547-40"><a href="sect061.html#cb547-40" aria-hidden="true" tabindex="-1"></a>    } <span class="cf">else</span> {</span>
<span id="cb547-41"><a href="sect061.html#cb547-41" aria-hidden="true" tabindex="-1"></a>      <span class="fu">cat</span>(<span class="st">&quot;</span><span class="sc">\n</span><span class="st"> Variances dissemblables. Utilisez le test de Welch-Satterwaithe!&quot;</span>)</span>
<span id="cb547-42"><a href="sect061.html#cb547-42" aria-hidden="true" tabindex="-1"></a>      p <span class="ot">&lt;-</span> p_welch</span>
<span id="cb547-43"><a href="sect061.html#cb547-43" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb547-44"><a href="sect061.html#cb547-44" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb547-45"><a href="sect061.html#cb547-45" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (p <span class="sc">&lt;=</span>.<span class="dv">05</span>){</span>
<span id="cb547-46"><a href="sect061.html#cb547-46" aria-hidden="true" tabindex="-1"></a>      <span class="fu">cat</span>(<span class="st">&quot;</span><span class="sc">\n</span><span class="st"> Les moyennes des deux groupes sont significativement différentes.&quot;</span>)</span>
<span id="cb547-47"><a href="sect061.html#cb547-47" aria-hidden="true" tabindex="-1"></a>    } <span class="cf">else</span> {</span>
<span id="cb547-48"><a href="sect061.html#cb547-48" aria-hidden="true" tabindex="-1"></a>      <span class="fu">cat</span>(<span class="st">&quot;</span><span class="sc">\n</span><span class="st"> Les moyennes des deux groupes ne sont pas significativement différentes.&quot;</span>)</span>
<span id="cb547-49"><a href="sect061.html#cb547-49" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb547-50"><a href="sect061.html#cb547-50" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb547-51"><a href="sect061.html#cb547-51" aria-hidden="true" tabindex="-1"></a><span class="co"># CAS 1 : données fictives ------------------</span></span>
<span id="cb547-52"><a href="sect061.html#cb547-52" aria-hidden="true" tabindex="-1"></a><span class="co"># Création du groupe A : 60 observations avec une vitesse moyenne de 18 et un écart-type de 1,5</span></span>
<span id="cb547-53"><a href="sect061.html#cb547-53" aria-hidden="true" tabindex="-1"></a>Velo1A <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">60</span>,<span class="dv">18</span>,<span class="fl">1.5</span>)</span>
<span id="cb547-54"><a href="sect061.html#cb547-54" aria-hidden="true" tabindex="-1"></a><span class="co"># Création du groupe B : 50 observations avec une vitesse moyenne de 15 et un écart-type de 1,5</span></span>
<span id="cb547-55"><a href="sect061.html#cb547-55" aria-hidden="true" tabindex="-1"></a>Velo1B <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">50</span>,<span class="dv">15</span>,<span class="fl">1.5</span>)</span>
<span id="cb547-56"><a href="sect061.html#cb547-56" aria-hidden="true" tabindex="-1"></a>df1 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb547-57"><a href="sect061.html#cb547-57" aria-hidden="true" tabindex="-1"></a>  <span class="at">vitesse =</span> <span class="fu">c</span>(Velo1A,Velo1B), </span>
<span id="cb547-58"><a href="sect061.html#cb547-58" aria-hidden="true" tabindex="-1"></a>  <span class="at">type =</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">&quot;Vélo personnel&quot;</span>,<span class="fu">length</span>(Velo1A)), <span class="fu">rep</span>(<span class="st">&quot;Vélopartage&quot;</span>,<span class="fu">length</span>(Velo1B)))</span>
<span id="cb547-59"><a href="sect061.html#cb547-59" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb547-60"><a href="sect061.html#cb547-60" aria-hidden="true" tabindex="-1"></a>boxplot1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>df1, <span class="at">mapping=</span><span class="fu">aes</span>(<span class="at">x=</span>type,<span class="at">y=</span>vitesse, <span class="at">colour=</span>type)) <span class="sc">+</span></span>
<span id="cb547-61"><a href="sect061.html#cb547-61" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">width=</span><span class="fl">0.2</span>)<span class="sc">+</span></span>
<span id="cb547-62"><a href="sect061.html#cb547-62" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Données fictives (cas 1)&quot;</span>)<span class="sc">+</span></span>
<span id="cb547-63"><a href="sect061.html#cb547-63" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Type de vélo&quot;</span>)<span class="sc">+</span></span>
<span id="cb547-64"><a href="sect061.html#cb547-64" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Vitesse de déplacement (km/h)&quot;</span>)<span class="sc">+</span></span>
<span id="cb547-65"><a href="sect061.html#cb547-65" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;none&quot;</span>)</span>
<span id="cb547-66"><a href="sect061.html#cb547-66" aria-hidden="true" tabindex="-1"></a><span class="co"># CAS 2 : données fictives ------------------</span></span>
<span id="cb547-67"><a href="sect061.html#cb547-67" aria-hidden="true" tabindex="-1"></a><span class="co"># Création du groupe A : 60 observations avec une vitesse moyenne de 18 et un écart-type de 3</span></span>
<span id="cb547-68"><a href="sect061.html#cb547-68" aria-hidden="true" tabindex="-1"></a>Velo2A <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">60</span>,<span class="dv">16</span>,<span class="dv">3</span>)</span>
<span id="cb547-69"><a href="sect061.html#cb547-69" aria-hidden="true" tabindex="-1"></a><span class="co"># Création du groupe B : 50 observations avec une vitesse moyenne de 15 et un écart-type de 1,5</span></span>
<span id="cb547-70"><a href="sect061.html#cb547-70" aria-hidden="true" tabindex="-1"></a>Velo2B <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">50</span>,<span class="dv">15</span>,<span class="fl">1.5</span>)</span>
<span id="cb547-71"><a href="sect061.html#cb547-71" aria-hidden="true" tabindex="-1"></a>df2 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb547-72"><a href="sect061.html#cb547-72" aria-hidden="true" tabindex="-1"></a>  <span class="at">vitesse =</span> <span class="fu">c</span>(Velo2A,Velo2B), </span>
<span id="cb547-73"><a href="sect061.html#cb547-73" aria-hidden="true" tabindex="-1"></a>  <span class="at">type =</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">&quot;Vélo personnel&quot;</span>,<span class="fu">length</span>(Velo2A)), <span class="fu">rep</span>(<span class="st">&quot;Vélopartage&quot;</span>,<span class="fu">length</span>(Velo2B)))</span>
<span id="cb547-74"><a href="sect061.html#cb547-74" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb547-75"><a href="sect061.html#cb547-75" aria-hidden="true" tabindex="-1"></a>boxplot2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>df2, <span class="at">mapping=</span><span class="fu">aes</span>(<span class="at">x=</span>type,<span class="at">y=</span>vitesse, <span class="at">colour=</span>type)) <span class="sc">+</span></span>
<span id="cb547-76"><a href="sect061.html#cb547-76" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">width=</span><span class="fl">0.2</span>)<span class="sc">+</span></span>
<span id="cb547-77"><a href="sect061.html#cb547-77" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Données fictives (cas 2)&quot;</span>)<span class="sc">+</span></span>
<span id="cb547-78"><a href="sect061.html#cb547-78" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Type de vélo&quot;</span>)<span class="sc">+</span></span>
<span id="cb547-79"><a href="sect061.html#cb547-79" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Vitesse de déplacement (km/h)&quot;</span>)<span class="sc">+</span></span>
<span id="cb547-80"><a href="sect061.html#cb547-80" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;none&quot;</span>)</span>
<span id="cb547-81"><a href="sect061.html#cb547-81" aria-hidden="true" tabindex="-1"></a><span class="fu">ggarrange</span>(boxplot1, boxplot2, <span class="at">ncol =</span> <span class="dv">2</span>, <span class="at">nrow =</span> <span class="dv">1</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:figttest1"></span>
<img src="MethodesQuantitScSocialesBolR_files/figure-html/figttest1-1.png" alt="Boîtes à moustaches sur des échantillons fictifs non appariés" width="75%" />
<p class="caption">
Figure 6.1: Boîtes à moustaches sur des échantillons fictifs non appariés
</p>
</div>
<div class="sourceCode" id="cb548"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb548-1"><a href="sect061.html#cb548-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Appel de la fonction pour le cas 1</span></span>
<span id="cb548-2"><a href="sect061.html#cb548-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tstudent_independants</span>(Velo1A, Velo1B)</span></code></pre></div>
<pre><code>## 
##  groupe A (n = 60), moy = 18.4, 
##            variance = 2.4, écart-type = 1.6
##  groupe B (n = 50), moy = 14.7, 
##           variance = 2.5, écart-type = 1.6
##  ratio variance = 0.95
##  t-test (variances égales): t(dl = 108) = 12.3343, p = 0
##  t-Welch (variances inégales): t(dl = 103.376) = 12.3034, p = 0
##  Variances semblables. Utilisez le test de Student!
##  Les moyennes des deux groupes sont significativement différentes.</code></pre>
<div class="sourceCode" id="cb550"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb550-1"><a href="sect061.html#cb550-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Appel de la fonction pour le cas 2</span></span>
<span id="cb550-2"><a href="sect061.html#cb550-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tstudent_independants</span>(Velo2A, Velo2B)</span></code></pre></div>
<pre><code>## 
##  groupe A (n = 60), moy = 15.3, 
##            variance = 7.4, écart-type = 2.7
##  groupe B (n = 50), moy = 15, 
##           variance = 2.5, écart-type = 1.6
##  ratio variance = 2.92
##  t-test (variances égales): t(dl = 108) = 0.7969, p = 0.427233
##  t-Welch (variances inégales): t(dl = 97.605) = 0.8336, p = 0.406549
##  Variances dissemblables. Utilisez le test de Welch-Satterwaithe!
##  Les moyennes des deux groupes ne sont pas significativement différentes.</code></pre>
<div id="sect06111" class="section level4 hasAnchor" number="6.1.1.1">
<h4><span class="header-section-number">6.1.1.1</span> Principe de base et formulation pour des échantillons dépendants (appariés)<a href="sect061.html#sect06111" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Nous disposons de plusieurs personnes pour lesquelles nous avons mesuré un phénomène (variable continue) à deux temps différents : généralement avant et après une expérimentation (analyse pré-post). Il s’agit de vérifier si la moyenne des différences des observations avant et après la période est différente de 0. Pour ce faire, nous réalisons les étapes suivantes :</p>
<ul>
<li>Nous posons l’hypothèse nulle (<em>H<sub>0</sub></em>), soit que la moyenne des différences entre les deux séries est égale à 0 (<span class="math inline">\(\bar{D} = 0\)</span> avec <span class="math inline">\(d = {x}_{t_1}- {x}_{t_2}\)</span>). L’hypothèse alternative (<em>H<sub>1</sub></em>) est donc <span class="math inline">\(\bar{D} \ne 0\)</span>. Notez que nous pouvons tester une autre valeur que 0.</li>
<li>Nous calculons la valeur de <em>t</em> et le nombre de degrés de liberté. La valeur de <em>t</em> est négative quand la moyenne des différences entre <span class="math inline">\({X}_{t_1}\)</span> et <span class="math inline">\({X}_{t_2}\)</span> est négative et inversement.</li>
<li>Nous comparons la valeur absolue de <em>t</em> (<span class="math inline">\(\mbox{|t|}\)</span>) avec celle issue de la table des valeurs critiques de T avec le nombre de degrés de liberté et en choisissant un degré de signification (habituellement, <em>p</em> = 0,05). Si <span class="math inline">\(\mbox{|t|}\)</span> est supérieure à la valeur <em>t</em> critique, alors les moyennes sont statistiquement différentes au degré de signification retenu.</li>
</ul>
<p>Pour le test de Student avec des échantillons appariés, la valeur de <em>t</em> se calcule comme suit :</p>
<p><span class="math display" id="eq:ttestapparie">\[\begin{equation}
t = \frac{\bar{D}-\mu_0}{\sigma_D / \sqrt{n}}
\tag{6.3}
\end{equation}\]</span>
</p>
<p>avec <span class="math inline">\(\bar{D}\)</span> étant la moyenne des différences entre les observations appariées de la série A et de la série B, <span class="math inline">\(\sigma_D\)</span> l’écart des différences, <em>n</em> le nombre d’observations, et finalement <span class="math inline">\(\mu_0\)</span> la valeur de l’hypothèse nulle que nous voulons tester (habituellement 0). Bien entendu, il est possible de fixer une autre valeur pour <span class="math inline">\(\mu_0\)</span> : par exemple, avec <span class="math inline">\(\mu_0 = 10\)</span>, nous chercherions ainsi à vérifier si la moyenne des différences est significativement différente de 10. Le nombre de degrés de liberté est égal à <span class="math inline">\(n-1\)</span>.</p>
<p>Dans la syntaxe ci-dessous, nous avons écrit une fonction dénommée <code>tstudent_dependants</code> permettant de réaliser le test de Student pour des échantillons appariés. Dans cette fonction, vous pouvez repérer comment sont calculés la différence entre les observations pairées, la moyenne et l’écart-type de cette différence, puis le nombre de degrés de liberté, les valeurs de <em>t</em> et de <em>p</em> pour les deux tests.</p>
<p>Pour illustrer l’utilisation de la fonction, nous avons créé aléatoirement deux jeux de données. Imaginons que ces données décrivent 50 personnes utilisant habituellement l’automobile pour se rendre au travail. Pour ces personnes, nous avons généré des valeurs du risque perçu de l’utilisation du vélo (de 0 à 100), et ce, avant et après une période de 20 jours ouvrables durant lesquels elles devaient impérativement se rendre au travail à vélo.</p>
<ul>
<li>Au cas 1, les valeurs de risque ont une moyenne de 70 avant l’expérimentation et de 50 après l’expérimentation, avec des écarts-types de 5.</li>
<li>Au cas 2, les valeurs de risque ont une moyenne de 70 avant et de 66 après, avec des écarts-types de 5.</li>
</ul>
<p>D’emblée, l’analyse visuelle des boîtes à moustaches (figure <a href="sect061.html#fig:figttest2">6.2</a>) pairées montre que la perception du risque semble avoir nettement diminué après l’expérimentation pour le cas 1, mais pas pour le cas 2. Cela est confirmé par les résultats des tests.</p>
<div class="sourceCode" id="cb552"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb552-1"><a href="sect061.html#cb552-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;ggplot2&quot;</span>)</span>
<span id="cb552-2"><a href="sect061.html#cb552-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;ggpubr&quot;</span>)</span>
<span id="cb552-3"><a href="sect061.html#cb552-3" aria-hidden="true" tabindex="-1"></a>tstudent_dependants <span class="ot">&lt;-</span> <span class="cf">function</span>(A, B, <span class="at">mu=</span><span class="dv">0</span>){</span>
<span id="cb552-4"><a href="sect061.html#cb552-4" aria-hidden="true" tabindex="-1"></a>  d <span class="ot">&lt;-</span> A<span class="sc">-</span>B           <span class="co"># différences entre les observations pairées</span></span>
<span id="cb552-5"><a href="sect061.html#cb552-5" aria-hidden="true" tabindex="-1"></a>  moy <span class="ot">&lt;-</span> <span class="fu">mean</span>(d)     <span class="co"># Moyenne des différences</span></span>
<span id="cb552-6"><a href="sect061.html#cb552-6" aria-hidden="true" tabindex="-1"></a>  e_t <span class="ot">&lt;-</span> <span class="fu">sd</span>(d)       <span class="co"># Écart-type des différences</span></span>
<span id="cb552-7"><a href="sect061.html#cb552-7" aria-hidden="true" tabindex="-1"></a>  n   <span class="ot">&lt;-</span> <span class="fu">length</span>(A)   <span class="co"># nombre d&#39;observations</span></span>
<span id="cb552-8"><a href="sect061.html#cb552-8" aria-hidden="true" tabindex="-1"></a>  dl  <span class="ot">&lt;-</span> n<span class="dv">-1</span>         <span class="co"># nombre de degrés de liberté (variances égales)</span></span>
<span id="cb552-9"><a href="sect061.html#cb552-9" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb552-10"><a href="sect061.html#cb552-10" aria-hidden="true" tabindex="-1"></a>  t <span class="ot">&lt;-</span> (moy<span class="sc">-</span> mu) <span class="sc">/</span> (e_t<span class="sc">/</span><span class="fu">sqrt</span>(n)) <span class="co"># valeur de t</span></span>
<span id="cb552-11"><a href="sect061.html#cb552-11" aria-hidden="true" tabindex="-1"></a>  p <span class="ot">&lt;-</span>  <span class="dv">2</span><span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>(<span class="fu">pt</span>(<span class="fu">abs</span>(t), dl)))</span>
<span id="cb552-12"><a href="sect061.html#cb552-12" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb552-13"><a href="sect061.html#cb552-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">&quot;</span><span class="sc">\n</span><span class="st"> groupe A : moy = &quot;</span>, <span class="fu">round</span>(<span class="fu">mean</span>(A),<span class="dv">1</span>),<span class="st">&quot;, var = &quot;</span>, </span>
<span id="cb552-14"><a href="sect061.html#cb552-14" aria-hidden="true" tabindex="-1"></a>         <span class="fu">round</span>(<span class="fu">var</span>(A),<span class="dv">1</span>),<span class="st">&quot;, sd = &quot;</span>, <span class="fu">round</span>(<span class="fu">sqrt</span>(<span class="fu">var</span>(A)),<span class="dv">1</span>),</span>
<span id="cb552-15"><a href="sect061.html#cb552-15" aria-hidden="true" tabindex="-1"></a>      <span class="st">&quot;</span><span class="sc">\n</span><span class="st"> groupe B : moy = &quot;</span>, <span class="fu">round</span>(<span class="fu">mean</span>(B),<span class="dv">1</span>),<span class="st">&quot;, var = &quot;</span>, </span>
<span id="cb552-16"><a href="sect061.html#cb552-16" aria-hidden="true" tabindex="-1"></a>         <span class="fu">round</span>(<span class="fu">var</span>(B),<span class="dv">1</span>),<span class="st">&quot;, sd = &quot;</span>, <span class="fu">round</span>(<span class="fu">sqrt</span>(<span class="fu">var</span>(B)),<span class="dv">1</span>),</span>
<span id="cb552-17"><a href="sect061.html#cb552-17" aria-hidden="true" tabindex="-1"></a>      <span class="st">&quot;</span><span class="sc">\n</span><span class="st"> Moyenne des différences = &quot;</span>, <span class="fu">round</span>(<span class="fu">mean</span>(moy),<span class="dv">1</span>),</span>
<span id="cb552-18"><a href="sect061.html#cb552-18" aria-hidden="true" tabindex="-1"></a>      <span class="st">&quot;</span><span class="sc">\n</span><span class="st"> Ecart-type des différences = &quot;</span>, <span class="fu">round</span>(<span class="fu">mean</span>(e_t),<span class="dv">1</span>),</span>
<span id="cb552-19"><a href="sect061.html#cb552-19" aria-hidden="true" tabindex="-1"></a>      <span class="st">&quot;</span><span class="sc">\n</span><span class="st"> t(dl = &quot;</span>, dl, <span class="st">&quot;) = &quot;</span>,<span class="fu">round</span>(t,<span class="dv">2</span>),</span>
<span id="cb552-20"><a href="sect061.html#cb552-20" aria-hidden="true" tabindex="-1"></a>      <span class="st">&quot;, p = &quot;</span>, <span class="fu">round</span>(p,<span class="dv">3</span>),  <span class="at">sep=</span><span class="st">&quot;&quot;</span>)</span>
<span id="cb552-21"><a href="sect061.html#cb552-21" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb552-22"><a href="sect061.html#cb552-22" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (p <span class="sc">&lt;=</span>.<span class="dv">05</span>){</span>
<span id="cb552-23"><a href="sect061.html#cb552-23" aria-hidden="true" tabindex="-1"></a>    <span class="fu">cat</span>(<span class="st">&quot;</span><span class="sc">\n</span><span class="st"> La moyenne des différences entre les échantillons est significative&quot;</span>)</span>
<span id="cb552-24"><a href="sect061.html#cb552-24" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb552-25"><a href="sect061.html#cb552-25" aria-hidden="true" tabindex="-1"></a>  <span class="cf">else</span>{</span>
<span id="cb552-26"><a href="sect061.html#cb552-26" aria-hidden="true" tabindex="-1"></a>    <span class="fu">cat</span>(<span class="st">&quot;</span><span class="sc">\n</span><span class="st"> La moyenne des différences entre les échantillons n&#39;est pas significative&quot;</span>)</span>
<span id="cb552-27"><a href="sect061.html#cb552-27" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb552-28"><a href="sect061.html#cb552-28" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb552-29"><a href="sect061.html#cb552-29" aria-hidden="true" tabindex="-1"></a><span class="co"># CAS 1 : données fictives ------------------</span></span>
<span id="cb552-30"><a href="sect061.html#cb552-30" aria-hidden="true" tabindex="-1"></a>Avant1 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">50</span>,<span class="dv">70</span>,<span class="dv">5</span>)</span>
<span id="cb552-31"><a href="sect061.html#cb552-31" aria-hidden="true" tabindex="-1"></a>Apres1 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">50</span>,<span class="dv">50</span>,<span class="dv">5</span>)</span>
<span id="cb552-32"><a href="sect061.html#cb552-32" aria-hidden="true" tabindex="-1"></a>df1 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Avant=</span>Avant1, <span class="at">Apres=</span>Apres1)</span>
<span id="cb552-33"><a href="sect061.html#cb552-33" aria-hidden="true" tabindex="-1"></a>boxplot1 <span class="ot">&lt;-</span> <span class="fu">ggpaired</span>(df1, <span class="at">cond1 =</span> <span class="st">&quot;Avant&quot;</span>, <span class="at">cond2 =</span> <span class="st">&quot;Apres&quot;</span>, <span class="at">fill =</span> <span class="st">&quot;condition&quot;</span>, </span>
<span id="cb552-34"><a href="sect061.html#cb552-34" aria-hidden="true" tabindex="-1"></a>                     <span class="at">palette =</span> <span class="st">&quot;jco&quot;</span>, </span>
<span id="cb552-35"><a href="sect061.html#cb552-35" aria-hidden="true" tabindex="-1"></a>                     <span class="at">xlab=</span><span class="st">&quot;&quot;</span>, <span class="at">ylab=</span><span class="st">&quot;Sentiment de sécurité&quot;</span>, </span>
<span id="cb552-36"><a href="sect061.html#cb552-36" aria-hidden="true" tabindex="-1"></a>                     <span class="at">title =</span> <span class="st">&quot;Données fictives (cas 1)&quot;</span>)</span>
<span id="cb552-37"><a href="sect061.html#cb552-37" aria-hidden="true" tabindex="-1"></a><span class="co"># CAS 2 : données fictives ------------------</span></span>
<span id="cb552-38"><a href="sect061.html#cb552-38" aria-hidden="true" tabindex="-1"></a>Avant2 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">50</span>,<span class="dv">70</span>,<span class="dv">5</span>)</span>
<span id="cb552-39"><a href="sect061.html#cb552-39" aria-hidden="true" tabindex="-1"></a>Apres2 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">50</span>,<span class="dv">66</span>,<span class="dv">5</span>)</span>
<span id="cb552-40"><a href="sect061.html#cb552-40" aria-hidden="true" tabindex="-1"></a>df2 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Avant=</span>Avant2, <span class="at">Apres=</span>Apres2)</span>
<span id="cb552-41"><a href="sect061.html#cb552-41" aria-hidden="true" tabindex="-1"></a>boxplot2 <span class="ot">&lt;-</span> <span class="fu">ggpaired</span>(df2, <span class="at">cond1 =</span> <span class="st">&quot;Avant&quot;</span>, <span class="at">cond2 =</span> <span class="st">&quot;Apres&quot;</span>, <span class="at">fill =</span> <span class="st">&quot;condition&quot;</span>,</span>
<span id="cb552-42"><a href="sect061.html#cb552-42" aria-hidden="true" tabindex="-1"></a>                     <span class="at">palette =</span> <span class="st">&quot;jco&quot;</span>, </span>
<span id="cb552-43"><a href="sect061.html#cb552-43" aria-hidden="true" tabindex="-1"></a>                     <span class="at">xlab=</span><span class="st">&quot;&quot;</span>, <span class="at">ylab=</span><span class="st">&quot;Sentiment de sécurité&quot;</span>, </span>
<span id="cb552-44"><a href="sect061.html#cb552-44" aria-hidden="true" tabindex="-1"></a>                     <span class="at">title =</span> <span class="st">&quot;Données fictives (cas 2)&quot;</span>)</span>
<span id="cb552-45"><a href="sect061.html#cb552-45" aria-hidden="true" tabindex="-1"></a><span class="fu">ggarrange</span>(boxplot1, boxplot2, <span class="at">ncol =</span> <span class="dv">2</span>, <span class="at">nrow =</span> <span class="dv">1</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:figttest2"></span>
<img src="MethodesQuantitScSocialesBolR_files/figure-html/figttest2-1.png" alt="Boites à moustaches sur des échantillons fictifs appariés" width="75%" />
<p class="caption">
Figure 6.2: Boites à moustaches sur des échantillons fictifs appariés
</p>
</div>
<div class="sourceCode" id="cb553"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb553-1"><a href="sect061.html#cb553-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Test t : appel de la fonction tstudent_dependants</span></span>
<span id="cb553-2"><a href="sect061.html#cb553-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tstudent_dependants</span>(Avant1, Apres1, <span class="at">mu=</span><span class="dv">0</span>)</span></code></pre></div>
<pre><code>## 
##  groupe A : moy = 68.9, var = 27.5, sd = 5.2
##  groupe B : moy = 49.4, var = 11.6, sd = 3.4
##  Moyenne des différences = 19.5
##  Ecart-type des différences = 6.3
##  t(dl = 49) = 21.76, p = 0
##  La moyenne des différences entre les échantillons est significative</code></pre>
<div class="sourceCode" id="cb555"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb555-1"><a href="sect061.html#cb555-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tstudent_dependants</span>(Avant2, Apres2, <span class="at">mu=</span><span class="dv">0</span>)</span></code></pre></div>
<pre><code>## 
##  groupe A : moy = 69.3, var = 28.5, sd = 5.3
##  groupe B : moy = 65.9, var = 37.6, sd = 6.1
##  Moyenne des différences = 3.3
##  Ecart-type des différences = 7.6
##  t(dl = 49) = 3.1, p = 0.003
##  La moyenne des différences entre les échantillons est significative</code></pre>
</div>
<div id="sect06112" class="section level4 hasAnchor" number="6.1.1.2">
<h4><span class="header-section-number">6.1.1.2</span> Mesure de la taille de l’effet<a href="sect061.html#sect06112" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>La taille de l’effet permet d’évaluer la magnitude (force) de l’effet d’une variable (ici la variable qualitative à deux modalités) sur une autre (ici la variable continue). Dans le cas d’une comparaison de moyennes (avec des échantillons pairés ou non), pour mesurer la taille de l’effet, nous utilisons habituellement le <em>d</em> de Cohen ou encore le <em>g</em> de Hedges; le second étant un ajustement du premier. Notez que nous analysons la taille de l’effet uniquement si le test de Student ou de Welch s’est révélé significatif (p &lt; 0,05).</p>
<p><strong>Pourquoi utiliser le <em>d</em> de Cohen?</strong> Deux propriétés en font une mesure particulièrement intéressante. Premièrement, elle est facile à calculer puisque <em>d</em> est le ratio entre la différence de deux moyennes de groupes (A, B) et l’écart-type combiné des deux groupes. Deuxièmement, <em>d</em> représente ainsi une mesure standardisée de la taille de l’effet; elle permet ainsi l’évaluation de la taille de l’effet indépendamment de l’unité de mesure de la variable continue. Concrètement, cela signifie que, quelle que soit l’unité de mesure de la variable continue <em>X</em>, <em>d</em> est toujours exprimée en unité d’écart-type de <em>X</em>. Cette propriété facilite ainsi grandement les comparaisons entre des valeurs de <em>d</em> calculées sur différentes combinaisons de variables (au même titre que le coefficient de variation ou le coefficient de corrélation, par exemple). Pour des échantillons indépendants de tailles différentes, le <em>d</em> de Cohen s’écrit :</p>
<p><span class="math display" id="eq:dcohen">\[\begin{equation}
\frac{\bar{X}_{A}-\bar{X}_{B}}{\sqrt{\frac{(n_A-1)S^2_A+(n_B-1)S^2_B}{n_A+n_B-2}}}
\tag{6.4}
\end{equation}\]</span>
</p>
<p>avec <span class="math inline">\(n_A\)</span>, <span class="math inline">\(n_B\)</span>, <span class="math inline">\(S^2_{X_A}\)</span> et <span class="math inline">\(S^2_{X_B}\)</span> étant respectivement les nombres d’observations et les variances pour les groupes <em>A</em> et <em>B</em>, <span class="math inline">\(S^2_p\)</span>.</p>
<p>Si les échantillons sont de tailles identiques (<span class="math inline">\(n_A=n_B\)</span>), alors <em>d</em> s’écrit :</p>
<p><span class="math display" id="eq:dcohen2">\[\begin{equation}
d = \frac{\bar{X}_{A}-\bar{X}_{B}}{\sqrt{(S^2_A+\S^2_B)/2}} = \frac{\bar{X}_{A}-\bar{X}_{B}}{(\sigma_A+\sigma_B)/2}
\tag{6.5}
\end{equation}\]</span>
</p>
<p>avec <span class="math inline">\(\sigma_A\)</span> et <span class="math inline">\(\sigma_B\)</span> étant les écarts-types des deux groupes (rappel : l’écart-type est la racine carrée de la variance).</p>
<p>Le <em>g</em> de Hedge est simplement une correction de <em>d</em>, particulièrement importante quand les échantillons sont de taille réduite.</p>
<p><span class="math display" id="eq:ghedge">\[\begin{equation}
g = d- \left(1- \frac{3}{4(n_A+n_B)-9} \right)
\tag{6.6}
\end{equation}\]</span>
</p>
<p>Moins utilisé en sciences sociales, mais surtout en études cliniques, le delta de Glass est simplement la différence des moyennes des deux groupes indépendants (numérateur) sur l’écart-type du deuxième groupe (démoninateur). Dans une étude clinique, nous avons habituellement un groupe qui subit un traitement (groupe de traitement) et un groupe qui reçoit un placebo (groupe de contrôle ou groupe témoin). L’effet de taille est ainsi évalué par rapport au groupe de contrôle :</p>
<p><span class="math display" id="eq:dDelta">\[\begin{equation}
\Delta = \frac{\bar{X}_{A}-\bar{X}_{B}}{\sigma_B}
\tag{6.7}
\end{equation}\]</span>
</p>
<p>Finalement, pour des échantillons dépendants (pairés), le delta de Glass s’écrit : <span class="math inline">\(d = \bar{D}/{\sigma_D}\)</span> avec <span class="math inline">\(\bar{D}\)</span> et <span class="math inline">\(\sigma_D\)</span> étant la moyenne et l’écart-type des différences entre les observations.</p>
<p><strong>Comment interpréter le <em>d</em> de Cohen?</strong> Un effet est considéré comme faible avec <span class="math inline">\(\lvert d \rvert\)</span> à 0,2, modéré à 0,50 et fort à 0,80 <span class="citation">(<a href="#ref-cohen1992" role="doc-biblioref">Cohen 1992</a>)</span>. Notez que ces seuils ne sont que des conventions pour vous guider à interpréter la mesure de Cohen. D’ailleurs, dans son livre intitulé <em>Statistical power analysis for the behavioral sciences</em>, il écrit : « all conventions are arbitrary. One can only demand of them that they not be unreasonable » <span class="citation">(<a href="#ref-cohen2013" role="doc-biblioref">Cohen 2013</a>)</span>. Plus récemment, Sawilowsky <span class="citation">(<a href="#ref-sawilowsky2009" role="doc-biblioref">2009</a>)</span> a ajouté d’autres seuils à ceux proposés par Cohen (tableau <a href="sect061.html#tab:tableconvcohen">6.1</a>).</p>
<table>
<caption>
<span id="tab:tableconvcohen">Tableau 6.1: </span>Conventions pour l’interprétation du <em>d</em> de Cohen
</caption>
<thead>
<tr>
<th style="text-align:left;">
Sawilowsky
</th>
<th style="text-align:left;">
Cohen
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
0,1 : Très faible
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
0,2 : Faible
</td>
<td style="text-align:left;">
0,2 : Faible
</td>
</tr>
<tr>
<td style="text-align:left;">
0,5 : Moyen
</td>
<td style="text-align:left;">
0,5 : Moyen
</td>
</tr>
<tr>
<td style="text-align:left;">
0,8 : Fort
</td>
<td style="text-align:left;">
0,8 : Fort
</td>
</tr>
<tr>
<td style="text-align:left;">
1,2 : Très fort
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
2,0 : Énorme
</td>
<td style="text-align:left;">
</td>
</tr>
</tbody>
</table>
</div>
<div id="sect06113" class="section level4 hasAnchor" number="6.1.1.3">
<h4><span class="header-section-number">6.1.1.3</span> Mise en œuvre dans R<a href="sect061.html#sect06113" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Nous avons écrit précédemment les fonctions <code>tstudent_independants</code> et <code>tstudent_dependants</code> uniquement pour décomposer les différentes étapes de calcul des tests de Student et de Welch. Heureusement, il existe des fonctions de base (<code>t.test</code> et <code>var.test</code>) qui permettent de réaliser l’un ou l’autre de ces deux tests avec une seule ligne de code.</p>
<p>La fonction <code>t.test</code> permet ainsi de calculer les tests de Student et de Welch :</p>
<ul>
<li><code>t.test(x ~ y, data=, mu = 0, paired = FALSE, var.equal = FALSE,  conf.level = 0.95)</code> ou <code>t.test(x =, y =, mu = 0, paired = FALSE, var.equal = FALSE,  conf.level = 0.95)</code>.</li>
<li>Le paramètre <code>paired</code> est utilisé pour spécifier si les échantillons sont dépendants (<code>paired=TRUE</code>) ou indépendants (<code>paired=FALSE</code>).</li>
<li>Le paramètre <code>var.equal</code> est utilisé pour spécifier si les variances sont égales pour le test de Student (<code>var.equal=TRUE</code>) ou dissemblables pour le test de Welch (<code>var.equal=FALSE</code>).</li>
<li><code>var.test(x, y)</code> ou <code>var.test(x ~ y, data=)</code> pour vérifier au préalable si les variances sont égales ou non et choisir ainsi un <em>t</em> de Student ou un <em>t</em> de Welch.</li>
</ul>
<p>Les fonctions <code>cohens_d</code> et <code>hedges_g</code> du <em>package</em> <code>effectsize</code> renvoient respectivement les mesures de <em>d</em> de Cohen et du <em>g</em> de Hedge :</p>
<ul>
<li><p><code>cohens_d(x ~ y, data = DataFrame, paired = FALSE, pooled_sd = TRUE)</code> ou <code>cohens_d(x, y, data = DataFrame, paired = FALSE, pooled_sd = TRUE)</code></p></li>
<li><p><code>hedges_g(x ~ y, data = DataFrame, paired = FALSE, pooled_sd = TRUE)</code> ou <code>hedges_g(x, y, data = DataFrame, paired = FALSE, pooled_sd = TRUE)</code></p></li>
<li><p><code>glass_delta(x ~ y, data = DataFrame, paired = FALSE, pooled_sd = TRUE)</code> ou <code>glass_delta(x, y, data = DataFrame, paired = FALSE, pooled_sd = TRUE)</code></p></li>
</ul>
<p>Notez que pour toutes ces fonctions, deux écritures sont possibles :</p>
<ul>
<li><code>x ~ y, data=</code> avec un <code>DataFrame</code> dans lequel <code>x</code> est une variable continue et <code>y</code> et un facteur binaire</li>
<li><code>x, y</code> qui sont tous deux des vecteurs numériques (variable continue).</li>
</ul>
<p><strong>Exemple de test pour des échantillons indépendants</strong></p>
<p>La figure <a href="sect061.html#fig:figlocataires">6.3</a> représente la cartographie du pourcentage de locataires par secteur de recensement (SR) pour la région métropolitaine de recensement de Montréal (RMR) en 2016, soit une variable continue. L’objectif est de vérifier si la moyenne de ce pourcentage des SR de l’agglomération de Montréal est significativement différente de celles de SR hors de l’agglomération.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:figlocataires"></span>
<img src="images/bivariee/FigureLocataires.jpg" alt="Pourcentage de locataires par secteur de recensement, région métropolitaine de recensement de Montréal, 2016" width="100%" />
<p class="caption">
Figure 6.3: Pourcentage de locataires par secteur de recensement, région métropolitaine de recensement de Montréal, 2016
</p>
</div>
<p>Les résultats de la syntaxe ci-dessous signalent que le pourcentage de locataires par SR est bien supérieur dans l’agglomération (moyenne = 59,7 %; écart-type = 21,4 %) qu’en dehors de l’agglomération de Montréal (moyenne = 27,3 %; écart-type = 20,1 %). Cette différence de 32,5 points de pourcentage est d’ailleurs significative et très forte (<em>t</em> = -23,95; <em>p</em> &lt; 0,001, d de Cohen = 1,54).</p>
<div class="sourceCode" id="cb557"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb557-1"><a href="sect061.html#cb557-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;foreign&quot;</span>)</span>
<span id="cb557-2"><a href="sect061.html#cb557-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;effectsize&quot;</span>)</span>
<span id="cb557-3"><a href="sect061.html#cb557-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;ggplot2&quot;</span>)</span>
<span id="cb557-4"><a href="sect061.html#cb557-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;dplyr&quot;</span>)</span>
<span id="cb557-5"><a href="sect061.html#cb557-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Importation du fichier</span></span>
<span id="cb557-6"><a href="sect061.html#cb557-6" aria-hidden="true" tabindex="-1"></a>dfRMR <span class="ot">&lt;-</span> <span class="fu">read.dbf</span>(<span class="st">&quot;data/bivariee/SRRMRMTL2016.dbf&quot;</span>)</span>
<span id="cb557-7"><a href="sect061.html#cb557-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Définition d&#39;un facteur binaire                  </span></span>
<span id="cb557-8"><a href="sect061.html#cb557-8" aria-hidden="true" tabindex="-1"></a>dfRMR<span class="sc">$</span>Montreal <span class="ot">&lt;-</span> <span class="fu">factor</span>(dfRMR<span class="sc">$</span>Montreal, </span>
<span id="cb557-9"><a href="sect061.html#cb557-9" aria-hidden="true" tabindex="-1"></a>                           <span class="at">levels=</span>  <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), </span>
<span id="cb557-10"><a href="sect061.html#cb557-10" aria-hidden="true" tabindex="-1"></a>                           <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Hors de Montréal&quot;</span>,<span class="st">&quot;Montréal&quot;</span>))</span>
<span id="cb557-11"><a href="sect061.html#cb557-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Comparaison des moyennes ------------------------</span></span>
<span id="cb557-12"><a href="sect061.html#cb557-12" aria-hidden="true" tabindex="-1"></a><span class="co">#Boite à moustaches (boxplot)</span></span>
<span id="cb557-13"><a href="sect061.html#cb557-13" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> dfRMR, <span class="at">mapping=</span><span class="fu">aes</span>(<span class="at">x=</span>Montreal,<span class="at">y=</span>Locataire,<span class="at">colour=</span>Montreal)) <span class="sc">+</span></span>
<span id="cb557-14"><a href="sect061.html#cb557-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">width=</span><span class="fl">0.2</span>)<span class="sc">+</span></span>
<span id="cb557-15"><a href="sect061.html#cb557-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position=</span><span class="st">&quot;none&quot;</span>)<span class="sc">+</span></span>
<span id="cb557-16"><a href="sect061.html#cb557-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Zone&quot;</span>)<span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Pourcentage de locataires&quot;</span>)<span class="sc">+</span></span>
<span id="cb557-17"><a href="sect061.html#cb557-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Locataires par secteur de recensement&quot;</span>, </span>
<span id="cb557-18"><a href="sect061.html#cb557-18" aria-hidden="true" tabindex="-1"></a>          <span class="at">subtitle=</span><span class="st">&quot;région métropolitaine de recensement de Montréal, 2016&quot;</span>)</span></code></pre></div>
<p><img src="MethodesQuantitScSocialesBolR_files/figure-html/unnamed-chunk-155-1.png" width="672" /></p>
<div class="sourceCode" id="cb558"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb558-1"><a href="sect061.html#cb558-1" aria-hidden="true" tabindex="-1"></a><span class="co"># nombre d&#39;observations, moyennes et écarts-types pour les deux échantillons</span></span>
<span id="cb558-2"><a href="sect061.html#cb558-2" aria-hidden="true" tabindex="-1"></a><span class="fu">group_by</span>(dfRMR, Montreal) <span class="sc">%&gt;%</span></span>
<span id="cb558-3"><a href="sect061.html#cb558-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb558-4"><a href="sect061.html#cb558-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb558-5"><a href="sect061.html#cb558-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">moy =</span> <span class="fu">mean</span>(Locataire, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb558-6"><a href="sect061.html#cb558-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">ecarttype =</span> <span class="fu">sd</span>(Locataire, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb558-7"><a href="sect061.html#cb558-7" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
<pre><code>## # A tibble: 2 × 4
##   Montreal             n   moy ecarttype
##   &lt;fct&gt;            &lt;int&gt; &lt;dbl&gt;     &lt;dbl&gt;
## 1 Hors de Montréal   430  27.3      20.1
## 2 Montréal           521  59.7      21.4</code></pre>
<div class="sourceCode" id="cb560"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb560-1"><a href="sect061.html#cb560-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Nous vérifions si les variances sont égales avec la fonction var.test</span></span>
<span id="cb560-2"><a href="sect061.html#cb560-2" aria-hidden="true" tabindex="-1"></a><span class="co"># quand la valeur de P est inférieure à 0,05 alors les variances diffèrent</span></span>
<span id="cb560-3"><a href="sect061.html#cb560-3" aria-hidden="true" tabindex="-1"></a>v <span class="ot">&lt;-</span> <span class="fu">var.test</span>(Locataire <span class="sc">~</span> Montreal, <span class="at">alternative=</span><span class="st">&#39;two.sided&#39;</span>, <span class="at">conf.level=</span>.<span class="dv">95</span>, <span class="at">data=</span>dfRMR)</span>
<span id="cb560-4"><a href="sect061.html#cb560-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(v)</span></code></pre></div>
<pre><code>## 
##  F test to compare two variances
## 
## data:  Locataire by Montreal
## F = 0.88156, num df = 429, denom df = 520, p-value = 0.1739
## alternative hypothesis: true ratio of variances is not equal to 1
## 95 percent confidence interval:
##  0.7361821 1.0573195
## sample estimates:
## ratio of variances 
##          0.8815563</code></pre>
<p>Le test indique que nous n’avons aucune raison de rejeter l’hypothèse nulle selon laquelle les variances sont égales. Pour l’île de Montréal, l’écart-type est de 21,4; il est de 20,1 hors de l’île, soit une différence négligeable.</p>
<div class="sourceCode" id="cb562"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb562-1"><a href="sect061.html#cb562-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcul du T de Student ou du T de Welch</span></span>
<span id="cb562-2"><a href="sect061.html#cb562-2" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> v<span class="sc">$</span>p.value</span>
<span id="cb562-3"><a href="sect061.html#cb562-3" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(p <span class="sc">&gt;=</span> <span class="fl">0.05</span>){</span>
<span id="cb562-4"><a href="sect061.html#cb562-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">&quot;</span><span class="sc">\n</span><span class="st"> Les variances ne diffèrent pas!&quot;</span>,</span>
<span id="cb562-5"><a href="sect061.html#cb562-5" aria-hidden="true" tabindex="-1"></a>     <span class="st">&quot;</span><span class="sc">\n</span><span class="st"> Nous utilisons le test de Student avec l&#39;option var.equal=TRUE&quot;</span>, <span class="at">sep=</span><span class="st">&quot;&quot;</span>)</span>
<span id="cb562-6"><a href="sect061.html#cb562-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">t.test</span>(Locataire <span class="sc">~</span> Montreal,  <span class="co"># variable continue ~ facteur binaire </span></span>
<span id="cb562-7"><a href="sect061.html#cb562-7" aria-hidden="true" tabindex="-1"></a>           <span class="at">data=</span>dfRMR,            <span class="co"># nom du DataFrame</span></span>
<span id="cb562-8"><a href="sect061.html#cb562-8" aria-hidden="true" tabindex="-1"></a>           <span class="at">conf.level=</span>.<span class="dv">95</span>,        <span class="co"># intervalle de confiance pour la valeur de t</span></span>
<span id="cb562-9"><a href="sect061.html#cb562-9" aria-hidden="true" tabindex="-1"></a>           <span class="at">paired =</span> <span class="cn">FALSE</span>,        <span class="co"># échantillons non pairés (indépendants)</span></span>
<span id="cb562-10"><a href="sect061.html#cb562-10" aria-hidden="true" tabindex="-1"></a>           <span class="at">var.equal=</span><span class="cn">TRUE</span>)        <span class="co"># variances égales</span></span>
<span id="cb562-11"><a href="sect061.html#cb562-11" aria-hidden="true" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb562-12"><a href="sect061.html#cb562-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">&quot;</span><span class="sc">\n</span><span class="st"> Les variances diffèrent!&quot;</span>,</span>
<span id="cb562-13"><a href="sect061.html#cb562-13" aria-hidden="true" tabindex="-1"></a>      <span class="st">&quot;</span><span class="sc">\n</span><span class="st"> Nous utiliseons le test de Welch avec l&#39;option var.equal=FALSE&quot;</span>, <span class="at">sep=</span><span class="st">&quot;&quot;</span>)</span>
<span id="cb562-14"><a href="sect061.html#cb562-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">t.test</span>(Locataire <span class="sc">~</span> Montreal,   <span class="co"># variable continue ~ facteur binaire </span></span>
<span id="cb562-15"><a href="sect061.html#cb562-15" aria-hidden="true" tabindex="-1"></a>         <span class="at">data=</span>dfRMR,             <span class="co"># nom du DataFrame</span></span>
<span id="cb562-16"><a href="sect061.html#cb562-16" aria-hidden="true" tabindex="-1"></a>         <span class="at">conf.level=</span>.<span class="dv">95</span>,         <span class="co"># intervalle de confiance pour la valeur de t</span></span>
<span id="cb562-17"><a href="sect061.html#cb562-17" aria-hidden="true" tabindex="-1"></a>         <span class="at">paired =</span> <span class="cn">FALSE</span>,         <span class="co"># échantillons non pairés (indépendants)</span></span>
<span id="cb562-18"><a href="sect061.html#cb562-18" aria-hidden="true" tabindex="-1"></a>         <span class="at">var.equal=</span><span class="cn">FALSE</span>)        <span class="co"># variances différentes</span></span>
<span id="cb562-19"><a href="sect061.html#cb562-19" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<pre><code>## 
##  Les variances ne diffèrent pas!
##  Nous utilisons le test de Student avec l&#39;option var.equal=TRUE</code></pre>
<pre><code>## 
##  Two Sample t-test
## 
## data:  Locataire by Montreal
## t = -23.95, df = 949, p-value &lt; 2.2e-16
## alternative hypothesis: true difference in means between group Hors de Montréal and group Montréal is not equal to 0
## 95 percent confidence interval:
##  -35.11182 -29.79341
## sample estimates:
## mean in group Hors de Montréal         mean in group Montréal 
##                       27.27340                       59.72601</code></pre>
<div class="sourceCode" id="cb565"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb565-1"><a href="sect061.html#cb565-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Effet de taille à analyser uniquement si le test est significatif</span></span>
<span id="cb565-2"><a href="sect061.html#cb565-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cohens_d</span>(Locataire <span class="sc">~</span> Montreal, <span class="at">data =</span> dfRMR, <span class="at">paired =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## Cohen&#39;s d |         95% CI
## --------------------------
## -1.56     | [-1.71, -1.41]
## 
## - Estimated using pooled SD.</code></pre>
<div class="sourceCode" id="cb567"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb567-1"><a href="sect061.html#cb567-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hedges_g</span>(Locataire <span class="sc">~</span> Montreal, <span class="at">data =</span> dfRMR, <span class="at">paired =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## Hedges&#39; g |         95% CI
## --------------------------
## -1.56     | [-1.70, -1.41]
## 
## - Estimated using pooled SD.</code></pre>
<p>Notez que les valeurs du <em>d</em> de Cohen et du <em>g</em> de Hedge sont très semblables; rappelons que le second est une correction du premier pour des échantillons de taille réduite. Avec 951 observations, nous disposons d’un échantillon suffisamment grand pour que cette correction soit négligeable.</p>
<p><strong>Exemple de syntaxe pour un test de Student pour des échantillons dépendants</strong></p>
<div class="sourceCode" id="cb569"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb569-1"><a href="sect061.html#cb569-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;ggpubr&quot;</span>)</span>
<span id="cb569-2"><a href="sect061.html#cb569-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;dplyr&quot;</span>)</span>
<span id="cb569-3"><a href="sect061.html#cb569-3" aria-hidden="true" tabindex="-1"></a>Pre <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">79</span>,<span class="dv">71</span>,<span class="dv">81</span>,<span class="dv">83</span>,<span class="dv">77</span>,<span class="dv">74</span>,<span class="dv">76</span>,<span class="dv">74</span>,<span class="dv">79</span>,<span class="dv">70</span>,<span class="dv">66</span>,<span class="dv">85</span>,<span class="dv">69</span>,<span class="dv">69</span>,<span class="dv">82</span>,</span>
<span id="cb569-4"><a href="sect061.html#cb569-4" aria-hidden="true" tabindex="-1"></a>         <span class="dv">69</span>,<span class="dv">81</span>,<span class="dv">70</span>,<span class="dv">83</span>,<span class="dv">68</span>,<span class="dv">77</span>,<span class="dv">76</span>,<span class="dv">77</span>,<span class="dv">70</span>,<span class="dv">68</span>,<span class="dv">80</span>,<span class="dv">65</span>,<span class="dv">65</span>,<span class="dv">75</span>,<span class="dv">84</span>)</span>
<span id="cb569-5"><a href="sect061.html#cb569-5" aria-hidden="true" tabindex="-1"></a>Post <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">56</span>,<span class="dv">47</span>,<span class="dv">40</span>,<span class="dv">45</span>,<span class="dv">49</span>,<span class="dv">51</span>,<span class="dv">54</span>,<span class="dv">47</span>,<span class="dv">44</span>,<span class="dv">54</span>,<span class="dv">42</span>,<span class="dv">56</span>,<span class="dv">45</span>,<span class="dv">45</span>,<span class="dv">48</span>,</span>
<span id="cb569-6"><a href="sect061.html#cb569-6" aria-hidden="true" tabindex="-1"></a>          <span class="dv">55</span>,<span class="dv">59</span>,<span class="dv">58</span>,<span class="dv">56</span>,<span class="dv">41</span>,<span class="dv">56</span>,<span class="dv">51</span>,<span class="dv">45</span>,<span class="dv">55</span>,<span class="dv">49</span>,<span class="dv">49</span>,<span class="dv">48</span>,<span class="dv">43</span>,<span class="dv">60</span>,<span class="dv">50</span>)</span>
<span id="cb569-7"><a href="sect061.html#cb569-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Première façon de faire un tableau : avec deux colonnes Avant et Après</span></span>
<span id="cb569-8"><a href="sect061.html#cb569-8" aria-hidden="true" tabindex="-1"></a>df1 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Avant=</span>Pre, <span class="at">Apres=</span>Post)</span>
<span id="cb569-9"><a href="sect061.html#cb569-9" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df1)</span></code></pre></div>
<pre><code>##   Avant Apres
## 1    79    56
## 2    71    47
## 3    81    40
## 4    83    45
## 5    77    49
## 6    74    51</code></pre>
<div class="sourceCode" id="cb571"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb571-1"><a href="sect061.html#cb571-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggpaired</span>(df1, <span class="at">cond1 =</span> <span class="st">&quot;Avant&quot;</span>, <span class="at">cond2 =</span> <span class="st">&quot;Apres&quot;</span>, <span class="at">fill =</span> <span class="st">&quot;condition&quot;</span>, <span class="at">palette =</span> <span class="st">&quot;jco&quot;</span>,</span>
<span id="cb571-2"><a href="sect061.html#cb571-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">xlab=</span><span class="st">&quot;&quot;</span>, <span class="at">ylab=</span><span class="st">&quot;Variable continue&quot;</span>)</span></code></pre></div>
<p><img src="MethodesQuantitScSocialesBolR_files/figure-html/unnamed-chunk-157-1.png" width="672" /></p>
<div class="sourceCode" id="cb572"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb572-1"><a href="sect061.html#cb572-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Nombre d&#39;observations, moyennes et écart-types</span></span>
<span id="cb572-2"><a href="sect061.html#cb572-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">nrow</span>(df1), <span class="st">&quot; observations&quot;</span>,</span>
<span id="cb572-3"><a href="sect061.html#cb572-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">&quot;</span><span class="sc">\n</span><span class="st">POST. moy = &quot;</span>, <span class="fu">round</span>(<span class="fu">mean</span>(df1<span class="sc">$</span>Avant),<span class="dv">1</span>), <span class="st">&quot;, e.t. = &quot;</span>, <span class="fu">round</span>(<span class="fu">sd</span>(df1<span class="sc">$</span>Avant),<span class="dv">1</span>),</span>
<span id="cb572-4"><a href="sect061.html#cb572-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">&quot;</span><span class="sc">\n</span><span class="st">PRE.  moy = &quot;</span>, <span class="fu">round</span>(<span class="fu">mean</span>(df1<span class="sc">$</span>Apres),<span class="dv">1</span>), <span class="st">&quot;, e.t. = &quot;</span>, <span class="fu">round</span>(<span class="fu">sd</span>(df1<span class="sc">$</span>Apres),<span class="dv">1</span>), <span class="at">sep=</span><span class="st">&quot;&quot;</span>)</span></code></pre></div>
<pre><code>## 30 observations
## POST. moy = 74.8, e.t. = 6.1
## PRE.  moy = 49.9, e.t. = 5.7</code></pre>
<div class="sourceCode" id="cb574"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb574-1"><a href="sect061.html#cb574-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(Pre, Post, <span class="at">paired =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  Pre and Post
## t = 18.701, df = 29, p-value &lt; 2.2e-16
## alternative hypothesis: true mean difference is not equal to 0
## 95 percent confidence interval:
##  22.11740 27.54926
## sample estimates:
## mean difference 
##        24.83333</code></pre>
<div class="sourceCode" id="cb576"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb576-1"><a href="sect061.html#cb576-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Deuxième façon de faire un tableau : avec une colonne pour la variable continue</span></span>
<span id="cb576-2"><a href="sect061.html#cb576-2" aria-hidden="true" tabindex="-1"></a><span class="co"># et une autre pour la variable qualitative</span></span>
<span id="cb576-3"><a href="sect061.html#cb576-3" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">length</span>(Pre)<span class="sc">*</span><span class="dv">2</span></span>
<span id="cb576-4"><a href="sect061.html#cb576-4" aria-hidden="true" tabindex="-1"></a>df2 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb576-5"><a href="sect061.html#cb576-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">id=</span>(<span class="dv">1</span><span class="sc">:</span>n),</span>
<span id="cb576-6"><a href="sect061.html#cb576-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">participant=</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(Pre)),</span>
<span id="cb576-7"><a href="sect061.html#cb576-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">risque=</span><span class="fu">c</span>(Pre,Post)</span>
<span id="cb576-8"><a href="sect061.html#cb576-8" aria-hidden="true" tabindex="-1"></a>       )</span>
<span id="cb576-9"><a href="sect061.html#cb576-9" aria-hidden="true" tabindex="-1"></a>df2<span class="sc">$</span>periode <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(df2<span class="sc">$</span>id <span class="sc">&lt;=</span> <span class="fu">length</span>(Pre), <span class="st">&quot;Pré&quot;</span>, <span class="st">&quot;Post&quot;</span>)</span>
<span id="cb576-10"><a href="sect061.html#cb576-10" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df2)</span></code></pre></div>
<pre><code>##   id participant risque periode
## 1  1           1     79     Pré
## 2  2           2     71     Pré
## 3  3           3     81     Pré
## 4  4           4     83     Pré
## 5  5           5     77     Pré
## 6  6           6     74     Pré</code></pre>
<div class="sourceCode" id="cb578"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb578-1"><a href="sect061.html#cb578-1" aria-hidden="true" tabindex="-1"></a><span class="co"># nombre d&#39;observations, moyennes et écarts-types pour les deux échantillons</span></span>
<span id="cb578-2"><a href="sect061.html#cb578-2" aria-hidden="true" tabindex="-1"></a><span class="fu">group_by</span>(df2, periode) <span class="sc">%&gt;%</span></span>
<span id="cb578-3"><a href="sect061.html#cb578-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb578-4"><a href="sect061.html#cb578-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb578-5"><a href="sect061.html#cb578-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">moy =</span> <span class="fu">mean</span>(risque, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb578-6"><a href="sect061.html#cb578-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">et =</span> <span class="fu">sd</span>(risque, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb578-7"><a href="sect061.html#cb578-7" aria-hidden="true" tabindex="-1"></a>    )</span></code></pre></div>
<pre><code>## # A tibble: 2 × 4
##   periode     n   moy    et
##   &lt;chr&gt;   &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 Post       30  49.9  5.67
## 2 Pré        30  74.8  6.10</code></pre>
<div class="sourceCode" id="cb580"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb580-1"><a href="sect061.html#cb580-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggpaired</span>(<span class="at">data=</span>df2, <span class="at">x=</span> <span class="st">&quot;periode&quot;</span>, <span class="at">y=</span><span class="st">&quot;risque&quot;</span>, <span class="at">fill =</span> <span class="st">&quot;periode&quot;</span>,</span>
<span id="cb580-2"><a href="sect061.html#cb580-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">xlab=</span><span class="st">&quot;&quot;</span>, <span class="at">ylab=</span><span class="st">&quot;Variable continue&quot;</span>)</span></code></pre></div>
<p><img src="MethodesQuantitScSocialesBolR_files/figure-html/unnamed-chunk-157-2.png" width="672" /></p>
<div class="sourceCode" id="cb581"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb581-1"><a href="sect061.html#cb581-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(risque <span class="sc">~</span> periode, <span class="at">data=</span>df2, <span class="at">paired =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  risque by periode
## t = -18.701, df = 29, p-value &lt; 2.2e-16
## alternative hypothesis: true mean difference is not equal to 0
## 95 percent confidence interval:
##  -27.54926 -22.11740
## sample estimates:
## mean difference 
##       -24.83333</code></pre>
</div>
<div id="sect06114" class="section level4 hasAnchor" number="6.1.1.4">
<h4><span class="header-section-number">6.1.1.4</span> Comparaison des moyennes pondérées<a href="sect061.html#sect06114" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="bloc_objectif">
<p>En études urbaines et en géographie, le recours aux données agrégées (non individuelles) est fréquent, par exemple au niveau des secteurs de recensement (comprenant généralement entre 2500 à 8000 habitants). Dans ce contexte, un secteur de recensement plus peuplé devrait avoir un poids plus important dans l’analyse. Il est possible d’utiliser les versions pondérées des tests présentés précédemment. Prenons deux exemples pour illustrer le tout :</p>
<ul>
<li><p>Pour chaque secteur de recensement des îles de Montréal et de Laval, nous avons calculé la distance au parc le plus proche à travers le réseau de rues avec un système d’information géographique (SIG). Nous souhaitons vérifier si les personnes âgées de moins de 15 ans résidant sur l’île de Montréal bénéficient en moyenne d’une meilleure accessibilité au parc.</p></li>
<li><p>Dans une étude sur la concentration de polluants atmosphériques dans l’environnement autour des écoles primaires montréalaises, Carrier <em>et al.</em> <span class="citation">(<a href="#ref-carrier2014" role="doc-biblioref">2014</a>)</span> souhaitaient vérifier si les élèves fréquentant les écoles les plus défavorisées sont plus exposé(e)s au dioxyde d’azote (NO<sub>2</sub>) dans leur milieu scolaire. Pour ce faire, ils ont réalisé un test <em>t</em> sur un tableau avec comme observations les écoles primaires et trois variables : la moyenne de NO<sub>2</sub> (variable continue), les quintiles extrêmes d’un indice de défavorisation (premier et dernier quintiles, variable qualitative) et le nombre d’élèves par école (variable pour la pondération).</p></li>
</ul>
<p>Pour réaliser un test <em>t</em> pondéré, nous pouvons utiliser la fonction <code>weighted_ttest</code> du package <code>sjstats</code>.</p>
</div>
<p>En guise d’exemple appliqué, dans la syntaxe ci-dessous, nous avons refait le même test <em>t</em> que précédemment (<code>Locataire ~ Montreal</code>) en pondérant chaque secteur de recensement par le nombre de logements qu’il comprend.</p>
<div class="sourceCode" id="cb583"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb583-1"><a href="sect061.html#cb583-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;sjstats&quot;</span>)</span>
<span id="cb583-2"><a href="sect061.html#cb583-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;dplyr&quot;</span>)</span>
<span id="cb583-3"><a href="sect061.html#cb583-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcul des statistiques pondérées</span></span>
<span id="cb583-4"><a href="sect061.html#cb583-4" aria-hidden="true" tabindex="-1"></a><span class="fu">group_by</span>(dfRMR, Montreal) <span class="sc">%&gt;%</span></span>
<span id="cb583-5"><a href="sect061.html#cb583-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb583-6"><a href="sect061.html#cb583-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">sum</span>(Logement),</span>
<span id="cb583-7"><a href="sect061.html#cb583-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">MoyPond =</span> <span class="fu">weighted_mean</span>(Locataire, Logement),</span>
<span id="cb583-8"><a href="sect061.html#cb583-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">ecarttypePond =</span> <span class="fu">weighted_sd</span>(Locataire, Logement)</span>
<span id="cb583-9"><a href="sect061.html#cb583-9" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
<pre><code>## # A tibble: 2 × 4
##   Montreal              n MoyPond ecarttypePond
##   &lt;fct&gt;             &lt;int&gt;   &lt;dbl&gt;         &lt;dbl&gt;
## 1 Hors de Montréal 856928    28.4          19.9
## 2 Montréal         870354    60.0          20.8</code></pre>
<div class="sourceCode" id="cb585"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb585-1"><a href="sect061.html#cb585-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Test t non pondéré</span></span>
<span id="cb585-2"><a href="sect061.html#cb585-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(Locataire <span class="sc">~</span> Montreal, dfRMR, </span>
<span id="cb585-3"><a href="sect061.html#cb585-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">paired =</span> <span class="cn">FALSE</span>, <span class="at">var.equal =</span> <span class="cn">TRUE</span>, <span class="at">conf.level=</span>.<span class="dv">95</span>)</span></code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  Locataire by Montreal
## t = -23.95, df = 949, p-value &lt; 2.2e-16
## alternative hypothesis: true difference in means between group Hors de Montréal and group Montréal is not equal to 0
## 95 percent confidence interval:
##  -35.11182 -29.79341
## sample estimates:
## mean in group Hors de Montréal         mean in group Montréal 
##                       27.27340                       59.72601</code></pre>
<div class="sourceCode" id="cb587"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb587-1"><a href="sect061.html#cb587-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Test t pondérée</span></span>
<span id="cb587-2"><a href="sect061.html#cb587-2" aria-hidden="true" tabindex="-1"></a><span class="fu">weighted_ttest</span>(Locataire <span class="sc">~</span> Montreal <span class="sc">+</span> Logement, dfRMR, </span>
<span id="cb587-3"><a href="sect061.html#cb587-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">paired =</span> <span class="cn">FALSE</span>, <span class="at">ci.lvl=</span>.<span class="dv">95</span>)</span></code></pre></div>
<pre><code>## 
## Two-Sample t-test (two.sided)
## 
## # comparison of Locataire by Montreal
## # t=-23.91  df=928  p-value=0.000
## 
##   mean in group Hors de Montréal: 28.396
##   mean in group Montréal        : 60.003
##   difference of mean            : -31.608 [-34.202  -29.013]</code></pre>
</div>
<div id="sect06115" class="section level4 hasAnchor" number="6.1.1.5">
<h4><span class="header-section-number">6.1.1.5</span> Comment rapporter un test de Student ou de Welch?<a href="sect061.html#sect06115" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Pour les différentes versions du test, il est important de rapporter les valeurs de <em>t</em> et de <em>p</em>, les moyennes et écarts-types des groupes. Voici quelques exemples.</p>
<p><strong>Test de Student ou de Welch pour échantillons indépendants</strong></p>
<ul>
<li>Dans la région métropolitaine de Montréal en 2005, le revenu total des femmes (moyenne = 29 117 dollars; écart-type = 258 022) est bien inférieur à celui des hommes (moyenne = 44 463; écart-type = 588 081). La différence entre les moyennes des deux sexes (-15 345) en faveur des hommes est d’ailleurs significative (<em>t</em> = -27,09; <em>p</em> &lt; 0,001).</li>
<li>Il y un effet significatif selon le sexe (<em>t</em> = -27,09; <em>p</em> &lt; 0,001), le revenu total des hommes (moyenne = 44 463; écart-type = 588 081) étant bien supérieur à celui des femmes (moyenne = 29 117; écart-type = 258 022).</li>
<li>50 personnes se rendent au travail à vélo (moyenne = 33,7; écart-type = 8,5) contre 60 en automobile (moyenne = 34; écart-type = 8,7). Il n’y a pas de différence significative entre les moyennes d’âge des deux groupes (<em>t</em>(108) = -0,79; <em>p</em> = 0,427).</li>
</ul>
<p><strong>Test de Student échantillons dépendants (pairés)</strong></p>
<ul>
<li>Nous constatons une diminution significative de la perception du risque après l’activité (moyenne = 49,9; écart-type = 5,7) comparativement à avant (moyenne = 74,8; écart-type = 6,1), avec une différence de -24,8 (<em>t</em>(29) = -18,7; <em>p</em> &lt; 0,001).</li>
<li>Les résultats du pré-test (moyenne = 49,9; écart-type = 5,7) et du post-test (moyenne = 74,8; écart-type = 6,1) montrent qu’il y une diminution significative de la perception du risque (<em>t</em>(29) = -18,7; <em>p</em> &lt; 0,001).</li>
</ul>
<p>Pour un texte en anglais, consultez
<a href="https://www.socscistatistics.com/tutorials/ttest/default.aspx" target="_blank">https://www.socscistatistics.com/tutorials/ttest/default.aspx</a>.</p>
</div>
</div>
<div id="sect0612" class="section level3 hasAnchor" number="6.1.2">
<h3><span class="header-section-number">6.1.2</span> Test non paramétrique de Wilcoxon<a href="sect061.html#sect0612" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="bloc_objectif">
<p>Si la variable continue est fortement anormalement distribuée, il est déconseillé d’utiliser les tests de Student et de Welch. Nous privilégions le test des rangs signés de Wilcoxon (<em>Wilcoxon rank-sum test</em> en anglais). Attention, il est aussi appelé test U de Mann-Whitney. Ce test permet alors de vérifier si les deux groupes présentent des médianes différentes.</p>
<p>Pour ce faire, nous utilisons la fonction <code>wilcox.test</code> dans laquelle le paramètre <code>paired</code> permet de spécifier si les échantillons sont indépendants ou non (<code>FALSE</code> ou <code>TRUE</code>).</p>
</div>
<p>Dans l’exemple suivant, nous analysons le pourcentage de locataires dans les secteurs de recensement de la région métropolitaine de Montréal. Plus spécifiquement, nous comparons ce pourcentage entre les secteurs présents sur l’île et les secteurs hors de l’île. Il s’agit donc d’un test avec des échantillons indépendants.</p>
<div class="sourceCode" id="cb589"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb589-1"><a href="sect061.html#cb589-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;foreign&quot;</span>)</span>
<span id="cb589-2"><a href="sect061.html#cb589-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;dplyr&quot;</span>)</span>
<span id="cb589-3"><a href="sect061.html#cb589-3" aria-hidden="true" tabindex="-1"></a><span class="do">###############################</span></span>
<span id="cb589-4"><a href="sect061.html#cb589-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Échantillons indépendants</span></span>
<span id="cb589-5"><a href="sect061.html#cb589-5" aria-hidden="true" tabindex="-1"></a><span class="do">###############################</span></span>
<span id="cb589-6"><a href="sect061.html#cb589-6" aria-hidden="true" tabindex="-1"></a>dfRMR <span class="ot">&lt;-</span> <span class="fu">read.dbf</span>(<span class="st">&quot;data/bivariee/SRRMRMTL2016.dbf&quot;</span>)</span>
<span id="cb589-7"><a href="sect061.html#cb589-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Définition d&#39;un facteur binaire                  </span></span>
<span id="cb589-8"><a href="sect061.html#cb589-8" aria-hidden="true" tabindex="-1"></a>dfRMR<span class="sc">$</span>Montreal <span class="ot">&lt;-</span> <span class="fu">factor</span>(dfRMR<span class="sc">$</span>Montreal, </span>
<span id="cb589-9"><a href="sect061.html#cb589-9" aria-hidden="true" tabindex="-1"></a>                           <span class="at">levels=</span>  <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), </span>
<span id="cb589-10"><a href="sect061.html#cb589-10" aria-hidden="true" tabindex="-1"></a>                           <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Hors de Montréal&quot;</span>,<span class="st">&quot;Montréal&quot;</span>))</span>
<span id="cb589-11"><a href="sect061.html#cb589-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcul du nombre d&#39;observations, des moyennes et </span></span>
<span id="cb589-12"><a href="sect061.html#cb589-12" aria-hidden="true" tabindex="-1"></a><span class="co"># des écarts-types des rangs pour les deux échantillons</span></span>
<span id="cb589-13"><a href="sect061.html#cb589-13" aria-hidden="true" tabindex="-1"></a><span class="fu">group_by</span>(dfRMR, Montreal) <span class="sc">%&gt;%</span></span>
<span id="cb589-14"><a href="sect061.html#cb589-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb589-15"><a href="sect061.html#cb589-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb589-16"><a href="sect061.html#cb589-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">moy_rang =</span> <span class="fu">mean</span>(<span class="fu">rank</span>(Locataire), <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb589-17"><a href="sect061.html#cb589-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">med_rang =</span> <span class="fu">median</span>(<span class="fu">rank</span>(Locataire), <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb589-18"><a href="sect061.html#cb589-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">ecarttype_rang =</span> <span class="fu">sd</span>(<span class="fu">rank</span>(Locataire), <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb589-19"><a href="sect061.html#cb589-19" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
<pre><code>## # A tibble: 2 × 5
##   Montreal             n moy_rang med_rang ecarttype_rang
##   &lt;fct&gt;            &lt;int&gt;    &lt;dbl&gt;    &lt;dbl&gt;          &lt;dbl&gt;
## 1 Hors de Montréal   430     216.     216.           124.
## 2 Montréal           521     261      261            151.</code></pre>
<div class="sourceCode" id="cb591"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb591-1"><a href="sect061.html#cb591-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Test des rangs signés de Wilcoxon sur des échantillons indépendants</span></span>
<span id="cb591-2"><a href="sect061.html#cb591-2" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(Locataire <span class="sc">~</span> Montreal, dfRMR, <span class="at">paired =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## 
##  Wilcoxon rank sum test with continuity correction
## 
## data:  Locataire by Montreal
## W = 33716, p-value &lt; 2.2e-16
## alternative hypothesis: true location shift is not equal to 0</code></pre>
<p>Nous observons bien ici une différence significative entre le pourcentage de locataires des secteurs de recensement sur l’île (rang médian = 216) et ceux en dehors de l’île (rang médian = 261).</p>
<p>Pour le second exemple, nous générons deux jeux de données au hasard représentant une mesure d’une variable pré-traitement (<em>pre</em>) et post-traitement (<em>post</em>) pour un même échantillon.</p>
<div class="sourceCode" id="cb593"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb593-1"><a href="sect061.html#cb593-1" aria-hidden="true" tabindex="-1"></a><span class="do">###############################</span></span>
<span id="cb593-2"><a href="sect061.html#cb593-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Échantillons dépendants</span></span>
<span id="cb593-3"><a href="sect061.html#cb593-3" aria-hidden="true" tabindex="-1"></a><span class="do">###############################</span></span>
<span id="cb593-4"><a href="sect061.html#cb593-4" aria-hidden="true" tabindex="-1"></a>pre <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">60</span><span class="sc">:</span><span class="dv">80</span>, <span class="dv">50</span>, <span class="at">replace=</span>T)</span>
<span id="cb593-5"><a href="sect061.html#cb593-5" aria-hidden="true" tabindex="-1"></a>post <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">30</span><span class="sc">:</span><span class="dv">65</span>, <span class="dv">50</span>, <span class="at">replace=</span>T)</span>
<span id="cb593-6"><a href="sect061.html#cb593-6" aria-hidden="true" tabindex="-1"></a>df1 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Avant=</span>pre, <span class="at">Apres=</span>post)</span>
<span id="cb593-7"><a href="sect061.html#cb593-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Nombre d&#39;observations, moyennes et écart-types</span></span>
<span id="cb593-8"><a href="sect061.html#cb593-8" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">nrow</span>(df1), <span class="st">&quot; observations&quot;</span>,</span>
<span id="cb593-9"><a href="sect061.html#cb593-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">&quot;</span><span class="sc">\n</span><span class="st">POST. median = &quot;</span>, <span class="fu">round</span>(<span class="fu">median</span>(df1<span class="sc">$</span>Avant),<span class="dv">1</span>), </span>
<span id="cb593-10"><a href="sect061.html#cb593-10" aria-hidden="true" tabindex="-1"></a>             <span class="st">&quot;, moy = &quot;</span>, <span class="fu">round</span>(<span class="fu">mean</span>(df1<span class="sc">$</span>Avant),<span class="dv">1</span>),</span>
<span id="cb593-11"><a href="sect061.html#cb593-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">&quot;</span><span class="sc">\n</span><span class="st">PRE.  median = &quot;</span>, <span class="fu">round</span>(<span class="fu">median</span>(df1<span class="sc">$</span>Apres),<span class="dv">1</span>), </span>
<span id="cb593-12"><a href="sect061.html#cb593-12" aria-hidden="true" tabindex="-1"></a>             <span class="st">&quot;, moy = &quot;</span>, <span class="fu">round</span>(<span class="fu">mean</span>(df1<span class="sc">$</span>Apres),<span class="dv">1</span>), <span class="at">sep=</span><span class="st">&quot;&quot;</span>)</span></code></pre></div>
<pre><code>## 50 observations
## POST. median = 71, moy = 70.4
## PRE.  median = 49.5, moy = 50</code></pre>
<div class="sourceCode" id="cb595"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb595-1"><a href="sect061.html#cb595-1" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(df1<span class="sc">$</span>Avant, df1<span class="sc">$</span>Apres, <span class="at">paired =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
##  Wilcoxon signed rank test with continuity correction
## 
## data:  df1$Avant and df1$Apres
## V = 1265, p-value = 1.411e-09
## alternative hypothesis: true location shift is not equal to 0</code></pre>
<p>À nouveau, nous obtenons une différence significative entre les deux variables.</p>
<p><strong>Comment rapporter un test de Wilcoxon?</strong></p>
<p>Lorsque nous rapportons les résultats d’un test de Wilcoxon, il est important de signaler la valeur du test (<em>W</em>), le degré de signification (valeur de <em>p</em>) et éventuellement la médiane des rangs ou de la variable originale pour les deux groupes. Voici quelques exemples :</p>
<ul>
<li>Les résultats du test des rangs signés de Wilcoxon signalent que les rangs de l’île de Montréal sont significativement plus élevés que ceux de l’île de Laval (<em>W</em> = 1223, <em>p</em> &lt; 0,001).</li>
<li>Les résultats du test de Wilcoxon signalent que les rangs post-tests sont significativement plus faibles que ceux du pré-test (<em>W</em> = 1273,5, <em>p</em> &lt; 0,001).</li>
<li>Les résultats du test de Wilcoxon signalent que la médiane des rangs pré-tests (médiane = 69) est significativement plus forte que celle du post-test (médiane = 50,5) (<em>W</em> = 1273,5, <em>p</em> &lt; 0,001).</li>
</ul>
</div>
</div>
<h3>R&eacute;f&eacute;rences</h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-carrier2014" class="csl-entry">
Carrier, Mathieu, Philippe Apparicio, Anne-Marie Séguin et Dan Crouse. 2014. <span>« Ambient air pollution concentration in Montreal and environmental equity: Are children at risk at school? »</span> <em>Case Studies on Transport Policy</em> 2 (2): 61‑69. <a href="https://doi.org/10.1016/j.cstp.2014.06.003">https://doi.org/10.1016/j.cstp.2014.06.003</a>.
</div>
<div id="ref-cohen1992" class="csl-entry">
Cohen, Jacob. 1992. <span>« A power primer. »</span> <em>Psychological bulletin</em> 112 (1): 155‑159. <a href="https://doi.org/10.1037/0033-2909.112.1.155">https://doi.org/10.1037/0033-2909.112.1.155</a>.
</div>
<div id="ref-cohen2013" class="csl-entry">
———. 2013. <em>Statistical power analysis for the behavioral sciences</em>. Academic press.
</div>
<div id="ref-sawilowsky2009" class="csl-entry">
Sawilowsky, Shlomo S. 2009. <span>« New effect size rules of thumb. »</span> <em>Journal of Modern Applied Statistical Methods</em> 8 (2): 467‑474. <a href="https://doi.org/10.22237/jmasm/1257035100">https://doi.org/10.22237/jmasm/1257035100</a>.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="chap06.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="sect062.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["MethodesQuantitScSocialesBolR.pdf"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "none"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
