<!DOCTYPE html>
<html lang="fr" xml:lang="fr">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>7.4 Différentes mesures pour les coefficients de régression | Méthodes quantitatives en sciences sociales : un grand bol d’R</title>
  <meta name="description" content="Ce livre vise à décrire une panoplie de méthodes quantitatives utilisées en sciences sociales avec le logiciel ouvert R. Il a d’ailleurs été écrit intégralement dans R avec rmarkdown. Le contenu est pensé pour être accessible à tous et toutes, même à ceux et celles n’ayant presque aucune base en statistique ou en programmation. Les personnes plus expérimentées y découvriront des sections sur des méthodes plus avancées comme les modèles à effets mixtes, les modèles multiniveaux, les modèles généralisés additifs ainsi que les méthodes factorielles et de classification. Ceux et celles souhaitant migrer progressivement d’un autre logiciel statistique vers R trouveront dans cet ouvrage les éléments pour une transition en douceur. La philosophie de ce livre est de donner toutes les clefs de compréhension et de mise en œuvre des méthodes abordées dans R. La présentation des méthodes est basée sur une approche compréhensive et intuitive plutôt que mathématique, sans pour autant que la rigueur statistique ne soit négligée." />
  <meta name="generator" content="bookdown 0.32 and GitBook 2.6.7" />

  <meta property="og:title" content="7.4 Différentes mesures pour les coefficients de régression | Méthodes quantitatives en sciences sociales : un grand bol d’R" />
  <meta property="og:type" content="book" />
  <meta property="og:image" content="https://laeq.github.io/LivreStatistique_website/images/introduction/ImageCouverture.png" />
  <meta property="og:description" content="Ce livre vise à décrire une panoplie de méthodes quantitatives utilisées en sciences sociales avec le logiciel ouvert R. Il a d’ailleurs été écrit intégralement dans R avec rmarkdown. Le contenu est pensé pour être accessible à tous et toutes, même à ceux et celles n’ayant presque aucune base en statistique ou en programmation. Les personnes plus expérimentées y découvriront des sections sur des méthodes plus avancées comme les modèles à effets mixtes, les modèles multiniveaux, les modèles généralisés additifs ainsi que les méthodes factorielles et de classification. Ceux et celles souhaitant migrer progressivement d’un autre logiciel statistique vers R trouveront dans cet ouvrage les éléments pour une transition en douceur. La philosophie de ce livre est de donner toutes les clefs de compréhension et de mise en œuvre des méthodes abordées dans R. La présentation des méthodes est basée sur une approche compréhensive et intuitive plutôt que mathématique, sans pour autant que la rigueur statistique ne soit négligée." />
  <meta name="github-repo" content="LAEQ/livre_statistique_Phil_Jere" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="7.4 Différentes mesures pour les coefficients de régression | Méthodes quantitatives en sciences sociales : un grand bol d’R" />
  
  <meta name="twitter:description" content="Ce livre vise à décrire une panoplie de méthodes quantitatives utilisées en sciences sociales avec le logiciel ouvert R. Il a d’ailleurs été écrit intégralement dans R avec rmarkdown. Le contenu est pensé pour être accessible à tous et toutes, même à ceux et celles n’ayant presque aucune base en statistique ou en programmation. Les personnes plus expérimentées y découvriront des sections sur des méthodes plus avancées comme les modèles à effets mixtes, les modèles multiniveaux, les modèles généralisés additifs ainsi que les méthodes factorielles et de classification. Ceux et celles souhaitant migrer progressivement d’un autre logiciel statistique vers R trouveront dans cet ouvrage les éléments pour une transition en douceur. La philosophie de ce livre est de donner toutes les clefs de compréhension et de mise en œuvre des méthodes abordées dans R. La présentation des méthodes est basée sur une approche compréhensive et intuitive plutôt que mathématique, sans pour autant que la rigueur statistique ne soit négligée." />
  <meta name="twitter:image" content="https://laeq.github.io/LivreStatistique_website/images/introduction/ImageCouverture.png" />

<meta name="author" content="Philippe Apparicio et Jérémy Gelb" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="sect073.html"/>
<link rel="next" href="sect075.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.6.1/htmlwidgets.js"></script>
<script src="libs/d3-4.13.0/d3.min.js"></script>
<script src="libs/d3-tip-0.8.1/index.js"></script>
<link href="libs/chorddiag-0.1.2.9000/chorddiag.css" rel="stylesheet" />
<script src="libs/chorddiag-0.1.2.9000/chorddiag.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="css/quizlib.min.css" type="text/css" />
<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Méthodes quantitatives en sciences sociales : un grand bol d'R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Bienvenue</a></li>
<li class="chapter" data-level="" data-path="préface.html"><a href="préface.html"><i class="fa fa-check"></i>Préface</a>
<ul>
<li class="chapter" data-level="" data-path="sect001.html"><a href="sect001.html"><i class="fa fa-check"></i>Un manuel sous la forme d’une ressource éducative libre</a></li>
<li class="chapter" data-level="" data-path="sect002.html"><a href="sect002.html"><i class="fa fa-check"></i>Un manuel conçu comme un projet collaboratif</a></li>
<li class="chapter" data-level="" data-path="sect003.html"><a href="sect003.html"><i class="fa fa-check"></i>Comment lire ce livre?</a></li>
<li class="chapter" data-level="" data-path="sect003B.html"><a href="sect003B.html"><i class="fa fa-check"></i>Comment utiliser les données du livre pour reproduire les exemples?</a></li>
<li class="chapter" data-level="" data-path="sect004.html"><a href="sect004.html"><i class="fa fa-check"></i>Structure du livre</a></li>
<li class="chapter" data-level="" data-path="sect005.html"><a href="sect005.html"><i class="fa fa-check"></i>Pourquoi faut-il programmer en sciences sociales?</a></li>
<li class="chapter" data-level="" data-path="sect006.html"><a href="sect006.html"><i class="fa fa-check"></i>Remerciements</a></li>
<li class="chapter" data-level="" data-path="sect007.html"><a href="sect007.html"><i class="fa fa-check"></i>Dédicace toute spéciale à Cargo et Ambrée</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="auteurs.html"><a href="auteurs.html"><i class="fa fa-check"></i>À propos des auteurs</a></li>
<li class="part"><span><b>I Découverte de R</b></span></li>
<li class="chapter" data-level="1" data-path="chap01.html"><a href="chap01.html"><i class="fa fa-check"></i><b>1</b> Prise en main de R</a>
<ul>
<li class="chapter" data-level="1.1" data-path="sect011.html"><a href="sect011.html"><i class="fa fa-check"></i><b>1.1</b> Histoire et philosophie de R</a></li>
<li class="chapter" data-level="1.2" data-path="sect012.html"><a href="sect012.html"><i class="fa fa-check"></i><b>1.2</b> Environnement de travail</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="sect012.html"><a href="sect012.html#sect0121"><i class="fa fa-check"></i><b>1.2.1</b> Installation de R</a></li>
<li class="chapter" data-level="1.2.2" data-path="sect012.html"><a href="sect012.html#sect0122"><i class="fa fa-check"></i><b>1.2.2</b> Environnement RStudio</a></li>
<li class="chapter" data-level="1.2.3" data-path="sect012.html"><a href="sect012.html#sect0123"><i class="fa fa-check"></i><b>1.2.3</b> Installation et chargement un <em>package</em></a></li>
<li class="chapter" data-level="1.2.4" data-path="sect012.html"><a href="sect012.html#aide-disponible"><i class="fa fa-check"></i><b>1.2.4</b> Aide disponible</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="sect013.html"><a href="sect013.html"><i class="fa fa-check"></i><b>1.3</b> Bases du langage R</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="sect013.html"><a href="sect013.html#sect0131"><i class="fa fa-check"></i><b>1.3.1</b> <em>Hello World</em>!</a></li>
<li class="chapter" data-level="1.3.2" data-path="sect013.html"><a href="sect013.html#sect0132"><i class="fa fa-check"></i><b>1.3.2</b> Objets et expressions</a></li>
<li class="chapter" data-level="1.3.3" data-path="sect013.html"><a href="sect013.html#sect0_133"><i class="fa fa-check"></i><b>1.3.3</b> Fonctions et arguments</a></li>
<li class="chapter" data-level="1.3.4" data-path="sect013.html"><a href="sect013.html#sect0134"><i class="fa fa-check"></i><b>1.3.4</b> Principaux types de données</a></li>
<li class="chapter" data-level="1.3.5" data-path="sect013.html"><a href="sect013.html#sect0135"><i class="fa fa-check"></i><b>1.3.5</b> Opérateurs</a></li>
<li class="chapter" data-level="1.3.6" data-path="sect013.html"><a href="sect013.html#sect0136"><i class="fa fa-check"></i><b>1.3.6</b> Structures de données</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="sect014.html"><a href="sect014.html"><i class="fa fa-check"></i><b>1.4</b> Manipulation de données</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="sect014.html"><a href="sect014.html#sect0141"><i class="fa fa-check"></i><b>1.4.1</b> Chargement d’un <em>DataFrame</em> depuis un fichier</a></li>
<li class="chapter" data-level="1.4.2" data-path="sect014.html"><a href="sect014.html#sect0142"><i class="fa fa-check"></i><b>1.4.2</b> Manipulation d’un <em>DataFrame</em></a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="sect016.html"><a href="sect016.html"><i class="fa fa-check"></i><b>1.5</b> Code R bien structuré</a></li>
<li class="chapter" data-level="1.6" data-path="sect017.html"><a href="sect017.html"><i class="fa fa-check"></i><b>1.6</b> Enregistrement des résultats</a></li>
<li class="chapter" data-level="1.7" data-path="sect018.html"><a href="sect018.html"><i class="fa fa-check"></i><b>1.7</b> Session de travail</a></li>
<li class="chapter" data-level="1.8" data-path="sect019.html"><a href="sect019.html"><i class="fa fa-check"></i><b>1.8</b> Conclusion et ressources pertinentes</a></li>
<li class="chapter" data-level="1.9" data-path="sect0110.html"><a href="sect0110.html"><i class="fa fa-check"></i><b>1.9</b> Quiz de révision du chapitre</a></li>
</ul></li>
<li class="part"><span><b>II Analyses univariées et graphiques dans R</b></span></li>
<li class="chapter" data-level="2" data-path="chap02.html"><a href="chap02.html"><i class="fa fa-check"></i><b>2</b> Statistiques descriptives univariées</a>
<ul>
<li class="chapter" data-level="2.1" data-path="sect021.html"><a href="sect021.html"><i class="fa fa-check"></i><b>2.1</b> Notion et types de variable</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="sect021.html"><a href="sect021.html#sect0211"><i class="fa fa-check"></i><b>2.1.1</b> Notion de variable</a></li>
<li class="chapter" data-level="2.1.2" data-path="sect021.html"><a href="sect021.html#sect0212"><i class="fa fa-check"></i><b>2.1.2</b> Types de variables</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="sect022.html"><a href="sect022.html"><i class="fa fa-check"></i><b>2.2</b> Types de données</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="sect022.html"><a href="sect022.html#sect0221"><i class="fa fa-check"></i><b>2.2.1</b> Données secondaires <em>versus</em> données primaires</a></li>
<li class="chapter" data-level="2.2.2" data-path="sect022.html"><a href="sect022.html#sect0222"><i class="fa fa-check"></i><b>2.2.2</b> Données transversales <em>versus</em> données longitudinales</a></li>
<li class="chapter" data-level="2.2.3" data-path="sect022.html"><a href="sect022.html#sect0223"><i class="fa fa-check"></i><b>2.2.3</b> Données spatiales versus données aspatiales</a></li>
<li class="chapter" data-level="2.2.4" data-path="sect022.html"><a href="sect022.html#sect0224"><i class="fa fa-check"></i><b>2.2.4</b> Données individuelles <em>versus</em> données agrégées</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="sect023.html"><a href="sect023.html"><i class="fa fa-check"></i><b>2.3</b> Statistique descriptive et statistique inférentielle</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="sect023.html"><a href="sect023.html#sect0231"><i class="fa fa-check"></i><b>2.3.1</b> Population, échantillon et inférence</a></li>
<li class="chapter" data-level="2.3.2" data-path="sect023.html"><a href="sect023.html#sect0232"><i class="fa fa-check"></i><b>2.3.2</b> Deux grandes familles de méthodes statistiques</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="sect024.html"><a href="sect024.html"><i class="fa fa-check"></i><b>2.4</b> Notion de distribution</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="sect024.html"><a href="sect024.html#définition-générale"><i class="fa fa-check"></i><b>2.4.1</b> Définition générale</a></li>
<li class="chapter" data-level="2.4.2" data-path="sect024.html"><a href="sect024.html#anatomie-dune-distribution"><i class="fa fa-check"></i><b>2.4.2</b> Anatomie d’une distribution</a></li>
<li class="chapter" data-level="2.4.3" data-path="sect024.html"><a href="sect024.html#principales-distributions"><i class="fa fa-check"></i><b>2.4.3</b> Principales distributions</a></li>
<li class="chapter" data-level="2.4.4" data-path="sect024.html"><a href="sect024.html#conclusion-sur-les-distributions"><i class="fa fa-check"></i><b>2.4.4</b> Conclusion sur les distributions</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="sect025.html"><a href="sect025.html"><i class="fa fa-check"></i><b>2.5</b> Statistiques descriptives sur des variables quantitatives</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="sect025.html"><a href="sect025.html#sect0251"><i class="fa fa-check"></i><b>2.5.1</b> Paramètres de tendance centrale</a></li>
<li class="chapter" data-level="2.5.2" data-path="sect025.html"><a href="sect025.html#sect0252"><i class="fa fa-check"></i><b>2.5.2</b> Paramètres de position</a></li>
<li class="chapter" data-level="2.5.3" data-path="sect025.html"><a href="sect025.html#sect0253"><i class="fa fa-check"></i><b>2.5.3</b> Paramètres de dispersion</a></li>
<li class="chapter" data-level="2.5.4" data-path="sect025.html"><a href="sect025.html#sect0254"><i class="fa fa-check"></i><b>2.5.4</b> Paramètres de forme</a></li>
<li class="chapter" data-level="2.5.5" data-path="sect025.html"><a href="sect025.html#sect0255"><i class="fa fa-check"></i><b>2.5.5</b> Transformation des variables</a></li>
<li class="chapter" data-level="2.5.6" data-path="sect025.html"><a href="sect025.html#sect0256"><i class="fa fa-check"></i><b>2.5.6</b> Mise en œuvre dans R</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="sect026.html"><a href="sect026.html"><i class="fa fa-check"></i><b>2.6</b> Statistiques descriptives sur des variables qualitatives et semi-qualitatives</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="sect026.html"><a href="sect026.html#sect0261"><i class="fa fa-check"></i><b>2.6.1</b> Fréquences</a></li>
<li class="chapter" data-level="2.6.2" data-path="sect026.html"><a href="sect026.html#sect0262"><i class="fa fa-check"></i><b>2.6.2</b> Mise en œuvre dans R</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="sect027.html"><a href="sect027.html"><i class="fa fa-check"></i><b>2.7</b> Statistiques descriptives pondérées : pour aller plus loin</a></li>
<li class="chapter" data-level="2.8" data-path="sect028.html"><a href="sect028.html"><i class="fa fa-check"></i><b>2.8</b> Quiz de révision du chapitre</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="chap03.html"><a href="chap03.html"><i class="fa fa-check"></i><b>3</b> Magie des graphiques</a>
<ul>
<li class="chapter" data-level="3.1" data-path="sect031.html"><a href="sect031.html"><i class="fa fa-check"></i><b>3.1</b> Philosophie du ggplot2</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="sect031.html"><a href="sect031.html#sect0311"><i class="fa fa-check"></i><b>3.1.1</b> Grammaire</a></li>
<li class="chapter" data-level="3.1.2" data-path="sect031.html"><a href="sect031.html#sect0312"><i class="fa fa-check"></i><b>3.1.2</b> Types de géométries</a></li>
<li class="chapter" data-level="3.1.3" data-path="sect031.html"><a href="sect031.html#sect0313"><i class="fa fa-check"></i><b>3.1.3</b> Habillage</a></li>
<li class="chapter" data-level="3.1.4" data-path="sect031.html"><a href="sect031.html#utilisation-des-thèmes"><i class="fa fa-check"></i><b>3.1.4</b> Utilisation des thèmes</a></li>
<li class="chapter" data-level="3.1.5" data-path="sect031.html"><a href="sect031.html#sect0314"><i class="fa fa-check"></i><b>3.1.5</b> Composition d’une figure avec plusieurs graphiques</a></li>
<li class="chapter" data-level="3.1.6" data-path="sect031.html"><a href="sect031.html#sect0315"><i class="fa fa-check"></i><b>3.1.6</b> Couleur</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="sect032.html"><a href="sect032.html"><i class="fa fa-check"></i><b>3.2</b> Principaux graphiques</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="sect032.html"><a href="sect032.html#sect0321"><i class="fa fa-check"></i><b>3.2.1</b> Histogramme</a></li>
<li class="chapter" data-level="3.2.2" data-path="sect032.html"><a href="sect032.html#sect0322"><i class="fa fa-check"></i><b>3.2.2</b> Graphique de densité</a></li>
<li class="chapter" data-level="3.2.3" data-path="sect032.html"><a href="sect032.html#sect0323"><i class="fa fa-check"></i><b>3.2.3</b> Nuage de points</a></li>
<li class="chapter" data-level="3.2.4" data-path="sect032.html"><a href="sect032.html#sect0324"><i class="fa fa-check"></i><b>3.2.4</b> Graphique en ligne</a></li>
<li class="chapter" data-level="3.2.5" data-path="sect032.html"><a href="sect032.html#sect0325"><i class="fa fa-check"></i><b>3.2.5</b> Boîte à moustaches</a></li>
<li class="chapter" data-level="3.2.6" data-path="sect032.html"><a href="sect032.html#sect0326"><i class="fa fa-check"></i><b>3.2.6</b> Graphique en violon</a></li>
<li class="chapter" data-level="3.2.7" data-path="sect032.html"><a href="sect032.html#sect0327"><i class="fa fa-check"></i><b>3.2.7</b> Graphique en barre</a></li>
<li class="chapter" data-level="3.2.8" data-path="sect032.html"><a href="sect032.html#sect0328"><i class="fa fa-check"></i><b>3.2.8</b> Graphique circulaire</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="sect033.html"><a href="sect033.html"><i class="fa fa-check"></i><b>3.3</b> Graphiques spéciaux</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="sect033.html"><a href="sect033.html#sect0331"><i class="fa fa-check"></i><b>3.3.1</b> Graphique en radar</a></li>
<li class="chapter" data-level="3.3.2" data-path="sect033.html"><a href="sect033.html#sect0332"><i class="fa fa-check"></i><b>3.3.2</b> Diagramme d’accord</a></li>
<li class="chapter" data-level="3.3.3" data-path="sect033.html"><a href="sect033.html#sect0333"><i class="fa fa-check"></i><b>3.3.3</b> Nuage de mots</a></li>
<li class="chapter" data-level="3.3.4" data-path="sect033.html"><a href="sect033.html#sect0334"><i class="fa fa-check"></i><b>3.3.4</b> Carte proportionnelle</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="sect034.html"><a href="sect034.html"><i class="fa fa-check"></i><b>3.4</b> Cartes</a></li>
<li class="chapter" data-level="3.5" data-path="sect035.html"><a href="sect035.html"><i class="fa fa-check"></i><b>3.5</b> Exportation des graphiques</a></li>
<li class="chapter" data-level="3.6" data-path="sect036.html"><a href="sect036.html"><i class="fa fa-check"></i><b>3.6</b> Conclusion sur les graphiques</a></li>
</ul></li>
<li class="part"><span><b>III Analyses bivariées</b></span></li>
<li class="chapter" data-level="4" data-path="chap04.html"><a href="chap04.html"><i class="fa fa-check"></i><b>4</b> Relation linéaire entre deux variables quantitatives</a>
<ul>
<li class="chapter" data-level="4.1" data-path="sect041.html"><a href="sect041.html"><i class="fa fa-check"></i><b>4.1</b> Bref retour sur le postulat de la relation linéaire</a></li>
<li class="chapter" data-level="4.2" data-path="sect042.html"><a href="sect042.html"><i class="fa fa-check"></i><b>4.2</b> Covariance</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="sect042.html"><a href="sect042.html#sect0421"><i class="fa fa-check"></i><b>4.2.1</b> Formulation</a></li>
<li class="chapter" data-level="4.2.2" data-path="sect042.html"><a href="sect042.html#sect0422"><i class="fa fa-check"></i><b>4.2.2</b> Interprétation</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="sect043.html"><a href="sect043.html"><i class="fa fa-check"></i><b>4.3</b> Corrélation</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="sect043.html"><a href="sect043.html#sect0431"><i class="fa fa-check"></i><b>4.3.1</b> Formulation</a></li>
<li class="chapter" data-level="4.3.2" data-path="sect043.html"><a href="sect043.html#sect0432"><i class="fa fa-check"></i><b>4.3.2</b> Interprétation</a></li>
<li class="chapter" data-level="4.3.3" data-path="sect043.html"><a href="sect043.html#sect0433"><i class="fa fa-check"></i><b>4.3.3</b> Corrélations pour des variables anormalement distribuées (coefficient de Spearman, tau de Kendall)</a></li>
<li class="chapter" data-level="4.3.4" data-path="sect043.html"><a href="sect043.html#sect0434"><i class="fa fa-check"></i><b>4.3.4</b> Corrélations robustes (<em>Biweight midcorrelation</em>, <em>Percentage bend correlation</em> et la corrélation <em>pi</em> de Shepherd)</a></li>
<li class="chapter" data-level="4.3.5" data-path="sect043.html"><a href="sect043.html#sect0435"><i class="fa fa-check"></i><b>4.3.5</b> Significativité des coefficients de corrélation</a></li>
<li class="chapter" data-level="4.3.6" data-path="sect043.html"><a href="sect043.html#sect0436"><i class="fa fa-check"></i><b>4.3.6</b> Corrélation partielle</a></li>
<li class="chapter" data-level="4.3.7" data-path="sect043.html"><a href="sect043.html#sect0437"><i class="fa fa-check"></i><b>4.3.7</b> Mise en œuvre dans R</a></li>
<li class="chapter" data-level="4.3.8" data-path="sect043.html"><a href="sect043.html#sect0438"><i class="fa fa-check"></i><b>4.3.8</b> Comment rapporter des valeurs de corrélations?</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="sect044.html"><a href="sect044.html"><i class="fa fa-check"></i><b>4.4</b> Régression linéaire simple</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="sect044.html"><a href="sect044.html#sect0441"><i class="fa fa-check"></i><b>4.4.1</b> Principe de base de la régression linéaire simple</a></li>
<li class="chapter" data-level="4.4.2" data-path="sect044.html"><a href="sect044.html#sect0442"><i class="fa fa-check"></i><b>4.4.2</b> Formulation de la droite de régression des moindres carrés ordinaires</a></li>
<li class="chapter" data-level="4.4.3" data-path="sect044.html"><a href="sect044.html#sect0443"><i class="fa fa-check"></i><b>4.4.3</b> Mesure de la qualité d’ajustement du modèle</a></li>
<li class="chapter" data-level="4.4.4" data-path="sect044.html"><a href="sect044.html#sect0444"><i class="fa fa-check"></i><b>4.4.4</b> Mise en œuvre dans R</a></li>
<li class="chapter" data-level="4.4.5" data-path="sect044.html"><a href="sect044.html#sect0445"><i class="fa fa-check"></i><b>4.4.5</b> Comment rapporter une régression linéaire simple</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="sect045.html"><a href="sect045.html"><i class="fa fa-check"></i><b>4.5</b> Quiz de révision du chapitre</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="chap05.html"><a href="chap05.html"><i class="fa fa-check"></i><b>5</b> Relation entre deux variables qualitatives</a>
<ul>
<li class="chapter" data-level="5.1" data-path="sect051.html"><a href="sect051.html"><i class="fa fa-check"></i><b>5.1</b> Construction de tableau de contingence</a></li>
<li class="chapter" data-level="5.2" data-path="sect052.html"><a href="sect052.html"><i class="fa fa-check"></i><b>5.2</b> Test du khi-deux</a></li>
<li class="chapter" data-level="5.3" data-path="sect053.html"><a href="sect053.html"><i class="fa fa-check"></i><b>5.3</b> Mise en œuvre dans R</a></li>
<li class="chapter" data-level="5.4" data-path="sect054.html"><a href="sect054.html"><i class="fa fa-check"></i><b>5.4</b> Interprétation d’un tableau de contingence</a></li>
<li class="chapter" data-level="5.5" data-path="sect055.html"><a href="sect055.html"><i class="fa fa-check"></i><b>5.5</b> Quiz de révision du chapitre</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="chap06.html"><a href="chap06.html"><i class="fa fa-check"></i><b>6</b> Relation entre une variable qualitative et une variable quantitative</a>
<ul>
<li class="chapter" data-level="6.1" data-path="sect061.html"><a href="sect061.html"><i class="fa fa-check"></i><b>6.1</b> Relation entre une variable quantitative et une variable qualitative à deux modalités</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="sect061.html"><a href="sect061.html#sect0611"><i class="fa fa-check"></i><b>6.1.1</b> Test <em>t</em> et ses différentes variantes</a></li>
<li class="chapter" data-level="6.1.2" data-path="sect061.html"><a href="sect061.html#sect0612"><i class="fa fa-check"></i><b>6.1.2</b> Test non paramétrique de Wilcoxon</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="sect062.html"><a href="sect062.html"><i class="fa fa-check"></i><b>6.2</b> Relation entre une variable quantitative et une variable qualitative à plus de deux modalités</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="sect062.html"><a href="sect062.html#sect0621"><i class="fa fa-check"></i><b>6.2.1</b> Analyse de variance</a></li>
<li class="chapter" data-level="6.2.2" data-path="sect062.html"><a href="sect062.html#sect0622"><i class="fa fa-check"></i><b>6.2.2</b> Test non paramétrique de Kruskal-Wallis</a></li>
<li class="chapter" data-level="6.2.3" data-path="sect062.html"><a href="sect062.html#sect0623"><i class="fa fa-check"></i><b>6.2.3</b> Mise en œuvre dans R</a></li>
<li class="chapter" data-level="6.2.4" data-path="sect062.html"><a href="sect062.html#sect0624"><i class="fa fa-check"></i><b>6.2.4</b> Comment rapporter les résultats d’une ANOVA et du test de Kruskal-Wallis</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="sect063.html"><a href="sect063.html"><i class="fa fa-check"></i><b>6.3</b> Conclusion sur la troisième partie</a></li>
<li class="chapter" data-level="6.4" data-path="sect064.html"><a href="sect064.html"><i class="fa fa-check"></i><b>6.4</b> Quiz de révision du chapitre</a></li>
</ul></li>
<li class="part"><span><b>IV Modèles de régression</b></span></li>
<li class="chapter" data-level="7" data-path="chap07.html"><a href="chap07.html"><i class="fa fa-check"></i><b>7</b> Régression linéaire multiple</a>
<ul>
<li class="chapter" data-level="7.1" data-path="sect071.html"><a href="sect071.html"><i class="fa fa-check"></i><b>7.1</b> Objectifs de la régression linéaire multiple et construction d’un modèle de régression</a></li>
<li class="chapter" data-level="7.2" data-path="sect072.html"><a href="sect072.html"><i class="fa fa-check"></i><b>7.2</b> Principes de base de la régression linéaire multiple</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="sect072.html"><a href="sect072.html#sect0721"><i class="fa fa-check"></i><b>7.2.1</b> Un peu d’équations…</a></li>
<li class="chapter" data-level="7.2.2" data-path="sect072.html"><a href="sect072.html#sect0722"><i class="fa fa-check"></i><b>7.2.2</b> Hypothèses de la régression linéaire multiple</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="sect073.html"><a href="sect073.html"><i class="fa fa-check"></i><b>7.3</b> Évaluation de la qualité d’ajustement du modèle</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="sect073.html"><a href="sect073.html#sect0731"><i class="fa fa-check"></i><b>7.3.1</b> Mesures de la qualité d’un modèle</a></li>
<li class="chapter" data-level="7.3.2" data-path="sect073.html"><a href="sect073.html#sect0732"><i class="fa fa-check"></i><b>7.3.2</b> Comparaison des modèles incrémentiels</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="sect074.html"><a href="sect074.html"><i class="fa fa-check"></i><b>7.4</b> Différentes mesures pour les coefficients de régression</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="sect074.html"><a href="sect074.html#sect0741"><i class="fa fa-check"></i><b>7.4.1</b> Coefficients de régression : évaluer l’effet des variables indépendantes</a></li>
<li class="chapter" data-level="7.4.2" data-path="sect074.html"><a href="sect074.html#sect0742"><i class="fa fa-check"></i><b>7.4.2</b> Coefficients de régression standardisés : repérer les variables les plus importantes du modèle</a></li>
<li class="chapter" data-level="7.4.3" data-path="sect074.html"><a href="sect074.html#sect0743"><i class="fa fa-check"></i><b>7.4.3</b> Significativité des coefficients de régression : valeurs de <em>t</em> et de <em>p</em></a></li>
<li class="chapter" data-level="7.4.4" data-path="sect074.html"><a href="sect074.html#sect0744"><i class="fa fa-check"></i><b>7.4.4</b> Intervalle de confiance des coefficients</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="sect075.html"><a href="sect075.html"><i class="fa fa-check"></i><b>7.5</b> Introduction de variables explicatives particulières</a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="sect075.html"><a href="sect075.html#sect0751"><i class="fa fa-check"></i><b>7.5.1</b> Exploration des relations non linéaires</a></li>
<li class="chapter" data-level="7.5.2" data-path="sect075.html"><a href="sect075.html#sect0752"><i class="fa fa-check"></i><b>7.5.2</b> Variable indépendante qualitative dichotomique</a></li>
<li class="chapter" data-level="7.5.3" data-path="sect075.html"><a href="sect075.html#sect0753"><i class="fa fa-check"></i><b>7.5.3</b> Variable indépendante qualitative polytomique</a></li>
<li class="chapter" data-level="7.5.4" data-path="sect075.html"><a href="sect075.html#sect0754"><i class="fa fa-check"></i><b>7.5.4</b> Variables d’interaction</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="sect076.html"><a href="sect076.html"><i class="fa fa-check"></i><b>7.6</b> Diagnostics de la régression</a>
<ul>
<li class="chapter" data-level="7.6.1" data-path="sect076.html"><a href="sect076.html#sect0761"><i class="fa fa-check"></i><b>7.6.1</b> Nombre d’observations</a></li>
<li class="chapter" data-level="7.6.2" data-path="sect076.html"><a href="sect076.html#sect0762"><i class="fa fa-check"></i><b>7.6.2</b> Normalité des résidus</a></li>
<li class="chapter" data-level="7.6.3" data-path="sect076.html"><a href="sect076.html#sect0763"><i class="fa fa-check"></i><b>7.6.3</b> Linéarité et homoscédasticité des résidus</a></li>
<li class="chapter" data-level="7.6.4" data-path="sect076.html"><a href="sect076.html#sect0764"><i class="fa fa-check"></i><b>7.6.4</b> Absence de multicolinéarité excessive</a></li>
<li class="chapter" data-level="7.6.5" data-path="sect076.html"><a href="sect076.html#sect0766"><i class="fa fa-check"></i><b>7.6.5</b> Absence d’observations aberrantes</a></li>
</ul></li>
<li class="chapter" data-level="7.7" data-path="sect077.html"><a href="sect077.html"><i class="fa fa-check"></i><b>7.7</b> Mise en œuvre dans R</a>
<ul>
<li class="chapter" data-level="7.7.1" data-path="sect077.html"><a href="sect077.html#sect0771"><i class="fa fa-check"></i><b>7.7.1</b> Fonctions <code>lm</code>, <code>summary()</code> et <code>confint()</code></a></li>
<li class="chapter" data-level="7.7.2" data-path="sect077.html"><a href="sect077.html#sect0772"><i class="fa fa-check"></i><b>7.7.2</b> Comparaison des modèles</a></li>
<li class="chapter" data-level="7.7.3" data-path="sect077.html"><a href="sect077.html#sect0773"><i class="fa fa-check"></i><b>7.7.3</b> Diagnostic sur un modèle</a></li>
<li class="chapter" data-level="7.7.4" data-path="sect077.html"><a href="sect077.html#sect0774"><i class="fa fa-check"></i><b>7.7.4</b> Graphiques pour les effets marginaux</a></li>
</ul></li>
<li class="chapter" data-level="7.8" data-path="sect078.html"><a href="sect078.html"><i class="fa fa-check"></i><b>7.8</b> Quiz de révision du chapitre</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="chap08.html"><a href="chap08.html"><i class="fa fa-check"></i><b>8</b> Régressions linéaires généralisées (GLM)</a>
<ul>
<li class="chapter" data-level="8.1" data-path="sect081.html"><a href="sect081.html"><i class="fa fa-check"></i><b>8.1</b> Qu’est qu’un modèle GLM?</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="sect081.html"><a href="sect081.html#sect0811"><i class="fa fa-check"></i><b>8.1.1</b> Formulation d’un GLM</a></li>
<li class="chapter" data-level="8.1.2" data-path="sect081.html"><a href="sect081.html#sect0812"><i class="fa fa-check"></i><b>8.1.2</b> Autres distributions et rôle de la fonction de lien</a></li>
<li class="chapter" data-level="8.1.3" data-path="sect081.html"><a href="sect081.html#sect0813"><i class="fa fa-check"></i><b>8.1.3</b> Conditions d’application</a></li>
<li class="chapter" data-level="8.1.4" data-path="sect081.html"><a href="sect081.html#sect0814"><i class="fa fa-check"></i><b>8.1.4</b> Résidus et déviance</a></li>
<li class="chapter" data-level="8.1.5" data-path="sect081.html"><a href="sect081.html#sect0815"><i class="fa fa-check"></i><b>8.1.5</b> Vérification l’ajustement</a></li>
<li class="chapter" data-level="8.1.6" data-path="sect081.html"><a href="sect081.html#sect0816"><i class="fa fa-check"></i><b>8.1.6</b> Comparaison de deux modèles GLM</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="sect082.html"><a href="sect082.html"><i class="fa fa-check"></i><b>8.2</b> Modèles GLM pour des variables qualitatives</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="sect082.html"><a href="sect082.html#sect0821"><i class="fa fa-check"></i><b>8.2.1</b> Modèle logistique binomial</a></li>
<li class="chapter" data-level="8.2.2" data-path="sect082.html"><a href="sect082.html#sect0822"><i class="fa fa-check"></i><b>8.2.2</b> Modèle probit binomial</a></li>
<li class="chapter" data-level="8.2.3" data-path="sect082.html"><a href="sect082.html#sect0823"><i class="fa fa-check"></i><b>8.2.3</b> Modèle logistique des cotes proportionnelles</a></li>
<li class="chapter" data-level="8.2.4" data-path="sect082.html"><a href="sect082.html#sect0824"><i class="fa fa-check"></i><b>8.2.4</b> Modèle logistique multinomial</a></li>
<li class="chapter" data-level="8.2.5" data-path="sect082.html"><a href="sect082.html#conclusion-sur-les-modèles-pour-des-variables-qualitatives"><i class="fa fa-check"></i><b>8.2.5</b> Conclusion sur les modèles pour des variables qualitatives</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="sect084.html"><a href="sect084.html"><i class="fa fa-check"></i><b>8.3</b> Modèles GLM pour des variables de comptage</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="sect084.html"><a href="sect084.html#sect0841"><i class="fa fa-check"></i><b>8.3.1</b> Modèle de Poisson</a></li>
<li class="chapter" data-level="8.3.2" data-path="sect084.html"><a href="sect084.html#sect0842"><i class="fa fa-check"></i><b>8.3.2</b> Modèle binomial négatif</a></li>
<li class="chapter" data-level="8.3.3" data-path="sect084.html"><a href="sect084.html#sect0843"><i class="fa fa-check"></i><b>8.3.3</b> Modèle de Poisson avec excès fixe de zéros</a></li>
<li class="chapter" data-level="8.3.4" data-path="sect084.html"><a href="sect084.html#sect0844"><i class="fa fa-check"></i><b>8.3.4</b> Modèle de Poisson avec excès ajusté de zéros</a></li>
<li class="chapter" data-level="8.3.5" data-path="sect084.html"><a href="sect084.html#sect0845"><i class="fa fa-check"></i><b>8.3.5</b> Conclusion sur les modèles destinés à des variables de comptage</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="sect085.html"><a href="sect085.html"><i class="fa fa-check"></i><b>8.4</b> Modèles GLM pour des variables continues</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="sect085.html"><a href="sect085.html#sect0851"><i class="fa fa-check"></i><b>8.4.1</b> Modèle GLM gaussien</a></li>
<li class="chapter" data-level="8.4.2" data-path="sect085.html"><a href="sect085.html#sect0852"><i class="fa fa-check"></i><b>8.4.2</b> Modèle GLM avec une distribution de Student</a></li>
<li class="chapter" data-level="8.4.3" data-path="sect085.html"><a href="sect085.html#sect0853"><i class="fa fa-check"></i><b>8.4.3</b> Modèle GLM avec distribution Gamma</a></li>
<li class="chapter" data-level="8.4.4" data-path="sect085.html"><a href="sect085.html#sect0854"><i class="fa fa-check"></i><b>8.4.4</b> Modèle GLM avec une distribution bêta</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="sect086.html"><a href="sect086.html"><i class="fa fa-check"></i><b>8.5</b> Conclusion sur les modèles linéaires généralisés</a></li>
<li class="chapter" data-level="8.6" data-path="sect087.html"><a href="sect087.html"><i class="fa fa-check"></i><b>8.6</b> Quiz de révision du chapitre</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="chap09.html"><a href="chap09.html"><i class="fa fa-check"></i><b>9</b> Régressions à effets mixtes (GLMM)</a>
<ul>
<li class="chapter" data-level="9.1" data-path="sect091.html"><a href="sect091.html"><i class="fa fa-check"></i><b>9.1</b> Introduction</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="sect091.html"><a href="sect091.html#sect0911"><i class="fa fa-check"></i><b>9.1.1</b> Indépendance des observations et effets de groupes</a></li>
<li class="chapter" data-level="9.1.2" data-path="sect091.html"><a href="sect091.html#sect0912"><i class="fa fa-check"></i><b>9.1.2</b> Terminologie: effets fixes et effets aléatoires</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="sect092.html"><a href="sect092.html"><i class="fa fa-check"></i><b>9.2</b> Principes de base des GLMM</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="sect092.html"><a href="sect092.html#sect0921"><i class="fa fa-check"></i><b>9.2.1</b> GLMM avec constantes aléatoires</a></li>
<li class="chapter" data-level="9.2.2" data-path="sect092.html"><a href="sect092.html#sect0923"><i class="fa fa-check"></i><b>9.2.2</b> GLMM avec pentes aléatoires</a></li>
<li class="chapter" data-level="9.2.3" data-path="sect092.html"><a href="sect092.html#sect0924"><i class="fa fa-check"></i><b>9.2.3</b> GLMM avec constantes et pentes aléatoires</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="sect093.html"><a href="sect093.html"><i class="fa fa-check"></i><b>9.3</b> Conditions d’application des GLMM</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="sect093.html"><a href="sect093.html#sect0931"><i class="fa fa-check"></i><b>9.3.1</b> Vérification de la distribution des effets aléatoires</a></li>
<li class="chapter" data-level="9.3.2" data-path="sect093.html"><a href="sect093.html#sect0932"><i class="fa fa-check"></i><b>9.3.2</b> Homogénéité des variances au sein des groupes</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="sect094.html"><a href="sect094.html"><i class="fa fa-check"></i><b>9.4</b> Inférence dans les modèles GLMM</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="sect094.html"><a href="sect094.html#sect0941"><i class="fa fa-check"></i><b>9.4.1</b> Inférence pour les effets fixes</a></li>
<li class="chapter" data-level="9.4.2" data-path="sect094.html"><a href="sect094.html#sect0942"><i class="fa fa-check"></i><b>9.4.2</b> Inférence pour les effets aléatoires, effet global</a></li>
<li class="chapter" data-level="9.4.3" data-path="sect094.html"><a href="sect094.html#sect0943"><i class="fa fa-check"></i><b>9.4.3</b> Inférence pour les effets aléatoires, des constantes et des pentes</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="sect095.html"><a href="sect095.html"><i class="fa fa-check"></i><b>9.5</b> Conclusion sur les GLMM</a></li>
<li class="chapter" data-level="9.6" data-path="sect096.html"><a href="sect096.html"><i class="fa fa-check"></i><b>9.6</b> Mise en œuvre des GLMM dans R</a>
<ul>
<li class="chapter" data-level="9.6.1" data-path="sect096.html"><a href="sect096.html#sect0961"><i class="fa fa-check"></i><b>9.6.1</b> Ajustement du modèle avec uniquement une constante aléatoire</a></li>
<li class="chapter" data-level="9.6.2" data-path="sect096.html"><a href="sect096.html#sect0962"><i class="fa fa-check"></i><b>9.6.2</b> Ajustement du modèle avec constantes et pentes aléatoires</a></li>
</ul></li>
<li class="chapter" data-level="9.7" data-path="sect097.html"><a href="sect097.html"><i class="fa fa-check"></i><b>9.7</b> Quiz de révision du chapitre</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="chap10.html"><a href="chap10.html"><i class="fa fa-check"></i><b>10</b> Régressions multiniveaux</a>
<ul>
<li class="chapter" data-level="10.1" data-path="sect101.html"><a href="sect101.html"><i class="fa fa-check"></i><b>10.1</b> Modèles multiniveaux : deux intérêts majeurs</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="sect101.html"><a href="sect101.html#sect1011"><i class="fa fa-check"></i><b>10.1.1</b> Répartition de la variance entre les différents niveaux</a></li>
<li class="chapter" data-level="10.1.2" data-path="sect101.html"><a href="sect101.html#sect1012"><i class="fa fa-check"></i><b>10.1.2</b> Estimation des coefficients aux différents niveaux</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="sect102.html"><a href="sect102.html"><i class="fa fa-check"></i><b>10.2</b> Différents types de modèles multiniveaux</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="sect102.html"><a href="sect102.html#sect1021"><i class="fa fa-check"></i><b>10.2.1</b> Description du jeu de données utilisé</a></li>
<li class="chapter" data-level="10.2.2" data-path="sect102.html"><a href="sect102.html#sect1022"><i class="fa fa-check"></i><b>10.2.2</b> Démarche classique pour les modèles multiniveaux</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="sect103.html"><a href="sect103.html"><i class="fa fa-check"></i><b>10.3</b> Conditions d’application des régressions multiniveaux</a></li>
<li class="chapter" data-level="10.4" data-path="sect104.html"><a href="sect104.html"><i class="fa fa-check"></i><b>10.4</b> Mise en œuvre dans R</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="sect104.html"><a href="sect104.html#sect1041"><i class="fa fa-check"></i><b>10.4.1</b> Le modèle vide</a></li>
<li class="chapter" data-level="10.4.2" data-path="sect104.html"><a href="sect104.html#sect1042"><i class="fa fa-check"></i><b>10.4.2</b> Modèle avec les variables indépendantes du niveau 1</a></li>
<li class="chapter" data-level="10.4.3" data-path="sect104.html"><a href="sect104.html#sect1043"><i class="fa fa-check"></i><b>10.4.3</b> Modèle avec les variables indépendantes aux niveaux 1 et 2</a></li>
<li class="chapter" data-level="10.4.4" data-path="sect104.html"><a href="sect104.html#sect10414"><i class="fa fa-check"></i><b>10.4.4</b> Modèle complet avec une interaction</a></li>
<li class="chapter" data-level="10.4.5" data-path="sect104.html"><a href="sect104.html#sect1045"><i class="fa fa-check"></i><b>10.4.5</b> Comparaison des quatre modèles</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="sect105.html"><a href="sect105.html"><i class="fa fa-check"></i><b>10.5</b> Quiz de révision du chapitre</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="chap11.html"><a href="chap11.html"><i class="fa fa-check"></i><b>11</b> Modèles généralisés additifs</a>
<ul>
<li class="chapter" data-level="11.1" data-path="sect111.html"><a href="sect111.html"><i class="fa fa-check"></i><b>11.1</b> Introduction</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="sect111.html"><a href="sect111.html#sect1111"><i class="fa fa-check"></i><b>11.1.1</b> Non linéarité fonctionnelle</a></li>
<li class="chapter" data-level="11.1.2" data-path="sect111.html"><a href="sect111.html#sect1112"><i class="fa fa-check"></i><b>11.1.2</b> Non linéarité avec des polynomiales</a></li>
<li class="chapter" data-level="11.1.3" data-path="sect111.html"><a href="sect111.html#sect1113"><i class="fa fa-check"></i><b>11.1.3</b> Non linéarité par segments</a></li>
<li class="chapter" data-level="11.1.4" data-path="sect111.html"><a href="sect111.html#sect1114"><i class="fa fa-check"></i><b>11.1.4</b> Non linéarité avec des <em>splines</em></a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="sect112.html"><a href="sect112.html"><i class="fa fa-check"></i><b>11.2</b> <em>Spline</em> de régression et <em>spline</em> de lissage</a></li>
<li class="chapter" data-level="11.3" data-path="sect113.html"><a href="sect113.html"><i class="fa fa-check"></i><b>11.3</b> Interprétation d’une <em>spline</em></a></li>
<li class="chapter" data-level="11.4" data-path="sect114.html"><a href="sect114.html"><i class="fa fa-check"></i><b>11.4</b> Multicolinéarité non linéaire</a></li>
<li class="chapter" data-level="11.5" data-path="sect115.html"><a href="sect115.html"><i class="fa fa-check"></i><b>11.5</b> <em>Splines</em> avancées</a>
<ul>
<li class="chapter" data-level="11.5.1" data-path="sect115.html"><a href="sect115.html#sect1151"><i class="fa fa-check"></i><b>11.5.1</b> <em>Splines</em> cycliques</a></li>
<li class="chapter" data-level="11.5.2" data-path="sect115.html"><a href="sect115.html#sect1152"><i class="fa fa-check"></i><b>11.5.2</b> Splines par groupe</a></li>
<li class="chapter" data-level="11.5.3" data-path="sect115.html"><a href="sect115.html#sect1153"><i class="fa fa-check"></i><b>11.5.3</b> <em>Splines</em> multivariées et <em>splines</em> d’interaction</a></li>
</ul></li>
<li class="chapter" data-level="11.6" data-path="sect116.html"><a href="sect116.html"><i class="fa fa-check"></i><b>11.6</b> Mise en oeuvre dans R</a></li>
<li class="chapter" data-level="11.7" data-path="sect117.html"><a href="sect117.html"><i class="fa fa-check"></i><b>11.7</b> GAMM</a></li>
<li class="chapter" data-level="11.8" data-path="sect118.html"><a href="sect118.html"><i class="fa fa-check"></i><b>11.8</b> Quiz de révision du chapitre</a></li>
</ul></li>
<li class="part"><span><b>V Analyses exploratoires multivariées</b></span></li>
<li class="chapter" data-level="12" data-path="chap12.html"><a href="chap12.html"><i class="fa fa-check"></i><b>12</b> Méthodes factorielles</a>
<ul>
<li class="chapter" data-level="12.1" data-path="sect121.html"><a href="sect121.html"><i class="fa fa-check"></i><b>12.1</b> Aperçu des méthodes factorielles</a>
<ul>
<li class="chapter" data-level="12.1.1" data-path="sect121.html"><a href="sect121.html#sect1211"><i class="fa fa-check"></i><b>12.1.1</b> Méthodes factorielles et types de données</a></li>
<li class="chapter" data-level="12.1.2" data-path="sect121.html"><a href="sect121.html#sect1212"><i class="fa fa-check"></i><b>12.1.2</b> Bref historique des méthodes factorielles</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="sect122.html"><a href="sect122.html"><i class="fa fa-check"></i><b>12.2</b> Analyses en composantes principales (ACP)</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="sect122.html"><a href="sect122.html#sect1221"><i class="fa fa-check"></i><b>12.2.1</b> Recherche d’une simplification</a></li>
<li class="chapter" data-level="12.2.2" data-path="sect122.html"><a href="sect122.html#sect1222"><i class="fa fa-check"></i><b>12.2.2</b> Aides à l’interprétation</a></li>
<li class="chapter" data-level="12.2.3" data-path="sect122.html"><a href="sect122.html#sect1223"><i class="fa fa-check"></i><b>12.2.3</b> Mise en œuvre dans R</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="sect123.html"><a href="sect123.html"><i class="fa fa-check"></i><b>12.3</b> Analyse factorielle des correspondances (AFC)</a>
<ul>
<li class="chapter" data-level="12.3.1" data-path="sect123.html"><a href="sect123.html#sect1231"><i class="fa fa-check"></i><b>12.3.1</b> Recherche d’une simplification basée sur la distance du khi-deux</a></li>
<li class="chapter" data-level="12.3.2" data-path="sect123.html"><a href="sect123.html#sect1232"><i class="fa fa-check"></i><b>12.3.2</b> Aides à l’interprétation</a></li>
<li class="chapter" data-level="12.3.3" data-path="sect123.html"><a href="sect123.html#sect1233"><i class="fa fa-check"></i><b>12.3.3</b> Mise en œuvre dans R</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="sect124.html"><a href="sect124.html"><i class="fa fa-check"></i><b>12.4</b> Analyse de correspondances multiples (ACM)</a>
<ul>
<li class="chapter" data-level="12.4.1" data-path="sect124.html"><a href="sect124.html#sect1241"><i class="fa fa-check"></i><b>12.4.1</b> Aides à l’interprétation</a></li>
<li class="chapter" data-level="12.4.2" data-path="sect124.html"><a href="sect124.html#sect1242"><i class="fa fa-check"></i><b>12.4.2</b> Mise en œuvre dans R</a></li>
</ul></li>
<li class="chapter" data-level="12.5" data-path="sect125.html"><a href="sect125.html"><i class="fa fa-check"></i><b>12.5</b> Quiz de révision du chapitre</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="chap13.html"><a href="chap13.html"><i class="fa fa-check"></i><b>13</b> Méthodes de classification non supervisée</a>
<ul>
<li class="chapter" data-level="13.1" data-path="sect131.html"><a href="sect131.html"><i class="fa fa-check"></i><b>13.1</b> Méthodes de classification : un aperçu</a></li>
<li class="chapter" data-level="13.2" data-path="sect132.html"><a href="sect132.html"><i class="fa fa-check"></i><b>13.2</b> Notions essentielles en classification</a>
<ul>
<li class="chapter" data-level="13.2.1" data-path="sect132.html"><a href="sect132.html#sect1321"><i class="fa fa-check"></i><b>13.2.1</b> Distance</a></li>
<li class="chapter" data-level="13.2.2" data-path="sect132.html"><a href="sect132.html#sect1322"><i class="fa fa-check"></i><b>13.2.2</b> Inertie</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="sect133.html"><a href="sect133.html"><i class="fa fa-check"></i><b>13.3</b> Classification ascendante hiérarchique</a>
<ul>
<li class="chapter" data-level="13.3.1" data-path="sect133.html"><a href="sect133.html#sect1331"><i class="fa fa-check"></i><b>13.3.1</b> Fonctionnement de l’algorithme</a></li>
<li class="chapter" data-level="13.3.2" data-path="sect133.html"><a href="sect133.html#sect1332"><i class="fa fa-check"></i><b>13.3.2</b> Choisir le bon nombre de groupes</a></li>
<li class="chapter" data-level="13.3.3" data-path="sect133.html"><a href="sect133.html#sect1333"><i class="fa fa-check"></i><b>13.3.3</b> Limites de la classification ascendante hiérarchique</a></li>
<li class="chapter" data-level="13.3.4" data-path="sect133.html"><a href="sect133.html#sect1334"><i class="fa fa-check"></i><b>13.3.4</b> Mise en oeuvre dans R</a></li>
</ul></li>
<li class="chapter" data-level="13.4" data-path="sect134.html"><a href="sect134.html"><i class="fa fa-check"></i><b>13.4</b> Nuées dynamiques</a>
<ul>
<li class="chapter" data-level="13.4.1" data-path="sect134.html"><a href="sect134.html#sect1341"><i class="fa fa-check"></i><b>13.4.1</b> <em>K-means</em></a></li>
<li class="chapter" data-level="13.4.2" data-path="sect134.html"><a href="sect134.html#sect1342"><i class="fa fa-check"></i><b>13.4.2</b> K-médianes</a></li>
<li class="chapter" data-level="13.4.3" data-path="sect134.html"><a href="sect134.html#sect1343"><i class="fa fa-check"></i><b>13.4.3</b> K-médoïds</a></li>
<li class="chapter" data-level="13.4.4" data-path="sect134.html"><a href="sect134.html#sect1344"><i class="fa fa-check"></i><b>13.4.4</b> Mise en oeuvre dans R</a></li>
<li class="chapter" data-level="13.4.5" data-path="sect134.html"><a href="sect134.html#sect1346"><i class="fa fa-check"></i><b>13.4.5</b> Extensions en logique floue : <em>c-means</em>, <em>c-medoids</em></a></li>
</ul></li>
<li class="chapter" data-level="13.5" data-path="sect135.html"><a href="sect135.html"><i class="fa fa-check"></i><b>13.5</b> Conclusion sur la cinquième partie</a></li>
<li class="chapter" data-level="13.6" data-path="sect136.html"><a href="sect136.html"><i class="fa fa-check"></i><b>13.6</b> Quiz de révision du chapitre</a></li>
</ul></li>
<li class="part"><span><b>VI Annexes</b></span></li>
<li class="chapter" data-level="14" data-path="annexe1.html"><a href="annexe1.html"><i class="fa fa-check"></i><b>14</b> Table des valeurs critiques de khi-deux</a></li>
<li class="chapter" data-level="15" data-path="annexe2.html"><a href="annexe2.html"><i class="fa fa-check"></i><b>15</b> Table des valeurs critiques de Fisher</a></li>
<li class="chapter" data-level="16" data-path="annexe3.html"><a href="annexe3.html"><i class="fa fa-check"></i><b>16</b> Table des valeurs critiques de <em>t</em></a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Méthodes quantitatives en sciences sociales : un grand bol d’R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="sect074" class="section level2 hasAnchor" number="7.4">
<h2><span class="header-section-number">7.4</span> Différentes mesures pour les coefficients de régression<a href="sect074.html#sect074" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>La fonction <code>summary(nom du modèle)</code> permet d’obtenir les résultats du modèle de régression. D’emblée, signalons que le modèle est globalement significatif (<em>F</em>(6,10203) = 1123, <em>p</em> = 0,000) avec un R<sup>2</sup> de 0,4182 indiquant que les variables indépendantes du modèle expliquent 41,82nbsp;% de la variance du pourcentage de végétation dans les îlots de l’île de Montréal.</p>
<div class="sourceCode" id="cb645"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb645-1"><a href="sect074.html#cb645-1" aria-hidden="true" tabindex="-1"></a>modelereg <span class="ot">&lt;-</span> <span class="fu">lm</span>(VegPct <span class="sc">~</span> HABHA<span class="sc">+</span>AgeMedian<span class="sc">+</span>Pct_014<span class="sc">+</span>Pct_65P<span class="sc">+</span>Pct_MV<span class="sc">+</span>Pct_FR, <span class="at">data =</span> DataFinal)</span>
<span id="cb645-2"><a href="sect074.html#cb645-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelereg)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = VegPct ~ HABHA + AgeMedian + Pct_014 + Pct_65P + 
##     Pct_MV + Pct_FR, data = DataFinal)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -48.876  -9.757  -0.232   9.499 103.830 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 26.355774   0.882235  29.874   &lt;2e-16 ***
## HABHA       -0.070401   0.002202 -31.975   &lt;2e-16 ***
## AgeMedian    0.010790   0.006369   1.694   0.0902 .  
## Pct_014      1.084478   0.032179  33.702   &lt;2e-16 ***
## Pct_65P      0.400531   0.018835  21.265   &lt;2e-16 ***
## Pct_MV      -0.031112   0.010406  -2.990   0.0028 ** 
## Pct_FR      -0.348256   0.011640 -29.918   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 14.16 on 10203 degrees of freedom
## Multiple R-squared:  0.4182, Adjusted R-squared:  0.4179 
## F-statistic:  1223 on 6 and 10203 DF,  p-value: &lt; 2.2e-16</code></pre>
<div id="sect0741" class="section level3 hasAnchor" number="7.4.1">
<h3><span class="header-section-number">7.4.1</span> Coefficients de régression : évaluer l’effet des variables indépendantes<a href="sect074.html#sect0741" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Les différents résultats pour les coefficients sont reportés au tableau <a href="sect074.html#tab:dataregmodel2">7.2</a>.</p>
<p><strong>La constante</strong> (<span class="math inline">\(\beta_0\)</span>) est la valeur attendue de la variable dépendante (<em>Y</em>) quand les valeurs de toutes les variables indépendantes sont égales à 0. Pour ce modèle, quand les variables indépendantes sont égales à 0, plus du quart de la superficie des îlots serait en moyenne couverte par de la végétation (<span class="math inline">\(\beta_0\)</span> = 26,36). Notez que la constante n’a pas toujours une interprétation pratique. Il est par exemple très invraisemblable de trouver un îlot avec de la population dans lequel il n’y aurait aucune personne à faible revenu, aucune personne ne déclarant appartenir à une minorité visible, aucun enfant de moins de 15 ans et aucune personne âgée 65 ans et plus. La constante a donc avant tout un rôle mathématique dans le modèle.</p>
<p><strong>Le coefficient de régression</strong> (<span class="math inline">\(\beta_1\)</span> à <span class="math inline">\(\beta_k\)</span>) indique le changement de la variable dépendante (<em>Y</em>) lorsque la variable indépendante augmente d’une unité, toutes choses étant égales par ailleurs. Il permet ainsi d’évaluer l’effet d’une augmentation d’une unité dans laquelle est mesurée la VI sur la VD.</p>
<div class="bloc_attention">
<p><strong>Que signifie l’expression <em>toutes choses étant égales par ailleurs</em> pour un coefficient de régression?</strong></p>
<p>Après l’apprentissage du grec, grâce aux nombreuses équations intégrées au livre, passons au latin! L’expression <em>toutes choses étant égales par ailleurs</em> vient du latin <em>ceteris paribus</em>, à ne pas confondre avec <em>c’est terrible Paris en bus</em> (petite blague formulée par un étudiant ayant suivi le cours <em>Méthodes quantitatives appliquées en études urbaines</em> à l’INRS il y a quelques années)! Certains auteurs emploient encore <em>ceteris paribus</em> : il est donc possible que vous la retrouviez dans un article scientifique…</p>
<p>Plus sérieusement, l’expression <em>toutes choses étant égales par ailleurs</em> signifie que l’on estime l’effet de la variable indépendante sur la variable dépendante, si toutes les autres variables indépendantes restent constantes ou autrement dit, une fois contrôlés tous les autres prédicteurs.</p>
</div>
<table>
<caption>
<span id="tab:dataregmodel2">Tableau 7.2: </span>Différentes mesures pour les coefficients
</caption>
<thead>
<tr>
<th style="text-align:left;">
Variable
</th>
<th style="text-align:right;">
Coef.
</th>
<th style="text-align:right;">
Erreur type
</th>
<th style="text-align:right;">
Valeur de T
</th>
<th style="text-align:right;">
P
</th>
<th style="text-align:right;">
coef. 2,5 %
</th>
<th style="text-align:right;">
coef. 97,5 %
</th>
<th style="text-align:right;">
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Constante
</td>
<td style="text-align:right;">
26,356
</td>
<td style="text-align:right;">
0,882
</td>
<td style="text-align:right;">
29,870
</td>
<td style="text-align:right;">
0,000
</td>
<td style="text-align:right;">
24,626
</td>
<td style="text-align:right;">
28,085
</td>
<td style="text-align:right;">
***
</td>
</tr>
<tr>
<td style="text-align:left;">
HABHA
</td>
<td style="text-align:right;">
-0,070
</td>
<td style="text-align:right;">
0,002
</td>
<td style="text-align:right;">
-31,970
</td>
<td style="text-align:right;">
0,000
</td>
<td style="text-align:right;">
-0,075
</td>
<td style="text-align:right;">
-0,066
</td>
<td style="text-align:right;">
***
</td>
</tr>
<tr>
<td style="text-align:left;">
AgeMedian
</td>
<td style="text-align:right;">
0,011
</td>
<td style="text-align:right;">
0,006
</td>
<td style="text-align:right;">
1,690
</td>
<td style="text-align:right;">
0,090
</td>
<td style="text-align:right;">
-0,002
</td>
<td style="text-align:right;">
0,023
</td>
<td style="text-align:right;">
.
</td>
</tr>
<tr>
<td style="text-align:left;">
Pct_014
</td>
<td style="text-align:right;">
1,084
</td>
<td style="text-align:right;">
0,032
</td>
<td style="text-align:right;">
33,700
</td>
<td style="text-align:right;">
0,000
</td>
<td style="text-align:right;">
1,021
</td>
<td style="text-align:right;">
1,148
</td>
<td style="text-align:right;">
***
</td>
</tr>
<tr>
<td style="text-align:left;">
Pct_65P
</td>
<td style="text-align:right;">
0,401
</td>
<td style="text-align:right;">
0,019
</td>
<td style="text-align:right;">
21,260
</td>
<td style="text-align:right;">
0,000
</td>
<td style="text-align:right;">
0,364
</td>
<td style="text-align:right;">
0,437
</td>
<td style="text-align:right;">
***
</td>
</tr>
<tr>
<td style="text-align:left;">
Pct_MV
</td>
<td style="text-align:right;">
-0,031
</td>
<td style="text-align:right;">
0,010
</td>
<td style="text-align:right;">
-2,990
</td>
<td style="text-align:right;">
0,003
</td>
<td style="text-align:right;">
-0,052
</td>
<td style="text-align:right;">
-0,011
</td>
<td style="text-align:right;">
**
</td>
</tr>
<tr>
<td style="text-align:left;">
Pct_FR
</td>
<td style="text-align:right;">
-0,348
</td>
<td style="text-align:right;">
0,012
</td>
<td style="text-align:right;">
-29,920
</td>
<td style="text-align:right;">
0,000
</td>
<td style="text-align:right;">
-0,371
</td>
<td style="text-align:right;">
-0,325
</td>
<td style="text-align:right;">
***
</td>
</tr>
</tbody>
</table>
<p>À partir des coefficients du tableau <a href="sect074.html#tab:dataregmodel2">7.2</a>, l’équation du modèle de régression s’écrit alors comme suit :</p>
<p><code>VegPct = 26,356 − 0,070 HABHA  + 0,011 AgeMedian + 1,084 Pct_014 + 0,401 Pct_65P −0,031 Pct_MV − 0,348 Pct_FR + e</code></p>
<p><strong>Comment interpréter un coefficient de régression pour une variable indépendante?</strong></p>
<p>Le signe du coefficient de régression indique si la variable indépendante est associée positivement ou négativement avec la variable dépendante. Par exemple, plus la densité de population est importante à travers les îlots de l’île de Montréal, plus la couverture végétale diminue.</p>
<p>Quant à la valeur absolue du coefficient, elle indique la taille de l’effet du prédicteur. Par exemple, 1,084 signifie que si toutes les autres variables indépendantes restent constantes, alors le pourcentage de végétation dans l’îlot augmente de 1,084 points de pourcentage pour chaque différence d’un point de pourcentage d’enfants de moins de 15 ans. Toutes choses étant égales par ailleurs, une augmentation de 10nbsp;% d’enfants dans un îlot entraîne alors une hausse de 10,8nbsp;% de la couverture végétale dans l’îlot.</p>
<p>L’analyse des coefficients montre ainsi qu’une fois contrôlées les deux caractéristiques relatives à la forme urbaine (densité de population et âge médian des bâtiments), plus les pourcentages d’enfants et de personnes âgées sont élevés, plus la couverture végétale de l’îlot est importante (B = 1,084 et 0,401), toutes choses étant égales par ailleurs. À l’inverse, de plus grands pourcentages de personnes à faible revenu et de minorités sont associés à une plus faible couverture végétale (B = −0,348 et −0,031).</p>
<p><strong>L’erreur type du coefficient de régression</strong></p>
<p>L’erreur type d’un coefficient permet d’évaluer son niveau de précision, soit le degré d’incertitude vis-à-vis du coefficient. Succinctement, elle correspond à l’écart-type de l’estimation (coefficient); elle est ainsi toujours positive. Plus la valeur de l’erreur type est faible, plus l’estimation du coefficient est précise. Notez toutefois qu’il n’est pas judicieux de comparer les erreurs types des coefficients pour des variables exprimées dans des unités de mesure différentes.</p>
<p>Comme nous le verrons plus loin, l’utilité principale de l’erreur type est qu’elle permet de calculer la valeur de <em>t</em> et l’intervalle de confiance du coefficient de régression.</p>
</div>
<div id="sect0742" class="section level3 hasAnchor" number="7.4.2">
<h3><span class="header-section-number">7.4.2</span> Coefficients de régression standardisés : repérer les variables les plus importantes du modèle<a href="sect074.html#sect0742" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Un coefficient de régression est exprimé dans les unités de mesure des variables indépendante (VI) et dépendante (VD) : une augmentation d’une unité de la VI a un effet de <span class="math inline">\(\beta\)</span> (valeur de coefficient) unité de mesure sur la VD, toutes choses étant égales par ailleurs. Prenons l’exemple d’un modèle fictif dans lequel une variable indépendante mesurée en mètres obtient un coefficient de régression de 0,000502. Si cette variable était exprimée en kilomètres et non en mètres, son coefficient serait alors de 0,502 (<span class="math inline">\(0,000502 \times 1000 = 0,502\)</span>). Cela explique que pour certaines variables, il est souvent préférable de modifier l’unité de mesure, particulièrement pour les variables de distance ou de revenu. Par exemple, dans un modèle de régression, nous introduisons habituellement une variable de revenu par tranche de mille dollars ou le loyer mensuel par tranche de cent dollars, puisque les coefficients du revenu ou de loyer exprimé en dollars risquent d’être extrêmement faibles. Concrètement, cela signifie que nous divisons la variable <em>revenu</em> par 1000 et celle du <em>loyer</em> par 100 avant de l’introduire dans le modèle.</p>
<p>Du fait de leur unités de mesure souvent différentes, vous aurez compris que nous ne pouvons pas comparer directement les coefficients de régression afin de repérer la ou les variables indépendantes (<em>X</em>) qui ont les effets (impacts) les plus importants sur la variable dépendante (<em>Y</em>). Pour remédier à ce problème, nous utilisons les <strong>coefficients de régression standardisés</strong>. Ces coefficients standardisés sont simplement les valeurs de coefficients de régression qui seraient obtenus si toutes les variables du modèle (VD et VI) étaient préalablement centrées réduites (soit avec une moyenne égale à 0 et un écart-type égal à 1; consultez la section <a href="sect025.html#sect02552">2.5.5.2</a> pour un rappel). Puisque toutes les variables du modèle sont exprimées en écarts-types, les coefficients standardisés permettent ainsi d’évaluer <strong>l’effet relatif</strong> des VI sur la VD. Cela permet ainsi de repérer la ou les variables les plus « importantes » du modèle.</p>
<p><strong>L’interprétation d’un coefficient de régression standardisé est donc la suivante : il indique le changement en termes d’unités d’écart-type de la variable dépendante (Y) à chaque ajout d’un écart-type de la variable indépendante, toutes choses étant égales par ailleurs</strong>.</p>
<p>Le coefficient de régression standardisé peut être aussi facilement calculé en utilisant les écarts-types des deux variables VI et VD :</p>
<p><span class="math display" id="eq:CoefStand">\[\begin{equation}
\beta_{z}= \beta \frac{s_x}{s_y}
\tag{7.14}
\end{equation}\]</span>
</p>
<p>La syntaxe R ci-dessous illustre trois façons d’obtenir les coefficients standardisés :</p>
<ul>
<li>en centrant et réduisant préalablement les variables avec la fonction <code>scale</code> avant de construire le modèle avec la fonction <code>lm</code>;</li>
<li>en calculant les écarts-types de VD et de VI et en appliquant l’équation <a href="sect074.html#eq:CoefStand">(7.14)</a>;</li>
<li>avec la fonction <code>lm.beta</code> du <em>package</em> <code>QuantPsyc</code>. Cette dernière méthode est moins « verbeuse » (deux lignes de code uniquement), mais nécessite de charger un <em>package</em> supplémentaire.</li>
</ul>
<div class="sourceCode" id="cb647"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb647-1"><a href="sect074.html#cb647-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Modèle de régression</span></span>
<span id="cb647-2"><a href="sect074.html#cb647-2" aria-hidden="true" tabindex="-1"></a>Modele1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(VegPct <span class="sc">~</span> HABHA<span class="sc">+</span>AgeMedian<span class="sc">+</span>Pct_014<span class="sc">+</span>Pct_65P<span class="sc">+</span>Pct_MV<span class="sc">+</span>Pct_FR, <span class="at">data =</span> DataFinal)</span>
<span id="cb647-3"><a href="sect074.html#cb647-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb647-4"><a href="sect074.html#cb647-4" aria-hidden="true" tabindex="-1"></a><span class="co">#  Méthode 1 : lm sur des variables centrées réduites</span></span>
<span id="cb647-5"><a href="sect074.html#cb647-5" aria-hidden="true" tabindex="-1"></a>ModeleZ <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">scale</span>(VegPct) <span class="sc">~</span> <span class="fu">scale</span>(HABHA)<span class="sc">+</span><span class="fu">scale</span>(AgeMedian)<span class="sc">+</span></span>
<span id="cb647-6"><a href="sect074.html#cb647-6" aria-hidden="true" tabindex="-1"></a>                           <span class="fu">scale</span>(Pct_014)<span class="sc">+</span><span class="fu">scale</span>(Pct_65P)<span class="sc">+</span></span>
<span id="cb647-7"><a href="sect074.html#cb647-7" aria-hidden="true" tabindex="-1"></a>                           <span class="fu">scale</span>(Pct_MV)<span class="sc">+</span><span class="fu">scale</span>(Pct_FR), <span class="at">data =</span> DataFinal)</span>
<span id="cb647-8"><a href="sect074.html#cb647-8" aria-hidden="true" tabindex="-1"></a>coefs <span class="ot">&lt;-</span> ModeleZ<span class="sc">$</span>coefficients</span>
<span id="cb647-9"><a href="sect074.html#cb647-9" aria-hidden="true" tabindex="-1"></a>coefs[<span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(coefs)]</span></code></pre></div>
<pre><code>##      (Intercept)     scale(HABHA) scale(AgeMedian)   scale(Pct_014)   scale(Pct_65P) 
##     3.721649e-16    -2.806891e-01     1.467299e-02     3.093456e-01     1.788453e-01 
##    scale(Pct_MV)    scale(Pct_FR) 
##    -2.755087e-02    -3.004544e-01</code></pre>
<div class="sourceCode" id="cb649"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb649-1"><a href="sect074.html#cb649-1" aria-hidden="true" tabindex="-1"></a><span class="co">#  Méthode 2 : à partir de l&#39;équation</span></span>
<span id="cb649-2"><a href="sect074.html#cb649-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Écart-type de la variable dépendante</span></span>
<span id="cb649-3"><a href="sect074.html#cb649-3" aria-hidden="true" tabindex="-1"></a>VDet <span class="ot">&lt;-</span> <span class="fu">sd</span>(DataFinal<span class="sc">$</span>VegPct)</span>
<span id="cb649-4"><a href="sect074.html#cb649-4" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;Écart-type de Y =&quot;</span>, <span class="fu">round</span>(VDet,<span class="dv">3</span>))</span></code></pre></div>
<pre><code>## Écart-type de Y = 18.562</code></pre>
<div class="sourceCode" id="cb651"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb651-1"><a href="sect074.html#cb651-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Écarts-types des variables indépendantes</span></span>
<span id="cb651-2"><a href="sect074.html#cb651-2" aria-hidden="true" tabindex="-1"></a>VI <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;HABHA&quot;</span>,<span class="st">&quot;AgeMedian&quot;</span>,<span class="st">&quot;Pct_014&quot;</span>,<span class="st">&quot;Pct_65P&quot;</span>,<span class="st">&quot;Pct_MV&quot;</span>,<span class="st">&quot;Pct_FR&quot;</span>)</span>
<span id="cb651-3"><a href="sect074.html#cb651-3" aria-hidden="true" tabindex="-1"></a>VIet <span class="ot">&lt;-</span> <span class="fu">sapply</span>(DataFinal[VI], sd)</span>
<span id="cb651-4"><a href="sect074.html#cb651-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Coefficients de régression du modèle sans la constante</span></span>
<span id="cb651-5"><a href="sect074.html#cb651-5" aria-hidden="true" tabindex="-1"></a>coefs <span class="ot">&lt;-</span> Modele1<span class="sc">$</span>coefficients[<span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(VIet)<span class="sc">+</span><span class="dv">1</span>]</span>
<span id="cb651-6"><a href="sect074.html#cb651-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Coefficients de régression du modèle</span></span>
<span id="cb651-7"><a href="sect074.html#cb651-7" aria-hidden="true" tabindex="-1"></a>coefstand <span class="ot">&lt;-</span> coefs <span class="sc">*</span> (VIet <span class="sc">/</span> VDet)</span>
<span id="cb651-8"><a href="sect074.html#cb651-8" aria-hidden="true" tabindex="-1"></a>coefstand</span></code></pre></div>
<pre><code>##       HABHA   AgeMedian     Pct_014     Pct_65P      Pct_MV      Pct_FR 
## -0.28068906  0.01467299  0.30934560  0.17884535 -0.02755087 -0.30045437</code></pre>
<div class="sourceCode" id="cb653"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb653-1"><a href="sect074.html#cb653-1" aria-hidden="true" tabindex="-1"></a><span class="co">#  Méthode 3 : avec la fonction lm.beta du package QuantPsyc</span></span>
<span id="cb653-2"><a href="sect074.html#cb653-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(QuantPsyc)</span>
<span id="cb653-3"><a href="sect074.html#cb653-3" aria-hidden="true" tabindex="-1"></a><span class="fu">lm.beta</span>(<span class="fu">lm</span>(VegPct <span class="sc">~</span> HABHA<span class="sc">+</span>AgeMedian<span class="sc">+</span>Pct_014<span class="sc">+</span>Pct_65P<span class="sc">+</span>Pct_MV<span class="sc">+</span>Pct_FR, <span class="at">data =</span> DataFinal))</span></code></pre></div>
<pre><code>##       HABHA   AgeMedian     Pct_014     Pct_65P      Pct_MV      Pct_FR 
## -0.28068906  0.01467299  0.30934560  0.17884535 -0.02755087 -0.30045437</code></pre>
<table>
<caption>
<span id="tab:CoefStand2">Tableau 7.3: </span>Calcul des coefficients standardisés
</caption>
<thead>
<tr>
<th style="text-align:left;">
Variable dépendante
</th>
<th style="text-align:right;">
Écart-type
</th>
<th style="text-align:right;">
Coef.
</th>
<th style="text-align:right;">
Coef. standardisé
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
HABHA
</td>
<td style="text-align:right;">
74,008
</td>
<td style="text-align:right;">
-0,070
</td>
<td style="text-align:right;">
-0,281
</td>
</tr>
<tr>
<td style="text-align:left;">
AgeMedian
</td>
<td style="text-align:right;">
25,241
</td>
<td style="text-align:right;">
0,011
</td>
<td style="text-align:right;">
0,015
</td>
</tr>
<tr>
<td style="text-align:left;">
Pct_014
</td>
<td style="text-align:right;">
5,295
</td>
<td style="text-align:right;">
1,084
</td>
<td style="text-align:right;">
0,309
</td>
</tr>
<tr>
<td style="text-align:left;">
Pct_65P
</td>
<td style="text-align:right;">
8,289
</td>
<td style="text-align:right;">
0,401
</td>
<td style="text-align:right;">
0,179
</td>
</tr>
<tr>
<td style="text-align:left;">
Pct_MV
</td>
<td style="text-align:right;">
16,438
</td>
<td style="text-align:right;">
-0,031
</td>
<td style="text-align:right;">
-0,028
</td>
</tr>
<tr>
<td style="text-align:left;">
Pct_FR
</td>
<td style="text-align:right;">
16,015
</td>
<td style="text-align:right;">
-0,348
</td>
<td style="text-align:right;">
-0,300
</td>
</tr>
</tbody>
</table>
<p>Par exemple, pour la variable <code>Pct_014</code>, le coefficient de régression standardisé est égal à :</p>
<p><span class="math display" id="eq:CoefStand2">\[\begin{equation}
\beta_{z}= 1,084 \times \frac{5,295}{18,562}=0,309
\tag{7.15}
\end{equation}\]</span>
</p>
<p>avec 1,084 étant le coefficient de régression de <code>Pct_014</code>, 5,295 et 18,562 étant respectivement les écarts-types de <code>Pct_014</code> (variable indépendante) et de <code>VegPct</code> (variable dépendante).</p>
<p>Au tableau <a href="sect074.html#tab:CoefStand2">7.3</a>, nous constatons que la valeur absolue du coefficient de régression pour <code>HABHA</code> est inférieure à celle de <code>Pct_65P</code> (−0,070 <em>versus</em> 0,401), ce qui n’est pas le cas pour leur coefficient standardisé (−0,281 <em>versus</em> 0,179). Rappelez-vous aussi que nous ne pouvons pas directement comparer les effets de ces deux variables à partir des coefficients de régression puisqu’elles sont exprimées dans des unités de mesure différentes : <code>HABHA</code> est exprimée en habitants par hectare et <code>Pct_65P</code> en pourcentage. À la lecture des coefficients standardisés, nous pouvons en conclure que la variable <code>HABHA</code> a un effet relatif plus important que <code>Pct_65P</code> (−0,281 <em>versus</em> 0,179).</p>
</div>
<div id="sect0743" class="section level3 hasAnchor" number="7.4.3">
<h3><span class="header-section-number">7.4.3</span> Significativité des coefficients de régression : valeurs de <em>t</em> et de <em>p</em><a href="sect074.html#sect0743" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Une fois les coefficients de régression obtenus, il convient de vérifier s’ils sont ou non significativement différents de 0. Si le coefficient de régression d’une variable indépendante est significativement différent de 0, nous concluons que la variable a un effet significatif sur la variable dépendante, toutes choses étant égales par ailleurs. Pour ce faire, il suffit de calculer la valeur de <em>t</em> qui est simplement le coefficient de régression divisé par son erreur type.</p>
<p><span class="math display" id="eq:ValeurT">\[\begin{equation}
t=\frac{\beta_k - 0}{s(\beta_k)}  
\tag{7.16}
\end{equation}\]</span>
</p>
<p>avec <span class="math inline">\(s(\beta_k)\)</span> étant l’erreur type du coefficient de régression. Notez que dans l’équation <a href="sect074.html#eq:ValeurT">(7.16)</a>, nous indiquons habituellement <span class="math inline">\(-0\)</span>, pour signaler que l’on veut vérifier si le coefficient est différent de 0. En guise d’exemple, au tableau <a href="sect074.html#tab:dataregmodel2">7.2</a>, la valeur de <em>t</em> de la variable <code>HABHA</code> est bien égale à :</p>
<p><span class="math inline">\(\mbox{−0,070401 / 0,002202 = −31,975}\)</span>.</p>
<div class="bloc_attention">
<p><strong>Démarche pour vérifier si un coefficient est significativement différent de 0 avec un seuil de confiance</strong></p>
<ol style="list-style-type: decimal">
<li>Poser l’hypothèse nulle (<em>H<sub>0</sub></em>) stipulant que le coefficient est égal à 0, soit <span class="math inline">\(H_0 : \beta_k = 0\)</span>. L’hypothèse alternative (<em>H<sub>1</sub></em>) est que le coefficient est différent de 0, soit <span class="math inline">\(H_1 : B_k \neq 0\)</span>.</li>
<li>Calculer la valeur de <em>t</em>, soit le coefficient de régression divisé par son erreur type (équation <a href="sect074.html#eq:ValeurT">(7.16)</a>).</li>
<li>Calculer le nombre de degrés de liberté, soit <span class="math inline">\(dl = n − k - 1\)</span>, <em>n</em> et <em>k</em> étant respectivement les nombres d’observations et de variables indépendantes.</li>
<li>Choisir un seuil de signification alpha (5 %, 1 % ou 0,1 %, soit <em>p</em> = 0,05, 0,01 ou 0,01).</li>
<li>Trouver la valeur critique de <em>t</em> dans la table T de Student (<a href="annexe3.html#annexe3">16</a>) avec <em>p</em> et le nombre de degrés de liberté (<em>dl</em>).</li>
<li>Valider ou réfuter l’hypothèse nulle (<em>H<sub>0</sub></em>) :</li>
</ol>
<ul>
<li>si la valeur de <em>t</em> est inférieure à la valeur critique de <em>t</em> avec <em>dl</em> et le seuil choisi, nous confirmons <em>H<sub>0</sub></em> : le coefficient n’est pas significativement différent de 0.</li>
<li>si la valeur de <em>t</em> est supérieure à la valeur critique de <em>t</em> avec <em>dl</em> et le seuil choisi, nous réfutons l’hypothèse nulle, et choisissons l’hypothèse alternative (<em>H<sub>1</sub></em>) stipulant que le coefficient est significativement différent de 0.</li>
</ul>
<p><strong>Valeurs critiques de la valeur de <em>t</em> à retenir!</strong></p>
<p>Lorsque le nombre de degrés de liberté (<em>n − k - 1</em>) est très important (supérieur à 2500), et donc le nombre d’observations de votre jeu de données, nous retenons habituellement les valeurs critiques suivantes : <strong>1,65 (<em>p</em> = 0,10), 1,96 (<em>p</em> = 0,05)</strong>, <strong>2,58 (<em>p</em> = 0,01)</strong> et <strong>3,29 (<em>p</em>=0,001)</strong>. Concrètement, cela signifie que :</p>
<ul>
<li><p>une valeur de <em>t</em> supérieure à 1,96 ou inférieure à -1,96 nous informe que la relation entre la variable indépendante et la variable dépendante est significative positivement ou négativement au seuil de 5 %. Autrement dit, vous avez moins de 5 % de chances de vous tromper en affirmant que le coefficient de régression est bien significativement différent de 0.</p></li>
<li><p>une valeur de <em>t</em> supérieure à 2,58 ou inférieure à -2,58 nous informe que la relation entre la variable indépendante et la variable dépendante est significative positivement ou négativement au seuil de 5 %. Autrement dit, vous avez moins de 1 % de chances de vous tromper en affirmant que le coefficient de régression est bien significativement différent de 0.</p></li>
<li><p>une valeur de <em>t</em> supérieure à 3,29 ou inférieure à -3,29 nous informe que la relation entre la variable indépendante et la variable dépendante est significative positivement ou négativement au seuil de 5 %. Autrement dit, vous avez moins de 0,1 % de chances de vous tromper en affirmant que le coefficient de régression est bien significativement différent de 0.</p></li>
</ul>
<p>Concrètement, retenez et utilisez les seuils de <span class="math inline">\(\pm\mbox{1,96}\)</span>, <span class="math inline">\(\pm\mbox{2,58}\)</span> et <span class="math inline">\(\pm\mbox{3,29}\)</span> pour repérer les variables significatives positivement ou négativement aux seuils respectifs de 0,5, 0,1 et 0,001.</p>
<p><strong>Que signifient les seuils 0,10, 0,05 et 0,001?</strong></p>
<p>L’interprétation exacte des seuils de significativité des coefficients d’une régression est quelque peu alambiquée, mais mérite de s’y attarder. En effet, indiquer qu’un coefficient est significatif est souvent perçu comme un argument fort pour une théorie, il est donc nécessaire d’avoir du recul et de bien comprendre ce que l’on entend par <strong>significatif</strong>.</p>
<p>Si un coefficient est significatif au seuil de 5 % dans notre modèle, cela signifie que si, pour l’ensemble d’une population, la valeur du coefficient est de 0 en réalité, alors nous avions moins de 5 % de chances de collecter un échantillon (pour cette population) ayant produit un coefficient aussi fort que celui que nous observons dans notre propre échantillon. Par conséquent, il serait très invraisemblable que le coefficient soit 0 puisque nous avons effectivement collecté un tel échantillon. Il s’agit d’une forme d’argumentation par l’absurde propre à la statistique fréquentiste.</p>
<p>Notez que si 100 études étaient conduites sur le même sujet et dans les mêmes conditions, nous nous attendrions à ce que 5 d’entre elles trouvent un coefficient significatif, du fait de la variation des échantillons. Ce constat souligne le fait que la recherche est un effort collectif et qu’une seule étude n’est pas suffisante pour trancher sur un sujet. Les revues systématiques de la littérature sont donc des travaux particulièrement importants pour la construction du consensus scientifique.</p>
<p><strong>Ne pas confondre significativité et effet de la variable indépendante</strong></p>
<p>Attention, un coefficient significatif n’est pas toujours intéressant! Autrement dit, bien qu’il soit significatif à un seuil donné (par exemple, <em>p</em> = 0,05), cela ne veut pas dire pour autant qu’il ait un effet important sur la variable dépendante. Il faut donc analyser simultanément les valeurs de <em>p</em> et des coefficients de régression.
Afin de mieux saisir l’effet d’un coefficient significatif, il est intéressant de représenter graphiquement l’effet marginal d’une variable indépendante (VI) sur une variable dépendante (VD), une fois contrôlées les autres VI du modèle de régression (section <a href="sect077.html#sect0774">7.7.4</a>).</p>
</div>
<p>Prenons deux variables indépendantes du tableau <a href="sect074.html#tab:dataregmodel2">7.2</a> – <code>HABHA</code> et <code>AgeMedian</code> – et vérifions si leurs coefficients de régression respectifs (−0,070 et 0,011) sont significatifs. Appliquons la démarche décrite dans l’encadré ci-dessus :</p>
<ol style="list-style-type: decimal">
<li>Nous posons l’hypothèse nulle stipulant que la valeur de ces deux coefficients est égale à 0, soit <span class="math inline">\(H_0 : \beta_k = 0\)</span>.</li>
<li>La valeur de <em>t</em> est égale à <code>−0,070401 / 0,002202 = −31,97139</code> pour <code>HABHA</code> et à <code>0,010790 / 0,006369 = 1,694144</code> pour <code>AgeMedian</code>.</li>
<li>Le nombre de degrés de liberté est égal à <span class="math inline">\(\mbox{dl} = \mbox{n}-\mbox{k}-\mbox{1} = \mbox{10 210} − \mbox{6} - \mbox{1} = \mbox{10 203}\)</span>.</li>
<li>Nous choisissons respectivement les seuils <span class="math inline">\(\alpha\)</span> de 0,10, 0,05, 0,01 ou 0,001.</li>
<li>Avec 10210 degrés de liberté, les valeurs critiques de la table T de Student (section <a href="annexe3.html#annexe3">16</a>) sont de 1,65 (<em>p</em> = 0,10), 1,96 (<em>p</em> = 0,05), 2,58 (<em>p</em> = 0,01), 3,29 (<em>p</em> = 0,001).</li>
<li>Il reste à valider ou réfuter l’hypothèse nulle (<em>H<sub>0</sub></em>) :</li>
</ol>
<ul>
<li><p>pour <code>HABHA</code>, la valeur absolue de <em>t</em> (−31,975) est supérieure à la valeur critique de 3,29. Son coefficient de régression est donc significativement différent de 0. Autrement dit, ce prédicteur a un effet significatif et négatif sur la variable dépendante.</p></li>
<li><p>pour <code>AgeMedian</code>, la valeur absolue de <em>t</em> (1,694) est supérieure à 1,65 (<em>p</em> = 0,10), mais inférieure à 1,96 (<em>p</em> = 0,05), à 2,58 (<em>p</em> = 0,01), à 3,29 (<em>p</em> = 0,001). Par conséquent, ce coefficient est différent de 0 uniquement au seuil de <em>p</em> = 0,10 et non au seuil de <em>p</em> = 0,05. Cela signifie que bous avons un peu moins de 10 % de chances de se tromper en affirmant que cette variable a un effet significatif sur la variable dépendante.</p></li>
</ul>
<div class="bloc_astuce">
<p><strong>Calculer et obtenir des valeurs de <em>p</em> dans R</strong></p>
<p>Il est très rare que d’utiliser directement la table <em>T</em> de Student pour obtenir un seuil de significativité.</p>
<p>D’une part, il est possible de calculer directement la valeur de <em>p</em> à partir de la valeur de <em>t</em> et du nombre de degrés de liberté avec la fonction <code>pt</code> avec les paramètres suivants :</p>
<p><code>pt(q= abs(valeur de T), df= nombre de degrés de liberté, lower.tail = F) *2</code></p>
<div class="sourceCode" id="cb655"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb655-1"><a href="sect074.html#cb655-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Degrés de liberté</span></span>
<span id="cb655-2"><a href="sect074.html#cb655-2" aria-hidden="true" tabindex="-1"></a>dl <span class="ot">&lt;-</span> <span class="fu">nrow</span>(DataFinal) <span class="sc">-</span> (<span class="fu">length</span>(Modele1<span class="sc">$</span>coefficients) <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">+</span> <span class="dv">1</span></span>
<span id="cb655-3"><a href="sect074.html#cb655-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb655-4"><a href="sect074.html#cb655-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Valeurs de T</span></span>
<span id="cb655-5"><a href="sect074.html#cb655-5" aria-hidden="true" tabindex="-1"></a>ValeurT <span class="ot">&lt;-</span> <span class="fu">summary</span>(Modele1)<span class="sc">$</span>coefficients[,<span class="dv">3</span>]</span>
<span id="cb655-6"><a href="sect074.html#cb655-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb655-7"><a href="sect074.html#cb655-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcul des valeurs de P</span></span>
<span id="cb655-8"><a href="sect074.html#cb655-8" aria-hidden="true" tabindex="-1"></a>ValeurP <span class="ot">&lt;-</span> <span class="fu">pt</span>(<span class="at">q=</span> <span class="fu">abs</span>(ValeurT), <span class="at">df=</span> dl, <span class="at">lower.tail =</span> F) <span class="sc">*</span><span class="dv">2</span></span>
<span id="cb655-9"><a href="sect074.html#cb655-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb655-10"><a href="sect074.html#cb655-10" aria-hidden="true" tabindex="-1"></a>df_tp <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb655-11"><a href="sect074.html#cb655-11" aria-hidden="true" tabindex="-1"></a>                <span class="at">ValeurT =</span> <span class="fu">round</span>(ValeurT,<span class="dv">3</span>), </span>
<span id="cb655-12"><a href="sect074.html#cb655-12" aria-hidden="true" tabindex="-1"></a>                <span class="at">ValeurP =</span> <span class="fu">round</span>(ValeurP,<span class="dv">3</span>)</span>
<span id="cb655-13"><a href="sect074.html#cb655-13" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb655-14"><a href="sect074.html#cb655-14" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(df_tp)</span></code></pre></div>
<pre><code>##             ValeurT ValeurP
## (Intercept)  29.874   0.000
## HABHA       -31.975   0.000
## AgeMedian     1.694   0.090
## Pct_014      33.702   0.000
## Pct_65P      21.265   0.000
## Pct_MV       -2.990   0.003
## Pct_FR      -29.918   0.000</code></pre>
<p>D’autre part, la fonction <code>summary</code> renvoie d’emblée les valeurs de <em>t</em> et de <em>p</em>. Par convention, R, comme la plupart des logiciels d’analyses statistiques, utilise aussi des symboles pour indiquer le seuil de signification du coefficient (voir tableau <a href="sect074.html#tab:CoefStand2">7.3</a>) :</p>
<p>’***’ <em>p</em> &lt;= 0,001</p>
<p>’**’ <em>p</em> &lt;= 0,01</p>
<p>’*’ <em>p</em> &lt;= 0,05</p>
<p>‘.’ <em>p</em> &lt;= 0,10</p>
</div>
</div>
<div id="sect0744" class="section level3 hasAnchor" number="7.4.4">
<h3><span class="header-section-number">7.4.4</span> Intervalle de confiance des coefficients<a href="sect074.html#sect0744" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Finalement, il est possible de calculer l’intervalle de confiance d’un coefficient à partir d’un niveau de signification (habituellement 0,95 ou encore 0,99). Pour ce faire, la fonction <code>confint(nom du modèle, level=.95)</code> est très utile. L’intérêt de ces intervalles de confiance pour les coefficients de régression est double :</p>
<ul>
<li>il permet de vérifier si le coefficient est ou non significatif au seuil retenu. Pour cela, la borne inférieure et la borne supérieure du coefficient doivent être toutes deux négatives ou positives. À l’inverse, un intervalle à cheval sur 0, soit avec une borne inférieure négative et une borne supérieure positive, n’est pas significatif.</li>
<li>il permet d’estimer la précision de l’estimation; plus l’intervalle du coefficient est réduit, plus l’estimation de l’effet de la variable indépendante est précise. Inversement, un intervalle large signale que le coefficient est incertain.</li>
</ul>
<p>Cela explique que de nombreux auteurs reportent les intervalles de confiance dans les articles scientifiques (habituellement à 95 %). Dans le modèle présenté ici, il est alors possible d’écrire : toutes choses étant égales par ailleurs, le pourcentage d’enfants de moins de 15 ans est positivement et significativement associé avec le pourcentage de la couverture végétale dans l’îlot (B = 1,084; IC 95 % = [1,021 - 1,148], <em>p</em> &lt; 0,001).</p>
<p>En guise d’exemple, à la lecture de la sortie R ci-dessous, l’estimation de l’effet de la variable indépendante <code>AgeMedian</code> sur la variable <code>VegPct</code> se situe dans l’intervalle -0,002 à 0,023 qui est à cheval sur 0. Contrairement aux autres variables, nous ne pouvons donc pas en conclure que cet effet est significatif avec <em>p</em> = 0,05.</p>
<div class="sourceCode" id="cb657"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb657-1"><a href="sect074.html#cb657-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Intervalle de confiance à 95 % des coefficients</span></span>
<span id="cb657-2"><a href="sect074.html#cb657-2" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">confint</span>(Modele1, <span class="at">level=</span>.<span class="dv">95</span>),<span class="dv">3</span>)</span></code></pre></div>
<pre><code>##              2.5 % 97.5 %
## (Intercept) 24.626 28.085
## HABHA       -0.075 -0.066
## AgeMedian   -0.002  0.023
## Pct_014      1.021  1.148
## Pct_65P      0.364  0.437
## Pct_MV      -0.052 -0.011
## Pct_FR      -0.371 -0.325</code></pre>
<div class="bloc_astuce">
<p><strong>Comment est calculé un intervalle de confiance?</strong></p>
<p>L’intervalle du coefficient est obtenu à partir de :</p>
<ol style="list-style-type: decimal">
<li>la valeur du coefficient (<span class="math inline">\(\beta_k\)</span>),</li>
<li>la valeur de son erreur type <span class="math inline">\(s(\beta_k)\)</span> et</li>
<li>la valeur critique de T (<span class="math inline">\(t_{\alpha/2}\)</span>) obtenue avec <span class="math inline">\(n-k-1\)</span> degrés de liberté et le niveau de significativité retenu (95 %, 99 % ou 99,9 %).</li>
</ol>
<p><span class="math display" id="eq:ICcoef">\[\begin{equation}
IC_{\beta_k}=  \left[ \beta_k - t_{\alpha/2} \times s(\beta_k) ; \beta_k + t_{\alpha/2} \times s(\beta_k)  \right]
\tag{7.17}
\end{equation}\]</span>
</p>
<p>Autrement dit, lorsque vous disposez d’un nombre très important d’observations, les intervalles de confiance s’écrivent simplement avec les fameuses valeurs critiques de T de 1,96, 2,58, 3,29 :</p>
<p><span class="math display" id="eq:IC95">\[\begin{equation}
\mbox{Intervalle à 95 \%\: } IC_{\beta_k}=  \left[ \beta_k - 1,96 \times s(\beta_k) ; \beta_k + 1,96 \times s(\beta_k)  \right]
\tag{7.18}
\end{equation}\]</span>
</p>
<p><span class="math display" id="eq:IC99">\[\begin{equation}
\mbox{Intervalle à 99 \%\: } IC_{\beta_k}=  \left[ \beta_k - 2,58 \times s(\beta_k) ; \beta_k + 2,58 \times s(\beta_k)  \right]
\tag{7.19}
\end{equation}\]</span>
</p>
<p><span class="math display" id="eq:IC999">\[\begin{equation}
\mbox{Intervalle à 99,9 \%\: } IC_{\beta_k}=  \left[ \beta_k - 3,29 \times s(\beta_k) ; \beta_k + 3,29 \times s(\beta_k)  \right]
\tag{7.20}
\end{equation}\]</span>
</p>
<p>La syntaxe R ci-dessous illustre comment calculer les intervalles de confiance à 95 % à partir de l’équation <a href="sect074.html#eq:ICcoef">(7.17)</a>. Rappelez-vous toutefois qu’il est bien plus simple d’utiliser la fonction <code>confint</code>:</p>
<ul>
<li><code>round(confint(Modele1, level=.95),3)</code></li>
<li><code>round(confint(Modele1, level=.99),3)</code></li>
<li><code>round(confint(Modele1, level=.999),3)</code></li>
</ul>
<div class="sourceCode" id="cb659"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb659-1"><a href="sect074.html#cb659-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Coeffients de régression</span></span>
<span id="cb659-2"><a href="sect074.html#cb659-2" aria-hidden="true" tabindex="-1"></a>coefs <span class="ot">&lt;-</span> Modele1<span class="sc">$</span>coefficients</span>
<span id="cb659-3"><a href="sect074.html#cb659-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb659-4"><a href="sect074.html#cb659-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Erreur type des coef.</span></span>
<span id="cb659-5"><a href="sect074.html#cb659-5" aria-hidden="true" tabindex="-1"></a>coefs_se <span class="ot">&lt;-</span> <span class="fu">summary</span>(Modele1)<span class="sc">$</span>coefficients[,<span class="dv">2</span>]</span>
<span id="cb659-6"><a href="sect074.html#cb659-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb659-7"><a href="sect074.html#cb659-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Nombre de degrés de liberté</span></span>
<span id="cb659-8"><a href="sect074.html#cb659-8" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">length</span>(Modele1<span class="sc">$</span>fitted.values)</span>
<span id="cb659-9"><a href="sect074.html#cb659-9" aria-hidden="true" tabindex="-1"></a>k <span class="ot">&lt;-</span> <span class="fu">length</span>(Modele1<span class="sc">$</span>coefficients)<span class="sc">-</span><span class="dv">1</span></span>
<span id="cb659-10"><a href="sect074.html#cb659-10" aria-hidden="true" tabindex="-1"></a>dl <span class="ot">&lt;-</span> n<span class="sc">-</span>k<span class="dv">-1</span></span>
<span id="cb659-11"><a href="sect074.html#cb659-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb659-12"><a href="sect074.html#cb659-12" aria-hidden="true" tabindex="-1"></a><span class="co"># valeurs critiques de T</span></span>
<span id="cb659-13"><a href="sect074.html#cb659-13" aria-hidden="true" tabindex="-1"></a>t95 <span class="ot">&lt;-</span>  <span class="fu">qt</span>(<span class="at">p=</span><span class="dv">1</span> <span class="sc">-</span> (<span class="fl">0.05</span><span class="sc">/</span><span class="dv">2</span>),  <span class="at">df=</span>dl)</span>
<span id="cb659-14"><a href="sect074.html#cb659-14" aria-hidden="true" tabindex="-1"></a>t99 <span class="ot">&lt;-</span>  <span class="fu">qt</span>(<span class="at">p=</span><span class="dv">1</span> <span class="sc">-</span> (<span class="fl">0.01</span><span class="sc">/</span><span class="dv">2</span>),  <span class="at">df=</span>dl)</span>
<span id="cb659-15"><a href="sect074.html#cb659-15" aria-hidden="true" tabindex="-1"></a>t99<span class="fl">.9</span> <span class="ot">&lt;-</span>  <span class="fu">qt</span>(<span class="at">p=</span><span class="dv">1</span> <span class="sc">-</span> (<span class="fl">0.001</span><span class="sc">/</span><span class="dv">2</span>),  <span class="at">df=</span>dl)</span>
<span id="cb659-16"><a href="sect074.html#cb659-16" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;Valeurs critiques de T en fonction du niveau de confiance&quot;</span>,</span>
<span id="cb659-17"><a href="sect074.html#cb659-17" aria-hidden="true" tabindex="-1"></a>    <span class="st">&quot;</span><span class="sc">\n</span><span class="st"> et du nombre de degrés de liberté&quot;</span>,</span>
<span id="cb659-18"><a href="sect074.html#cb659-18" aria-hidden="true" tabindex="-1"></a>    <span class="st">&quot;</span><span class="sc">\n</span><span class="st">95 % : &quot;</span>, t95,</span>
<span id="cb659-19"><a href="sect074.html#cb659-19" aria-hidden="true" tabindex="-1"></a>    <span class="st">&quot;</span><span class="sc">\n</span><span class="st">99 % : &quot;</span>, t99,</span>
<span id="cb659-20"><a href="sect074.html#cb659-20" aria-hidden="true" tabindex="-1"></a>    <span class="st">&quot;</span><span class="sc">\n</span><span class="st">99,9 % : &quot;</span>, t99<span class="fl">.9</span></span>
<span id="cb659-21"><a href="sect074.html#cb659-21" aria-hidden="true" tabindex="-1"></a>    )</span></code></pre></div>
<pre><code>## Valeurs critiques de T en fonction du niveau de confiance 
##  et du nombre de degrés de liberté 
## 95 % :  1.960197 
## 99 % :  2.576311 
## 99,9 % :  3.291481</code></pre>
<div class="sourceCode" id="cb661"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb661-1"><a href="sect074.html#cb661-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Intervalle de confiance à 95</span></span>
<span id="cb661-2"><a href="sect074.html#cb661-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb661-3"><a href="sect074.html#cb661-3" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(</span>
<span id="cb661-4"><a href="sect074.html#cb661-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">IC2.5  =</span> <span class="fu">round</span>(coefs<span class="sc">-</span>t95<span class="sc">*</span>coefs_se,<span class="dv">3</span>),</span>
<span id="cb661-5"><a href="sect074.html#cb661-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">IC97.5 =</span> <span class="fu">round</span>(coefs<span class="sc">+</span>t95<span class="sc">*</span>coefs_se,<span class="dv">3</span>)</span>
<span id="cb661-6"><a href="sect074.html#cb661-6" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
<pre><code>##              IC2.5 IC97.5
## (Intercept) 24.626 28.085
## HABHA       -0.075 -0.066
## AgeMedian   -0.002  0.023
## Pct_014      1.021  1.148
## Pct_65P      0.364  0.437
## Pct_MV      -0.052 -0.011
## Pct_FR      -0.371 -0.325</code></pre>
<div class="sourceCode" id="cb663"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb663-1"><a href="sect074.html#cb663-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Intervalle de confiance à 99</span></span>
<span id="cb663-2"><a href="sect074.html#cb663-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb663-3"><a href="sect074.html#cb663-3" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(</span>
<span id="cb663-4"><a href="sect074.html#cb663-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">IC0.5 =</span> <span class="fu">round</span>(coefs<span class="sc">-</span>t99<span class="sc">*</span>coefs_se,<span class="dv">3</span>),</span>
<span id="cb663-5"><a href="sect074.html#cb663-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">IC99.5 =</span> <span class="fu">round</span>(coefs<span class="sc">+</span>t99<span class="sc">*</span>coefs_se,<span class="dv">3</span>)</span>
<span id="cb663-6"><a href="sect074.html#cb663-6" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>##              IC0.5 IC99.5
## (Intercept) 24.083 28.629
## HABHA       -0.076 -0.065
## AgeMedian   -0.006  0.027
## Pct_014      1.002  1.167
## Pct_65P      0.352  0.449
## Pct_MV      -0.058 -0.004
## Pct_FR      -0.378 -0.318</code></pre>
<div class="sourceCode" id="cb665"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb665-1"><a href="sect074.html#cb665-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Intervalle de confiance à 99.9</span></span>
<span id="cb665-2"><a href="sect074.html#cb665-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(</span>
<span id="cb665-3"><a href="sect074.html#cb665-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">IC0.05 =</span> <span class="fu">round</span>(coefs<span class="sc">-</span>t99<span class="fl">.9</span><span class="sc">*</span>coefs_se,<span class="dv">3</span>),</span>
<span id="cb665-4"><a href="sect074.html#cb665-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">IC99.95 =</span> <span class="fu">round</span>(coefs<span class="sc">+</span>t99<span class="fl">.9</span><span class="sc">*</span>coefs_se,<span class="dv">3</span>)</span>
<span id="cb665-5"><a href="sect074.html#cb665-5" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
<pre><code>##             IC0.05 IC99.95
## (Intercept) 23.452  29.260
## HABHA       -0.078  -0.063
## AgeMedian   -0.010   0.032
## Pct_014      0.979   1.190
## Pct_65P      0.339   0.463
## Pct_MV      -0.065   0.003
## Pct_FR      -0.387  -0.310</code></pre>
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="sect073.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="sect075.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["MethodesQuantitScSocialesBolR.pdf"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "none"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
