<!DOCTYPE html>
<html lang="fr" xml:lang="fr">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>6.2 Relation entre une variable quantitative et une variable qualitative à plus de deux modalités | Méthodes quantitatives en sciences sociales : un grand bol d’R</title>
  <meta name="description" content="Ce livre vise à décrire une panoplie de méthodes quantitatives utilisées en sciences sociales avec le logiciel ouvert R. Il a d’ailleurs été écrit intégralement dans R avec rmarkdown. Le contenu est pensé pour être accessible à tous et toutes, même à ceux et celles n’ayant presque aucune base en statistique ou en programmation. Les personnes plus expérimentées y découvriront des sections sur des méthodes plus avancées comme les modèles à effets mixtes, les modèles multiniveaux, les modèles généralisés additifs ainsi que les méthodes factorielles et de classification. Ceux et celles souhaitant migrer progressivement d’un autre logiciel statistique vers R trouveront dans cet ouvrage les éléments pour une transition en douceur. La philosophie de ce livre est de donner toutes les clefs de compréhension et de mise en œuvre des méthodes abordées dans R. La présentation des méthodes est basée sur une approche compréhensive et intuitive plutôt que mathématique, sans pour autant que la rigueur statistique ne soit négligée." />
  <meta name="generator" content="bookdown 0.32 and GitBook 2.6.7" />

  <meta property="og:title" content="6.2 Relation entre une variable quantitative et une variable qualitative à plus de deux modalités | Méthodes quantitatives en sciences sociales : un grand bol d’R" />
  <meta property="og:type" content="book" />
  <meta property="og:image" content="https://laeq.github.io/LivreStatistique_website/images/introduction/ImageCouverture.png" />
  <meta property="og:description" content="Ce livre vise à décrire une panoplie de méthodes quantitatives utilisées en sciences sociales avec le logiciel ouvert R. Il a d’ailleurs été écrit intégralement dans R avec rmarkdown. Le contenu est pensé pour être accessible à tous et toutes, même à ceux et celles n’ayant presque aucune base en statistique ou en programmation. Les personnes plus expérimentées y découvriront des sections sur des méthodes plus avancées comme les modèles à effets mixtes, les modèles multiniveaux, les modèles généralisés additifs ainsi que les méthodes factorielles et de classification. Ceux et celles souhaitant migrer progressivement d’un autre logiciel statistique vers R trouveront dans cet ouvrage les éléments pour une transition en douceur. La philosophie de ce livre est de donner toutes les clefs de compréhension et de mise en œuvre des méthodes abordées dans R. La présentation des méthodes est basée sur une approche compréhensive et intuitive plutôt que mathématique, sans pour autant que la rigueur statistique ne soit négligée." />
  <meta name="github-repo" content="LAEQ/livre_statistique_Phil_Jere" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="6.2 Relation entre une variable quantitative et une variable qualitative à plus de deux modalités | Méthodes quantitatives en sciences sociales : un grand bol d’R" />
  
  <meta name="twitter:description" content="Ce livre vise à décrire une panoplie de méthodes quantitatives utilisées en sciences sociales avec le logiciel ouvert R. Il a d’ailleurs été écrit intégralement dans R avec rmarkdown. Le contenu est pensé pour être accessible à tous et toutes, même à ceux et celles n’ayant presque aucune base en statistique ou en programmation. Les personnes plus expérimentées y découvriront des sections sur des méthodes plus avancées comme les modèles à effets mixtes, les modèles multiniveaux, les modèles généralisés additifs ainsi que les méthodes factorielles et de classification. Ceux et celles souhaitant migrer progressivement d’un autre logiciel statistique vers R trouveront dans cet ouvrage les éléments pour une transition en douceur. La philosophie de ce livre est de donner toutes les clefs de compréhension et de mise en œuvre des méthodes abordées dans R. La présentation des méthodes est basée sur une approche compréhensive et intuitive plutôt que mathématique, sans pour autant que la rigueur statistique ne soit négligée." />
  <meta name="twitter:image" content="https://laeq.github.io/LivreStatistique_website/images/introduction/ImageCouverture.png" />

<meta name="author" content="Philippe Apparicio et Jérémy Gelb" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="sect061.html"/>
<link rel="next" href="sect063.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.6.1/htmlwidgets.js"></script>
<script src="libs/d3-4.13.0/d3.min.js"></script>
<script src="libs/d3-tip-0.8.1/index.js"></script>
<link href="libs/chorddiag-0.1.2.9000/chorddiag.css" rel="stylesheet" />
<script src="libs/chorddiag-0.1.2.9000/chorddiag.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="css/quizlib.min.css" type="text/css" />
<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Méthodes quantitatives en sciences sociales : un grand bol d'R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Bienvenue</a></li>
<li class="chapter" data-level="" data-path="préface.html"><a href="préface.html"><i class="fa fa-check"></i>Préface</a>
<ul>
<li class="chapter" data-level="" data-path="sect001.html"><a href="sect001.html"><i class="fa fa-check"></i>Un manuel sous la forme d’une ressource éducative libre</a></li>
<li class="chapter" data-level="" data-path="sect002.html"><a href="sect002.html"><i class="fa fa-check"></i>Un manuel conçu comme un projet collaboratif</a></li>
<li class="chapter" data-level="" data-path="sect003.html"><a href="sect003.html"><i class="fa fa-check"></i>Comment lire ce livre?</a></li>
<li class="chapter" data-level="" data-path="sect003B.html"><a href="sect003B.html"><i class="fa fa-check"></i>Comment utiliser les données du livre pour reproduire les exemples?</a></li>
<li class="chapter" data-level="" data-path="sect004.html"><a href="sect004.html"><i class="fa fa-check"></i>Structure du livre</a></li>
<li class="chapter" data-level="" data-path="sect005.html"><a href="sect005.html"><i class="fa fa-check"></i>Pourquoi faut-il programmer en sciences sociales?</a></li>
<li class="chapter" data-level="" data-path="sect006.html"><a href="sect006.html"><i class="fa fa-check"></i>Remerciements</a></li>
<li class="chapter" data-level="" data-path="sect007.html"><a href="sect007.html"><i class="fa fa-check"></i>Dédicace toute spéciale à Cargo et Ambrée</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="auteurs.html"><a href="auteurs.html"><i class="fa fa-check"></i>À propos des auteurs</a></li>
<li class="part"><span><b>I Découverte de R</b></span></li>
<li class="chapter" data-level="1" data-path="chap01.html"><a href="chap01.html"><i class="fa fa-check"></i><b>1</b> Prise en main de R</a>
<ul>
<li class="chapter" data-level="1.1" data-path="sect011.html"><a href="sect011.html"><i class="fa fa-check"></i><b>1.1</b> Histoire et philosophie de R</a></li>
<li class="chapter" data-level="1.2" data-path="sect012.html"><a href="sect012.html"><i class="fa fa-check"></i><b>1.2</b> Environnement de travail</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="sect012.html"><a href="sect012.html#sect0121"><i class="fa fa-check"></i><b>1.2.1</b> Installation de R</a></li>
<li class="chapter" data-level="1.2.2" data-path="sect012.html"><a href="sect012.html#sect0122"><i class="fa fa-check"></i><b>1.2.2</b> Environnement RStudio</a></li>
<li class="chapter" data-level="1.2.3" data-path="sect012.html"><a href="sect012.html#sect0123"><i class="fa fa-check"></i><b>1.2.3</b> Installation et chargement un <em>package</em></a></li>
<li class="chapter" data-level="1.2.4" data-path="sect012.html"><a href="sect012.html#aide-disponible"><i class="fa fa-check"></i><b>1.2.4</b> Aide disponible</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="sect013.html"><a href="sect013.html"><i class="fa fa-check"></i><b>1.3</b> Bases du langage R</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="sect013.html"><a href="sect013.html#sect0131"><i class="fa fa-check"></i><b>1.3.1</b> <em>Hello World</em>!</a></li>
<li class="chapter" data-level="1.3.2" data-path="sect013.html"><a href="sect013.html#sect0132"><i class="fa fa-check"></i><b>1.3.2</b> Objets et expressions</a></li>
<li class="chapter" data-level="1.3.3" data-path="sect013.html"><a href="sect013.html#sect0_133"><i class="fa fa-check"></i><b>1.3.3</b> Fonctions et arguments</a></li>
<li class="chapter" data-level="1.3.4" data-path="sect013.html"><a href="sect013.html#sect0134"><i class="fa fa-check"></i><b>1.3.4</b> Principaux types de données</a></li>
<li class="chapter" data-level="1.3.5" data-path="sect013.html"><a href="sect013.html#sect0135"><i class="fa fa-check"></i><b>1.3.5</b> Opérateurs</a></li>
<li class="chapter" data-level="1.3.6" data-path="sect013.html"><a href="sect013.html#sect0136"><i class="fa fa-check"></i><b>1.3.6</b> Structures de données</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="sect014.html"><a href="sect014.html"><i class="fa fa-check"></i><b>1.4</b> Manipulation de données</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="sect014.html"><a href="sect014.html#sect0141"><i class="fa fa-check"></i><b>1.4.1</b> Chargement d’un <em>DataFrame</em> depuis un fichier</a></li>
<li class="chapter" data-level="1.4.2" data-path="sect014.html"><a href="sect014.html#sect0142"><i class="fa fa-check"></i><b>1.4.2</b> Manipulation d’un <em>DataFrame</em></a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="sect016.html"><a href="sect016.html"><i class="fa fa-check"></i><b>1.5</b> Code R bien structuré</a></li>
<li class="chapter" data-level="1.6" data-path="sect017.html"><a href="sect017.html"><i class="fa fa-check"></i><b>1.6</b> Enregistrement des résultats</a></li>
<li class="chapter" data-level="1.7" data-path="sect018.html"><a href="sect018.html"><i class="fa fa-check"></i><b>1.7</b> Session de travail</a></li>
<li class="chapter" data-level="1.8" data-path="sect019.html"><a href="sect019.html"><i class="fa fa-check"></i><b>1.8</b> Conclusion et ressources pertinentes</a></li>
<li class="chapter" data-level="1.9" data-path="sect0110.html"><a href="sect0110.html"><i class="fa fa-check"></i><b>1.9</b> Quiz de révision du chapitre</a></li>
</ul></li>
<li class="part"><span><b>II Analyses univariées et graphiques dans R</b></span></li>
<li class="chapter" data-level="2" data-path="chap02.html"><a href="chap02.html"><i class="fa fa-check"></i><b>2</b> Statistiques descriptives univariées</a>
<ul>
<li class="chapter" data-level="2.1" data-path="sect021.html"><a href="sect021.html"><i class="fa fa-check"></i><b>2.1</b> Notion et types de variable</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="sect021.html"><a href="sect021.html#sect0211"><i class="fa fa-check"></i><b>2.1.1</b> Notion de variable</a></li>
<li class="chapter" data-level="2.1.2" data-path="sect021.html"><a href="sect021.html#sect0212"><i class="fa fa-check"></i><b>2.1.2</b> Types de variables</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="sect022.html"><a href="sect022.html"><i class="fa fa-check"></i><b>2.2</b> Types de données</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="sect022.html"><a href="sect022.html#sect0221"><i class="fa fa-check"></i><b>2.2.1</b> Données secondaires <em>versus</em> données primaires</a></li>
<li class="chapter" data-level="2.2.2" data-path="sect022.html"><a href="sect022.html#sect0222"><i class="fa fa-check"></i><b>2.2.2</b> Données transversales <em>versus</em> données longitudinales</a></li>
<li class="chapter" data-level="2.2.3" data-path="sect022.html"><a href="sect022.html#sect0223"><i class="fa fa-check"></i><b>2.2.3</b> Données spatiales versus données aspatiales</a></li>
<li class="chapter" data-level="2.2.4" data-path="sect022.html"><a href="sect022.html#sect0224"><i class="fa fa-check"></i><b>2.2.4</b> Données individuelles <em>versus</em> données agrégées</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="sect023.html"><a href="sect023.html"><i class="fa fa-check"></i><b>2.3</b> Statistique descriptive et statistique inférentielle</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="sect023.html"><a href="sect023.html#sect0231"><i class="fa fa-check"></i><b>2.3.1</b> Population, échantillon et inférence</a></li>
<li class="chapter" data-level="2.3.2" data-path="sect023.html"><a href="sect023.html#sect0232"><i class="fa fa-check"></i><b>2.3.2</b> Deux grandes familles de méthodes statistiques</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="sect024.html"><a href="sect024.html"><i class="fa fa-check"></i><b>2.4</b> Notion de distribution</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="sect024.html"><a href="sect024.html#définition-générale"><i class="fa fa-check"></i><b>2.4.1</b> Définition générale</a></li>
<li class="chapter" data-level="2.4.2" data-path="sect024.html"><a href="sect024.html#anatomie-dune-distribution"><i class="fa fa-check"></i><b>2.4.2</b> Anatomie d’une distribution</a></li>
<li class="chapter" data-level="2.4.3" data-path="sect024.html"><a href="sect024.html#principales-distributions"><i class="fa fa-check"></i><b>2.4.3</b> Principales distributions</a></li>
<li class="chapter" data-level="2.4.4" data-path="sect024.html"><a href="sect024.html#conclusion-sur-les-distributions"><i class="fa fa-check"></i><b>2.4.4</b> Conclusion sur les distributions</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="sect025.html"><a href="sect025.html"><i class="fa fa-check"></i><b>2.5</b> Statistiques descriptives sur des variables quantitatives</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="sect025.html"><a href="sect025.html#sect0251"><i class="fa fa-check"></i><b>2.5.1</b> Paramètres de tendance centrale</a></li>
<li class="chapter" data-level="2.5.2" data-path="sect025.html"><a href="sect025.html#sect0252"><i class="fa fa-check"></i><b>2.5.2</b> Paramètres de position</a></li>
<li class="chapter" data-level="2.5.3" data-path="sect025.html"><a href="sect025.html#sect0253"><i class="fa fa-check"></i><b>2.5.3</b> Paramètres de dispersion</a></li>
<li class="chapter" data-level="2.5.4" data-path="sect025.html"><a href="sect025.html#sect0254"><i class="fa fa-check"></i><b>2.5.4</b> Paramètres de forme</a></li>
<li class="chapter" data-level="2.5.5" data-path="sect025.html"><a href="sect025.html#sect0255"><i class="fa fa-check"></i><b>2.5.5</b> Transformation des variables</a></li>
<li class="chapter" data-level="2.5.6" data-path="sect025.html"><a href="sect025.html#sect0256"><i class="fa fa-check"></i><b>2.5.6</b> Mise en œuvre dans R</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="sect026.html"><a href="sect026.html"><i class="fa fa-check"></i><b>2.6</b> Statistiques descriptives sur des variables qualitatives et semi-qualitatives</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="sect026.html"><a href="sect026.html#sect0261"><i class="fa fa-check"></i><b>2.6.1</b> Fréquences</a></li>
<li class="chapter" data-level="2.6.2" data-path="sect026.html"><a href="sect026.html#sect0262"><i class="fa fa-check"></i><b>2.6.2</b> Mise en œuvre dans R</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="sect027.html"><a href="sect027.html"><i class="fa fa-check"></i><b>2.7</b> Statistiques descriptives pondérées : pour aller plus loin</a></li>
<li class="chapter" data-level="2.8" data-path="sect028.html"><a href="sect028.html"><i class="fa fa-check"></i><b>2.8</b> Quiz de révision du chapitre</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="chap03.html"><a href="chap03.html"><i class="fa fa-check"></i><b>3</b> Magie des graphiques</a>
<ul>
<li class="chapter" data-level="3.1" data-path="sect031.html"><a href="sect031.html"><i class="fa fa-check"></i><b>3.1</b> Philosophie du ggplot2</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="sect031.html"><a href="sect031.html#sect0311"><i class="fa fa-check"></i><b>3.1.1</b> Grammaire</a></li>
<li class="chapter" data-level="3.1.2" data-path="sect031.html"><a href="sect031.html#sect0312"><i class="fa fa-check"></i><b>3.1.2</b> Types de géométries</a></li>
<li class="chapter" data-level="3.1.3" data-path="sect031.html"><a href="sect031.html#sect0313"><i class="fa fa-check"></i><b>3.1.3</b> Habillage</a></li>
<li class="chapter" data-level="3.1.4" data-path="sect031.html"><a href="sect031.html#utilisation-des-thèmes"><i class="fa fa-check"></i><b>3.1.4</b> Utilisation des thèmes</a></li>
<li class="chapter" data-level="3.1.5" data-path="sect031.html"><a href="sect031.html#sect0314"><i class="fa fa-check"></i><b>3.1.5</b> Composition d’une figure avec plusieurs graphiques</a></li>
<li class="chapter" data-level="3.1.6" data-path="sect031.html"><a href="sect031.html#sect0315"><i class="fa fa-check"></i><b>3.1.6</b> Couleur</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="sect032.html"><a href="sect032.html"><i class="fa fa-check"></i><b>3.2</b> Principaux graphiques</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="sect032.html"><a href="sect032.html#sect0321"><i class="fa fa-check"></i><b>3.2.1</b> Histogramme</a></li>
<li class="chapter" data-level="3.2.2" data-path="sect032.html"><a href="sect032.html#sect0322"><i class="fa fa-check"></i><b>3.2.2</b> Graphique de densité</a></li>
<li class="chapter" data-level="3.2.3" data-path="sect032.html"><a href="sect032.html#sect0323"><i class="fa fa-check"></i><b>3.2.3</b> Nuage de points</a></li>
<li class="chapter" data-level="3.2.4" data-path="sect032.html"><a href="sect032.html#sect0324"><i class="fa fa-check"></i><b>3.2.4</b> Graphique en ligne</a></li>
<li class="chapter" data-level="3.2.5" data-path="sect032.html"><a href="sect032.html#sect0325"><i class="fa fa-check"></i><b>3.2.5</b> Boîte à moustaches</a></li>
<li class="chapter" data-level="3.2.6" data-path="sect032.html"><a href="sect032.html#sect0326"><i class="fa fa-check"></i><b>3.2.6</b> Graphique en violon</a></li>
<li class="chapter" data-level="3.2.7" data-path="sect032.html"><a href="sect032.html#sect0327"><i class="fa fa-check"></i><b>3.2.7</b> Graphique en barre</a></li>
<li class="chapter" data-level="3.2.8" data-path="sect032.html"><a href="sect032.html#sect0328"><i class="fa fa-check"></i><b>3.2.8</b> Graphique circulaire</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="sect033.html"><a href="sect033.html"><i class="fa fa-check"></i><b>3.3</b> Graphiques spéciaux</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="sect033.html"><a href="sect033.html#sect0331"><i class="fa fa-check"></i><b>3.3.1</b> Graphique en radar</a></li>
<li class="chapter" data-level="3.3.2" data-path="sect033.html"><a href="sect033.html#sect0332"><i class="fa fa-check"></i><b>3.3.2</b> Diagramme d’accord</a></li>
<li class="chapter" data-level="3.3.3" data-path="sect033.html"><a href="sect033.html#sect0333"><i class="fa fa-check"></i><b>3.3.3</b> Nuage de mots</a></li>
<li class="chapter" data-level="3.3.4" data-path="sect033.html"><a href="sect033.html#sect0334"><i class="fa fa-check"></i><b>3.3.4</b> Carte proportionnelle</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="sect034.html"><a href="sect034.html"><i class="fa fa-check"></i><b>3.4</b> Cartes</a></li>
<li class="chapter" data-level="3.5" data-path="sect035.html"><a href="sect035.html"><i class="fa fa-check"></i><b>3.5</b> Exportation des graphiques</a></li>
<li class="chapter" data-level="3.6" data-path="sect036.html"><a href="sect036.html"><i class="fa fa-check"></i><b>3.6</b> Conclusion sur les graphiques</a></li>
</ul></li>
<li class="part"><span><b>III Analyses bivariées</b></span></li>
<li class="chapter" data-level="4" data-path="chap04.html"><a href="chap04.html"><i class="fa fa-check"></i><b>4</b> Relation linéaire entre deux variables quantitatives</a>
<ul>
<li class="chapter" data-level="4.1" data-path="sect041.html"><a href="sect041.html"><i class="fa fa-check"></i><b>4.1</b> Bref retour sur le postulat de la relation linéaire</a></li>
<li class="chapter" data-level="4.2" data-path="sect042.html"><a href="sect042.html"><i class="fa fa-check"></i><b>4.2</b> Covariance</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="sect042.html"><a href="sect042.html#sect0421"><i class="fa fa-check"></i><b>4.2.1</b> Formulation</a></li>
<li class="chapter" data-level="4.2.2" data-path="sect042.html"><a href="sect042.html#sect0422"><i class="fa fa-check"></i><b>4.2.2</b> Interprétation</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="sect043.html"><a href="sect043.html"><i class="fa fa-check"></i><b>4.3</b> Corrélation</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="sect043.html"><a href="sect043.html#sect0431"><i class="fa fa-check"></i><b>4.3.1</b> Formulation</a></li>
<li class="chapter" data-level="4.3.2" data-path="sect043.html"><a href="sect043.html#sect0432"><i class="fa fa-check"></i><b>4.3.2</b> Interprétation</a></li>
<li class="chapter" data-level="4.3.3" data-path="sect043.html"><a href="sect043.html#sect0433"><i class="fa fa-check"></i><b>4.3.3</b> Corrélations pour des variables anormalement distribuées (coefficient de Spearman, tau de Kendall)</a></li>
<li class="chapter" data-level="4.3.4" data-path="sect043.html"><a href="sect043.html#sect0434"><i class="fa fa-check"></i><b>4.3.4</b> Corrélations robustes (<em>Biweight midcorrelation</em>, <em>Percentage bend correlation</em> et la corrélation <em>pi</em> de Shepherd)</a></li>
<li class="chapter" data-level="4.3.5" data-path="sect043.html"><a href="sect043.html#sect0435"><i class="fa fa-check"></i><b>4.3.5</b> Significativité des coefficients de corrélation</a></li>
<li class="chapter" data-level="4.3.6" data-path="sect043.html"><a href="sect043.html#sect0436"><i class="fa fa-check"></i><b>4.3.6</b> Corrélation partielle</a></li>
<li class="chapter" data-level="4.3.7" data-path="sect043.html"><a href="sect043.html#sect0437"><i class="fa fa-check"></i><b>4.3.7</b> Mise en œuvre dans R</a></li>
<li class="chapter" data-level="4.3.8" data-path="sect043.html"><a href="sect043.html#sect0438"><i class="fa fa-check"></i><b>4.3.8</b> Comment rapporter des valeurs de corrélations?</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="sect044.html"><a href="sect044.html"><i class="fa fa-check"></i><b>4.4</b> Régression linéaire simple</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="sect044.html"><a href="sect044.html#sect0441"><i class="fa fa-check"></i><b>4.4.1</b> Principe de base de la régression linéaire simple</a></li>
<li class="chapter" data-level="4.4.2" data-path="sect044.html"><a href="sect044.html#sect0442"><i class="fa fa-check"></i><b>4.4.2</b> Formulation de la droite de régression des moindres carrés ordinaires</a></li>
<li class="chapter" data-level="4.4.3" data-path="sect044.html"><a href="sect044.html#sect0443"><i class="fa fa-check"></i><b>4.4.3</b> Mesure de la qualité d’ajustement du modèle</a></li>
<li class="chapter" data-level="4.4.4" data-path="sect044.html"><a href="sect044.html#sect0444"><i class="fa fa-check"></i><b>4.4.4</b> Mise en œuvre dans R</a></li>
<li class="chapter" data-level="4.4.5" data-path="sect044.html"><a href="sect044.html#sect0445"><i class="fa fa-check"></i><b>4.4.5</b> Comment rapporter une régression linéaire simple</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="sect045.html"><a href="sect045.html"><i class="fa fa-check"></i><b>4.5</b> Quiz de révision du chapitre</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="chap05.html"><a href="chap05.html"><i class="fa fa-check"></i><b>5</b> Relation entre deux variables qualitatives</a>
<ul>
<li class="chapter" data-level="5.1" data-path="sect051.html"><a href="sect051.html"><i class="fa fa-check"></i><b>5.1</b> Construction de tableau de contingence</a></li>
<li class="chapter" data-level="5.2" data-path="sect052.html"><a href="sect052.html"><i class="fa fa-check"></i><b>5.2</b> Test du khi-deux</a></li>
<li class="chapter" data-level="5.3" data-path="sect053.html"><a href="sect053.html"><i class="fa fa-check"></i><b>5.3</b> Mise en œuvre dans R</a></li>
<li class="chapter" data-level="5.4" data-path="sect054.html"><a href="sect054.html"><i class="fa fa-check"></i><b>5.4</b> Interprétation d’un tableau de contingence</a></li>
<li class="chapter" data-level="5.5" data-path="sect055.html"><a href="sect055.html"><i class="fa fa-check"></i><b>5.5</b> Quiz de révision du chapitre</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="chap06.html"><a href="chap06.html"><i class="fa fa-check"></i><b>6</b> Relation entre une variable qualitative et une variable quantitative</a>
<ul>
<li class="chapter" data-level="6.1" data-path="sect061.html"><a href="sect061.html"><i class="fa fa-check"></i><b>6.1</b> Relation entre une variable quantitative et une variable qualitative à deux modalités</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="sect061.html"><a href="sect061.html#sect0611"><i class="fa fa-check"></i><b>6.1.1</b> Test <em>t</em> et ses différentes variantes</a></li>
<li class="chapter" data-level="6.1.2" data-path="sect061.html"><a href="sect061.html#sect0612"><i class="fa fa-check"></i><b>6.1.2</b> Test non paramétrique de Wilcoxon</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="sect062.html"><a href="sect062.html"><i class="fa fa-check"></i><b>6.2</b> Relation entre une variable quantitative et une variable qualitative à plus de deux modalités</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="sect062.html"><a href="sect062.html#sect0621"><i class="fa fa-check"></i><b>6.2.1</b> Analyse de variance</a></li>
<li class="chapter" data-level="6.2.2" data-path="sect062.html"><a href="sect062.html#sect0622"><i class="fa fa-check"></i><b>6.2.2</b> Test non paramétrique de Kruskal-Wallis</a></li>
<li class="chapter" data-level="6.2.3" data-path="sect062.html"><a href="sect062.html#sect0623"><i class="fa fa-check"></i><b>6.2.3</b> Mise en œuvre dans R</a></li>
<li class="chapter" data-level="6.2.4" data-path="sect062.html"><a href="sect062.html#sect0624"><i class="fa fa-check"></i><b>6.2.4</b> Comment rapporter les résultats d’une ANOVA et du test de Kruskal-Wallis</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="sect063.html"><a href="sect063.html"><i class="fa fa-check"></i><b>6.3</b> Conclusion sur la troisième partie</a></li>
<li class="chapter" data-level="6.4" data-path="sect064.html"><a href="sect064.html"><i class="fa fa-check"></i><b>6.4</b> Quiz de révision du chapitre</a></li>
</ul></li>
<li class="part"><span><b>IV Modèles de régression</b></span></li>
<li class="chapter" data-level="7" data-path="chap07.html"><a href="chap07.html"><i class="fa fa-check"></i><b>7</b> Régression linéaire multiple</a>
<ul>
<li class="chapter" data-level="7.1" data-path="sect071.html"><a href="sect071.html"><i class="fa fa-check"></i><b>7.1</b> Objectifs de la régression linéaire multiple et construction d’un modèle de régression</a></li>
<li class="chapter" data-level="7.2" data-path="sect072.html"><a href="sect072.html"><i class="fa fa-check"></i><b>7.2</b> Principes de base de la régression linéaire multiple</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="sect072.html"><a href="sect072.html#sect0721"><i class="fa fa-check"></i><b>7.2.1</b> Un peu d’équations…</a></li>
<li class="chapter" data-level="7.2.2" data-path="sect072.html"><a href="sect072.html#sect0722"><i class="fa fa-check"></i><b>7.2.2</b> Hypothèses de la régression linéaire multiple</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="sect073.html"><a href="sect073.html"><i class="fa fa-check"></i><b>7.3</b> Évaluation de la qualité d’ajustement du modèle</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="sect073.html"><a href="sect073.html#sect0731"><i class="fa fa-check"></i><b>7.3.1</b> Mesures de la qualité d’un modèle</a></li>
<li class="chapter" data-level="7.3.2" data-path="sect073.html"><a href="sect073.html#sect0732"><i class="fa fa-check"></i><b>7.3.2</b> Comparaison des modèles incrémentiels</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="sect074.html"><a href="sect074.html"><i class="fa fa-check"></i><b>7.4</b> Différentes mesures pour les coefficients de régression</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="sect074.html"><a href="sect074.html#sect0741"><i class="fa fa-check"></i><b>7.4.1</b> Coefficients de régression : évaluer l’effet des variables indépendantes</a></li>
<li class="chapter" data-level="7.4.2" data-path="sect074.html"><a href="sect074.html#sect0742"><i class="fa fa-check"></i><b>7.4.2</b> Coefficients de régression standardisés : repérer les variables les plus importantes du modèle</a></li>
<li class="chapter" data-level="7.4.3" data-path="sect074.html"><a href="sect074.html#sect0743"><i class="fa fa-check"></i><b>7.4.3</b> Significativité des coefficients de régression : valeurs de <em>t</em> et de <em>p</em></a></li>
<li class="chapter" data-level="7.4.4" data-path="sect074.html"><a href="sect074.html#sect0744"><i class="fa fa-check"></i><b>7.4.4</b> Intervalle de confiance des coefficients</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="sect075.html"><a href="sect075.html"><i class="fa fa-check"></i><b>7.5</b> Introduction de variables explicatives particulières</a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="sect075.html"><a href="sect075.html#sect0751"><i class="fa fa-check"></i><b>7.5.1</b> Exploration des relations non linéaires</a></li>
<li class="chapter" data-level="7.5.2" data-path="sect075.html"><a href="sect075.html#sect0752"><i class="fa fa-check"></i><b>7.5.2</b> Variable indépendante qualitative dichotomique</a></li>
<li class="chapter" data-level="7.5.3" data-path="sect075.html"><a href="sect075.html#sect0753"><i class="fa fa-check"></i><b>7.5.3</b> Variable indépendante qualitative polytomique</a></li>
<li class="chapter" data-level="7.5.4" data-path="sect075.html"><a href="sect075.html#sect0754"><i class="fa fa-check"></i><b>7.5.4</b> Variables d’interaction</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="sect076.html"><a href="sect076.html"><i class="fa fa-check"></i><b>7.6</b> Diagnostics de la régression</a>
<ul>
<li class="chapter" data-level="7.6.1" data-path="sect076.html"><a href="sect076.html#sect0761"><i class="fa fa-check"></i><b>7.6.1</b> Nombre d’observations</a></li>
<li class="chapter" data-level="7.6.2" data-path="sect076.html"><a href="sect076.html#sect0762"><i class="fa fa-check"></i><b>7.6.2</b> Normalité des résidus</a></li>
<li class="chapter" data-level="7.6.3" data-path="sect076.html"><a href="sect076.html#sect0763"><i class="fa fa-check"></i><b>7.6.3</b> Linéarité et homoscédasticité des résidus</a></li>
<li class="chapter" data-level="7.6.4" data-path="sect076.html"><a href="sect076.html#sect0764"><i class="fa fa-check"></i><b>7.6.4</b> Absence de multicolinéarité excessive</a></li>
<li class="chapter" data-level="7.6.5" data-path="sect076.html"><a href="sect076.html#sect0766"><i class="fa fa-check"></i><b>7.6.5</b> Absence d’observations aberrantes</a></li>
</ul></li>
<li class="chapter" data-level="7.7" data-path="sect077.html"><a href="sect077.html"><i class="fa fa-check"></i><b>7.7</b> Mise en œuvre dans R</a>
<ul>
<li class="chapter" data-level="7.7.1" data-path="sect077.html"><a href="sect077.html#sect0771"><i class="fa fa-check"></i><b>7.7.1</b> Fonctions <code>lm</code>, <code>summary()</code> et <code>confint()</code></a></li>
<li class="chapter" data-level="7.7.2" data-path="sect077.html"><a href="sect077.html#sect0772"><i class="fa fa-check"></i><b>7.7.2</b> Comparaison des modèles</a></li>
<li class="chapter" data-level="7.7.3" data-path="sect077.html"><a href="sect077.html#sect0773"><i class="fa fa-check"></i><b>7.7.3</b> Diagnostic sur un modèle</a></li>
<li class="chapter" data-level="7.7.4" data-path="sect077.html"><a href="sect077.html#sect0774"><i class="fa fa-check"></i><b>7.7.4</b> Graphiques pour les effets marginaux</a></li>
</ul></li>
<li class="chapter" data-level="7.8" data-path="sect078.html"><a href="sect078.html"><i class="fa fa-check"></i><b>7.8</b> Quiz de révision du chapitre</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="chap08.html"><a href="chap08.html"><i class="fa fa-check"></i><b>8</b> Régressions linéaires généralisées (GLM)</a>
<ul>
<li class="chapter" data-level="8.1" data-path="sect081.html"><a href="sect081.html"><i class="fa fa-check"></i><b>8.1</b> Qu’est qu’un modèle GLM?</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="sect081.html"><a href="sect081.html#sect0811"><i class="fa fa-check"></i><b>8.1.1</b> Formulation d’un GLM</a></li>
<li class="chapter" data-level="8.1.2" data-path="sect081.html"><a href="sect081.html#sect0812"><i class="fa fa-check"></i><b>8.1.2</b> Autres distributions et rôle de la fonction de lien</a></li>
<li class="chapter" data-level="8.1.3" data-path="sect081.html"><a href="sect081.html#sect0813"><i class="fa fa-check"></i><b>8.1.3</b> Conditions d’application</a></li>
<li class="chapter" data-level="8.1.4" data-path="sect081.html"><a href="sect081.html#sect0814"><i class="fa fa-check"></i><b>8.1.4</b> Résidus et déviance</a></li>
<li class="chapter" data-level="8.1.5" data-path="sect081.html"><a href="sect081.html#sect0815"><i class="fa fa-check"></i><b>8.1.5</b> Vérification l’ajustement</a></li>
<li class="chapter" data-level="8.1.6" data-path="sect081.html"><a href="sect081.html#sect0816"><i class="fa fa-check"></i><b>8.1.6</b> Comparaison de deux modèles GLM</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="sect082.html"><a href="sect082.html"><i class="fa fa-check"></i><b>8.2</b> Modèles GLM pour des variables qualitatives</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="sect082.html"><a href="sect082.html#sect0821"><i class="fa fa-check"></i><b>8.2.1</b> Modèle logistique binomial</a></li>
<li class="chapter" data-level="8.2.2" data-path="sect082.html"><a href="sect082.html#sect0822"><i class="fa fa-check"></i><b>8.2.2</b> Modèle probit binomial</a></li>
<li class="chapter" data-level="8.2.3" data-path="sect082.html"><a href="sect082.html#sect0823"><i class="fa fa-check"></i><b>8.2.3</b> Modèle logistique des cotes proportionnelles</a></li>
<li class="chapter" data-level="8.2.4" data-path="sect082.html"><a href="sect082.html#sect0824"><i class="fa fa-check"></i><b>8.2.4</b> Modèle logistique multinomial</a></li>
<li class="chapter" data-level="8.2.5" data-path="sect082.html"><a href="sect082.html#conclusion-sur-les-modèles-pour-des-variables-qualitatives"><i class="fa fa-check"></i><b>8.2.5</b> Conclusion sur les modèles pour des variables qualitatives</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="sect084.html"><a href="sect084.html"><i class="fa fa-check"></i><b>8.3</b> Modèles GLM pour des variables de comptage</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="sect084.html"><a href="sect084.html#sect0841"><i class="fa fa-check"></i><b>8.3.1</b> Modèle de Poisson</a></li>
<li class="chapter" data-level="8.3.2" data-path="sect084.html"><a href="sect084.html#sect0842"><i class="fa fa-check"></i><b>8.3.2</b> Modèle binomial négatif</a></li>
<li class="chapter" data-level="8.3.3" data-path="sect084.html"><a href="sect084.html#sect0843"><i class="fa fa-check"></i><b>8.3.3</b> Modèle de Poisson avec excès fixe de zéros</a></li>
<li class="chapter" data-level="8.3.4" data-path="sect084.html"><a href="sect084.html#sect0844"><i class="fa fa-check"></i><b>8.3.4</b> Modèle de Poisson avec excès ajusté de zéros</a></li>
<li class="chapter" data-level="8.3.5" data-path="sect084.html"><a href="sect084.html#sect0845"><i class="fa fa-check"></i><b>8.3.5</b> Conclusion sur les modèles destinés à des variables de comptage</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="sect085.html"><a href="sect085.html"><i class="fa fa-check"></i><b>8.4</b> Modèles GLM pour des variables continues</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="sect085.html"><a href="sect085.html#sect0851"><i class="fa fa-check"></i><b>8.4.1</b> Modèle GLM gaussien</a></li>
<li class="chapter" data-level="8.4.2" data-path="sect085.html"><a href="sect085.html#sect0852"><i class="fa fa-check"></i><b>8.4.2</b> Modèle GLM avec une distribution de Student</a></li>
<li class="chapter" data-level="8.4.3" data-path="sect085.html"><a href="sect085.html#sect0853"><i class="fa fa-check"></i><b>8.4.3</b> Modèle GLM avec distribution Gamma</a></li>
<li class="chapter" data-level="8.4.4" data-path="sect085.html"><a href="sect085.html#sect0854"><i class="fa fa-check"></i><b>8.4.4</b> Modèle GLM avec une distribution bêta</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="sect086.html"><a href="sect086.html"><i class="fa fa-check"></i><b>8.5</b> Conclusion sur les modèles linéaires généralisés</a></li>
<li class="chapter" data-level="8.6" data-path="sect087.html"><a href="sect087.html"><i class="fa fa-check"></i><b>8.6</b> Quiz de révision du chapitre</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="chap09.html"><a href="chap09.html"><i class="fa fa-check"></i><b>9</b> Régressions à effets mixtes (GLMM)</a>
<ul>
<li class="chapter" data-level="9.1" data-path="sect091.html"><a href="sect091.html"><i class="fa fa-check"></i><b>9.1</b> Introduction</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="sect091.html"><a href="sect091.html#sect0911"><i class="fa fa-check"></i><b>9.1.1</b> Indépendance des observations et effets de groupes</a></li>
<li class="chapter" data-level="9.1.2" data-path="sect091.html"><a href="sect091.html#sect0912"><i class="fa fa-check"></i><b>9.1.2</b> Terminologie: effets fixes et effets aléatoires</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="sect092.html"><a href="sect092.html"><i class="fa fa-check"></i><b>9.2</b> Principes de base des GLMM</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="sect092.html"><a href="sect092.html#sect0921"><i class="fa fa-check"></i><b>9.2.1</b> GLMM avec constantes aléatoires</a></li>
<li class="chapter" data-level="9.2.2" data-path="sect092.html"><a href="sect092.html#sect0923"><i class="fa fa-check"></i><b>9.2.2</b> GLMM avec pentes aléatoires</a></li>
<li class="chapter" data-level="9.2.3" data-path="sect092.html"><a href="sect092.html#sect0924"><i class="fa fa-check"></i><b>9.2.3</b> GLMM avec constantes et pentes aléatoires</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="sect093.html"><a href="sect093.html"><i class="fa fa-check"></i><b>9.3</b> Conditions d’application des GLMM</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="sect093.html"><a href="sect093.html#sect0931"><i class="fa fa-check"></i><b>9.3.1</b> Vérification de la distribution des effets aléatoires</a></li>
<li class="chapter" data-level="9.3.2" data-path="sect093.html"><a href="sect093.html#sect0932"><i class="fa fa-check"></i><b>9.3.2</b> Homogénéité des variances au sein des groupes</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="sect094.html"><a href="sect094.html"><i class="fa fa-check"></i><b>9.4</b> Inférence dans les modèles GLMM</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="sect094.html"><a href="sect094.html#sect0941"><i class="fa fa-check"></i><b>9.4.1</b> Inférence pour les effets fixes</a></li>
<li class="chapter" data-level="9.4.2" data-path="sect094.html"><a href="sect094.html#sect0942"><i class="fa fa-check"></i><b>9.4.2</b> Inférence pour les effets aléatoires, effet global</a></li>
<li class="chapter" data-level="9.4.3" data-path="sect094.html"><a href="sect094.html#sect0943"><i class="fa fa-check"></i><b>9.4.3</b> Inférence pour les effets aléatoires, des constantes et des pentes</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="sect095.html"><a href="sect095.html"><i class="fa fa-check"></i><b>9.5</b> Conclusion sur les GLMM</a></li>
<li class="chapter" data-level="9.6" data-path="sect096.html"><a href="sect096.html"><i class="fa fa-check"></i><b>9.6</b> Mise en œuvre des GLMM dans R</a>
<ul>
<li class="chapter" data-level="9.6.1" data-path="sect096.html"><a href="sect096.html#sect0961"><i class="fa fa-check"></i><b>9.6.1</b> Ajustement du modèle avec uniquement une constante aléatoire</a></li>
<li class="chapter" data-level="9.6.2" data-path="sect096.html"><a href="sect096.html#sect0962"><i class="fa fa-check"></i><b>9.6.2</b> Ajustement du modèle avec constantes et pentes aléatoires</a></li>
</ul></li>
<li class="chapter" data-level="9.7" data-path="sect097.html"><a href="sect097.html"><i class="fa fa-check"></i><b>9.7</b> Quiz de révision du chapitre</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="chap10.html"><a href="chap10.html"><i class="fa fa-check"></i><b>10</b> Régressions multiniveaux</a>
<ul>
<li class="chapter" data-level="10.1" data-path="sect101.html"><a href="sect101.html"><i class="fa fa-check"></i><b>10.1</b> Modèles multiniveaux : deux intérêts majeurs</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="sect101.html"><a href="sect101.html#sect1011"><i class="fa fa-check"></i><b>10.1.1</b> Répartition de la variance entre les différents niveaux</a></li>
<li class="chapter" data-level="10.1.2" data-path="sect101.html"><a href="sect101.html#sect1012"><i class="fa fa-check"></i><b>10.1.2</b> Estimation des coefficients aux différents niveaux</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="sect102.html"><a href="sect102.html"><i class="fa fa-check"></i><b>10.2</b> Différents types de modèles multiniveaux</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="sect102.html"><a href="sect102.html#sect1021"><i class="fa fa-check"></i><b>10.2.1</b> Description du jeu de données utilisé</a></li>
<li class="chapter" data-level="10.2.2" data-path="sect102.html"><a href="sect102.html#sect1022"><i class="fa fa-check"></i><b>10.2.2</b> Démarche classique pour les modèles multiniveaux</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="sect103.html"><a href="sect103.html"><i class="fa fa-check"></i><b>10.3</b> Conditions d’application des régressions multiniveaux</a></li>
<li class="chapter" data-level="10.4" data-path="sect104.html"><a href="sect104.html"><i class="fa fa-check"></i><b>10.4</b> Mise en œuvre dans R</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="sect104.html"><a href="sect104.html#sect1041"><i class="fa fa-check"></i><b>10.4.1</b> Le modèle vide</a></li>
<li class="chapter" data-level="10.4.2" data-path="sect104.html"><a href="sect104.html#sect1042"><i class="fa fa-check"></i><b>10.4.2</b> Modèle avec les variables indépendantes du niveau 1</a></li>
<li class="chapter" data-level="10.4.3" data-path="sect104.html"><a href="sect104.html#sect1043"><i class="fa fa-check"></i><b>10.4.3</b> Modèle avec les variables indépendantes aux niveaux 1 et 2</a></li>
<li class="chapter" data-level="10.4.4" data-path="sect104.html"><a href="sect104.html#sect10414"><i class="fa fa-check"></i><b>10.4.4</b> Modèle complet avec une interaction</a></li>
<li class="chapter" data-level="10.4.5" data-path="sect104.html"><a href="sect104.html#sect1045"><i class="fa fa-check"></i><b>10.4.5</b> Comparaison des quatre modèles</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="sect105.html"><a href="sect105.html"><i class="fa fa-check"></i><b>10.5</b> Quiz de révision du chapitre</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="chap11.html"><a href="chap11.html"><i class="fa fa-check"></i><b>11</b> Modèles généralisés additifs</a>
<ul>
<li class="chapter" data-level="11.1" data-path="sect111.html"><a href="sect111.html"><i class="fa fa-check"></i><b>11.1</b> Introduction</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="sect111.html"><a href="sect111.html#sect1111"><i class="fa fa-check"></i><b>11.1.1</b> Non linéarité fonctionnelle</a></li>
<li class="chapter" data-level="11.1.2" data-path="sect111.html"><a href="sect111.html#sect1112"><i class="fa fa-check"></i><b>11.1.2</b> Non linéarité avec des polynomiales</a></li>
<li class="chapter" data-level="11.1.3" data-path="sect111.html"><a href="sect111.html#sect1113"><i class="fa fa-check"></i><b>11.1.3</b> Non linéarité par segments</a></li>
<li class="chapter" data-level="11.1.4" data-path="sect111.html"><a href="sect111.html#sect1114"><i class="fa fa-check"></i><b>11.1.4</b> Non linéarité avec des <em>splines</em></a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="sect112.html"><a href="sect112.html"><i class="fa fa-check"></i><b>11.2</b> <em>Spline</em> de régression et <em>spline</em> de lissage</a></li>
<li class="chapter" data-level="11.3" data-path="sect113.html"><a href="sect113.html"><i class="fa fa-check"></i><b>11.3</b> Interprétation d’une <em>spline</em></a></li>
<li class="chapter" data-level="11.4" data-path="sect114.html"><a href="sect114.html"><i class="fa fa-check"></i><b>11.4</b> Multicolinéarité non linéaire</a></li>
<li class="chapter" data-level="11.5" data-path="sect115.html"><a href="sect115.html"><i class="fa fa-check"></i><b>11.5</b> <em>Splines</em> avancées</a>
<ul>
<li class="chapter" data-level="11.5.1" data-path="sect115.html"><a href="sect115.html#sect1151"><i class="fa fa-check"></i><b>11.5.1</b> <em>Splines</em> cycliques</a></li>
<li class="chapter" data-level="11.5.2" data-path="sect115.html"><a href="sect115.html#sect1152"><i class="fa fa-check"></i><b>11.5.2</b> Splines par groupe</a></li>
<li class="chapter" data-level="11.5.3" data-path="sect115.html"><a href="sect115.html#sect1153"><i class="fa fa-check"></i><b>11.5.3</b> <em>Splines</em> multivariées et <em>splines</em> d’interaction</a></li>
</ul></li>
<li class="chapter" data-level="11.6" data-path="sect116.html"><a href="sect116.html"><i class="fa fa-check"></i><b>11.6</b> Mise en oeuvre dans R</a></li>
<li class="chapter" data-level="11.7" data-path="sect117.html"><a href="sect117.html"><i class="fa fa-check"></i><b>11.7</b> GAMM</a></li>
<li class="chapter" data-level="11.8" data-path="sect118.html"><a href="sect118.html"><i class="fa fa-check"></i><b>11.8</b> Quiz de révision du chapitre</a></li>
</ul></li>
<li class="part"><span><b>V Analyses exploratoires multivariées</b></span></li>
<li class="chapter" data-level="12" data-path="chap12.html"><a href="chap12.html"><i class="fa fa-check"></i><b>12</b> Méthodes factorielles</a>
<ul>
<li class="chapter" data-level="12.1" data-path="sect121.html"><a href="sect121.html"><i class="fa fa-check"></i><b>12.1</b> Aperçu des méthodes factorielles</a>
<ul>
<li class="chapter" data-level="12.1.1" data-path="sect121.html"><a href="sect121.html#sect1211"><i class="fa fa-check"></i><b>12.1.1</b> Méthodes factorielles et types de données</a></li>
<li class="chapter" data-level="12.1.2" data-path="sect121.html"><a href="sect121.html#sect1212"><i class="fa fa-check"></i><b>12.1.2</b> Bref historique des méthodes factorielles</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="sect122.html"><a href="sect122.html"><i class="fa fa-check"></i><b>12.2</b> Analyses en composantes principales (ACP)</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="sect122.html"><a href="sect122.html#sect1221"><i class="fa fa-check"></i><b>12.2.1</b> Recherche d’une simplification</a></li>
<li class="chapter" data-level="12.2.2" data-path="sect122.html"><a href="sect122.html#sect1222"><i class="fa fa-check"></i><b>12.2.2</b> Aides à l’interprétation</a></li>
<li class="chapter" data-level="12.2.3" data-path="sect122.html"><a href="sect122.html#sect1223"><i class="fa fa-check"></i><b>12.2.3</b> Mise en œuvre dans R</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="sect123.html"><a href="sect123.html"><i class="fa fa-check"></i><b>12.3</b> Analyse factorielle des correspondances (AFC)</a>
<ul>
<li class="chapter" data-level="12.3.1" data-path="sect123.html"><a href="sect123.html#sect1231"><i class="fa fa-check"></i><b>12.3.1</b> Recherche d’une simplification basée sur la distance du khi-deux</a></li>
<li class="chapter" data-level="12.3.2" data-path="sect123.html"><a href="sect123.html#sect1232"><i class="fa fa-check"></i><b>12.3.2</b> Aides à l’interprétation</a></li>
<li class="chapter" data-level="12.3.3" data-path="sect123.html"><a href="sect123.html#sect1233"><i class="fa fa-check"></i><b>12.3.3</b> Mise en œuvre dans R</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="sect124.html"><a href="sect124.html"><i class="fa fa-check"></i><b>12.4</b> Analyse de correspondances multiples (ACM)</a>
<ul>
<li class="chapter" data-level="12.4.1" data-path="sect124.html"><a href="sect124.html#sect1241"><i class="fa fa-check"></i><b>12.4.1</b> Aides à l’interprétation</a></li>
<li class="chapter" data-level="12.4.2" data-path="sect124.html"><a href="sect124.html#sect1242"><i class="fa fa-check"></i><b>12.4.2</b> Mise en œuvre dans R</a></li>
</ul></li>
<li class="chapter" data-level="12.5" data-path="sect125.html"><a href="sect125.html"><i class="fa fa-check"></i><b>12.5</b> Quiz de révision du chapitre</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="chap13.html"><a href="chap13.html"><i class="fa fa-check"></i><b>13</b> Méthodes de classification non supervisée</a>
<ul>
<li class="chapter" data-level="13.1" data-path="sect131.html"><a href="sect131.html"><i class="fa fa-check"></i><b>13.1</b> Méthodes de classification : un aperçu</a></li>
<li class="chapter" data-level="13.2" data-path="sect132.html"><a href="sect132.html"><i class="fa fa-check"></i><b>13.2</b> Notions essentielles en classification</a>
<ul>
<li class="chapter" data-level="13.2.1" data-path="sect132.html"><a href="sect132.html#sect1321"><i class="fa fa-check"></i><b>13.2.1</b> Distance</a></li>
<li class="chapter" data-level="13.2.2" data-path="sect132.html"><a href="sect132.html#sect1322"><i class="fa fa-check"></i><b>13.2.2</b> Inertie</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="sect133.html"><a href="sect133.html"><i class="fa fa-check"></i><b>13.3</b> Classification ascendante hiérarchique</a>
<ul>
<li class="chapter" data-level="13.3.1" data-path="sect133.html"><a href="sect133.html#sect1331"><i class="fa fa-check"></i><b>13.3.1</b> Fonctionnement de l’algorithme</a></li>
<li class="chapter" data-level="13.3.2" data-path="sect133.html"><a href="sect133.html#sect1332"><i class="fa fa-check"></i><b>13.3.2</b> Choisir le bon nombre de groupes</a></li>
<li class="chapter" data-level="13.3.3" data-path="sect133.html"><a href="sect133.html#sect1333"><i class="fa fa-check"></i><b>13.3.3</b> Limites de la classification ascendante hiérarchique</a></li>
<li class="chapter" data-level="13.3.4" data-path="sect133.html"><a href="sect133.html#sect1334"><i class="fa fa-check"></i><b>13.3.4</b> Mise en oeuvre dans R</a></li>
</ul></li>
<li class="chapter" data-level="13.4" data-path="sect134.html"><a href="sect134.html"><i class="fa fa-check"></i><b>13.4</b> Nuées dynamiques</a>
<ul>
<li class="chapter" data-level="13.4.1" data-path="sect134.html"><a href="sect134.html#sect1341"><i class="fa fa-check"></i><b>13.4.1</b> <em>K-means</em></a></li>
<li class="chapter" data-level="13.4.2" data-path="sect134.html"><a href="sect134.html#sect1342"><i class="fa fa-check"></i><b>13.4.2</b> K-médianes</a></li>
<li class="chapter" data-level="13.4.3" data-path="sect134.html"><a href="sect134.html#sect1343"><i class="fa fa-check"></i><b>13.4.3</b> K-médoïds</a></li>
<li class="chapter" data-level="13.4.4" data-path="sect134.html"><a href="sect134.html#sect1344"><i class="fa fa-check"></i><b>13.4.4</b> Mise en oeuvre dans R</a></li>
<li class="chapter" data-level="13.4.5" data-path="sect134.html"><a href="sect134.html#sect1346"><i class="fa fa-check"></i><b>13.4.5</b> Extensions en logique floue : <em>c-means</em>, <em>c-medoids</em></a></li>
</ul></li>
<li class="chapter" data-level="13.5" data-path="sect135.html"><a href="sect135.html"><i class="fa fa-check"></i><b>13.5</b> Conclusion sur la cinquième partie</a></li>
<li class="chapter" data-level="13.6" data-path="sect136.html"><a href="sect136.html"><i class="fa fa-check"></i><b>13.6</b> Quiz de révision du chapitre</a></li>
</ul></li>
<li class="part"><span><b>VI Annexes</b></span></li>
<li class="chapter" data-level="14" data-path="annexe1.html"><a href="annexe1.html"><i class="fa fa-check"></i><b>14</b> Table des valeurs critiques de khi-deux</a></li>
<li class="chapter" data-level="15" data-path="annexe2.html"><a href="annexe2.html"><i class="fa fa-check"></i><b>15</b> Table des valeurs critiques de Fisher</a></li>
<li class="chapter" data-level="16" data-path="annexe3.html"><a href="annexe3.html"><i class="fa fa-check"></i><b>16</b> Table des valeurs critiques de <em>t</em></a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Méthodes quantitatives en sciences sociales : un grand bol d’R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="sect062" class="section level2 hasAnchor" number="6.2">
<h2><span class="header-section-number">6.2</span> Relation entre une variable quantitative et une variable qualitative à plus de deux modalités<a href="sect062.html#sect062" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="bloc_objectif">
<p><strong>Existe-t-il une relation entre une variable continue et une variable qualitative comprenant plus de deux modalités?</strong> Pour répondre à cette question, nous avons recours à deux méthodes : l’analyse de variance – <strong>ANOVA</strong>, <em><strong>AN</strong>alysis <strong>O</strong>f <strong>VA</strong>riance</em> en anglais – et le test non paramétrique de Kruskal-Wallis. La première permet de vérifier si les moyennes de plusieurs groupes d’une population donnée sont ou non significativement différentes; la seconde, si leurs médianes sont différentes.</p>
</div>
<div id="sect0621" class="section level3 hasAnchor" number="6.2.1">
<h3><span class="header-section-number">6.2.1</span> Analyse de variance<a href="sect062.html#sect0621" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>L’analyse de variance (ANOVA) est largement utilisée en psychologie, en médecine et en pharmacologie. Prenons un exemple classique en pharmacologie pour tester l’efficacité d’un médicament. Quatre groupes de population sont constitués :</p>
<ul>
<li>un premier groupe d’individus pour lequel nous administrons un placebo (un médicament sans substance active), soit le groupe de contrôle ou le groupe témoin;</li>
<li>un second groupe auquel nous administrons le médicament avec un faible dosage;</li>
<li>un troisième avec un dosage moyen;</li>
<li>un quatrième avec un dosage élevé.</li>
</ul>
<p>La variable continue permet d’évaluer l’évolution de l’état de santé des individus (par exemple, la variation du taux de globules rouges dans le sang avant et après le traitement). Si le traitement est efficace, nous nous attendons alors à ce que les moyennes des deuxième, troisième et quatrième groupes soient plus élevées que celle du groupe de contrôle. Les différences de moyennes entre les second, troisième et quatrième groupes permettent aussi de repérer le dosage le plus efficace. Si nous n’observons aucune différence significative entre les groupes, cela signifie que l’effet du médicament ne diffère pas de l’effet d’un placébo.</p>
<p>L’ANOVA est aussi très utilisée en études urbaines, principalement pour vérifier si un phénomène urbain varie selon plusieurs groupes d’une population donnée ou de régions géographiques. En guise d’exemple, le recours à l’ANOVA permet de répondre aux questions suivantes :</p>
<ul>
<li><p>Les moyennes des niveaux d’exposition à un polluant atmosphérique (variable continue) varient-elles significativement selon le mode de transport utilisé (automobile, vélo, transport en commun) pour des trajets similaires en heures de pointe?</p></li>
<li><p>Pour une métropole donnée, les moyennes des loyers (variable continue) sont-elles différentes entre les logements de la ville centre versus ceux localisés dans la première couronne et ceux de la seconde couronne?</p></li>
</ul>
<div id="sect06211" class="section level4 hasAnchor" number="6.2.1.1">
<h4><span class="header-section-number">6.2.1.1</span> Calcul des trois variances pour l’ANOVA<a href="sect062.html#sect06211" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>L’ANOVA repose sur le calcul de trois variances :</p>
<ul>
<li><p><strong>la variance totale</strong> (<em>VT</em>) de la variable dépendante continue, soit la somme des carrés des écarts à la moyenne de l’ensemble de la population (équation <a href="sect062.html#eq:anova1">(6.8)</a>);</p></li>
<li><p>la <strong>variance intergroupe</strong> (<em>Var<sub>inter</sub></em>) ou variance expliquée (<em>VE</em>), soit la somme des carrés des écarts entre la moyenne de chaque groupe et la moyenne de l’ensemble du jeu de données multipliées par le nombre d’individus appartenant à chacun des groupes (équation <a href="sect062.html#eq:anova2">(6.9)</a>);</p></li>
<li><p>la <strong>variance intragroupe</strong> (<em>Var<sub>intra</sub></em>) ou variance non expliquée (<em>VNE</em>), soit la somme des variances des groupes de la variable indépendante (équation <a href="sect062.html#eq:anova3">(6.10)</a>).</p></li>
</ul>
<p><span class="math display" id="eq:anova1">\[\begin{equation}
VT=\sum_{i=1}^n (y_{i}-\overline{y})^2
\tag{6.8}
\end{equation}\]</span>
</p>
<p><span class="math display" id="eq:anova2">\[\begin{equation}
Var_{inter} \mbox{ ou } VE=n_{g_1}\sum_{i\in{g_1}}(\overline{y_{g_1}}-\overline{y})^2 + n_{g_2}\sum_{i\in{g_2}}(\overline{y_{g_2}}-\overline{y})^2 + ... + n_{g_k}\sum_{i\in{g_n}}(\overline{y_{g_k}}-\overline{y})^2
\tag{6.9}
\end{equation}\]</span>
</p>
<p><span class="math display" id="eq:anova3">\[\begin{equation}
Var_{intra} \mbox{ ou } VNE=\sum_{i\in{g_1}}(y_{i}-\overline{y_{g_1}})^2 + \sum_{i\in{g_2}}(y_{i}-\overline{y_{g_2}})^2 + ... + \sum_{i\in{g_n}}(y_{i}-\overline{y_{g_k}})^2
\tag{6.10}
\end{equation}\]</span>
</p>
<p>où <span class="math inline">\(\overline{y}\)</span> est la moyenne de l’ensemble de la population; <span class="math inline">\(\overline{y_{g_1}}\)</span>, <span class="math inline">\(\overline{y_{g_2}}\)</span>, <span class="math inline">\(\overline{y_{g_k}}\)</span> sont respectivement les moyennes des groupes 1 à <em>k</em> (<em>k</em> étant le nombre de modalités de la variable qualitative) et <span class="math inline">\(n_{g_1}\)</span>,<span class="math inline">\(n_{g_2}\)</span> et <span class="math inline">\(n_{g_k}\)</span> sont les nombres d’observations dans les groupes 1 à <em>k</em>.</p>
<p>La variance totale (<em>VT</em>) est égale à la somme de la variance intergroupe (expliquée) et la variance intragroupe (non expliquée) (équation <a href="sect062.html#eq:anova5">(6.11)</a>). Le ratio entre la variance intergroupe (expliquée) et la variance totale est dénommé <em>Eta<sup>2</sup></em> (équation <a href="sect062.html#eq:anova6">(6.12)</a>). Il varie de 0 à 1 et exprime la proportion de la variance de la variable continue qui est expliquée par les différentes modalités de la variable qualitative.</p>
<p><span class="math display" id="eq:anova5">\[\begin{equation}
VT = Var_{inter} + Var_{intra} \mbox{ ou } VT = VNE + VE
\tag{6.11}
\end{equation}\]</span>
</p>
<p><span class="math display" id="eq:anova6">\[\begin{equation}
\eta^2= \frac{Var_{inter}}{VT} \mbox{ ou }  \eta^2= \frac{VE}{VT}
\tag{6.12}
\end{equation}\]</span>
</p>
<div class="bloc_astuce">
<p><strong>La décomposition de la variance totale</strong> – égale à la somme des variances intragroupe et intergroupe – est fondamentale en statistique. Nous verrons qu’elle est aussi utilisée pour évaluer la qualité d’une partition d’une population en plusieurs groupes dans le chapitre sur les méthodes de classification (chapitre <a href="chap13.html#chap13">13</a>). En ANOVA, nous retenons que :</p>
<ul>
<li>plus la variance intragroupe est faible, plus les différents groupes sont homogènes;</li>
<li>plus la variance intergroupe est forte, plus les moyennes des groupes sont différentes et donc plus les groupes sont dissemblables.</li>
</ul>
<p>Autrement dit, plus la variance intergroupe (<strong>dissimilarité</strong> des groupes) est maximisée et corollairement plus la variance intragroupe (<strong>homogénéité</strong> de chacun des groupes) est minimisée, plus les groupes sont clairement distincts et plus l’ANOVA est performante.</p>
</div>
<p>Examinons un premier jeu de données fictives sur la vitesse de déplacement de cyclistes (variable continue exprimée en km/h) et une variable qualitative comprenant trois groupes de cyclistes utilisant soit un vélo personnel (<em>n<sub>A</sub></em> = 5), soit en libre-service (<em>n<sub>B</sub></em> = 7), soit électrique (<em>n<sub>C</sub></em> = 6) (tableau <a href="sect062.html#tab:aovfictive1">6.2</a>). D’emblée, nous notons que les moyennes de vitesse des trois groupes sont différentes : 17,6 km/h pour les cyclistes avec leur vélo personnel, 12,3 km/h celles et ceux avec des vélos en libre-service et 23,1 km/h pour les cyclistes avec un vélo électrique. Pour chaque observation, la troisième colonne du tableau représente les écarts à la moyenne globale mis au carré, tandis que les colonnes suivantes représentent la déviation au carré de chaque observation à la moyenne de son groupe d’appartenance. Ainsi, pour la première observation, nous avons <span class="math inline">\((\mbox{16,900} - \mbox{17,339})^2 = \mbox{0,193}\)</span> et <span class="math inline">\((\mbox{16,900} - \mbox{17,580})^2~ = \mbox{0,462}\)</span>. Les valeurs des trois variances sont les suivantes :</p>
<ul>
<li>la <strong>variance totale</strong> (<em>VT</em>) est donc égale à la somme de la troisième colonne (<span class="math inline">\(\mbox{424,663}\)</span>).</li>
<li>la <strong>variance intergroupe</strong> (expliquée, <em>VE</em>), elle est égale à <span class="math inline">\(\mbox{5}\times(\mbox{17,580-17,339})^2+\mbox{7}\times(\mbox{12,257-17,339})^2+\mbox{6}\times(\mbox{23,067-17,339})^2 = \mbox{377,904}\)</span>.</li>
<li>la <strong>variance intragroupe</strong> (non expliquée, <em>VNE</em>) est égale à <span class="math inline">\(\mbox{11,228+21,537+13,993=46,758}\)</span>.</li>
</ul>
<p>Nous avons donc <span class="math inline">\(VT = Var_{inter} + Var_{intra}\)</span>, soit <span class="math inline">\(\mbox{424,663 = 377,904 + 46,758}\)</span> et <span class="math inline">\(\eta_2 = \mbox{377,904 / 424,663 = 0,89}\)</span>. Cela signale que 89 % de la variance de la vitesse des cyclistes est expliquée par le type de vélo utilisé.</p>
<table>
<caption>
<span id="tab:aovfictive1">Tableau 6.2: </span>Données fictives et calcul des trois variances (cas 1)
</caption>
<thead>
<tr>
<th style="text-align:left;">
Type de vélo
</th>
<th style="text-align:center;">
km/h
</th>
<th style="text-align:right;">
<span class="math inline">\((y_{i}-\overline{y})^2\)</span>
</th>
<th style="text-align:right;">
<span class="math inline">\((y_{i}-\overline{y_{A}})^2\)</span>
</th>
<th style="text-align:right;">
<span class="math inline">\((y_{i}-\overline{y_{B}})^2\)</span>
</th>
<th style="text-align:right;">
<span class="math inline">\((y_{i}-\overline{y_{C}})^2\)</span>
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
A. personnel
</td>
<td style="text-align:center;">
16,900
</td>
<td style="text-align:right;">
0,193
</td>
<td style="text-align:right;">
0,462
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:left;">
A. personnel
</td>
<td style="text-align:center;">
20,400
</td>
<td style="text-align:right;">
9,370
</td>
<td style="text-align:right;">
7,952
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:left;">
A. personnel
</td>
<td style="text-align:center;">
16,100
</td>
<td style="text-align:right;">
1,535
</td>
<td style="text-align:right;">
2,190
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:left;">
A. personnel
</td>
<td style="text-align:center;">
17,700
</td>
<td style="text-align:right;">
0,130
</td>
<td style="text-align:right;">
0,014
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:left;">
A. personnel
</td>
<td style="text-align:center;">
16,800
</td>
<td style="text-align:right;">
0,290
</td>
<td style="text-align:right;">
0,608
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:left;">
B. libre-service
</td>
<td style="text-align:center;">
13,400
</td>
<td style="text-align:right;">
15,515
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
1,306
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:left;">
B. libre-service
</td>
<td style="text-align:center;">
11,300
</td>
<td style="text-align:right;">
36,468
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
0,916
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:left;">
B. libre-service
</td>
<td style="text-align:center;">
14,000
</td>
<td style="text-align:right;">
11,148
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
3,038
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:left;">
B. libre-service
</td>
<td style="text-align:center;">
12,400
</td>
<td style="text-align:right;">
24,393
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
0,020
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:left;">
B. libre-service
</td>
<td style="text-align:center;">
13,700
</td>
<td style="text-align:right;">
13,242
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
2,082
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:left;">
B. libre-service
</td>
<td style="text-align:center;">
8,500
</td>
<td style="text-align:right;">
78,126
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
14,116
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:left;">
B. libre-service
</td>
<td style="text-align:center;">
12,500
</td>
<td style="text-align:right;">
23,415
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
0,059
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:left;">
C. électrique
</td>
<td style="text-align:center;">
22,900
</td>
<td style="text-align:right;">
30,926
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
0,028
</td>
</tr>
<tr>
<td style="text-align:left;">
C. électrique
</td>
<td style="text-align:center;">
26,000
</td>
<td style="text-align:right;">
75,015
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
8,604
</td>
</tr>
<tr>
<td style="text-align:left;">
C. électrique
</td>
<td style="text-align:center;">
23,600
</td>
<td style="text-align:right;">
39,202
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
0,284
</td>
</tr>
<tr>
<td style="text-align:left;">
C. électrique
</td>
<td style="text-align:center;">
21,000
</td>
<td style="text-align:right;">
13,404
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
4,271
</td>
</tr>
<tr>
<td style="text-align:left;">
C. électrique
</td>
<td style="text-align:center;">
22,300
</td>
<td style="text-align:right;">
24,613
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
0,588
</td>
</tr>
<tr>
<td style="text-align:left;">
C. électrique
</td>
<td style="text-align:center;">
22,600
</td>
<td style="text-align:right;">
27,679
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
0,218
</td>
</tr>
<tr>
<td style="text-align:left;">
grande moyenne
</td>
<td style="text-align:center;">
17,339
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:left;">
moyenne groupe A
</td>
<td style="text-align:center;">
17,580
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:left;">
moyenne groupe B
</td>
<td style="text-align:center;">
12,257
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:left;">
moyenne groupe C
</td>
<td style="text-align:center;">
23,067
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:left;">
Variance totale
</td>
<td style="text-align:center;">
</td>
<td style="text-align:right;">
424,663
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:left;">
Variance intragroupe
</td>
<td style="text-align:center;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
11,228
</td>
<td style="text-align:right;">
21,537
</td>
<td style="text-align:right;">
13,993
</td>
</tr>
</tbody>
</table>
<p>Examinons un deuxième jeu de données fictives pour lequel le type de vélo utilisé n’aurait que peu d’effet sur la vitesse des cyclistes (tableau <a href="sect062.html#tab:aovfictive2">6.3</a>). D’emblée, les moyennes des trois groupes semblent très similaires (19,3, 17,9 et 18,7). Les valeurs des trois variances sont les suivantes :</p>
<ul>
<li>la <strong>variance totale</strong> (<em>VT</em>) est égale à <span class="math inline">\(\mbox{121,756}\)</span>.</li>
<li>la <strong>variance intergroupe</strong> (expliquée, <em>VE</em>) est égale à <span class="math inline">\(\mbox{5}\times(\mbox{19,300-18,528})^2+\mbox{7}\times(\mbox{17,871-18,528})^2+\mbox{6}\times(\mbox{18,650-18,528})^2 = \mbox{6,087}\)</span>.</li>
<li>la <strong>variance intragroupe</strong> (non expliquée, <em>VNE</em>) est égale à <span class="math inline">\(\mbox{9,140+50,254+56,275 = 115,669}\)</span>.</li>
</ul>
<p>Nous avons donc <span class="math inline">\(VT = Var_{inter} + Var_{intra}\)</span>, soit <span class="math inline">\(\mbox{121,756 = 6,087 + 115,669}\)</span> et <span class="math inline">\(\eta_2 = \mbox{6,087 / 121,756 = 0,05}\)</span>. Cela signale que 5 % de la variance de la vitesse des cyclistes est uniquement expliquée par le type de vélo utilisé.</p>
<table>
<caption>
<span id="tab:aovfictive2">Tableau 6.3: </span>Données fictives et calcul des trois variances (cas 2)
</caption>
<thead>
<tr>
<th style="text-align:left;">
Type de vélo
</th>
<th style="text-align:center;">
km/h
</th>
<th style="text-align:right;">
<span class="math inline">\((y_{i}-\overline{y})^2\)</span>
</th>
<th style="text-align:right;">
<span class="math inline">\((y_{i}-\overline{y_{A}})^2\)</span>
</th>
<th style="text-align:right;">
<span class="math inline">\((y_{i}-\overline{y_{B}})^2\)</span>
</th>
<th style="text-align:right;">
<span class="math inline">\((y_{i}-\overline{y_{C}})^2\)</span>
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
A. personnel
</td>
<td style="text-align:center;">
17,500
</td>
<td style="text-align:right;">
1,056
</td>
<td style="text-align:right;">
3,24
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:left;">
A. personnel
</td>
<td style="text-align:center;">
19,000
</td>
<td style="text-align:right;">
0,223
</td>
<td style="text-align:right;">
0,09
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:left;">
A. personnel
</td>
<td style="text-align:center;">
19,700
</td>
<td style="text-align:right;">
1,374
</td>
<td style="text-align:right;">
0,16
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:left;">
A. personnel
</td>
<td style="text-align:center;">
18,700
</td>
<td style="text-align:right;">
0,030
</td>
<td style="text-align:right;">
0,36
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:left;">
A. personnel
</td>
<td style="text-align:center;">
21,600
</td>
<td style="text-align:right;">
9,439
</td>
<td style="text-align:right;">
5,29
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:left;">
B. libre-service
</td>
<td style="text-align:center;">
13,700
</td>
<td style="text-align:right;">
23,307
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
17,401
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:left;">
B. libre-service
</td>
<td style="text-align:center;">
20,800
</td>
<td style="text-align:right;">
5,163
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
8,577
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:left;">
B. libre-service
</td>
<td style="text-align:center;">
15,100
</td>
<td style="text-align:right;">
11,750
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
7,681
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:left;">
B. libre-service
</td>
<td style="text-align:center;">
18,800
</td>
<td style="text-align:right;">
0,074
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
0,862
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:left;">
B. libre-service
</td>
<td style="text-align:center;">
21,500
</td>
<td style="text-align:right;">
8,834
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
13,167
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:left;">
B. libre-service
</td>
<td style="text-align:center;">
16,500
</td>
<td style="text-align:right;">
4,112
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
1,881
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:left;">
B. libre-service
</td>
<td style="text-align:center;">
18,700
</td>
<td style="text-align:right;">
0,030
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
0,687
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:left;">
C. électrique
</td>
<td style="text-align:center;">
16,600
</td>
<td style="text-align:right;">
3,716
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
4,203
</td>
</tr>
<tr>
<td style="text-align:left;">
C. électrique
</td>
<td style="text-align:center;">
16,300
</td>
<td style="text-align:right;">
4,963
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
5,523
</td>
</tr>
<tr>
<td style="text-align:left;">
C. électrique
</td>
<td style="text-align:center;">
15,600
</td>
<td style="text-align:right;">
8,572
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
9,303
</td>
</tr>
<tr>
<td style="text-align:left;">
C. électrique
</td>
<td style="text-align:center;">
20,000
</td>
<td style="text-align:right;">
2,167
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
1,822
</td>
</tr>
<tr>
<td style="text-align:left;">
C. électrique
</td>
<td style="text-align:center;">
24,600
</td>
<td style="text-align:right;">
36,872
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
35,402
</td>
</tr>
<tr>
<td style="text-align:left;">
C. électrique
</td>
<td style="text-align:center;">
18,800
</td>
<td style="text-align:right;">
0,074
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
0,022
</td>
</tr>
<tr>
<td style="text-align:left;">
grande moyenne
</td>
<td style="text-align:center;">
18,528
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:left;">
moyenne groupe A
</td>
<td style="text-align:center;">
19,300
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:left;">
moyenne groupe B
</td>
<td style="text-align:center;">
17,871
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:left;">
moyenne groupe C
</td>
<td style="text-align:center;">
18,650
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:left;">
Variance totale
</td>
<td style="text-align:center;">
</td>
<td style="text-align:right;">
121,756
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:left;">
Variance intragroupe
</td>
<td style="text-align:center;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
9,14
</td>
<td style="text-align:right;">
50,254
</td>
<td style="text-align:right;">
56,275
</td>
</tr>
</tbody>
</table>
</div>
<div id="sect06212" class="section level4 hasAnchor" number="6.2.1.2">
<h4><span class="header-section-number">6.2.1.2</span> Test de Fisher<a href="sect062.html#sect06212" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Pour vérifier si les moyennes sont statistiquement différentes (autrement dit, si leur différence est significativement différente de 0), nous avons recours au test <em>F</em> de Fisher. Pour ce faire, nous posons l’hypothèse nulle (<em>H<sub>0</sub></em>), soit que les moyennes des groupes sont égales; autrement dit que la variable qualitative n’a pas d’effet sur la variable continue (indépendance entre les deux variables). L’hypothèse alternative (<em>H<sub>1</sub></em>) est donc que les moyennes sont différentes. Pour nos deux jeux de données fictives ci-dessus comprenant trois groupes, <em>H<sub>0</sub></em> signifie que <span class="math inline">\(\overline{y_{A}}=\overline{y_{B}}=\overline{y_{C}}\)</span>. La statistique <em>F</em> se calcule comme suit :</p>
<p><span class="math display" id="eq:anovaF">\[\begin{equation}
F = \frac{\frac{Var{inter}}{k-1}}{\frac{Var{intra}}{n-k}}\mbox{ ou } F = \frac{\frac{VE}{k-1}}{\frac{VNE}{n-k}}
\tag{6.13}
\end{equation}\]</span>
</p>
<p>où <span class="math inline">\(n\)</span> et <span class="math inline">\(k\)</span> sont respectivement les nombres d’observations et de modalités de la variable qualitative. L’hypothèse nulle (les moyennes sont égales) est rejetée si la valeur du <em>F</em> calculé est supérieure à la valeur critique de la table <em>F</em> avec les degrés de liberté <em>(k-1, n-k)</em> et un seuil
<span class="math inline">\(\alpha\)</span> (<em>p</em>=0,05 habituellement) (voir la table des valeurs critiques de <em>F</em>, section <a href="annexe2.html#annexe2">15</a>). Notez que nous utilisons rarement la table <em>F</em> puisqu’avec la fonction <code>aov</code>, nous obtenons directement la valeur <em>F</em> et celle de <em>p</em> qui lui est associée. Concrètement, si le test <em>F</em> est significatif (avec <em>p</em> &lt; 0,05), plus la valeur de <em>F</em> est élevée, plus la différence entre les moyennes est élevée.</p>
<p>Appliquons rapidement la démarche du test <em>F</em> à nos deux jeux de données fictives qui comprennent 3 modalités pour la variable qualitative et 18 observations. Avec <span class="math inline">\(\alpha\)</span> = 0,05, 2 degrés de liberté (3-1) au numérateur et 15 au dénominateur (18-3), la valeur critique de F est de 3,68. Nous en concluons alors que :</p>
<ul>
<li>pour le cas A, le <em>F</em> calculé est égal à <span class="math inline">\(\mbox{(377,904 / 2) / (46,758 / 15) = 60,62}\)</span>. Il est supérieur à la valeur <em>F</em> critique; les moyennes sont donc statistiquement différentes au seuil 0,05. Autrement dit, nous aurions eu moins de 5 % de chance d’obtenir un échantillon produisant ces résultats si en réalité la différence entre les moyennes était de 0.</li>
<li>pour le cas B, le <em>F</em> calculé est égal à <span class="math inline">\(\mbox{(6,087 / 2) / (115,669 / 15) = 0,39}\)</span>. Il est inférieur à la valeur <em>F</em> critique; les moyennes ne sont donc pas statistiquement différentes au seuil de 0,05.</li>
</ul>
</div>
<div id="sect06213" class="section level4 hasAnchor" number="6.2.1.3">
<h4><span class="header-section-number">6.2.1.3</span> Conditions d’application de l’ANOVA et solutions de rechange<a href="sect062.html#sect06213" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Trois conditions d’application doivent être vérifiées avant d’effectuer une analyse de variance sur un jeu de données :</p>
<ul>
<li><p><strong>Normalité des groupes.</strong> Le test de Fisher repose sur le postulat que les échantillons (groupes) sont normalement distribués. Pour le vérifier, nous avons recours au test de normalité de Shapiro–Wilk (section <a href="sect025.html#sect025413">2.5.4.1.3</a>). Rappelez-vous toutefois que ce test est très restrictif, surtout pour de grands échantillons.</p></li>
<li><p><strong>Homoscédasticité</strong>. La variance dans les échantillons doit être la même (homogénéité des variances). Pour vérifier cette condition, nous utilisons les tests de Levene, de Bartlett ou de Breusch-Pagan.</p></li>
<li><p><strong>Indépendance des observations (pseudo-réplication).</strong> Chaque individu doit appartenir à un et un seul groupe. En d’autres termes, les observations ne sont pas indépendantes si plusieurs mesures (variable continue) sont faites sur un même individu. Si c’est le cas, nous utiliserons alors une analyse de variance sur des mesures répétées (voir le bloc à la fin du chapitre).</p></li>
</ul>
<p><strong>Quelles sont les conséquences si les conditions d’application ne sont pas respectées?</strong> La non-vérification des conditions d’application cause deux problèmes distincts : elle affecte la puissance du test (sa capacité à détecter un effet, si celui-ci existe réellement) et le taux d’erreur de type 1 (la probabilité de trouver un résultat significatif alors qu’aucune relation n’existe réellement, soit un faux-positif) <span class="citation">(<a href="#ref-glass1972consequences" role="doc-biblioref">Glass, Peckham et Sanders 1972</a>; <a href="#ref-lix1996consequences" role="doc-biblioref">Lix, Keselman et Keselman 1996</a>)</span>.</p>
<ul>
<li>Si la distribution est asymétrique plutôt que centrée (comme pour une distribution normale), la puissance et le taux d’erreur de type 1 sont tous les deux peu affectés, car le test est non orienté (la différence de moyennes peut être négative ou positive).</li>
<li>Si la distribution est leptocurtique (pointue, avec des extrémités de la distribution plus importantes), le taux d’erreur de type 1 est peu affecté; en revanche, la puissance du test est réduite. L’inverse s’observe si la distribution est platicurtique (aplatie, c’est-à-dire avec des extrémités de la distribution plus réduites.</li>
<li>Si les groupes ont des variances différentes, le taux d’erreur de type 1 augmente légèrement.</li>
<li>Si les observations ne sont pas indépendantes, à la fois le taux d’erreur de type 1 et la puissance du test sont fortement affectés.</li>
<li>Si les échantillons sont petits, les effets présentés ci-dessus sont démultipliés.</li>
<li>Si plusieurs conditions ne sont pas respectées, les conséquences présentées ci-dessus s’additionnent, voire se combinent.</li>
</ul>
<p><strong>Que faire quand les conditions d’application relatives à la normalité ou à l’homoscédasticité ne sont vraiment pas respectées?</strong> Signalons d’emblée que le non-respect de ces conditions ne change rien à la décomposition de la variance (<em>VT = V<sub>intra</sub>+V<sub>inter</sub></em>). Cela signifie que vous pouvez toujours calculer <em>Eta<sup>2</sup></em>. Par contre, le test de Fisher ne peut pas être utilisé, car il est biaisé comme décrit précédemment. Quatre solutions sont envisageables :</p>
<ul>
<li><p>Lorsque les échantillons sont fortement anormalement distribués, certains auteurs vont simplement transformer leur variable en appliquant une fonction logarithme (le plus souvent) ou racine carrée, inverse ou exponentielle, et reporter le test de Fisher calculé sur cette transformation. Attention toutefois! Transformer une variable ne va pas systématiquement la rapprocher d’une distribution normale et complique l’interprétation finale des résultats. Par conséquent, avant de recalculer votre test <em>F</em>, il convient de réaliser un test de normalité de Shapiro–Wilk et un test d’homoscédasticité (Levene, Bartlett ou Breusch-Pagan) sur la variable continue transformée.</p></li>
<li><p>Détecter les observations qui contribuent le plus à l’anormalité et à l’hétéroscédasticité (valeurs aberrantes ou extrêmes). Supprimez-les et refaites votre ANOVA en vous assurant que les conditions sont désormais respectées. Notez que supprimer des observations peut être une pratique éthiquement questionnable en statistique. Si vos échantillons sont bien constitués et que la mesure collectée n’est pas erronée, pourquoi donc la supprimer? Si vous optez pour cette solution, prenez soin de comparer les résultats avant et après la suppression des observations. Si les conditions sont respectées après la suppression et que les résultats de l’ANOVA (<em>Eta<sup>2</sup></em> et test <em>F</em> de Fisher) sont très semblables, conservez donc les résultats de l’ANOVA initiale et signalez que vous avez procédé aux deux tests.</p></li>
<li><p>Lorsque les variances des groupes sont dissemblables, vous pouvez utiliser le test de Welch pour l’ANOVA au lieu du test <em>F</em> de Fisher.</p></li>
<li><p>Dernière solution, lorsque les deux conditions ne sont vraiment pas respectées, utilisez le test non paramétrique de Kruskal-Wallis. Par analogie au <em>t</em> de Student, il correspond au test des rangs signés de Wilcoxon. Ce test est décrit dans la section suivante.</p></li>
</ul>
<p>Vous l’aurez compris, dans de nombreux cas en statistique, les choix méthodologiques dépendent en partie de la subjectivité des chercheur(e)s. Il faut s’adapter au jeu de données et à la culture statistique en vigueur dans votre champ d’études. N’hésitez pas à réaliser plusieurs tests différents pour évaluer la robustesse de vos conclusions et fiez-vous en premier lieu à ceux pour lesquels votre jeu de données est le plus adapté.</p>
</div>
</div>
<div id="sect0622" class="section level3 hasAnchor" number="6.2.2">
<h3><span class="header-section-number">6.2.2</span> Test non paramétrique de Kruskal-Wallis<a href="sect062.html#sect0622" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Le test non paramétrique de Kruskal-Wallis est une solution de rechange à l’ANOVA classique lorsque le jeu de données présente de graves problèmes de normalité et d’hétéroscédasticité. Cette méthode représente une ANOVA appliquée à une variable continue transformée préalablement en rangs. Du fait de la transformation en rangs, nous ne vérifions plus si les moyennes sont différentes, mais bel et bien si les médianes de la variable continue sont différentes. Pour ce faire, nous utiliserons la fonction <code>kruskal.test</code>.</p>
</div>
<div id="sect0623" class="section level3 hasAnchor" number="6.2.3">
<h3><span class="header-section-number">6.2.3</span> Mise en œuvre dans R<a href="sect062.html#sect0623" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Dans une étude récente, Apparicio <em>et al.</em> <span class="citation">(<a href="#ref-2018_1" role="doc-biblioref">2018</a>)</span> ont comparé les expositions au bruit et à la pollution atmosphérique aux heures de pointe à Montréal en fonction du mode de transport utilisé. Pour ce faire, trois équipes de trois personnes ont été constituées : une personne à vélo, une autre en automobile et une dernière se déplaçant en transport en commun, équipées de capteurs de pollution, de sonomètres, de vêtements biométriques et d’une montre GPS. Chaque matin, à huit heures précises, les membres de chaque équipe ont réalisé un trajet d’un quartier périphérique de Montréal vers un pôle d’enseignement (université) ou d’emploi localisé au centre-ville. Le trajet inverse était réalisé le soir à 17 h. Au total, une centaine de trajets ont ainsi été réalisés. Des analyses de variance ont ainsi permis de comparer les trois modes (automobile, vélo et transport en commun) en fonction des temps de déplacement, des niveaux d’exposition au bruit, des niveaux d’exposition au dioxyde d’azote et de la dose totale inhalée de dioxyde d’azote. Nous vous proposons ici d’analyser une partie de ces données.</p>
<div id="sect06231" class="section level4 hasAnchor" number="6.2.3.1">
<h4><span class="header-section-number">6.2.3.1</span> Première ANOVA : différences entre les temps de déplacement<a href="sect062.html#sect06231" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Comme première analyse de variance, nous vérifions si les moyennes des temps de déplacement sont différentes entre les trois modes de transport.</p>
<p>Dans un premier temps, nous calculons les moyennes des différents groupes. Nous pouvons alors constater que les moyennes sont très semblables : 37,7 minutes pour l’automobile versus 38,4 et 41,6 pour le vélo et le transport en commun. Aussi, les variances des trois groupes sont relativement similaires.</p>
<div class="sourceCode" id="cb597"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb597-1"><a href="sect062.html#cb597-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;rstatix&quot;</span>)</span>
<span id="cb597-2"><a href="sect062.html#cb597-2" aria-hidden="true" tabindex="-1"></a><span class="co"># chargement des DataFrames</span></span>
<span id="cb597-3"><a href="sect062.html#cb597-3" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">&quot;data/bivariee/dataPollution.RData&quot;</span>)</span>
<span id="cb597-4"><a href="sect062.html#cb597-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Statistiques descriptives pour les groupes (moyenne et écart-type)</span></span>
<span id="cb597-5"><a href="sect062.html#cb597-5" aria-hidden="true" tabindex="-1"></a>df_TrajetsDuree <span class="sc">%&gt;%</span>                                 <span class="co"># Nom du DataFrame</span></span>
<span id="cb597-6"><a href="sect062.html#cb597-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(Mode) <span class="sc">%&gt;%</span>                                <span class="co"># Variable qualitative</span></span>
<span id="cb597-7"><a href="sect062.html#cb597-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">get_summary_stats</span>(DureeMinute, <span class="at">type =</span> <span class="st">&quot;mean_sd&quot;</span>)  <span class="co"># Variable continue </span></span></code></pre></div>
<pre><code>## # A tibble: 3 × 5
##   Mode    variable        n  mean    sd
##   &lt;chr&gt;   &lt;chr&gt;       &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 1. Auto DureeMinute    33  37.7  12.8
## 2 2. Velo DureeMinute    33  38.4  15.2
## 3 3. TC   DureeMinute    33  41.6  11.4</code></pre>
<p>Pour visualiser la distribution des données pour les trois groupes, vous pouvez créer des graphiques de densité et en violon (figure <a href="sect062.html#fig:figAnova1a">6.4</a>). La juxtaposition des trois distributions montre que les distributions des valeurs pour les trois groupes sont globalement similaires. Cela est corroboré par le fait que les boîtes du graphique en violon sont situées à la même hauteur. Autrement dit, à la lecture des deux graphiques, il ne semble pas y avoir de différences significatives entre les trois groupes en termes de temps de déplacement.</p>
<div class="sourceCode" id="cb599"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb599-1"><a href="sect062.html#cb599-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;ggplot2&quot;</span>)</span>
<span id="cb599-2"><a href="sect062.html#cb599-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;ggpubr&quot;</span>)</span>
<span id="cb599-3"><a href="sect062.html#cb599-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Graphique de densité</span></span>
<span id="cb599-4"><a href="sect062.html#cb599-4" aria-hidden="true" tabindex="-1"></a>GraphDens <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> df_TrajetsDuree, </span>
<span id="cb599-5"><a href="sect062.html#cb599-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">mapping=</span><span class="fu">aes</span>(<span class="at">x=</span>DureeMinute,<span class="at">colour=</span>Mode,<span class="at">fill=</span>Mode)) <span class="sc">+</span></span>
<span id="cb599-6"><a href="sect062.html#cb599-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">alpha=</span><span class="fl">0.55</span>,<span class="at">mapping=</span><span class="fu">aes</span>(<span class="at">y=</span>..scaled..))<span class="sc">+</span></span>
<span id="cb599-7"><a href="sect062.html#cb599-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title=</span><span class="st">&quot;a. Graphique de densité&quot;</span>,</span>
<span id="cb599-8"><a href="sect062.html#cb599-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">x =</span> <span class="st">&quot;Densité&quot;</span>,</span>
<span id="cb599-9"><a href="sect062.html#cb599-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">y =</span> <span class="st">&quot;Durée du trajet (en minutes)&quot;</span>)</span>
<span id="cb599-10"><a href="sect062.html#cb599-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Graphique en violon</span></span>
<span id="cb599-11"><a href="sect062.html#cb599-11" aria-hidden="true" tabindex="-1"></a>GraphViolon <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(df_TrajetsDuree, <span class="fu">aes</span>(<span class="at">x=</span>Mode, <span class="at">y=</span>DureeMinute)) <span class="sc">+</span></span>
<span id="cb599-12"><a href="sect062.html#cb599-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_violin</span>(<span class="at">fill=</span><span class="st">&quot;white&quot;</span>) <span class="sc">+</span></span>
<span id="cb599-13"><a href="sect062.html#cb599-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">width=</span><span class="fl">0.1</span>, <span class="fu">aes</span>(<span class="at">x=</span>Mode, <span class="at">y=</span>DureeMinute,<span class="at">fill=</span>Mode))<span class="sc">+</span></span>
<span id="cb599-14"><a href="sect062.html#cb599-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">&quot;b. Graphique en violon&quot;</span>,</span>
<span id="cb599-15"><a href="sect062.html#cb599-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Mode de transport&quot;</span>,</span>
<span id="cb599-16"><a href="sect062.html#cb599-16" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Durée du trajet (en minutes)&quot;</span>)<span class="sc">+</span></span>
<span id="cb599-17"><a href="sect062.html#cb599-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;none&quot;</span>)</span>
<span id="cb599-18"><a href="sect062.html#cb599-18" aria-hidden="true" tabindex="-1"></a><span class="fu">ggarrange</span>(GraphDens, GraphViolon)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:figAnova1a"></span>
<img src="MethodesQuantitScSocialesBolR_files/figure-html/figAnova1a-1.png" alt="Graphiques de densité et en violon" width="75%" />
<p class="caption">
Figure 6.4: Graphiques de densité et en violon
</p>
</div>
<p>Nous pouvons vérifier si les échantillons sont normalement distribués avec la fonction <code>shapiro_test</code> du package <code>rstatix</code>. À titre de rappel, l’hypothèse nulle (<em>H<sub>0</sub></em>) de ce test est que la distribution est normale. Par conséquent, quand la valeur de <em>p</em> associée à la statistique de Shapiro est supérieure à 0,05, alors nous ne pouvons rejeter l’hypothèse d’une distribution normale (autrement dit, la distribution est anormale). À la lecture des résultats ci-dessous, seul le groupe utilisant le transport en commun présente une distribution proche de la normalité (<em>p</em> = 0,0504). Ce test étant très restrictif, il est fortement conseillé de visualiser le diagramme quantile-quantile pour chaque groupe (graphique QQ plot) (figure <a href="sect062.html#fig:figQqplot">6.5</a>). Ces graphiques sont utilisés pour déterminer visuellement si une distribution empirique (observée sur des données), s’approche d’une distribution théorique (ici la loi normale). Si effectivement les deux distributions sont proches, les points du diagramme devraient tous tomber sur une ligne droite parfaite. Un intervalle de confiance (représenté ici en gris) peut être construit pour obtenir une interprétation plus nuancée. Dans notre cas, seules deux observations pour le vélo et deux autres pour l’automobile s’éloignent vraiment de la ligne droite. Nous pouvons considérer que ces trois distributions s’approchent d’une distribution normale.</p>
<div class="sourceCode" id="cb600"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb600-1"><a href="sect062.html#cb600-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;dplyr&quot;</span>)</span>
<span id="cb600-2"><a href="sect062.html#cb600-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;ggpubr&quot;</span>)</span>
<span id="cb600-3"><a href="sect062.html#cb600-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;rstatix&quot;</span>)</span>
<span id="cb600-4"><a href="sect062.html#cb600-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Condition 1 : normalité des échantillons</span></span>
<span id="cb600-5"><a href="sect062.html#cb600-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Test pour la normalité des échantillons (groupes) : test de Shapiro</span></span>
<span id="cb600-6"><a href="sect062.html#cb600-6" aria-hidden="true" tabindex="-1"></a> df_TrajetsDuree <span class="sc">%&gt;%</span>          <span class="co"># Nom du DataFrame</span></span>
<span id="cb600-7"><a href="sect062.html#cb600-7" aria-hidden="true" tabindex="-1"></a>   <span class="fu">group_by</span>(Mode) <span class="sc">%&gt;%</span>         <span class="co"># Variable qualitative</span></span>
<span id="cb600-8"><a href="sect062.html#cb600-8" aria-hidden="true" tabindex="-1"></a>   <span class="fu">shapiro_test</span>(DureeMinute)  <span class="co"># Variable continue </span></span></code></pre></div>
<pre><code>## # A tibble: 3 × 4
##   Mode    variable    statistic         p
##   &lt;chr&gt;   &lt;chr&gt;           &lt;dbl&gt;     &lt;dbl&gt;
## 1 1. Auto DureeMinute     0.905 0.00729  
## 2 2. Velo DureeMinute     0.797 0.0000288
## 3 3. TC   DureeMinute     0.936 0.0504</code></pre>
<div class="sourceCode" id="cb602"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb602-1"><a href="sect062.html#cb602-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Graphiques qqplot pour les groupes</span></span>
<span id="cb602-2"><a href="sect062.html#cb602-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggqqplot</span>(df_TrajetsDuree, <span class="st">&quot;DureeMinute&quot;</span>, <span class="at">facet.by =</span> <span class="st">&quot;Mode&quot;</span>, </span>
<span id="cb602-3"><a href="sect062.html#cb602-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">xlab=</span><span class="st">&quot;Théorique&quot;</span>, <span class="at">ylab=</span><span class="st">&quot;Échantillon&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:figQqplot"></span>
<img src="MethodesQuantitScSocialesBolR_files/figure-html/figQqplot-1.png" alt="QQ Plot pour les groupes" width="75%" />
<p class="caption">
Figure 6.5: QQ Plot pour les groupes
</p>
</div>
<p>Pour vérifier l’hypothèse d’homogénéité des variances, vous pouvez utiliser les tests de Levene, de Bartlett ou de Breusch-Pagan. Les valeurs de <em>p</em>, toutes supérieures à 0,05, signalent que la condition d’homogénéité des variances est respectée.</p>
<div class="sourceCode" id="cb603"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb603-1"><a href="sect062.html#cb603-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;rstatix&quot;</span>)</span>
<span id="cb603-2"><a href="sect062.html#cb603-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;lmtest&quot;</span>)</span>
<span id="cb603-3"><a href="sect062.html#cb603-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;car&quot;</span>)</span>
<span id="cb603-4"><a href="sect062.html#cb603-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Condition 2 : homogénéité des variances (homocédasticité)</span></span>
<span id="cb603-5"><a href="sect062.html#cb603-5" aria-hidden="true" tabindex="-1"></a><span class="fu">leveneTest</span>(DureeMinute <span class="sc">~</span> Mode, <span class="at">data =</span> df_TrajetsDuree)</span></code></pre></div>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = median)
##       Df F value Pr(&gt;F)
## group  2  0.2418 0.7857
##       96</code></pre>
<div class="sourceCode" id="cb605"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb605-1"><a href="sect062.html#cb605-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bartlett.test</span>(DureeMinute <span class="sc">~</span> Mode, <span class="at">data =</span> df_TrajetsDuree)</span></code></pre></div>
<pre><code>## 
##  Bartlett test of homogeneity of variances
## 
## data:  DureeMinute by Mode
## Bartlett&#39;s K-squared = 2.6718, df = 2, p-value = 0.2629</code></pre>
<div class="sourceCode" id="cb607"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb607-1"><a href="sect062.html#cb607-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bptest</span>(DureeMinute <span class="sc">~</span> Mode, <span class="at">data =</span> df_TrajetsDuree)</span></code></pre></div>
<pre><code>## 
##  studentized Breusch-Pagan test
## 
## data:  DureeMinute ~ Mode
## BP = 1.3322, df = 2, p-value = 0.5137</code></pre>
<p>Deux fonctions peuvent être utilisées pour calculer l’analyse de variance : la fonction de base <code>aov(variable continue ~ variable qualitative, data = votre DataFrame)</code> ou bien la fonction <code>anova_test(variable continue ~ variable qualitative, data = votre DataFrame)</code> du package <code>rstatix</code>. Comparativement à <code>aov</code>, l’avantage de la fonction <code>anova_test</code> est qu’elle calcule aussi le <em>Eta<sup>2</sup></em>.</p>
<div class="sourceCode" id="cb609"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb609-1"><a href="sect062.html#cb609-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;rstatix&quot;</span>)</span>
<span id="cb609-2"><a href="sect062.html#cb609-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;car&quot;</span>)</span>
<span id="cb609-3"><a href="sect062.html#cb609-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;effectsize&quot;</span>)</span>
<span id="cb609-4"><a href="sect062.html#cb609-4" aria-hidden="true" tabindex="-1"></a><span class="co"># ANOVA avec la fonction aov</span></span>
<span id="cb609-5"><a href="sect062.html#cb609-5" aria-hidden="true" tabindex="-1"></a>aov1 <span class="ot">&lt;-</span> <span class="fu">aov</span>(DureeMinute <span class="sc">~</span> Mode, <span class="at">data =</span> df_TrajetsDuree)</span>
<span id="cb609-6"><a href="sect062.html#cb609-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(aov1)</span></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value Pr(&gt;F)
## Mode         2    287   143.2    0.82  0.444
## Residuals   96  16781   174.8</code></pre>
<div class="sourceCode" id="cb611"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb611-1"><a href="sect062.html#cb611-1" aria-hidden="true" tabindex="-1"></a><span class="co"># calcul de Eta2 avec la fonction eta_squared du package effectsize</span></span>
<span id="cb611-2"><a href="sect062.html#cb611-2" aria-hidden="true" tabindex="-1"></a>effectsize<span class="sc">::</span><span class="fu">eta_squared</span>(aov1)</span></code></pre></div>
<pre><code>## # Effect Size for ANOVA
## 
## Parameter | Eta2 |       95% CI
## -------------------------------
## Mode      | 0.02 | [0.00, 1.00]
## 
## - One-sided CIs: upper bound fixed at [1.00].</code></pre>
<div class="sourceCode" id="cb613"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb613-1"><a href="sect062.html#cb613-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ANOVA avec la fonction anova_test du package rstatix</span></span>
<span id="cb613-2"><a href="sect062.html#cb613-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova_test</span>(DureeMinute <span class="sc">~</span> Mode, <span class="at">data =</span> df_TrajetsDuree)</span></code></pre></div>
<pre><code>## ANOVA Table (type II tests)
## 
##   Effect DFn DFd    F     p p&lt;.05   ges
## 1   Mode   2  96 0.82 0.444       0.017</code></pre>
<p>La valeur de <em>p</em> associée à la statistique <em>F</em> (0,444) nous permet de conclure qu’il n’y a pas de différences significatives entre les moyennes des temps de déplacement des trois modes de transport.</p>
</div>
<div id="sect06232" class="section level4 hasAnchor" number="6.2.3.2">
<h4><span class="header-section-number">6.2.3.2</span> Deuxième ANOVA : différences entre les niveaux d’exposition au bruit<a href="sect062.html#sect06232" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Dans ce second exercice, nous analysons les différences d’exposition au bruit. D’emblée, les statistiques descriptives révèlent que les moyennes sont dissemblables : 66,8 dB(A) pour l’automobile versus 68,8 et 74 pour le vélo et le transport en commun. Aussi, la variance du transport en commun est très différente des autres.</p>
<div class="sourceCode" id="cb615"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb615-1"><a href="sect062.html#cb615-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;rstatix&quot;</span>)</span>
<span id="cb615-2"><a href="sect062.html#cb615-2" aria-hidden="true" tabindex="-1"></a><span class="co"># chargement des DataFrames</span></span>
<span id="cb615-3"><a href="sect062.html#cb615-3" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">&quot;data/bivariee/dataPollution.RData&quot;</span>)</span>
<span id="cb615-4"><a href="sect062.html#cb615-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Statistiques descriptives pour les groupes (moyenne et écart-type)</span></span>
<span id="cb615-5"><a href="sect062.html#cb615-5" aria-hidden="true" tabindex="-1"></a> df_Bruit <span class="sc">%&gt;%</span>                                 <span class="co"># Nom du DataFrame</span></span>
<span id="cb615-6"><a href="sect062.html#cb615-6" aria-hidden="true" tabindex="-1"></a>   <span class="fu">group_by</span>(Mode) <span class="sc">%&gt;%</span>                                <span class="co"># Variable qualitative</span></span>
<span id="cb615-7"><a href="sect062.html#cb615-7" aria-hidden="true" tabindex="-1"></a>   <span class="fu">get_summary_stats</span>(laeq, <span class="at">type =</span> <span class="st">&quot;mean_sd&quot;</span>)  <span class="co"># Variable continue </span></span></code></pre></div>
<pre><code>## # A tibble: 3 × 5
##   Mode    variable     n  mean    sd
##   &lt;chr&gt;   &lt;chr&gt;    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 1. Auto laeq      1094  66.8  4.56
## 2 2. Velo laeq      1124  68.8  4.29
## 3 3. TC   laeq      1207  74.0  6.79</code></pre>
<p>À la lecture des graphiques de densité et en violon (figure <a href="sect062.html#fig:figAnova1b">6.6</a>), il semble clair que les niveaux d’exposition au bruit sont plus faibles pour les automobilistes et plus élevés pour les cyclistes et surtout les personnes en transport en commun. En outre, la distribution des valeurs d’exposition au bruit dans le transport en commun semble bimodale. Cela s’explique par le fait que les niveaux de bruit sont beaucoup plus élevés dans le métro que dans les autobus.</p>
<div class="sourceCode" id="cb617"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb617-1"><a href="sect062.html#cb617-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;ggplot2&quot;</span>)</span>
<span id="cb617-2"><a href="sect062.html#cb617-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;ggpubr&quot;</span>)</span>
<span id="cb617-3"><a href="sect062.html#cb617-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Graphique en densité</span></span>
<span id="cb617-4"><a href="sect062.html#cb617-4" aria-hidden="true" tabindex="-1"></a>GraphDens <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> df_Bruit, </span>
<span id="cb617-5"><a href="sect062.html#cb617-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">mapping=</span><span class="fu">aes</span>(<span class="at">x=</span>laeq,<span class="at">colour=</span>Mode,<span class="at">fill=</span>Mode)) <span class="sc">+</span></span>
<span id="cb617-6"><a href="sect062.html#cb617-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">alpha=</span><span class="fl">0.55</span>,<span class="at">mapping=</span><span class="fu">aes</span>(<span class="at">y=</span>..scaled..))<span class="sc">+</span></span>
<span id="cb617-7"><a href="sect062.html#cb617-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">&quot;a. graphique de densité&quot;</span>,</span>
<span id="cb617-8"><a href="sect062.html#cb617-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">x=</span><span class="st">&quot;Exposition au bruit (dB(A))&quot;</span>)</span>
<span id="cb617-9"><a href="sect062.html#cb617-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Graphique en violon</span></span>
<span id="cb617-10"><a href="sect062.html#cb617-10" aria-hidden="true" tabindex="-1"></a>GraphViolon <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(df_Bruit, <span class="fu">aes</span>(<span class="at">x=</span>Mode, <span class="at">y=</span>laeq)) <span class="sc">+</span></span>
<span id="cb617-11"><a href="sect062.html#cb617-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_violin</span>(<span class="at">fill=</span><span class="st">&quot;white&quot;</span>) <span class="sc">+</span></span>
<span id="cb617-12"><a href="sect062.html#cb617-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">width=</span><span class="fl">0.1</span>, <span class="fu">aes</span>(<span class="at">x=</span>Mode, <span class="at">y=</span>laeq,<span class="at">fill=</span>Mode))<span class="sc">+</span></span>
<span id="cb617-13"><a href="sect062.html#cb617-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">&quot;b. Graphique en violon&quot;</span>,</span>
<span id="cb617-14"><a href="sect062.html#cb617-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Mode de transport&quot;</span>,</span>
<span id="cb617-15"><a href="sect062.html#cb617-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">y=</span><span class="st">&quot;Exposition au bruit (dB(A))&quot;</span>)<span class="sc">+</span></span>
<span id="cb617-16"><a href="sect062.html#cb617-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;none&quot;</span>)</span>
<span id="cb617-17"><a href="sect062.html#cb617-17" aria-hidden="true" tabindex="-1"></a><span class="fu">ggarrange</span>(GraphDens, GraphViolon)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:figAnova1b"></span>
<img src="MethodesQuantitScSocialesBolR_files/figure-html/figAnova1b-1.png" alt="Graphique de densité et en violon" width="75%" />
<p class="caption">
Figure 6.6: Graphique de densité et en violon
</p>
</div>
<p>Le test de Shapiro et les graphiques QQ plot (figure <a href="sect062.html#fig:figQqplot2">6.7</a>) révèlent que les distributions des trois groupes sont anormales. Ce résultat n’est pas surprenant si l’on tient compte de la nature logarithmique de l’échelle décibel.</p>
<div class="sourceCode" id="cb618"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb618-1"><a href="sect062.html#cb618-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;dplyr&quot;</span>)</span>
<span id="cb618-2"><a href="sect062.html#cb618-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;ggpubr&quot;</span>)</span>
<span id="cb618-3"><a href="sect062.html#cb618-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;rstatix&quot;</span>)</span>
<span id="cb618-4"><a href="sect062.html#cb618-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Condition 1 : normalité des échantillons</span></span>
<span id="cb618-5"><a href="sect062.html#cb618-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Test pour la normalité des échantillons (groupes) : test de Shapiro</span></span>
<span id="cb618-6"><a href="sect062.html#cb618-6" aria-hidden="true" tabindex="-1"></a>df_Bruit <span class="sc">%&gt;%</span>          <span class="co"># Nom du DataFrame</span></span>
<span id="cb618-7"><a href="sect062.html#cb618-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Mode) <span class="sc">%&gt;%</span>         <span class="co"># Variable qualitative</span></span>
<span id="cb618-8"><a href="sect062.html#cb618-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">shapiro_test</span>(laeq)  <span class="co"># Variable continue </span></span></code></pre></div>
<pre><code>## # A tibble: 3 × 4
##   Mode    variable statistic        p
##   &lt;chr&gt;   &lt;chr&gt;        &lt;dbl&gt;    &lt;dbl&gt;
## 1 1. Auto laeq         0.971 4.92e-14
## 2 2. Velo laeq         0.992 5.12e- 6
## 3 3. TC   laeq         0.966 3.34e-16</code></pre>
<div class="sourceCode" id="cb620"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb620-1"><a href="sect062.html#cb620-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Graphiques qqplot pour les groupes</span></span>
<span id="cb620-2"><a href="sect062.html#cb620-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggqqplot</span>(df_Bruit, <span class="st">&quot;laeq&quot;</span>, <span class="at">facet.by =</span> <span class="st">&quot;Mode&quot;</span>, <span class="at">xlab=</span><span class="st">&quot;Théorique&quot;</span>, <span class="at">ylab=</span><span class="st">&quot;Échantillon&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:figQqplot2"></span>
<img src="MethodesQuantitScSocialesBolR_files/figure-html/figQqplot2-1.png" alt="QQ Plot pour les groupes" width="75%" />
<p class="caption">
Figure 6.7: QQ Plot pour les groupes
</p>
</div>
<p>En outre, selon les valeurs des tests de Levene, de Bartlett ou de Breusch-Pagan, les variances ne sont pas égales.</p>
<div class="sourceCode" id="cb621"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb621-1"><a href="sect062.html#cb621-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;rstatix&quot;</span>)</span>
<span id="cb621-2"><a href="sect062.html#cb621-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;lmtest&quot;</span>)</span>
<span id="cb621-3"><a href="sect062.html#cb621-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;car&quot;</span>)</span>
<span id="cb621-4"><a href="sect062.html#cb621-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Condition 2 : homogénéité des variances (homocédasticité)</span></span>
<span id="cb621-5"><a href="sect062.html#cb621-5" aria-hidden="true" tabindex="-1"></a><span class="fu">leveneTest</span>(laeq <span class="sc">~</span> Mode, <span class="at">data =</span> df_Bruit)</span></code></pre></div>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = median)
##         Df F value    Pr(&gt;F)    
## group    2   190.3 &lt; 2.2e-16 ***
##       3422                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb623"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb623-1"><a href="sect062.html#cb623-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bartlett.test</span>(laeq <span class="sc">~</span> Mode, <span class="at">data =</span> df_Bruit)</span></code></pre></div>
<pre><code>## 
##  Bartlett test of homogeneity of variances
## 
## data:  laeq by Mode
## Bartlett&#39;s K-squared = 306.64, df = 2, p-value &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb625"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb625-1"><a href="sect062.html#cb625-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bptest</span>(laeq <span class="sc">~</span> Mode, <span class="at">data =</span> df_Bruit)</span></code></pre></div>
<pre><code>## 
##  studentized Breusch-Pagan test
## 
## data:  laeq ~ Mode
## BP = 279.85, df = 2, p-value &lt; 2.2e-16</code></pre>
<p>Étant donné que les deux conditions (normalité et homogénéité des variances) ne sont pas respectées, il est préférable d’utiliser un test non paramétrique de Kruskal-Wallis. Calculons toutefois préalablement l’ANOVA classique et l’ANOVA de Welch puisque les variances ne sont pas égales. Les valeurs de <em>p</em> des deux tests (Fisher et Welch) signalent que les moyennes d’exposition au bruit sont statistiquement différentes entre les trois modes de transport.</p>
<div class="sourceCode" id="cb627"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb627-1"><a href="sect062.html#cb627-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;rstatix&quot;</span>)</span>
<span id="cb627-2"><a href="sect062.html#cb627-2" aria-hidden="true" tabindex="-1"></a><span class="co"># ANOVA avec la fonction anova_test du package rstatix</span></span>
<span id="cb627-3"><a href="sect062.html#cb627-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova_test</span>(laeq <span class="sc">~</span> Mode, <span class="at">data =</span> df_Bruit)</span></code></pre></div>
<pre><code>## ANOVA Table (type II tests)
## 
##   Effect DFn  DFd       F         p p&lt;.05   ges
## 1   Mode   2 3422 544.214 6.12e-206     * 0.241</code></pre>
<div class="sourceCode" id="cb629"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb629-1"><a href="sect062.html#cb629-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ANOVA avec le test de Welch puisque les variances ne sont pas égales</span></span>
<span id="cb629-2"><a href="sect062.html#cb629-2" aria-hidden="true" tabindex="-1"></a><span class="fu">welch_anova_test</span>(laeq <span class="sc">~</span> Mode, <span class="at">data =</span> df_Bruit)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 7
##   .y.       n statistic   DFn   DFd         p method     
## * &lt;chr&gt; &lt;int&gt;     &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt;      
## 1 laeq   3425      446.     2 2248. 9.47e-164 Welch ANOVA</code></pre>
<p>Une fois démontré que les moyennes sont différentes, le test de Tukey est particulièrement intéressant puisqu’il nous permet de repérer les différences de moyennes significatives deux à deux, tout en ajustant les valeurs de <em>p</em> obtenues en fonction du nombre de comparaisons effectuées. Ci-dessous, nous constatons que toutes les paires sont statistiquement différentes et que la différence de moyennes entre les automobilistes et les cyclistes est de 1,9 dB(A) et surtout de 7,1 dB(A) entre les automobilistes et les personnes ayant pris le transport en commun.</p>
<div class="sourceCode" id="cb631"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb631-1"><a href="sect062.html#cb631-1" aria-hidden="true" tabindex="-1"></a>aov2 <span class="ot">&lt;-</span> <span class="fu">aov</span>(laeq <span class="sc">~</span> Mode, <span class="at">data =</span> df_Bruit)</span>
<span id="cb631-2"><a href="sect062.html#cb631-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Test de Tukey pour comparer les moyennes entre elles</span></span>
<span id="cb631-3"><a href="sect062.html#cb631-3" aria-hidden="true" tabindex="-1"></a><span class="fu">TukeyHSD</span>(aov2, <span class="at">conf.level =</span> <span class="fl">0.95</span>)</span></code></pre></div>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = laeq ~ Mode, data = df_Bruit)
## 
## $Mode
##                     diff      lwr      upr p adj
## 2. Velo-1. Auto 1.941698 1.406343 2.477053     0
## 3. TC-1. Auto   7.113506 6.587309 7.639703     0
## 3. TC-2. Velo   5.171808 4.649307 5.694309     0</code></pre>
<p>Le calcul du test non paramétrique de Kruskal-Wallis avec la fonction <code>kruskal.test</code> démontre aussi que les médianes des groupes sont différentes (<em>p</em> &lt; 0,001). De manière comparable au test de Tukey, la fonction <code>pairwise.wilcox.test</code> permet aussi de repérer les différences significatives entre les paires de groupes. Pour conclure, tant l’ANOVA que le test non paramétrique de Kruskal-Wallis indiquent que les trois modes de transport sont significativement différents quant à l’exposition au bruit, avec des valeurs plus faibles pour les automobilistes comparativement aux cyclistes et aux personnes ayant pris le transport en commun.</p>
<div class="sourceCode" id="cb633"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb633-1"><a href="sect062.html#cb633-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Test de Kruskal-Wallis</span></span>
<span id="cb633-2"><a href="sect062.html#cb633-2" aria-hidden="true" tabindex="-1"></a><span class="fu">kruskal.test</span>(laeq <span class="sc">~</span> Mode, <span class="at">data =</span> df_Bruit)</span></code></pre></div>
<pre><code>## 
##  Kruskal-Wallis rank sum test
## 
## data:  laeq by Mode
## Kruskal-Wallis chi-squared = 784.74, df = 2, p-value &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb635"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb635-1"><a href="sect062.html#cb635-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcul de la moyenne des rangs pour les trois groupes</span></span>
<span id="cb635-2"><a href="sect062.html#cb635-2" aria-hidden="true" tabindex="-1"></a>df_Bruit<span class="sc">$</span>laeqRank <span class="ot">&lt;-</span> <span class="fu">rank</span>(df_Bruit<span class="sc">$</span>laeq)</span>
<span id="cb635-3"><a href="sect062.html#cb635-3" aria-hidden="true" tabindex="-1"></a>df_Bruit <span class="sc">%&gt;%</span></span>
<span id="cb635-4"><a href="sect062.html#cb635-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Mode) <span class="sc">%&gt;%</span></span>
<span id="cb635-5"><a href="sect062.html#cb635-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">get_summary_stats</span>(laeqRank, <span class="at">type =</span> <span class="st">&quot;mean&quot;</span>)</span></code></pre></div>
<pre><code>## # A tibble: 3 × 4
##   Mode    variable     n  mean
##   &lt;chr&gt;   &lt;chr&gt;    &lt;dbl&gt; &lt;dbl&gt;
## 1 1. Auto laeqRank  1094 1188.
## 2 2. Velo laeqRank  1124 1572.
## 3 3. TC   laeqRank  1207 2320.</code></pre>
<div class="sourceCode" id="cb637"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb637-1"><a href="sect062.html#cb637-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Comparaison des groupes avec la fonction pairwise.wilcox.test</span></span>
<span id="cb637-2"><a href="sect062.html#cb637-2" aria-hidden="true" tabindex="-1"></a><span class="fu">pairwise.wilcox.test</span>(df_Bruit<span class="sc">$</span>laeq, df_Bruit<span class="sc">$</span>Mode, <span class="at">p.adjust.method =</span> <span class="st">&quot;BH&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  Pairwise comparisons using Wilcoxon rank sum test with continuity correction 
## 
## data:  df_Bruit$laeq and df_Bruit$Mode 
## 
##         1. Auto 2. Velo
## 2. Velo &lt;2e-16  -      
## 3. TC   &lt;2e-16  &lt;2e-16 
## 
## P value adjustment method: BH</code></pre>
</div>
</div>
<div id="sect0624" class="section level3 hasAnchor" number="6.2.4">
<h3><span class="header-section-number">6.2.4</span> Comment rapporter les résultats d’une ANOVA et du test de Kruskal-Wallis<a href="sect062.html#sect0624" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Plusieurs éléments doivent être reportés pour détailler les résultats d’une ANOVA ou d’un test de Kruskal-Wallis : la valeur de <em>F</em>, de <em>W</em> (dans le cas d’une ANOVA de Welch) ou du χ2 (Kruskal-Wallis), les valeurs de <em>p</em>, les moyennes ou médianes respectives des groupes et éventuellement un tableau détaillant les écarts intergroupes obtenus avec les tests de Tukey ou Wilcoxon par paires.</p>
<ul>
<li><p>Les résultats de l’analyse de variance à un facteur démontrent que le mode de transport utilisé n’a pas d’effet significatif sur le temps de déplacement en heures de pointe à Montréal (<em>F</em>(2,96) = 0,82, <em>p</em> = 0,444). En effet, pour des trajets de dix kilomètres entre un quartier périphérique et le centre-ville, les cyclistes (Moy = 38,4, ET = 15,2) arrivent en moyenne moins d’une minute après les automobilistes (Moy = 37,7, ET = 12,8) et moins de quatre minutes comparativement aux personnes ayant pris le transport en commun (Moy = 41,6, ET = 11,4).</p></li>
<li><p>Les résultats de l’analyse de variance à un facteur démontrent que le mode de transport utilisé a un impact significatif sur le niveau d’exposition en heures de pointe à Montréal (<em>F</em>(2,96) = 544, <em>p</em> &lt; 0,001 et <em>Welch</em>(2,96) = 446, <em>p</em> &lt; 0,001). En effet, les personnes en transport en commun (Moy = 74,0, ET = 6,79) et les cyclistes (Moy = 68,8, ET = 4,3) ont des niveaux d’exposition au bruit significativement plus élevés que les automobilistes (Moy = 66,8, ET = 4,56).</p></li>
<li><p>Les résultats du test de Kruskal-Wallis démontrent qu’il existe des différences significatives d’exposition au bruit entre les trois modes de transport (χ2(2) = 784,74, <em>p</em> &lt; 0,001) avec des moyennes de rangs de 1094 pour l’automobile, de 1124 pour le vélo et de 1207 pour le transport en commun.</p></li>
</ul>
<div class="bloc_aller_loin">
<p>Nous avons vu que l’ANOVA permet de comparer les moyennes d’une variable continue à partir d’une variable qualitative comprenant plusieurs modalités (facteur) pour des observations indépendantes. Il y a donc une seule variable dépendante (continue) et une seule variable indépendante. Sachez qu’il existe de nombreuses extensions de l’ANOVA classique :</p>
<ul>
<li><p><strong>une ANOVA à deux facteurs</strong>, soit avec une variable dépendante continue et deux variables indépendantes qualitatives (<em>two-way ANOVA</em> en anglais). Nous évaluons ainsi les effets des deux variables (<em>a</em>, <em>b</em>) et de leur interaction (<em>ab</em>) sur une variable continue.</p></li>
<li><p><strong>une ANOVA multifacteur</strong> avec une variable dépendante continue et plus de deux variables indépendantes qualitatives. Par exemple, avec trois variables qualitatives pour expliquer la variable continue, nous incluons les effets de chaque variable qualitative (<em>a</em>, <em>b</em>, <em>c</em>), ainsi que de leurs interactions (<em>ab</em>, <em>ac</em>, <em>bc</em>, <em>abc</em>).</p></li>
<li><p><strong>L’analyse de covariance</strong> (<strong>ANCOVA</strong>, <em><strong>AN</strong>alysis of <strong>COVA</strong>riance</em> en anglais) comprend une variable dépendante continue, une variable indépendante qualitative (facteur) et plusieurs variables indépendantes continues dites covariables. L’objectif est alors de vérifier si les moyennes d’une variable dépendante sont différentes pour plusieurs groupes d’une population donnée, après avoir contrôlé l’effet d’une ou de plusieurs variables continues. Par exemple, pour une métropole donnée, nous pourrions vouloir comparer les moyennes de loyers entre la ville-centre et ceux des première et seconde couronnes (facteur), une fois contrôlée la taille de ces derniers (variable covariée continue). En effet, une partie de la variance des loyers s’explique certainement par la taille des logements.</p></li>
<li><p><strong>L’analyse de variance multivariée</strong> (<strong>MANOVA</strong>, <em><strong>M</strong>ultivariate <strong>AN</strong>alysis <strong>O</strong>f <strong>VA</strong>riance</em> en anglais) comprend deux variables dépendantes continues ou plus et une variable indépendante qualitative (facteur). Par exemple, nous souhaiterions comparer les moyennes d’exposition au bruit et à différents polluants (dioxyde d’azote, particules fines, ozone) (variables dépendantes continues) selon le mode de transport utilisé (automobile, vélo, transport en commun), soit le facteur.</p></li>
<li><p><strong>L’analyse de covariance multivariée</strong> (<strong>MANCOVA</strong>, <em><strong>M</strong>ultivariate <strong>AN</strong>alysis of <strong>COVA</strong>riance</em> en anglais), soit une analyse qui comprend deux variables dépendantes continues ou plus (comme la MANOVA) et une variable qualitative comme variable indépendante (facteur) et une covariable continue ou plus.</p></li>
</ul>
<p>Pour le test <em>t</em>, nous avons vu qu’il peut s’appliquer soit à deux échantillons indépendants (non appariés), soit à deux échantillons dépendants (appariés). Notez qu’il existe aussi des extensions de l’ANOVA pour des échantillons pairés. Nous parlons alors d’<strong>analyse de variance sur des mesures répétées</strong>. Par exemple, nous pourrions évaluer la perception du sentiment de sécurité relativement à la pratique du vélo d’hiver pour un échantillon de cyclistes ayant décidé de l’adopter récemment, et ce, à plusieurs moments : avant leur première saison, à la fin de leur premier hiver, à la fin de leur second hiver. Autre exemple, nous pourrions sélectionner un échantillon d’individus (100, par exemple) pour lesquels nous évaluerions leurs perceptions de l’environnement sonore dans différents lieux de la ville. Comme pour l’ANOVA classique (échantillons non appariés), il existe des extensions de l’ANOVA sur des mesures répétées permettant d’inclure plusieurs facteurs (groupes de population); nous mesurons alors une variable continue pour plusieurs groupes d’individus à différents moments ou pour des conditions différentes. Il est aussi possible de réaliser une ANOVA pour des mesures répétées avec une ou plusieurs covariables continues.</p>
<p>Bref, si l’ANOVA était un roman, elle serait certainement « un monde sans fin » de Ken Follett! Notez toutefois que la SUPERNOVA, la BOSSA-NOVA et le CASANOVA ne sont pas des variantes de l’ANOVA!</p>
</div>
</div>
</div>
<h3>R&eacute;f&eacute;rences</h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-2018_1" class="csl-entry">
Apparicio, Philippe, Jérémy Gelb, Mathieu Carrier, Marie-Ève Mathieu et Simon Kingham. 2018. <span>« Exposure to noise and air pollution by mode of transportation during rush hours in Montreal. »</span> <em>Journal of Transport Geography</em> 70: 182‑192. <a href="https://doi.org/10.1016/j.jtrangeo.2018.06.007">https://doi.org/10.1016/j.jtrangeo.2018.06.007</a>.
</div>
<div id="ref-glass1972consequences" class="csl-entry">
Glass, Gene V, Percy D Peckham et James R Sanders. 1972. <span>« Consequences of failure to meet assumptions underlying the fixed effects analyses of variance and covariance. »</span> <em>Review of educational research</em> 42 (3): 237‑288.
</div>
<div id="ref-lix1996consequences" class="csl-entry">
Lix, Lisa M, Joanne C Keselman et HJ Keselman. 1996. <span>« Consequences of assumption violations revisited: A quantitative review of alternatives to the one-way analysis of variance F test. »</span> <em>Review of educational research</em> 66 (4): 579‑619. <a href="https://doi.org/10.3102/00346543066004579">https://doi.org/10.3102/00346543066004579</a>.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="sect061.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="sect063.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["MethodesQuantitScSocialesBolR.pdf"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "none"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
